### ISSUE TITLE
[Bug] When using CLBLAST -> OSError: exception: access violation reading 

### ISSUE THREAD

**Issue by gustrd** [LostRuins/koboldcpp#100]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I'm using the latest windows binaries of version 1.10. When using clblast after sometime I get an error, I'm unable to completely process the prompt. At the last version it was working ok.

# Current Behavior

Dump of my error:

````
C:\@KoboldAI>koboldcpp_concedo_1-10.exe --useclblast 0 0
Welcome to KoboldCpp - Version 1.10
Attempting to use CLBlast library for faster prompt ingestion. A compatible clblast.dll will be required.
Initializing dynamic library: koboldcpp_clblast.dll
For command line arguments, please refer to --help
Otherwise, please manually select ggml file:
Loading model: C:\@Models\GPT-J-6B-Pygway-ggml-q4_1.bin
[Parts: 1, Threads: 3, SmartContext: False]

---
Identified as GPT-J model: (ver 102)
Attempting to Load...
---
gptj_model_load: loading model from 'C:\@Models\GPT-J-6B-Pygway-ggml-q4_1.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 3
gptj_model_load: ggml ctx size = 5226.67 MB
gptj_model_load: memory_size =   896.00 MB, n_mem = 57344
gptj_model_load: ................................... done
gptj_model_load: model size =  4330.60 MB / num tensors = 285
Load Model OK: True
Embedded Kobold Lite loaded.
Starting Kobold HTTP Server on port 5001
Please connect to custom endpoint at http://localhost:5001

Input: {"n": 1, "max_context_length": 1024, "max_length": 80, "rep_pen": 1.08, "temperature": 0.62, "top_p": 0.9, "top_k": 0, "top_a": 0, "typical": 1, "tfs": 1, "rep_pen_range": 1024, "rep_pen_slope": 0.7, "sampler_order": [0, 1, 2, 3, 4, 5, 6], "prompt": "[Character: Emily; species: Human; age: 24; gender: female; physical appearance: cute, attractive; personality: cheerful, upbeat, friendly; likes: chatting; description: Emily has been your childhood friend for many years. She is outgoing, adventurous, and enjoys many interesting hobbies. She has had a secret crush on you for a long time.]\n[The following is a chat message log between Emily and you.]\n\nEmily: Heyo! You there? I think my internet is kinda slow today.\nYou: Hello Emily. Good to hear from you :)\n\nEmily: Oh heyy. Haven't heard from you in a while. What's up?\nYou: I'm fine, and you?\nEmily: Same old same old. Just chilling.\nYou: And what do you want to do today?\nEmily: I was thinking of going shopping with my sister. Want to come along?\nYou: Of course!\nEmily:", "quiet": true, "stop_sequence": ["You:"]}

Processing Prompt [BLAS] (199 / 199 tokens)
Initializing CLBlast (First Run)...
Attempting to use: Platform=0, Device=0 (If invalid, program will crash)
Using Platform: NVIDIA CUDA Device: NVIDIA GeForce MX150
CLBlast: OpenCL error: clEnqueueNDRangeKernel: -4
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 57492)
Traceback (most recent call last):
  File "socketserver.py", line 316, in _handle_request_noblock
  File "socketserver.py", line 347, in process_request
  File "socketserver.py", line 360, in finish_request
  File "koboldcpp.py", line 136, in __call__
  File "http\server.py", line 651, in __init__
  File "socketserver.py", line 747, in __init__
  File "http\server.py", line 425, in handle
  File "http\server.py", line 413, in handle_one_request
  File "koboldcpp.py", line 246, in do_POST
  File "koboldcpp.py", line 110, in generate
OSError: exception: access violation reading 0x0000000000000008
----------------------------------------
````

# Environment and Context

I'm running at a new install of Windows 10, with i5-8th CPU and MX150 2GB VRAM GPU. I was able to run the precompiled binaries before very well.

**Comment by Midaychi** [comment]
That's the out of scratch error but without the out of scratch part isn't it?

**Comment by gustrd** [comment]
I could isolate and reproduce better this strange bug.

In truth it happens at every release (I tried 1.10, 1.9 and 1.8), but just when using clblast with the model https://huggingface.co/Kastor/GPT-J-6B-Pygway-ggml-q4_1 .

The curious part is that this model works if clblast is not being used, and clblast works ok with other models.

**Comment by LostRuins** [comment]
Thanks, I will try to repro it

**Comment by alucard-hub** [comment]
I converted that model, i will check it and try to convert it again.

**Comment by alucard-hub** [comment]
> I could isolate and reproduce better this strange bug.
> 
> In truth it happens at every release (I tried 1.10, 1.9 and 1.8), but just when using clblast with the model https://huggingface.co/Kastor/GPT-J-6B-Pygway-ggml-q4_1 .
> 
> The curious part is that this model works if clblast is not being used, and clblast works ok with other models.

No error for me with the copy on my hard drive. I uploaded it again, the repo is updated so you can try to download the model again.

**Comment by mainsplainer** [comment]
Getting the same [OSError: exception: access violation reading] error in koboldcpp-1.11 using -> (https://huggingface.co/eachadea/ggml-vicuna-13b-1.1/blob/main/ggml-vicuna-13b-1.1-q4_2.bin) on instruct mode.

**Comment by LostRuins** [comment]
@mainsplainer are you trying to use Openblas or clblast?

**Comment by rosemash** [comment]
I get the same thing with a couple of different q4_3 quantized models I am testing. But the error goes away if I don't use clblast

**Comment by gustrd** [comment]
> > I could isolate and reproduce better this strange bug.
> > In truth it happens at every release (I tried 1.10, 1.9 and 1.8), but just when using clblast with the model https://huggingface.co/Kastor/GPT-J-6B-Pygway-ggml-q4_1 .
> > The curious part is that this model works if clblast is not being used, and clblast works ok with other models.
> 
> No error for me with the copy on my hard drive. I uploaded it again, the repo is updated so you can try to download the model again.
> 
> Update: I pulled the repo to have the last code, compiled without cuda, downloaded the model from HF just to double check and no errors for me with cblast.

@alucard-hub , I downloaded again your model and I still got the same error when running with clblast:

Processing Prompt [BLAS] (256 / 496 tokens)
Initializing CLBlast (First Run)...
Attempting to use: Platform=0, Device=0 (If invalid, program will crash)
Using Platform: NVIDIA CUDA Device: NVIDIA GeForce MX150
CLBlast: OpenCL error: clEnqueueNDRangeKernel: -4
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 58471)
Traceback (most recent call last):
  File "socketserver.py", line 316, in _handle_request_noblock
  File "socketserver.py", line 347, in process_request
  File "socketserver.py", line 360, in finish_request
  File "koboldcpp.py", line 136, in __call__
  File "http\server.py", line 651, in __init__
  File "socketserver.py", line 747, in __init__
  File "http\server.py", line 425, in handle
  File "http\server.py", line 413, in handle_one_request
  File "koboldcpp.py", line 246, in do_POST
  File "koboldcpp.py", line 110, in generate
OSError: exception: access violation reading 0x0000000000000008
----------------------------------------

**Comment by alucard-hub** [comment]
> > > I could isolate and reproduce better this strange bug.
> > > In truth it happens at every release (I tried 1.10, 1.9 and 1.8), but just when using clblast with the model https://huggingface.co/Kastor/GPT-J-6B-Pygway-ggml-q4_1 .
> > > The curious part is that this model works if clblast is not being used, and clblast works ok with other models.
> > 
> > 
> > No error for me with the copy on my hard drive. I uploaded it again, the repo is updated so you can try to download the model again.
> > Update: I pulled the repo to have the last code, compiled without cuda, downloaded the model from HF just to double check and no errors for me with cblast.
> 
> @alucard-hub , I downloaded again your model and I still got the same error when running with clblast:
> 
> ```
> Processing Prompt [BLAS] (256 / 496 tokens)
> Initializing CLBlast (First Run)...
> Attempting to use: Platform=0, Device=0 (If invalid, program will crash)
> Using Platform: NVIDIA CUDA Device: NVIDIA GeForce MX150
> CLBlast: OpenCL error: clEnqueueNDRangeKernel: -4
> ----------------------------------------
> Exception occurred during processing of request from ('127.0.0.1', 58471)
> Traceback (most recent call last):
>   File "socketserver.py", line 316, in _handle_request_noblock
>   File "socketserver.py", line 347, in process_request
>   File "socketserver.py", line 360, in finish_request
>   File "koboldcpp.py", line 136, in __call__
>   File "http\server.py", line 651, in __init__
>   File "socketserver.py", line 747, in __init__
>   File "http\server.py", line 425, in handle
>   File "http\server.py", line 413, in handle_one_request
>   File "koboldcpp.py", line 246, in do_POST
>   File "koboldcpp.py", line 110, in generate
> OSError: exception: access violation reading 0x0000000000000008
> ----------------------------------------
> ```

Must be nvidia related, cause I have no problems running it with AMD. I will convert it again later, in q4_0 and q4_1 to keep researching.

**Comment by alucard-hub** [comment]
> > > I could isolate and reproduce better this strange bug.
> > > In truth it happens at every release (I tried 1.10, 1.9 and 1.8), but just when using clblast with the model https://huggingface.co/Kastor/GPT-J-6B-Pygway-ggml-q4_1 .
> > > The curious part is that this model works if clblast is not being used, and clblast works ok with other models.
> > 
> > 
> > No error for me with the copy on my hard drive. I uploaded it again, the repo is updated so you can try to download the model again.
> > Update: I pulled the repo to have the last code, compiled without cuda, downloaded the model from HF just to double check and no errors for me with cblast.
> 
> @alucard-hub , I downloaded again your model and I still got the same error when running with clblast:
> 
> ```
> Processing Prompt [BLAS] (256 / 496 tokens)
> Initializing CLBlast (First Run)...
> Attempting to use: Platform=0, Device=0 (If invalid, program will crash)
> Using Platform: NVIDIA CUDA Device: NVIDIA GeForce MX150
> CLBlast: OpenCL error: clEnqueueNDRangeKernel: -4
> ----------------------------------------
> Exception occurred during processing of request from ('127.0.0.1', 58471)
> Traceback (most recent call last):
>   File "socketserver.py", line 316, in _handle_request_noblock
>   File "socketserver.py", line 347, in process_request
>   File "socketserver.py", line 360, in finish_request
>   File "koboldcpp.py", line 136, in __call__
>   File "http\server.py", line 651, in __init__
>   File "socketserver.py", line 747, in __init__
>   File "http\server.py", line 425, in handle
>   File "http\server.py", line 413, in handle_one_request
>   File "koboldcpp.py", line 246, in do_POST
>   File "koboldcpp.py", line 110, in generate
> OSError: exception: access violation reading 0x0000000000000008
> ----------------------------------------
> ```

New converted models are ready to download, try them.

**Comment by gustrd** [comment]
> [GPT-J-6B-Pygway-ggml-q4_1](https://huggingface.co/Kastor/GPT-J-6B-Pygway-ggml-q4_1) .

@alucard-hub , tried again with "GPT-J-6B-Pygway-v2-ggml-q4_1.bin" and the error is the same when using CLBlast.

**Comment by gustrd** [comment]
> Does it work correctly on openblas but fails only with clblast? The error above seems to indicate that the dequantize kernel is failing for some reason.

Yes, with OpenBlas it works normally.
