### ISSUE TITLE
The stop sequence feature introduced in 1.9 doesn't work as intended.

### ISSUE THREAD

**Issue by NovNovikov** [LostRuins/koboldcpp#101]
# Expected Behavior

In the description of 1.9 it was written:
"Now has support for stopping sequences fully implemented in the API! They've been implemented in a similar and compatible way to my United PR https://github.com/one-some/KoboldAI-united/pull/5 and they should be shortly usable in online Lite as well as (eventually) the main kobold client when it gets merged. What this means is that now the AI will be able to finish a response early even if not all the response tokens are consumed, and save time by sending the reply instead of generating excess unneeded tokens."
So the generation should stop when it encounters a name of the user.

# Current Behavior

It works when the network generates the user's reply as "Name:", but doesn't work when it is generates as "Name". So it works in 50% of cases.

**Comment by LostRuins** [comment]
Hmm, you wouldn't actually want `Name` to be a stop sequence by default. Because it's possible for the bot to refer to you by name and then that would cut the convo off. 

This usually happens the model was prompted poorly. But eventually I do plan to expose stopping tokens as an editable field so anyone can add their own.

**Comment by leuchtetgruen** [comment]
I'm experiencing the same behaviour in chats with Vicunia. It sometimes responds with and sometimes without the colon.

I think reacting to a line break immediately followed by `Name` as a stop sequence would also work.  This way it wouldnt trigger when the AI mentions you in a sentence but it would still trigger when it "forgets" the colon.

**Comment by MetroByte** [comment]
For web users, who use the browser version. There is workaround. If you add a space in file `klite.embd` at `(_.stop_sequence=[localsettings.chatname+":"` after `:`, it would work fine. AI would use a token after the nickname and then gives up generating. Also you can put some another keywords, comma separated. I also put `"You: ","\\end{code}","###"`

**Comment by LostRuins** [comment]
Yep that is one way. API supports up to 10 different stopper tokens for each generation, so a quick fix is simply editing the HTML file of the client

**Comment by LostRuins** [comment]
Update: In V1.11 you can now configure any custom stop sequence you want from the UI, under the Memory panel.

**Comment by NovNovikov** [comment]
Ok, this works somehow, thanks!

**Comment by NovNovikov** [comment]
Is there a way to introduce several custom stop sequences? When I enter two separate words - for example Player, <Player> - the stop sequence mechanism works as one line "Player, <Player>"

**Comment by LostRuins** [comment]
No, currently the stop sequence only works for one extra sequence.

**Comment by LostRuins** [comment]
Hi all, multiple stop sequences are now supported. You can separate them with a `||$||` delimiter in the Kobold Lite UI.
