### ISSUE TITLE
Add support for Tekken pre-tokenizer to support Nemo 12B

### ISSUE THREAD

**Issue by invisietch** [LostRuins/koboldcpp#1011]
**Describe the Issue**
Mistral/Nvidia recently released [Nemo 12B](https://mistral.ai/news/mistral-nemo/) and llama.cpp have [added support](https://github.com/ggerganov/llama.cpp/pull/8579) for its new pre-tokenizer, tekken.

Is this likely to be added to koboldcpp soon? The latest release is still failing when trying to load Nemo GGUFs.

Is there a similar PR I could look at to make this change myself?

**Additional Information:**

```
❯ ./koboldcpp-linux-x64-cuda1210 --usecublas --gpulayers 95 --tensor_split 1 0 0 0 0 --flashattention --contextsize 16384 /mnt/models/Mistral-Nemo-Instruct-2407-Q6_K.gguf
***
Welcome to KoboldCpp - Version 1.70.1
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.so
==========
Namespace(benchmark=None, blasbatchsize=512, blasthreads=11, chatcompletionsadapter='', config=None, contextsize=16384, debugmode=0, flashattention=True, forceversion=0, foreground=False, gpulayers=95, highpriority=False, hordeconfig=None, hordegenlen=0, hordekey='', hordemaxctx=0, hordemodelname='', hordeworkername='', host='', ignoremissing=False, launch=False, lora=None, mmproj='', model='', model_param='/mnt/models/Mistral-Nemo-Instruct-2407-Q6_K.gguf', multiuser=0, noavx2=False, noblas=False, nocertify=False, nommap=False, noshift=False, onready='', password=None, port=5001, port_param=5001, preloadstory='', quantkv=0, quiet=False, remotetunnel=False, ropeconfig=[0.0, 10000.0], sdclamped=0, sdconfig=None, sdlora='', sdloramult=1.0, sdmodel='', sdquant=False, sdthreads=0, sdvae='', sdvaeauto=False, skiplauncher=False, smartcontext=False, ssl=None, tensor_split=[1.0, 0.0, 0.0, 0.0, 0.0], threads=11, unpack='', useclblast=None, usecublas=[], usemlock=False, usevulkan=None, whispermodel='')
==========
Loading model: /mnt/models/Mistral-Nemo-Instruct-2407-Q6_K.gguf

The reported GGUF Arch is: llama
Arch Category: 0

---
Identified as GGUF model: (ver 6)
Attempting to Load...
---
Using automatic RoPE scaling for GGUF. If the model has custom RoPE settings, they'll be used directly instead!
It means that the RoPE values written above will be replaced by the RoPE values indicated after loading.
System Info: AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 |

llama_model_loader: loaded meta data with 25 key-value pairs and 363 tensors from /mnt/models/Mistral-Nemo-Instruct-2407-Q6_K.gguf (version GGUF V3 (latest))
llama_model_load: error loading model: error loading model vocabulary: unknown pre-tokenizer type: 'mistral-bpe'
llama_load_model_from_file: failed to load model
[1]    419861 segmentation fault (core dumped)  ./koboldcpp-linux-x64-cuda1210 --usecublas --gpulayers 95 --tensor_split 1 0
```

**Comment by LostRuins** [comment]
Yes, it'll be in the next release. Generally I prefer to merge it after the PR is accepted upstream, in case the implementation gets changed after. If by the 1.71 release it's not merged, then I will merge that PR directly.

**Comment by henk717** [comment]
"Have added" isn't accurate yet, the PR is still open so its a "Will most likely add". Once they do we tend to get these kinds of changes by upgrading the llamacpp its based off.

**Comment by invisietch** [comment]
Looks like that got merged and released now.

**Comment by XZVB12** [comment]
> Looks like that got merged and released now.

It is also necessary to[ merge this commit](https://github.com/ggerganov/llama.cpp/pull/8604)

**Comment by scyl** [comment]
> > Looks like that got merged and released now.
> 
> It is also necessary to[ merge this commit](https://github.com/ggerganov/llama.cpp/pull/8604)

Looks like it is merged now, I assume NeMo 12B soon?

**Comment by LostRuins** [comment]
Should be fixed in the latest release

**Comment by vincemue** [comment]
would this include dolphin-2.9.3-mistral-nemo?
![Screenshot 2024-08-01 222039](https://github.com/user-attachments/assets/98cad821-e829-4964-8546-748578702b01)

**Comment by henk717** [comment]
Yes, but only if its quantized correctly. The quant you are using is incorrect.

**Comment by XZVB12** [comment]
> would this include dolphin-2.9.3-mistral-nemo? ![Screenshot 2024-08-01 222039](https://private-user-images.githubusercontent.com/120366587/354557556-98cad821-e829-4964-8546-748578702b01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDQ3MDcsIm5iZiI6MTcyMjYwNDQwNywicGF0aCI6Ii8xMjAzNjY1ODcvMzU0NTU3NTU2LTk4Y2FkODIxLWU4MjktNDk2NC04NTQ2LTc0ODU3ODcwMmIwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxMzEzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGIwYTU4ZDFmMmFmMDQyNjJkMzE2Y2E4YTk5OTcxMTdiMGE2YjA1ZGQzMTBiZGE5YWRkNjlkNzc2YjI3YjZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dDfy2-fZnO1xk1hKIjHsWce-nm18u4xGN950L1pRJQM)

try --override-kv tokenizer.ggml.pre=str:tekken

**Comment by henk717** [comment]
Thats not a thing on KoboldCpp and it shouldn't be needed, just use a quant that correctly defines it as the tekken tokenizer rather than a made up one.

**Comment by vincemue** [comment]
thanks for the hints, first I wasnt sure what you guys where talking about, but i seem to have figured it out.
this one also helped: https://huggingface.co/cognitivecomputations/dolphin-2.9.3-mistral-nemo-12b-gguf/discussions/1

1. Downloaded HxD (hex editor)
2.  changed ONLY the pre-tokenizer part in gguf
3. replaced the 'dolphin12b' string with 'tekken' on the right side and filled up with 0 on the left side.

![image](https://github.com/user-attachments/assets/c86792df-5d7b-4c52-9212-fad81e0dbbd1)
