### ISSUE TITLE
Is there a way to make this only use 1 gpu instead of both of them?

### ISSUE THREAD

**Issue by Xeraster** [LostRuins/koboldcpp#1014]
I have 2 gpus with 12gb of vram each. It's really cool that koboldcpp can split its vram usage between 2 gpus. However i'm trying to run other stuff at the same time. Easy diffusion can't use split vram like koboldcpp can. I have to stop koboldcpp in order to use easy diffusion because the 5gb koboldcpp uses up accross 2 gpus doesn't leave enough vram on either gpu for easy diffusion to run as it needs about 11gb of vram.

This is the command I run to use koboldcpp:
`./koboldcpp-linux-x64-cuda1150 --model models/Wizard-Vicuna-13B-Uncensored.Q5_K_M.gguf --port $port --noavx2 --threads $threads --usevulkan --gpulayers 35 --contextsize 4096`
iirc only the vulkan option works on my system. Is there a way to get it to use only 1 gpu without using something besides vulkan?

Alternatively if someone knows of a stable diffusion fork that allows 2 gpus and split vram access, let me know?

**Comment by LostRuins** [comment]
Add a value after `--usevulkan`. For example, to use gpu0, do `--usevulkan 0` and to use gpu1 do `--usevulkan 1`. Only that gpu ID will be used.
