### ISSUE TITLE
Support ComfyUI as image generation backend

### ISSUE THREAD

**Issue by krypt-lx** [LostRuins/koboldcpp#1017]
I see there are some options, but no ComfyUI in the list

There are some instructions on using ComfyUI in such way:
https://9elements.com/blog/hosting-a-comfyui-workflow-via-api/
Basically, it boils down to loading prepared json, modifying some fields in it and sending request while listening web socket for progress/response

Just to be clear: I'm not a regular KoboltCpp user, just trying different things and noticed ComfyUI is not listed as a possible option

**Comment by henk717** [comment]
Would be a feature request for https://github.com/LostRuins/lite.koboldai.net

**Comment by LostRuins** [comment]
This is now added in the latest version
