### ISSUE TITLE
suggestion: provide one-folder pyinstaller for cuda builds

### ISSUE THREAD

**Issue by 91135** [LostRuins/koboldcpp#1018]
for faster start and less storage strain due to large size

**Comment by henk717** [comment]
We already have to deal with multiple gigabytes of upload at the moment, but it does have an option to extract the pyinstaller so you can run it in regular python.

**Comment by LostRuins** [comment]
Run koboldcpp with `--unpack` and it will extract to an empty directory, then you can access the files or run it from there.

**Comment by LostRuins** [comment]
Yeah, and portability. Zero install, zero dependency, it just works.
