### ISSUE TITLE
L3.1 GGUFs made post Llama.cpp b3479 update not working in Kobold.cpp

### ISSUE THREAD

**Issue by InferenceIllusionist** [LostRuins/koboldcpp#1026]
**Describe the Issue**

Hi folks just reporting an issue I ran into with Llama 3.1 and Kobold.cpp. From testing this does not appear to impact older quants, but quantizations created after today may cause some end-user frustrations and I wanted to share my experience in case others are seeing the same.

1. Downloaded fp16 safetensors from this link: https://huggingface.co/Undi95/Meta-Llama-3.1-8B-Claude
2. Converted to gguf using convert_hf_to_gguf.py: `python convert_hf_to_gguf.py .\models\Meta-Llama-3.1-8B-Claude`
3. Opened resulting f16.gguf in Kobold 1.71
4. Error message appears, kobold crashes and exits:

```
llama_model_load: error loading model: done_getting_tensors: wrong number of tensors; expected 292, got 291
llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "koboldcpp.py", line 4208, in <module>
    main(parser.parse_args(),start_server=True)
  File "koboldcpp.py", line 3883, in main
    loadok = load_model(modelname)
  File "koboldcpp.py", line 773, in load_model
    ret = handle.load_model(inputs)
OSError: exception: access violation reading 0x0000000000001894
[64592] Failed to execute script 'koboldcpp' due to unhandled exception!
```

**Additional Information:**

- May have been caused by both RoPe and subsequent tensor updates to conversion in [b3472](https://github.com/ggerganov/llama.cpp/releases/tag/b3472)
- Converted f16 gguf works perfectly in llama.cpp post b3472
- Older GGUFs converted before b3472 seem to work fine as well (tested with Q4_K_M)
- Unclear if other architectures are affected

**Comment by LostRuins** [comment]
This should be fixed in 1.71.1

**Comment by MarcusLlewellyn** [comment]
Making sure I was using 1.71.1 fixed this issue for me.

**Comment by InferenceIllusionist** [comment]
Confirmed working in 1.71.1, thanks for the speedy response

**Comment by rabidcopy** [comment]
Not sure if this is specific to llama.cpp or Koboldcpp, but using newly created GGUFs that need 1.71.1 have roughly a 30-40% token per second hit when using Vulkan (even when offloading no layers to the GPU). Processing is still fast. CPU/BLAS/CLBlast backends seem unaffected and have similar speeds to prior versions.
