### ISSUE TITLE
Error using Kobold on Colab 

### ISSUE THREAD

**Issue by SusieDreemurr** [LostRuins/koboldcpp#1030]
**Describe the Issue**
Never has this issue with Koboldcpp on Colab, but since yesterday I've been getting this error. I made sure everything was inputted correctly before running the cell. Happens with every model I try.

**Additional Information:**
![kobold error 2](https://github.com/user-attachments/assets/265cebf8-b5b7-45b5-ada8-e45c00749556)

![koboldcpp colab error](https://github.com/user-attachments/assets/75d12c0c-8f4a-44e2-86af-da0d813615dd)

**Comment by LostRuins** [comment]
Are you using the official colab? That colab looks outdated. Can you try on this link

https://colab.research.google.com/github/LostRuins/koboldcpp/blob/concedo/colab.ipynb

**Comment by SusieDreemurr** [comment]
> Are you using the official colab? That colab looks outdated. Can you try on this link
> 
> https://colab.research.google.com/github/LostRuins/koboldcpp/blob/concedo/colab.ipynb

Maybe I wasn't using the official one like I thought I was. It seems to work now. Thank you.
