### ISSUE TITLE
fatal error: 'execinfo.h' file not found

### ISSUE THREAD

**Issue by inspir3dArt** [LostRuins/koboldcpp#1034]
I tried to update koboldcpp in Termux on Android to test some llama 3.1 8b based models. It looks like koboldcpp / llamacpp can't currently be build in Termux.

`ggml/src/ggml.c:145:10: fatal error: 'execinfo.h' file not found
  145 | #include <execinfo.h>
      |          ^~~~~~~~~~~~
1 error generated.
make: *** [Makefile:405: ggml.o] Error 1`

I found this that seems to be related:
https://github.com/ggerganov/llama.cpp/issues/8762

**Comment by LostRuins** [comment]
Hi, can you try my experimental branch?

`git clone -b concedo_experimental https://github.com/LostRuins/koboldcpp.git`

**Comment by inspir3dArt** [comment]
Works fine. Thank you for fixing it.
