### ISSUE TITLE
After loading the model, click Launch and the following error appears

### ISSUE THREAD

**Issue by githubberers** [LostRuins/koboldcpp#1036]
After loading the model, click Launch and the following error appears：

***
Welcome to KoboldCpp - Version l.69
For command line arguments, please refer to --help　***
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be requir ed.
Initializing dynamic library: koboldcpp_cublas. dll Iraceback (most recent call last): 
File“PyInstallerlloaderlpyimodo3_ctypes.py"，line 53，in_init File "ctypesl_init_-py"
line 373,in
init
OSError：［WinError1l14]动态链接库（DLL）初始化例程失败。
The above exception was the direct cause of the following exception:
Traceback (most recent call last): File"koboldcpp.py"，
 line 3783， in <module>
File"koboldcpp.py"
line 3378， in main
File"koboldcpp.py"
"，line 307，in init_library
File"PyInstaiieriloaderlpyimodo3_ctypes.py"，line 55，in，
init
pyimodo3_ctypes.PyInstallerImportError: Failed to load dynlib/dll 'C:l\Users/\RTX\\AppDatal/\Lo calllTempll_MEI15i242/\koboldcpp_cublas.dll'. Most likely this dynlib/dll was not found when the  applicationwasfrozen.
[6300] Failed to execute script 'koboldcpp’ due to unhandled exception!

**Comment by Vibecoder9000** [comment]
Install latest version and retry.

**Comment by githubberers** [comment]
> Install latest version and retry.

I have already installed the latest version, but I still have the above problem. What plugins or environments do I need to install and use them together?

**Comment by LostRuins** [comment]
Could your virus scanner be deleting the dll file? Can you try using the "unpack" option and seeing if all files are inside (including koboldcpp_cublas.dll and cublasLt64_11.dll etc

**Comment by githubberers** [comment]
Before clicking the launch button, there are related dll files; once the launch button is clicked, koboldcpp.exe crashes. The first screenshot was captured by recording the screen, and then the information in the screenshot was captured. Can someone help me troubleshoot this problem? I'm eager to start using koboldcpp.

**Comment by LostRuins** [comment]
Please try "Unpack" the exe
![image](https://github.com/user-attachments/assets/f5853578-6010-4460-b529-24fb9f958f8d)

Do you see the cublas libraries?
![image](https://github.com/user-attachments/assets/99813599-95d6-47cd-be8d-a06a8e3fd2b1)

Also, you can try the oldcpu version: https://github.com/LostRuins/koboldcpp/releases/download/v1.72/koboldcpp_oldcpu.exe

Lastly, please try the Vulkan or Vulkan OldCPU version

![image](https://github.com/user-attachments/assets/a110d885-6e16-4198-8f65-4ec0e815c868)

**Comment by githubberers** [comment]
> Please try "Unpack" the exe ![image](https://private-user-images.githubusercontent.com/39025047/355479876-f5853578-6010-4460-b529-24fb9f958f8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTQ1NTYsIm5iZiI6MTcyMjk5NDI1NiwicGF0aCI6Ii8zOTAyNTA0Ny8zNTU0Nzk4NzYtZjU4NTM1NzgtNjAxMC00NDYwLWI1MjktMjRmYjlmOTU4ZjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAxMzA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMzU3ZmFlYzQ1ZTA2MjE0ZTVjZWE2N2RkNjZjODVmY2FiODcwNGViYmY0Mjk2MWE0Y2ExM2YwYTY0OWI3ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nUfauw2uz86YHNAVJmSpjCL7L4JWb5RZ7NVi8WZ9cO8)
> 
> Do you see the cublas libraries? ![image](https://private-user-images.githubusercontent.com/39025047/355480135-99813599-95d6-47cd-be8d-a06a8e3fd2b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTQ1NTYsIm5iZiI6MTcyMjk5NDI1NiwicGF0aCI6Ii8zOTAyNTA0Ny8zNTU0ODAxMzUtOTk4MTM1OTktOTVkNi00N2NkLWJlOGQtYTA2YThlM2ZkMmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAxMzA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZGY2NzBhM2QxYmUxZTliM2ZjOTQwNTkyYzVhMzg1NWJlZjRlYTg2YWQ4MzY3OGRiOWRlYWRiNzRjYTM0MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dscZJX0mnMzoeZZeqBlazPJL6SmjHYZYZkMo2mdLpXM)
> 
> Also, you can try the oldcpu version: https://github.com/LostRuins/koboldcpp/releases/download/v1.72/koboldcpp_oldcpu.exe
> 
> Lastly, please try the Vulkan or Vulkan OldCPU version
> 
> ![image](https://private-user-images.githubusercontent.com/39025047/355480626-a110d885-6e16-4198-8f65-4ec0e815c868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTQ1NTYsIm5iZiI6MTcyMjk5NDI1NiwicGF0aCI6Ii8zOTAyNTA0Ny8zNTU0ODA2MjYtYTExMGQ4ODUtNmUxNi00MTk4LThmNjUtNGVjMGU4MTVjODY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAxMzA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZjJjMzE3NWEyMWU1YWQ2OTg2MDhhZjM4NGJlNWZmZDg3M2JlNDk0ZDAxMGE5MzZjNzcxZTc4YzU3YWU3MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ZXoT68RaPQenV4c76GR3BgTkGxHumq5hOGXJV9FWqA)

I can run koboldcpp_cu12.exe in OldCPU Presets, thank you very much！By the way, what software can be used to Unpack koboldcpp.exe?

**Comment by LostRuins** [comment]
It's an option inside the "Extras" tab
![image](https://github.com/user-attachments/assets/b12b81b2-dda3-46c1-bda9-6ea7e011592f)

**Comment by githubberers** [comment]
Thanks a lot
