### ISSUE TITLE
Repeated token issue

### ISSUE THREAD

**Issue by Vibecoder9000** [LostRuins/koboldcpp#1038]
**Describe the Issue**

The issue. Repeated tokens. 1k-2k into context, counting swipes and regenerations, the model suddenly devolves into repeating a single word/character(s). Different gguf models produce different tokens. For instance, Mistral Nemo instruct 2407 gguf produces "pered", while other models produce "(rr" and "Manners " and "alto". I'm using sillytavern, and I tested resetting samplers, DRY, different text completion presets, and pretty much every slider in AI response configuration. I've tried gguf models from q4-6, different context lengths. I've tried different instruction presets and Instruct mode. No worlds are active in Sillytavern. 
![image](https://github.com/user-attachments/assets/0b9eef97-7d50-49c3-8e73-21b1879887b0). For my extensions, I'm using character expressions only. Blank persona, but the issue persists with a well-written one, and a simple one. I've tried different characters. The issue persists in 1.69, 1.71, and 1.72. I've tried a new installation of Sillytavern. I imported a character, swiped it a couple of times, and it repeated.

Using vulkan, the first run ran at 22t/s, blas processing. It then crashed with error Processing Prompt [BLAS] (2016 / 2016 tokens)
Generating (41 / 2048 tokens)[WinError -1073741569] Windows Error 0xc00000ff. Running it with flash attention brings it down to CtxLimit:3452/8192, Amt:95/95, Process:0.15s (148.0ms/T = 6.76T/s), Generate:13.43s (141.3ms/T = 7.07T/s), Total:13.58s (7.00T/s).

CLblast: CtxLimit:3452/8192, Amt:95/95, Process:0.14s (142.0ms/T = 7.04T/s), Generate:11.66s (122.7ms/T = 8.15T/s), Total:11.80s (8.05T/s). No errors so far.

https://paste.quest/?6c1ea6d24186e57d#8PgNQpFJFEcUYfCZXHCCWWr4S9tFhgivpq4FJdug3bmy

**Additional Information:**
Please provide as much relevant information about your setup as possible, such as the Operating System, CPU, GPU, KoboldCpp Version, and relevant logs (helpful to include the launch params from the terminal output, flags and crash logs)

Newest Sillytavern via updateandlaunch.bat, koboldcpp 1.72, windows 11. Power limited 3090 to 300w. 

PC: 

PCPartPicker Part List: https://pcpartpicker.com/list/tzm4HG

CPU: AMD Ryzen 7 7700X 4.5 GHz 8-Core Processor  ($289.65 @ Newegg) 
CPU Cooler: Thermalright Peerless Assassin 120 SE WHITE ARGB 66.17 CFM CPU Cooler 
Motherboard: Asus ROG STRIX B650-A GAMING WIFI ATX AM5 Motherboard  ($217.76 @ Amazon) 
Memory: Silicon Power XPOWER Zenith RGB Gaming 64 GB (2 x 32 GB) DDR5-6000 CL30 Memory  ($187.99 @ Newegg Sellers) 
Storage: Crucial T500 2 TB M.2-2280 PCIe 4.0 X4 NVME Solid State Drive  ($145.99 @ Amazon) 
Storage: Crucial T500 2 TB M.2-2280 PCIe 4.0 X4 NVME Solid State Drive  ($145.99 @ Amazon) 
Video Card: EVGA XC3 BLACK GAMING GeForce RTX 3090 24 GB Video Card 
Power Supply: Asus ROG Strix Aura Edition 750 W 80+ Gold Certified Fully Modular ATX Power Supply  ($169.99 @ B&H) 
Custom: GIM ATX Mid-Tower PC Case White 10 Pre-Installed 120mm RGB Fans Gaming PC Case 2 Tempered Glass Panels Gaming Style Windows Computer & Desktop Case USB 3.0 I/O Port, Water-Cooling Ready (White) ($159.99)

**Comment by LostRuins** [comment]
Can you try running it without context shift (`--noshift`) and see if the same issue happens?

**Comment by Vibecoder9000** [comment]
Wow, worked. It's running into context limit now, reprocessing the entire history. I don't know what's happening here, but the issue's fixed. Thanks for helping. 

Edit: Intended. Didn't read the description of context shift.

**Comment by Vibecoder9000** [comment]
Well, it's started happening again. 1.72, same model. 4k context, but I started seeing it again with 32k originally—same symptoms as last time. Repeated "peredpered" around 2k into generated text, treats swipes on sillytavern, and retries on koboldai lite as continuations that count towards time till repetitions. I have no idea why it wasn't an issue, I tested running a blank character card with 2k context, and ran new messages until I crashed into context several times and it was deleting tokens, 40ish 300-400 token messages. That's why I closed, but apparently, there's another factor. I don't know where to begin with this one, and my environment hasn't changed except for reinstalling the same version of pytorch (pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121).

**Comment by LostRuins** [comment]
Okay now I'm kind of suspecting it to be an issue with this model architecture itself, since from your logs no context shift ever took place. Please try:
- Increase rep pen: Your rep pen is currently set to 1. Please try increasing it to 1.1, and setting a rep_pen_range of at least 300.
- Decrease temperature: Temp of 2 is probably a bit too high. Please try lowering it to 1.

If that does not work, try a different model and a different quant format.

**Comment by Vibecoder9000** [comment]
Weird results. I tried it, same thing. On swiping, it fixed itself for a few swipes, but then devolved halfway through. Asking the llm to explain gives this response. Do note that I'm no longer using koboldcpp as my main backend, as tabbyapi+exllamav2 is about 30-50% faster with context quantization and caching.

"-nd development consider the potential consequences and engage with stakeholders, including the public, is crucial for achieving aperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedperedpered\n[INST] Agn\u00e9s Oblige: stop saying that [/INST]\nplease stop repeating:", "max_new_tokens": 1000, "max_tokens": 1000, "logprobs": 10, "temperature": 1, "top_p": 1, "typical_p": 1, "typical": 1, "sampler_seed": -1, "min_p": 0.1, "repetition_penalty": 1.1, "frequency_penalty": 0, "presence_penalty": 0, "top_k": 0, "skew": 0, "min_tokens": 0, "length_penalty": 1, "early_stopping": false, "add_bos_token": true, "smoothing_factor": 0, "smoothing_curve": 1, "dry_allowed_length": 2, "dry_multiplier": 2, "dry_base": 2.03, "dry_sequence_breakers": "[\"\\n\", \":\", \"\\\"\", \"*\"]", "dry_penalty_last_n": 0, "max_tokens_second": 0, "stopping_strings": ["\nAgn\u00e9s Oblige:", "[INST] "], "stop": ["\nAgn\u00e9s Oblige:", "[INST] "], "truncation_length": 128000, "ban_eos_token": false, "skip_special_tokens": true, "top_a": 0, "tfs": 1, "mirostat_mode": 0, "mirostat_tau": 5, "mirostat_eta": 0.1, "custom_token_bans": "", "banned_strings": [], "api_type": "koboldcpp", "api_server": "http://127.0.0.1:5001/", "legacy_api": false, "sampler_order": [5, 6, 0, 1, 2, 3, 4], "grammar": "", "rep_pen": 1.1, "rep_pen_range": 300, "repetition_penalty_range": 300, "seed": -1, "guidance_scale": 1, "negative_prompt": "", "grammar_string": "", "repeat_penalty": 1.1, "tfs_z": 1, "repeat_last_n": 300, "n_predict": 1000, "num_predict": 1000, "num_ctx": 128000, "mirostat": 0, "ignore_eos": false, "n_probs": 10, "rep_pen_slope": 1, "stream": true}
Failed to process regex: '[^\r\n\p{L}\p{N}]?((?=[\p{L}])([^a-z]))*((?=[\p{L}])([^A-Z]))+|[^\r\n\p{L}\p{N}]?((?=[\p{L}])([^a-z]))+((?=[\p{L}])([^A-Z]))*|\p{N}| ?[^\s\p{L}\p{N}]+[\r\n/]*|\s*[\r\n]+|\s+(?!\S)|\s+'
Regex error: regex_error(error_stack): There was insufficient memory to determine whether the regular expression could match the specified character sequence.
[WinError -529697949] Windows Error 0xe06d7363

**Comment by Vibecoder9000** [comment]
1.3/1000, same result, 3/204000, unable to create a coherent responec.

**Comment by LostRuins** [comment]
So you get the same issue with exllama? Then it's definitely a model thing and not related to the backend

**Comment by Vibecoder9000** [comment]
No, I swapped to exlama for speed and to avoid the error. It does not appear in exllama. Also, trying different models in kobold results in the same bug.

**Comment by LostRuins** [comment]
Have you tried replacing or updating the AMD drivers? I think some of them might be a bit glitchy. Try 1.73?

**Comment by Vibecoder9000** [comment]
Sorry, amd drivers? I'm using a 3090. Is this referring to amd64?

**Comment by LostRuins** [comment]
Ah okay for some reason I thought you were running an amd card. Is there a reason you picked vulkan over cuda then?

**Comment by Vibecoder9000** [comment]
I was testing what actually worked, the issue is occurring with Cuda. I forget why, this issue is pretty old. You can check this discord thread for older info: https://discord.com/channels/1100685673633153084/1268649909310193767

I use tabbyapi now, much faster and with context caching. This fix isn't really that important for me, but for other people with the same issue.

**Comment by Vibecoder9000** [comment]
Closing as nobody else has this issue and I've found a workaround that's faster and better.
