### ISSUE TITLE
How to increase the generation limit in responses in apiopenai endpoint

### ISSUE THREAD

**Issue by investing0** [LostRuins/koboldcpp#1040]
Hello, The endpoint of the API openai has a generation limit in responses of 350 tokens, when using other ui, is it possible to somehow increase it to a limit of 4000 tokens, like in koboldlite. Tried in https://github.com/Bin-Huang/chatbox

**Comment by LostRuins** [comment]
Technically the frontend is responsible for setting this in the `max_tokens` field. However, next version I can expose a field for this value to be overwritten with an adapter. I can also increase the default slightly.

Does the frontend not allow you to trigger a continued generation after each one?

**Comment by investing0** [comment]
Technically the frontend is responsible for setting this in the max_tokens field. - Yea, this is strange, msty, gptnext and other, not this has function, only available in the syllitavern.

However, next version I can expose a field for this value to be overwritten with an adapter. of this kind? - http://localhost:5001/v1/max-tokens

I can also increase the default slightly. -- Can the answer be the maximum? The answer won't be 4000 tokens every time anyway, or will it bother others?

Does the frontend not allow you to trigger a continued generation after each one?  - nope


If you're wondering why I need other frontends:
1. https://github.com/ztjhz/BetterChatGPT - it's convenient to specify system, assistant, and person, the first picture is on the link, you can also do this in chatbox.
2. In the corporate theme, strange indents - https://postimg.cc/06rBJmSy  (And if there are a lot of lists and sublists, this stretches out a lot.)
and when you click edit a message that is in the middle of the chat, you have to scroll the page up. It's also better to center it on the left edge, otherwise little text fits in the center and the answer seems short, but you need to scroll to read it.

**Comment by LostRuins** [comment]
No, the amount to generate cannot be set arbitrarily high as it is taking buffer space from the context size.
