### ISSUE TITLE
Cant install koboldcpp

### ISSUE THREAD

**Issue by KintCark** [LostRuins/koboldcpp#1042]
Hey how do I run the koboldcpp.bin file I'm trying to install this on Android but I can get the file to work. I tried rename the file to koboldcpp.sh and chmod it but it still says no such file or directory please fix the file format am I supposed to extract it?

**Comment by LostRuins** [comment]
You need to use termux, the instructions are here:

https://github.com/LostRuins/koboldcpp?tab=readme-ov-file#compiling-on-android-termux-installation

follow them step by step.

**Comment by KintCark** [comment]
Nvm I'll just use stable diffusion ccp it's the same thing
