### ISSUE TITLE
How to use models?

### ISSUE THREAD

**Issue by KintCark** [LostRuins/koboldcpp#1044]
So I installed it on my phone but how do I use my own models I can't run automatic 1111 and koboldcpp at same time so can u make this app run Stable Diffusion models?

**Comment by pbz134** [comment]
It already runs Stable Diffusion models. Check the "Image" tab in the koboldcpp GUI, or type --help for more CLI arguments

**Comment by KintCark** [comment]
So if I use --model and put a checkpoint then when I type a prompt into the chat it will generate images?

**Comment by henk717** [comment]
Images are a seperate option, it will be with the Add Img button.

**Comment by LostRuins** [comment]
@KintCark use `--sdmodel` to load stable diffusion models. Run `--help` for more info.
Wiki is here https://github.com/LostRuins/koboldcpp/wiki

**Comment by KintCark** [comment]
> @KintCark use `--sdmodel` to load stable diffusion models. Run `--help` for more info.
> Wiki is here https://github.com/LostRuins/koboldcpp/wiki

Thx I figured it out
