### ISSUE TITLE
SSE streaming over API?

### ISSUE THREAD

**Issue by pbz134** [LostRuins/koboldcpp#1048]
Hello,

I heard that SSE streaming over API has now been added in the new update. However, I can't seem to make it work when changing the address from "const response = await axios.post(`${ENDPOINT}/api/v1/generate`, prompt);" to "const response = await axios.post(`${ENDPOINT}/api/extra/generate/stream`, prompt);"

koboldcpp doesn't seem to receive any input tokens and thus generates no response. Is this a user error or is the program bugged?

Here is the UI:
[UI-Test.zip](https://github.com/user-attachments/files/16509575/UI-Test.zip)

Thanks!

**Comment by LostRuins** [comment]
In order for you to use SSE streaming, your client needs to handle SSE responses. 

Take a look at https://medium.com/@david.richards.tech/sse-server-sent-events-using-a-post-request-without-eventsource-1c0bd6f14425

Alternatively, you can use polled-streaming which is easier to use. Take a look at https://lite.koboldai.net/koboldcpp_api#/api%2Fextra/get_api_extra_generate_check

**Comment by pbz134** [comment]
Thank you!
