### ISSUE TITLE
koboldcpp.exe crashes immediately after clicking the launch button. Help Me! I'm eager to start using koboldcpp

### ISSUE THREAD

**Issue by githubberers** [LostRuins/koboldcpp#1049]
Before launching model, I encounter an issue with related DLL files. The software crashes immediately after clicking the launch button. I've attached a screenshot of the error message for reference. Can someone help me troubleshoot this problem? I'm eager to start using koboldcpp
![a](https://github.com/user-attachments/assets/330eac68-380a-4cd0-b41a-7aa00e24cd74)
![2](https://github.com/user-attachments/assets/c7bf672a-01f6-487a-8eb7-94121430c102)
.

**Comment by LostRuins** [comment]
Follow up in https://github.com/LostRuins/koboldcpp/issues/1036
