### ISSUE TITLE
This is not an issue but a feature request 

### ISSUE THREAD

**Issue by KintCark** [LostRuins/koboldcpp#1053]
Hey how can I make the ai chat make an I'm a ge after adding an safetensors file I want the ai to write me an prompt then is generates the Image, is there a command or something to do this? I tried imagine/ create/ but it didn't work.

**Comment by LostRuins** [comment]
First, make sure both an image and text model is loaded in KoboldCpp.
Then. just prompt the AI as normal.
Once the text is generated, clik add img/automatically
![image](https://github.com/user-attachments/assets/bf2ab3a0-d8ff-4355-bc6a-1ba1b9e150ad)
