### ISSUE TITLE
Simple bug

### ISSUE THREAD

**Issue by Vibecoder9000** [LostRuins/koboldcpp#1055]
**Describe the Issue**
A clear and detailed description of what the issue is, and how to duplicate it (if applicable).

Putting a " ' " by typo in layers field crashes the program. That's it, that's the issue.

Also, it'd be great if auto was either not set on -1 on opening the program, that or having it set to max layers by default if the model can fit. I've started with a few layers missing for not really any reason, it's just an extra click.

**Additional Information:**
Please provide as much relevant information about your setup as possible, such as the Operating System, CPU, GPU, KoboldCpp Version, and relevant logs (helpful to include the launch params from the terminal output, flags and crash logs)

**Comment by LostRuins** [comment]
I would think that is a valid thing to do, since "'" is not a valid input for layers. It should popup as an error.
