### ISSUE TITLE
Request: Add input box to the idle duration in idle responses

### ISSUE THREAD

**Issue by morbidCode** [LostRuins/koboldcpp#1060]
Hello. The idle responses feature in kobold light UI is amazing. But for chatting with multiple characters, I find that the shortest duration available (15s) is too slow, since I sometimes want multiple characters to talk to each other. Can you add an additional textbox so we can manually input the exact duration? Thanks!

**Comment by LostRuins** [comment]
Fyi you can manually trigger a generation anytime by clicking the "Submit" button. What duration would you like to see added? I can add one more option.

**Comment by morbidCode** [comment]
Can you add 1s, 3s and 5s? Thanks!

**Comment by LostRuins** [comment]
I can add 5s, but 1s and 3s are too short and would probably be better triggered by submitting manually.

**Comment by morbidCode** [comment]
Sounds good, thanks!

**Comment by LostRuins** [comment]
5s option has been added in 1.73
