### ISSUE TITLE
unknown model architecture: '' and SEGV while loading the model sdxl_lightning_4step.q8_0.gguf

### ISSUE THREAD

**Issue by yurivict** [LostRuins/koboldcpp#1065]
koboldcpp fails to load [this](https://huggingface.co/OlegSkutte/SDXL-Lightning-GGUF/resolve/main/sdxl_lightning_4step.q8_0.gguf) model:
```
llama_model_loader: loaded meta data with 0 key-value pairs and 2641 tensors from /disk-samsung/llama-cpp-experiments/models/sdxl_lightning_4step.q8_0.gguf (version GGUF V3 (latest))
llama_model_load: error loading model: error loading model architecture: unknown model architecture: ''
llama_load_model_from_file: failed to load model
Segmentation fault
```

Version: 1.72
clang-18
FreeBSD 14.1

**Comment by LostRuins** [comment]
You need to load stable diffusion models with `--sdmodel` instead of `--model` (or using the GUI, select it as "Image Model", not "Model")

**Comment by yurivict** [comment]
There's no such field "Image Model".
There is the field "Stable Diffusion Model" on the "Image Gen" tab.
But this model fails later:
```
Warning: KCPP text generation not initialized!

Output: 
```

This model is supposed to generate images.

**Comment by LostRuins** [comment]
> There is the field "Stable Diffusion Model" on the "Image Gen" tab.

Yes that is correct.

I am confused. Do you not want to generate images? You don't prompt for text when you are generating images.

Instead, click and "Add Img" button 
![image](https://github.com/user-attachments/assets/ea7e0af1-465a-4d8f-ae90-c8893c898fce)
and then select "Custom Prompt" 
![image](https://github.com/user-attachments/assets/525f3e54-d5b8-40da-b763-fde552be00ff)
and type your image prompt.

Alternatively, KoboldCpp also comes with an image gen SD UI http://localhost:5001/sdui which you may prefer

**Comment by yurivict** [comment]
This worked.

Thank you for your help!
