### ISSUE TITLE
SDUI negative_prompt URL parameter not working / implemented

### ISSUE THREAD

**Issue by xifer** [LostRuins/koboldcpp#1072]
Works:
http://localhost:5001/sdui?prompt=prompt
(Seed, steps, width, height, etc work too.)

Does not work:
http://localhost:5001/sdui?negative_prompt=prompt

I checked out [https://github.com/LostRuins/koboldcpp/blob/concedo/kcpp_sdui.embd](https://github.com/LostRuins/koboldcpp/blob/concedo/kcpp_sdui.embd), it looked to me like seed, steps, width, height, prompt were implemented but not negative_prompt.

Is there another an un-minified version this is built from?

**Comment by LostRuins** [comment]
You are trying to run it as a get request to the url? Why not use the api directly then

**Comment by LostRuins** [comment]
Check out the sdapi reference

https://lite.koboldai.net/koboldcpp_api

**Comment by LostRuins** [comment]
https://github.com/ayunami2000/stable-ui

Stable UI comes from here. But it's been unmaintained for a while

**Comment by xifer** [comment]
> You are trying to run it as a get request to the url? Why not use the api directly then

I am using those http params as starting point when I launch sdui from a script.

> https://github.com/ayunami2000/stable-ui
> 
> Stable UI comes from here. But it's been unmaintained for a while

Ah, this is what I needed: https://github.com/ayunami2000/stable-ui/blob/1da33e7baecfad5cf91760b6c36f440eba5b24ec/src/stores/generator.ts#L374

Works:
http://localhost:5001/sdui?prompt=prompt%20%23%23%23%20negative%20prompt

"%20%23%23%23%20" = " ### "
And putting a '#' in the URL will not pass it as a character, so %23 is a required replacement.

Thanks!
