### ISSUE TITLE
DRY sampling is broken in release version 1.73

### ISSUE THREAD

**Issue by anon0730** [LostRuins/koboldcpp#1078]
I was wondering why I was suddenly getting a lot of repeating phrases again so I turned up the DRY multiplier and still the phrases would repeat so I suspected something is wrong with the backend and seems I was right. Using --debugmode you can see the DRY penalties are reported in the console but not properly applied.

Here's a part where the model is trying to repeat the clichéd phrase "her red eyes sparkling with mischief."
With DRY penalty off (multiplier 0) this is what I get:
![iblHL](https://github.com/user-attachments/assets/77167df2-da01-44a6-9acf-cf55d25ef427)
Now with DRY multiplier at 0.1 on koboldcpp 1.72 it penalizes some tokens, most notably the token "red" and this is what happens:
![DvpjZ](https://github.com/user-attachments/assets/921b4fea-400d-4a82-9d65-aeaa4b171ae7)
Using 0.8 multiplier the penalty is so big "red" is gone completely.
![image](https://github.com/user-attachments/assets/f6f33cdd-891e-4a77-ab32-97546a0d32d6)

Now let's try koboldcpp 1.73
DRY multiplier 0.1:
![image](https://github.com/user-attachments/assets/432e8b88-b065-409a-a7e8-08d63d4caa36)
DRY multiplier 0.8:
![image](https://github.com/user-attachments/assets/f4353780-39e7-444d-ae50-729dbc907d7d)
As you can see DRY tries to desperately penalize these tokens, each one more than the last because the penalized string keeps continuing but the probabilities don't reflect the penalty.

**Additional Information:**
Temperature 0.5, every other sampler disabled.
launch params used: `.\koboldcpp.exe --usecublas --threads 5 --highpriority --nommap --gpulayers 20 --contextsize 16384 --debugmode`
Windows exe releases of 1.72 and 1.73 used (cuda12 version)
Model: mini-magnum-12b-v1.1.Q5_K_M.gguf (Mistral-Nemo finetune)
Windows 10 with Ryzen 3600, RTX 2070 Super (though I don't think these would matter).

**Comment by LostRuins** [comment]
Bug is confirmed. In 1.73, dry is penalizing random tokens. A fix is being developed
 

For now, Do not use it or use 1.72

**Comment by LostRuins** [comment]
Alright, I've just released KCPP 1.73.1, which should solve this issue. Can you please update and try again?

**Comment by anon0730** [comment]
I tested around a bit and it seems to work without any problems again. The right tokens are penalized and the penalty is properly relative to multiplier. Thank you for fixing it, I'm gonna close the issue.
