### ISSUE TITLE
Please, introduce a manual stop button

### ISSUE THREAD

**Issue by NovNovikov** [LostRuins/koboldcpp#108]
# Expected Behavior

Would be nice to have a stop button that would stop the token generation immideately. The text generation webui has this kind of functionality. This is important because sometimes the automatic stop token recognition doesn't work.

# Current Behavior

Now there is now way to manually stop token generation.

**Comment by LostRuins** [comment]
Try enable streaming mode (just use `--stream --launch` to start).
Then when it's streaming, you can press the abort and it should work.
