### ISSUE TITLE
Program version number when using the -h command line argument

### ISSUE THREAD

**Issue by Vladonai** [LostRuins/koboldcpp#1083]
Starting with version 1.73, the version number is not printed when using the -h command line argument. It would be nice to return this information.

**Comment by LostRuins** [comment]
I did that to ensure no outputs are printed prematurely in case the user runs with --prompt

I'll add the version number into the help menu titles instead, how about this https://github.com/LostRuins/koboldcpp/commit/0b96097439e86fc79aa2d619ed2e96937b8f939a

**Comment by Vladonai** [comment]
"KoboldCpp Server - Version 1.74". That's enough.
