### ISSUE TITLE
IPv6 Socket Failed to Bind. IPv6 will be unavailable.

### ISSUE THREAD

**Issue by jojorne** [LostRuins/koboldcpp#1101]
**Describe the Issue**
A few days ago, kobo was crashing with IPv6 failure. So I disabled it. Today, I tried again and it doesn't crash anymore.
The first time was because it couldn't convert IPv4 to IPv6. Now, I don't know if it's still the same problem.

**Additional Information:**
KoboldCpp 1.74
Windows 11

**Comment by jojorne** [comment]
```python
if ipv6_sock:
    try:
        ipv6_sock.bind((addr, port))
        ipv6_sock.listen(numThreads)
    except Exception as ex:
        ipv6_sock = None
        print("IPv6 Socket Failed to Bind. IPv6 will be unavailable.")
```

`addr` here is IPv4 and not IPv6.

**Comment by LostRuins** [comment]
It tries to bind on both protocols. If IPv6 fails, you will still have IPv4 and vice versa.
Is your network dual stack?
Does going to http://localhost:5001 still work for you?

You can test each type specifically with http://127.0.0.1:5001 and [http://[::1]:5001/](http://[::1]:5001)

**Comment by jojorne** [comment]
Dual stack? 🤔

![image](https://github.com/user-attachments/assets/1972b0dc-23f7-4395-9724-e16f80f978bb)

But as IPv6 Socket Failed to Bind, [http://[::1]:5001/](http://%5B::1%5D:5001) is unavailable.

Edit: Okay, probably not dual stack then. 😅
