### ISSUE TITLE
Auto gpu layer

### ISSUE THREAD

**Issue by ss4elby** [LostRuins/koboldcpp#1105]
Hello, since I have updated to any version of 1.73 or the small update 1.73.1 using -1 it does not detect or use my gpu accurately. I have a tesla p40, I dunno what the major changes were but I know not its slow and using cpu so I have to change it manually to use the layers. Not a big deal but it is something that isnt working so I thought I would tell you.

**Comment by LostRuins** [comment]
Can you provide more details? What is not detected? Does the GPU name show up and switch to cublas mode?

**Comment by ss4elby** [comment]
Oh yes of course sorry I was not clear there. version 1.72 cublas tesla p40 if I select -1 it shows 43/43 layers on this model, but if I change to 1.73 or 1.73.1 same options it will show 27/43. Not a large deal I can just set it to 43 layers. But for some reason it's not taking all the layers, which I believe that is what the -1 was supposed to do.

**Comment by LostRuins** [comment]
The layer estimation now takes into account the current VRAM usage also. Do you have more than 1 card, and is the other card using memory?

**Comment by ss4elby** [comment]
I have two cards. I have one amd gpu, but that one should be not used by kobold, the tesla I have is only used for ai related stuff.

**Comment by LostRuins** [comment]
-1 bases it's calculations on the available free VRAM, so i'm guessing there might have been something else running that was also using VRAM and affecting the calculated value.

In any case, like you said, not a big issue - just override it with the correct values.

**Comment by ss4elby** [comment]
Thank you, I suppose you are right. Either way yes manually its fine!
