### ISSUE TITLE
error of scripr cobolcpp

### ISSUE THREAD

**Issue by zhadow01** [LostRuins/koboldcpp#111]
i open gmll-model.bin with cobolcpp, and see this error:
Identified as LLAMA model: (ver 3)

Attempting to Load...

System Info: AVX = 1 | AVX2 = 1 | AVX512 = © | AVX512_VBMI = © | AVX512_VNNI = @ | FMA = 1 | NEON = @ | ARM_FMA = © | F1
6C = 1 | FP16_VA = © | WASM_SIMD = 6 | BLAS = 1 | SSE3 = 1 | VSX = 0

Llama.cpp: loading model from C:\Users\zhadow\Desktop\gpt\ggml-model.bin

Llama_model_load_internal: format ggjt v1 (latest)

Llama_model_load_internal: n_vocab 32001

Llama_model_load_internal: n_ctx 20u8

Llama_model_load_internal: n_embd 5120

Llama_model_load_internal: n_mult = 256
Llama_model_load_internal: n_head 40
Llama_model_load_internal: n_layer = 40
Llama_model_load_internal: n_rot 128

Llama_model_load_internal: ftype
Llama_model_load_internal: n_ff 13824

Llama_model_load_internal: n_parts 1

Llama_model_load_internal: model size = 138

Llama_model_load_internal: ggml ctx size 73.73 KB
Llama_model_load_internal: mem required = 9807.47 MB (+ 1608.00 MB per state)
Traceback (most recent call last):

2 (mostly Qu_e)

File "koboldcpp.py", line 586, in <module>
File "koboldcpp.py", line 443, in main
File "koboldcpp.py", line 168, in load_model

OsError: [WinError -1073741795] Windows Error @xc900001d
[552] Failed to execute script 'koboldcpp' due to unhandled exception!

**Comment by LostRuins** [comment]
Try with `--noavx` flag, and make sure you have enough RAM.

**Comment by zhadow01** [comment]
> Try with `--noavx` flag, and make sure you have enough RAM.

how many RAM kobolcpp need?

and i start kobolcpp with --noavx, and this error:
Welcome to KoboldCpp - Version 1.12
Attempting to use OpenBLAS library for faster prompt ingestion. A compatible libopenblas will be required.
Initializing dynamic library: koboldcpp_openblas.dll
Loading model: C:\Users\zhadow\Desktop\gpt\ggml-model.bin
[Threads: 2, SmartContext: False]

---
Identified as LLAMA model: (ver 3)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from C:\Users\zhadow\Desktop\gpt\ggml-model.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =  73.73 KB
llama_model_load_internal: mem required  = 9807.47 MB (+ 1608.00 MB per state)
Traceback (most recent call last):
  File "koboldcpp.py", line 506, in <module>
  File "koboldcpp.py", line 443, in main
  File "koboldcpp.py", line 108, in load_model
OSError: [WinError -1073741795] Windows Error 0xc000001d
[7472] Failed to execute script 'koboldcpp' due to unhandled exception!

**Comment by LostRuins** [comment]
Try the latest version v1.15, run from the GUI and select the option `Use OpenBLAS (Old Devices)`

**Comment by zhadow01** [comment]
new error
Welcome to KoboldCpp - Version 1.15
For command line arguments, please refer to --help
Otherwise, please manually select ggml file:
Attempting to library without OpenBLAS.
Initializing dynamic library: koboldcpp.dll
==========
Loading model: C:\Users\zhadow\Desktop\gpt\koboldcpp.exe
[Threads: 2, SmartContext: False]

---
Identified as LLAMA model: (ver 0)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
gptj_model_load: loading model from 'C:\Users\zhadow\Desktop\gpt\koboldcpp.exe' - please wait ...
gptj_model_load: invalid model file 'C:\Users\zhadow\Desktop\gpt\koboldcpp.exe' (bad magic)
gpttype_load_model: failed to load model from 'C:\Users\zhadow\Desktop\gpt\koboldcpp.exe'
Load Model OK: False
Could not load model: C:\Users\zhadow\Desktop\gpt\koboldcpp.exe

**Comment by LostRuins** [comment]
what model are you trying to use? Is it a ggml model?

**Comment by zhadow01** [comment]
it is vicuna

**Comment by rombodawg** [comment]
I got the same error, when trying to run the vicuna 30b 8k model
