### ISSUE TITLE
Gguf llm support gone?

### ISSUE THREAD

**Issue by KintCark** [LostRuins/koboldcpp#1112]
How do we use local llm gguf models now I don't see anywhere a option for it. I liked the old version better....×_×

UPDATE: I saw a back button, I pressed it an boom!, I'm back to the older version:>

**Comment by LostRuins** [comment]
GGUF files are always supported. What do you mean you don't see an option for it?

**Comment by KintCark** [comment]
> GGUF files are always supported. What do you mean you don't see an option for it?

I found it I had to press the back button at bottom right which took me to the llm.
I was in stableui

**Comment by LostRuins** [comment]
You can always relaunch the UI with http://localhost:5001 in your web browser
