### ISSUE TITLE
Allow printing of non-ASCII characters

### ISSUE THREAD

**Issue by Kas1o** [LostRuins/koboldcpp#1124]
koboldcpp.py Line 2005
set ensure_ascii=False can help non-English user read their prompt simpler.

**Comment by LostRuins** [comment]
It should work. If it does not work, your terminal does not support printing non-english characters.

![image](https://github.com/user-attachments/assets/3aedd335-5aea-43f2-a188-aaf1952e2c6b)

**Comment by Kas1o** [comment]
![image](https://github.com/user-attachments/assets/86aaf21a-9183-4d63-968c-2be9de2f49cc)
I am using Windows Terminal, Output can display but Prompt will only display in unicode sequence.

**Comment by LostRuins** [comment]
Ah, that's because it's printing out the raw json stringified payload
