### ISSUE TITLE
Feature request: blank preset - all samplers disabled.

### ISSUE THREAD

**Issue by morbidCode** [LostRuins/koboldcpp#1127]
Hi,

I noticed that in some models huggingface page, They have recommended samplers like temperature, min_p, etc and no other values for other samplers. I think it means all other samplers are disabled. Same goes for new samplers like XTC, where you only tinker with DRY and min_p (and possibly temperature?) and ignore the rest. Problem is the default values for a sampler can be different (I.E. top_p=1, top_k =0), and so someone might accidentally leave some samplers on while trying to adjust the samplers into the recommended settings by the model.

My suggestion: let’s add a preset (blank preset?) where all samplers start off disabled, and then users can enable the ones they actually want.

What do you think?

**Comment by LostRuins** [comment]
Sure, I can do that.

**Comment by LostRuins** [comment]
Added in latest version
