### ISSUE TITLE
Mistral Gen 2 template

### ISSUE THREAD

**Issue by Vladonai** [LostRuins/koboldcpp#1133]
ver. 1.75.2
```
User tag:</s>\n[INST]
Assistant tag:[/INST]\n

```
Maybe the right thing to do
`User tag:</s>\n<s>\n[INST]`

Then the system prompt will have the form
```
<s>
[INST]User's Instructions[/INST]
Assistant's response
</s>

```
That would make sense, I think.

**Comment by LostRuins** [comment]
You'll have to check with @pandora-s-git who is from Mistral and contributed the new templates

**Comment by pandora-s-git** [comment]
Hi there, It is important to not include the newlines, if any question regarding the templates please  take a look at the following document explaining all the details: https://github.com/mistralai/cookbook/blob/main/concept-deep-dive/tokenization/chat_templates.md

All these white spaces are of extreme importance if we want it to match perfectly with the expected tokens.
