### ISSUE TITLE
Enhancement: Implement antislop-sampler

### ISSUE THREAD

**Issue by envy-ai** [LostRuins/koboldcpp#1141]
There's apparently work being done on a new sampler that is able to get rid of annoying recurring SLOP (Superfluous Language Overuse Pattern) phrases ("shivers down their spine", etc) without biasing against individual tokens by backtracking a configurable number of tokens and adjusting probabilities when one of these phrases is encountered.

https://github.com/sam-paech/antislop-sampler

Looks really promising for improving creative writing output and reducing GPT-isms.

**Comment by LostRuins** [comment]
Looks interesting.

**Comment by LostRuins** [comment]
Hi, this has been added in the latest release!
