### ISSUE TITLE
TTS support for aarch64(ARM64) OSX is broken, xtts-api-server, Alltalk Can not be installed on ARM64 OSX MAC

### ISSUE THREAD

**Issue by gihub24** [LostRuins/koboldcpp#1148]
**Describe the Issue**
xtts-api-server, Alltalk Can not be installed on ARM64 OSX.
Tried installing via pip install, and also tried via python3 -m pip install.
Each install gives various errors and cannot install: xtts-api-server,or Alltalk

xtts-api server error:
[https://github.com/daswer123/xtts-api-server/issues/87](https://github.com/daswer123/xtts-api-server/issues/87)

Alltalk error:
python -m unidic download
SSL: Certificate_verify_failed
error cannot download
[https://github.com/myshell-ai/MeloTTS/issues/62](https://github.com/myshell-ai/MeloTTS/issues/62)
Tried this still gives error:
SyntaxError: invalid syntax

2024 Macbook Air M2 16GB Sonoma 14.6.1

**Comment by LostRuins** [comment]
Alright, but that's not a koboldcpp issue, you should check with the respective devs of those softwares

**Comment by henk717** [comment]
I don't think XTTS is mac compatible in general, thats all third party stuff. The browser based TTS voices in the dropdown can work as an alternative.
