### ISSUE TITLE
How to avoid generate text contain * in chat mode

### ISSUE THREAD

**Issue by longerjim** [LostRuins/koboldcpp#1169]
**Describe the Issue**
I've use several different model on koboldcpp to chat with, and find same issue.
AI generate text between * like narrative or actions, some model even generate actions in [].
I know i can use eos token to cut the text, which will make content much smaller.
And i find no * text in chatgpt4o, so it is a model issue or koboldcpp setting?

![image](https://github.com/user-attachments/assets/dac0e7e5-38a1-47e0-b4ff-007fbdfb98dc)

**Additional Information:**
koboldcpp 1.72
Rocinante-12B-v2d
Eris_PrimeV4-Vision-32k-7B
NousResearch_Nous-Hermes-2-Vision

**Comment by LostRuins** [comment]
It's probably a prompting thing. But you can ban the * token if you want
