### ISSUE TITLE
[Feature Request] Optional notification sound when generation is finished

### ISSUE THREAD

**Issue by AllesMeins** [LostRuins/koboldcpp#1173]
This is just a small improvement, but I would very much appreciate it. I've a machine that's a bit on the slow side (or I tend to run models that are out of my league :-) ) so reply generation can take some time. So I was wondering: Would it be possible to add the option for some notification sound, once it is finished? 

Especially for chat mode this would feel quite natural - like in a chat with real people. You wouldn't stare on the screen like a maniac waiting for an answer. You would write your question and than do something else until you here the "beep" that a new message has arrived. So is this something you could add without too much hustle?

**Comment by LostRuins** [comment]
It exists, please select these options
![image](https://github.com/user-attachments/assets/488d9f9c-ad17-4eb0-99ff-80381d4b4ff8)

notify on done = gives a browser notification when response is done
beep on done = plays a beep when response is done

**Comment by AllesMeins** [comment]
Oh, thank you for your quick help. I must have missed it, because it's grouped with the TTS options and I didn't look closely enough. Sorry for wasting your time.
