### ISSUE TITLE
Inquiry about the priority of multiple GPU usage

### ISSUE THREAD

**Issue by Doooge** [LostRuins/koboldcpp#1174]
I would like to ask a question. My environment is Windows with multiple GPUs. When I start the program, I notice that although the memory of all GPUs is occupied, only the GPU 0 is always 100% utilized, while the load on other slots fluctuates occasionally. Is there any way to prioritize using the GPU1? The performance of these GPUs is different.

**Comment by LostRuins** [comment]
Main gpu is based on the order in nvidia-smi.

**Comment by Doooge** [comment]
Using the nvidia-smi command in the cmd window, I can see the call of each graphics card, if both graphics cards are in WDDM, I can manually disable the other graphics cards through the Device Manager, and change the target graphics card to GPU0. However, when the primary card is WDDM and the secondary graphics card mode is TCC, the secondary graphics card number will not change and will remain GPU0 (it seems that the order is determined by the name of the graphics card itself). I made the secondary graphics card work mode switch from TCC to WDDM, then disabled it and undisabled it again, making it GPU1, and successfully solved the problem. I hope that my experience can help other friends who encounter similar problems, and I also hope that in the future, the UI interface can provide the function of specifying a certain graphics card as an operation card on the basis of selecting multi-graphics card operations.

**Comment by Doooge** [comment]
It's also worth noting that when I only have one graphics card to work with, using a larger model or a longer context doesn't crash, but it slows down, and I guess the new version of the driver supports some features that allow excess data to be used up and then spread across memory, slowing down but running successfully.
When working on multiple graphics cards, the model I loaded is slightly larger or the context is too long, and the software directly reports an error and terminates due to insufficient memory, although it has little impact on the use after minor adjustments, I don't know if this situation is a problem

**Comment by Vladonai** [comment]
> Using the nvidia-smi command in the cmd window, I can see the call of each graphics card, if both graphics cards are in WDDM, I can manually disable the other graphics cards through the Device Manager, and change the target graphics card to GPU0. However, when the primary card is WDDM and the secondary graphics card mode is TCC, the secondary graphics card number will not change and will remain GPU0 (it seems that the order is determined by the name of the graphics card itself). I made the secondary graphics card work mode switch from TCC to WDDM, then disabled it and undisabled it again, making it GPU1, and successfully solved the problem. I hope that my experience can help other friends who encounter similar problems, and I also hope that in the future, the UI interface can provide the function of specifying a certain graphics card as an operation card on the basis of selecting multi-graphics card operations.

As far as I know, the CUDA driver sorts cards by performance (although this can be changed at the application level). But nvidia-smi sorts cards by the order in which they are placed in PCIe slots. As for choosing the order of cards in koboldcpp, the command “set CUDA_VISIBLE_DEVICES=0,1,2” where 0,1,2 are GPU 0, 1 or 2 respectively can help. The order can be changed "set CUDA_VISIBLE_DEVICES=1,2,0" for example.

**Comment by LostRuins** [comment]
yup, that indeed should help solve your issue

**Comment by Doooge** [comment]
Thank you very much
