### ISSUE TITLE
Ability to load multiple LoRA for SD Image Generation

### ISSUE THREAD

**Issue by dajamox** [LostRuins/koboldcpp#1181]
**Describe the Issue**
There are a variety of LoRA for different purposes, such as better image generation with much fewer needed steps like SDXL-Lightning, different art styles, scene compositions, characters.

Being able to load only one is very limiting, even more so for those with weaker hardware who want to try various models in combination with SDXL-Lightning with other LoRA, so it would be amazing to have this feature available.

**Usecase**
* Using a standard SDXL/Pony model, loading the SDXL-Lightning LoRA for image generation with fewer steps, and then loading a style LoRA, character LoRA, etc.

**Additional Information:**
 - gpu: `AMD Radeon RX 590 Series (radeonsi, polaris10, LLVM 18.1.8, DRM 3.59)`
 - cpu: `AMD Ryzen 5 3600 6-Core Processor`
 - koboldcpp: `1.76`
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.2-xanmod1, NixOS, 24.11 (Vicuna), 24.11.20241014.a3c0b3b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - nixpkgs: `/nix/store/xnjw9gmfmpppdj6bxpw6cfkspc3h6xwl-source`

**Comment by LostRuins** [comment]
Have you considered merging some of them together?

**Comment by dajamox** [comment]
> Have you considered merging some of them together?

If koboldcpp provides a script for it, I didn't know. I would like it if you could kindly pointed me to some resources for that as I'm still quite new to this.

Using such a method wouldn't be a great solution though. For example, quickly changing between weights/strength for different LoRA wouldn't be possible and you'd have to make multiple merges with different weights and keep them all on disk, which would increase space usage substantially.

I'm not aware of how speedy such a process would be on weaker hardware either, and my hardware barely qualifies as low-end at this point.

I'm sorry if this is a big task to ask for, I would love for this feature to be implemented, but I understand if you don't want to do it.

**Comment by LostRuins** [comment]
Yeah unfortunately for the moment I think only a single lora is supported.

**Comment by dajamox** [comment]
Unfortunate but understandable, should this issue be closed or remain open?

**Comment by LostRuins** [comment]
I'll close it for now, may be revisited in future

**Comment by basxto** [comment]
Does this work with bf3f2e1ba814db6f92aecc4bdc58c28ea3662bfc ?

**Comment by LostRuins** [comment]
Yes, multiple lora is now supported.
