### ISSUE TITLE
Add a feature to choose the next character chatting in a card.

### ISSUE THREAD

**Issue by pbz134** [LostRuins/koboldcpp#1183]
When having a conversation with multiple characters (e.g. chatting with a character card and then adding more participants), the one who writes the next message is chosen randomly, it seems.

Sometimes I have to regenerate and cancel 10 times to get the character I want to respond.

I think it would be nice to add a set of buttons somewhere that allows the user to select a specific participant for the next turn in the chat :)

**Comment by LostRuins** [comment]
This feature exists. Click the Chat Participants button at the bottom left corner

![image](https://github.com/user-attachments/assets/5a7a0975-d52f-46cd-9f62-5371936267ad)

you can add, enable or disable characters here

**Comment by pbz134** [comment]
Ah, that's just what I needed! Thanks!
