### ISSUE TITLE
Koboldcpp crashes.

### ISSUE THREAD

**Issue by Mumitroll95** [LostRuins/koboldcpp#1185]
Try to learn as much as possible about the GPU layers if you need launch buttons that close quickly using the command line, after which everything closes.
Windows 10
AMD Ryzen 7 PRO 2700 Eight-Core Processor 
NVIDIA GeForce RTX 4070 Ti SUPER
Memory 32.0GB Speed: 2400 MHz
Llama-3.1-70B-Instruct-lorablated-Q4_K_L.gguf
If you leave the value -1, the web version starts, but text generation is very slow, 1 word per minute. 
Please tell me if I'm choosing the wrong settings or the wrong model?
![1](https://github.com/user-attachments/assets/acf9b942-d175-443e-8551-67251a3087f0)
![2](https://github.com/user-attachments/assets/d720baec-2242-4e42-8047-cc3622ee31e4)
![3](https://github.com/user-attachments/assets/aa2c939d-fd1d-446a-bf1d-f31db315eef9)
![4](https://github.com/user-attachments/assets/b1a5d930-65e6-4cc2-ae10-a375407c4d37)

**Comment by manuel-schmied** [comment]
I don't completely understand your grammar, but I'm assuming you have a crash when you try to set layers to a high value manually.
In this case, the crash probably occurs because you try to stuff more layers into your VRAM than fit. -1 will try to auto set it short of that.

And while 1 word per minute is very slow, you will not find a setting over 1T/sec probably with your hardware on that model, because it doesn't fit into your 16GB VRAM and the automatic CPU offload (which helps you run it at all) is the bottleneck.

**Comment by Mumitroll95** [comment]
> I don't completely understand your grammar, but I'm assuming you have a crash when you try to set layers to a high value manually. In this case, the crash probably occurs because you try to stuff more layers into your VRAM than fit. -1 will try to auto set it short of that.
> 
> And while 1 word per minute is very slow, you will not find a setting over 1T/sec probably with your hardware on that model, because it doesn't fit into your 16GB VRAM and the automatic CPU offload (which helps you run it at all) is the bottleneck.

I'm not very experienced in this matter, please tell me, it turns out that I can't use 70B models above Q4 at all? Theoretically, my graphics card is powerful enough for this.

**Comment by manuel-schmied** [comment]
> I'm not very experienced in this matter, please tell me, it turns out that I can't use 70B models above Q4 at all? Theoretically, my graphics card is powerful enough for this.

Only very slowly with CPU offload as you experienced. Even highly quantized ggufs like Q2 of 70B will usually have over 24GB and file size roughly correlates with VRAM usage. Then context comes on top. So even a 4090 cannot run 70b fully in the GPU. Your 16GB VRAM will not fit the roughly 40gb by a large margin, you'd need 3 4070 Ti SUPER for that.

**Comment by Mumitroll95** [comment]
Thanks for the explanation

> > I'm not very experienced in this matter, please tell me, it turns out that I can't use 70B models above Q4 at all? Theoretically, my graphics card is powerful enough for this.
> 
> Only very slowly with CPU offload as you experienced. Even highly quantized ggufs like Q2 of 70B will usually have over 24GB and file size roughly correlates with VRAM usage. Then context comes on top. So even a 4090 cannot run 70b fully in the GPU. Your 16GB VRAM will not fit the roughly 40gb by a large margin, you'd need 3 4070 Ti SUPER for that.

Thanks for the explanation
