### ISSUE TITLE
Whisper errors on KoboldAI Lite frontend (SillyTavern with same KoboldCpp Whisper works well)

### ISSUE THREAD

**Issue by Denplay195** [LostRuins/koboldcpp#1189]
When using Whisper model (ggml-tiny-en.bin) in KoboldAI Lite frontend (SillyTavern works perfectly well with the same Whisper loaded through KoboldCpp), a window shows 'Error while submitting prompt: Error: Error occurred while SSE streaming: Service Unavailable' and doesn't start processing the text appeared after recognition

If I try again with token streaming changed to 'Poll' or even 'Off' it says 'Error occurred during text generation: {"detail":{"msg":"Server is busy; please try again later.","type":"service_unavailable"}}'

![image](https://github.com/user-attachments/assets/3283c684-7c42-4184-90c6-5bafb46ba044)

Same with every text and whisper models I've tried, no matter which size (From 3b to 13b)
Also switching the voice input modes doesn't help

NoAVX2 Vulkan backend

**Comment by Denplay195** [comment]
It seems like the voice input in KoboldAI Lite frontend is showing to be busy though it was already finished, the generation starts when I close the error window and click on "Busy" submit mic button

**Comment by LostRuins** [comment]
Thanks for reporting this. This happens because the request comes too soon. An easy fix is to enable multiuser mode (checkbox or using `--multiuser`). It will be fixed in the next version.

**Comment by LostRuins** [comment]
Hi, should be fixed in the latest build

**Comment by Denplay195** [comment]
![image](https://github.com/user-attachments/assets/cde6d7cc-825d-4c67-8b2a-eb2f1b1f2575)
Indeed it is! (I've tested without multiuser), closing the issue 👍
