### ISSUE TITLE
Multiuser issue

### ISSUE THREAD

**Issue by longerjim** [LostRuins/koboldcpp#1193]
**Describe the Issue**
A koboldcpp instance is loaded and two user is using it.
Two user use different prompt to chat with and cause server to Processing full Prompt every time some output is generated. 

Is there any config i missed or contextshift do not support the situation that different context is using at same time?

**Additional Information:**
koboldcpp 1.76

**Comment by LostRuins** [comment]
This is correct, contextshift will not work if two users use two completely different prompts. Prompt processing is usually quite fast if using CUDA or Vulkan.
