### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by dmitriyaleksandr** [LostRuins/koboldcpp#1194]
Hello friends
I use SillyTavern (last release) with coboldcpp (1.76 - koboldcpp_cu12). 
System 12900 + 32RAM + 4090.
I try model MN-12B-Lyra-v4-GGUF from QuantFactory (HF). Context size i use - 8064.
After a short time of correspondence, the AI gets stuck in a loop, replies by repeating the same characters/words without meaning (just repeats one letter or more in the reply, examle - "let let let let").
I use the default settings of koboldcpp. I just raise the context a little 8064 (the same context 8064 is in the tavern).
In webui with same model (MN-12B-Lyra-v4-GGUF) and default settings - all works fine.
All models that I tried above 7B were stuck (with recommended presets, ready presets, etc.)
I like cobold, it works great with all my 7B, but i want to solve this problem and move to 12B and above.
Maybe something is wrong with my settings? What I don't understand? Please help me.

**Comment by pl752** [comment]
Check temperature, dry and xtc sampler settings and min_p is set to 0.01 or higher. Also verify checksums of used models and try something like testmem and memtest-vulkan to verify your RAM and 4090's VRAM are stable and don't spoil up the weights data. Also try compiling from sources or using older versions of binary to check for bugs, also check if behavior is reproducible with NoBlas (cpu-only). Also very low bit quants of weights (<=4bpw) or cache can sometimes yield unexpected behaviors. Also you can try different version of CUDA toolkit.
(Edit: Also 8064 is not power of two, try something like 8192 if your vram size is sufficient)

**Comment by dmitriyaleksandr** [comment]
> (Edit: Also 8064 is not power of two, try something like 8192 if your vram size is sufficient)

Thank you! of course I made a 8192 (I made a mistake in my description)
