### ISSUE TITLE
1.77 initialization too slow

### ISSUE THREAD

**Issue by morbidCode** [LostRuins/koboldcpp#1196]
Hi,
I noticed something wierd in the latest version 1.77. The loading of the model became extremely slow. I use 3x RTX 6000 Ada on runpod, all layers offloaded. In 1.76, I'll only have to wait for about 5 to 15 minutes for the model to be loaded successfully, but 1.77 is taking aprox 30 to 45 mins (tested it 3 times). Here's the relevant output from the terminal.

    llm_load_print_meta: general.name     = Lumikabra 195B_v0.3
    llm_load_print_meta: BOS token        = 1 '<s>'
    llm_load_print_meta: EOS token        = 2 '</s>'
    llm_load_print_meta: UNK token        = 0 '<unk>'
    llm_load_print_meta: LF token         = 781 '<0x0A>'
    llm_load_print_meta: EOG token        = 2 '</s>'
    llm_load_print_meta: max token length = 48
    llm_load_tensors: ggml ctx size =    2.78 MiB
    // hangs up to 30 mins, only about 10 to 15 mins on 1.76 and earlier
    llm_load_tensors: offloading 140 repeating layers to GPU
    llm_load_tensors: offloading non-repeating layers to GPU
    llm_load_tensors: offloaded 141/141 layers to GPU
    llm_load_tensors:        CPU buffer size =   216.00 MiB
    llm_load_tensors:      CUDA0 buffer size = 37321.22 MiB
    llm_load_tensors:      CUDA1 buffer size = 36516.84 MiB
    llm_load_tensors:      CUDA2 buffer size = 36720.42 MiB
    .................................................................................................... // these dots take 10 to 15 minuts, only takes like 30 seconds for 1.76 and earlier
    Automatic RoPE Scaling: Using model internal value.

What should I do? I'm using the cuda 1210 version.

Thanks!

**Comment by LostRuins** [comment]
The first time you load a new version, it needs to compile the kernels. This is normal. Just let it load, close and restart once done. It should be fine.
