### ISSUE TITLE
Oute TTS integration

### ISSUE THREAD

**Issue by Raskoll2** [LostRuins/koboldcpp#1202]
https://github.com/edwko/OuteTTS/

Oute TTS is a llama based speech model, meaning it works with llama.cpp and can be quantized as a gguf. This would be an awesome model to have in the audio tab like whisper. 

I don't think koboldcpp supports the TTS part of the openai API, and implementing it entirely for this model would suck, but just adding it as a drop down TTS provider is plenty. Having a standard voice pipeline would be a good base to create things like OpenWeb UI's call mode, and home assistant integration or what not. It opens doors!

Being llama.cpp compatible should make this pretty easy, please consider it 🙏. Thanks for your hard work

**Comment by LostRuins** [comment]
It's not llama.cpp compatible. 

OuteTTS uses and relies on pytorch, not ggml. Take a look at https://github.com/edwko/OuteTTS/blob/main/outetts/v0_1/encoder/model.py

**Comment by logikstate** [comment]
the latest github code has inference via llama-cpp-python bindings https://github.com/edwko/OuteTTS

# Configure the GGUF model
model_config = outetts.GGUFModelConfig_v1(
    model_path="local/path/to/model.gguf",
    language="en", # Supported languages in v0.2: en, zh, ja, ko
    n_gpu_layers=0,
)

# Initialize the GGUF interface
interface = outetts.InterfaceGGUF(model_version="0.2", cfg=model_config)

**Comment by LostRuins** [comment]
It still requires pytorch and transformers

**Comment by logikstate** [comment]
looks like this got added to llama cpp already https://github.com/ggerganov/llama.cpp/tree/master/examples/tts

**Comment by LostRuins** [comment]
It's added in the latest release v1.82!
