### ISSUE TITLE
0xc0000142 error

### ISSUE THREAD

**Issue by condblock** [LostRuins/koboldcpp#1208]
![image](https://github.com/user-attachments/assets/91050abb-517c-4ff3-8060-57d69f9ea3f0)
i just dowloaded koboldcpp_cu12.exe and execute it.

**Comment by condblock** [comment]
[1.76](https://github.com/LostRuins/koboldcpp/releases/tag/v1.76) is working

**Comment by LostRuins** [comment]
Try redownload the exe, reboot your PC, and launch it again. Make sure its not blocked by any antivirus.

If the cu12 version does not work, try the koboldcpp.exe (cu11) instead
