### ISSUE TITLE
HIPBLAS no longer works when compiling from source on Linux after upgrade to ROCM 6.2.2

### ISSUE THREAD

**Issue by alraban** [LostRuins/koboldcpp#1216]
**Describe the Issue**
I've been building koboldcpp from source with HIPBLAS enabled on Linux for a year or so with great success:  everything was working fine until a few weeks ago.  Then my distro upgraded all ROCM libraries to 6.2.2 a couple weeks back, and koboldcpp no longer works when attempting to use HIPBLAS, after compiling with HIPBLAS enabled.  The compile appears to go correctly, and koboldcpp superficially runs, but whenever I attempt to chat with a model I get the following error:

> Processing Prompt (18 / 18 tokens)
> rocBLAS error: Tensile solution found, but exception thrown for { a_type: "f16_r", b_type: "f16_r", c_type: "f16_r", d_type: "f16_r", compute_type: "f16_r", transA: 'T', transB: 'N', M: 6144, N: 18, K: 6144, alpha: 1, row_stride_a: 1, col_stride_a: 6144, row_stride_b: 1, col_stride_b: 6144, row_stride_c: 1, col_stride_c: 6144, row_stride_d: 1, col_stride_d: 6144, beta: 0, batch_count: 1, strided_batch: true, stride_a: 1, stride_b: 1, stride_c: 1, stride_d: 1, atomics_mode: atomics_allowed }
> Alpha value 7.21875 doesn't match that set in problem: 1
> This message will be only be displayed once, unless the ROCBLAS_VERBOSE_TENSILE_ERROR environment variable is set.
> ROCm error: CUBLAS_STATUS_INTERNAL_ERROR
>   current device: 0, in function ggml_cuda_op_mul_mat_cublas at ggml/src/ggml-cuda.cu:1245
>   hipblasGemmEx(ctx.cublas_handle(id), HIPBLAS_OP_T, HIPBLAS_OP_N, row_diff, src1_ncols, ne10, &alpha_f16, src0_ptr, HIPBLAS_R_16F, ne00, src1_ptr, HIPBLAS_R_16F, ne10, &beta_f16, dst_f16.get(), HIPBLAS_R_16F, ldc, HIPBLAS_R_16F, HIPBLAS_GEMM_DEFAULT)
> ggml/src/ggml-cuda.cu:72: ROCm error
> error: Could not convert process PID: "attach 29105" into a pid.
> Aborted (core dumped)
> 

I tested with a fresh compile of the current version of koboldcpp and also with compiles of several older releases as well (going back to 1.67) and all fail in a similar way (albeit the older versions show slightly different errors).  The problems started with all compiles immediately after the ROCM library upgrade.

The VULKAN backend mostly works fine, but is less performant and occasionally "binds up" (generating nonsense results like the letters "ck" over and over until the program is restarted), so I thought I'd report the issue in hopes that the HIPBLAS issue could be resolved.

About my setup:

I'm running on Arch Linux with an AMD 7900XT.  Everything worked great for a year or so until the ROCM update.

**Comment by LostRuins** [comment]
Is downgrading the rocm library possible? This seems like it would be out of my control.

Unfortunately I can't really support ROCM directly as I don't have an AMD card. Perhaps you can try @YellowRoseCx fork if it's been solved there https://github.com/YellowRoseCx/koboldcpp-rocm

**Comment by alraban** [comment]
Downgrading is possible but only a temporary fix, obviously, as the ROCM libs will continue to be upgraded in the future.  I wasn't sure what the status of support here was as up until now mainline koboldCPP has been compiling with HIPBLAS and working correctly.

I did try Yellow Rose's fork but it gave an identical error.  I would report the bug over there, but they don't have issues open so I didn't see any way to file a bug there?

**Comment by LostRuins** [comment]
Ah I see. Perhaps you can also report this issue on the rocm library side of things. I'm sorry I can't really help there.

**Comment by YellowRoseCx** [comment]
If it's not an rocblas issue it might be a llama.CPP issue

https://github.com/ggerganov/whisper.cpp/issues/2541


Maybe you could try deleting your rocblas tensile solutions and seeing if that helps


I don't remember where they're kept exactly, I think it's in a .folder in your home folder, and I'm not home to check right now

**Comment by YellowRoseCx** [comment]
the files at ``/home/USERNAME/.config/miopen`` i.e. ``~/.config/miopen``, back them up (just in case) and then delete them all, the next time you use rocblas it should remake the file and maybe fix the issue? It's where the user database for tensile solutions are stored 

https://rocm.docs.amd.com/projects/MIOpen/en/latest/conceptual/perfdb.html

I know it's for MIOpen, but I believe miopen is part of rocblas operations

**Comment by alraban** [comment]
At your suggestion I checked some of the upstream bug trackers, and it looks like it was an issue with the way my distro (Arch Linux) was packaging rocblas.  Here's the relevant bug report with someone seeing a similar error, and a fix:  https://gitlab.archlinux.org/archlinux/packaging/packages/rocblas/-/issues/2

The rebuilt rocblas with the fix hit the repos tonight, and based on my initial tests HIPBLAS is working again.   Thanks very much for your help, I'm closing this now!
