### ISSUE TITLE
Version 1.78 warning: tensor 'token_embd.weight' cannot be used with preferred buffer type CUDA_Host, using CPU instead

### ISSUE THREAD

**Issue by loge-gh** [LostRuins/koboldcpp#1223]
With version 1.78 some strange warning has appeared:
`llm_load_tensors: tensor 'token_embd.weight' (f16) (and 0 others) cannot be used with preferred buffer type CUDA_Host, using CPU instead`
Despite the warning it looks like the model still using CUDA: on RTX 3090
`txLimit:232/8192, Amt:220/220, Init:0.00s, Process:0.01s (0.9ms/T = 1166.67T/s), Generate:4.46s (20.3ms/T = 49.37T/s), Total:4.46s (49.31T/s)`
I'm observing this behavior for every model I load with 1.78 in contrast with 1.77 which works just fine. This holds for every quantization I've tried. E.g. for Mistral-Large-Instruct-2407-Q4_K_M 
`llm_load_tensors: tensor 'token_embd.weight' (q4_K) (and 524 others) cannot be used with preferred buffer type CUDA_Host, using CPU instead`

**Additional Information:**
I'm using Linux binary build from "Releases" page. My custom build shows the same behavior.

Model loading log:
``` ./koboldcpp-linux-x64-cuda1210 --model ~/models/Llama3/Llama-3.1-8B-Lexi-Uncensored_V2_F16.gguf --contextsize 8192  --threads 16 --gpulayers 99 --tensor_split 1 0  --port 12000 --flashattention 
***
Welcome to KoboldCpp - Version 1.78
No GPU or CPU backend was selected. Trying to assign one for you automatically...
Auto Selected CUDA Backend...

Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.so
==========
Namespace(benchmark=None, blasbatchsize=512, blasthreads=16, chatcompletionsadapter='', config=None, contextsize=8192, debugmode=0, flashattention=True, forceversion=0, foreground=False, gpulayers=99, highpriority=False, hordeconfig=None, hordegenlen=0, hordekey='', hordemaxctx=0, hordemodelname='', hordeworkername='', host='', ignoremissing=False, launch=False, lora=None, mmproj='', model='/home/loge/llm/models/Llama3/Llama-3.1-8B-Lexi-Uncensored_V2_F16.gguf', model_param='/home/loge/llm/models/Llama3/Llama-3.1-8B-Lexi-Uncensored_V2_F16.gguf', multiuser=1, noavx2=False, noblas=False, nocertify=False, nofastforward=False, nommap=False, nomodel=False, noshift=False, onready='', password=None, port=12000, port_param=5001, preloadstory='', prompt='', promptlimit=100, quantkv=0, quiet=False, remotetunnel=False, ropeconfig=[0.0, 10000.0], sdclamped=0, sdclipg='', sdclipl='', sdconfig=None, sdlora='', sdloramult=1.0, sdmodel='', sdquant=False, sdt5xxl='', sdthreads=0, sdvae='', sdvaeauto=False, showgui=False, skiplauncher=False, smartcontext=False, ssl=None, tensor_split=[1.0, 0.0], threads=16, unpack='', useclblast=None, usecpu=False, usecublas=['normal', 'mmq'], usemlock=False, usevulkan=None, whispermodel='')
==========
Loading model: /home/loge/llm/models/Llama3/Llama-3.1-8B-Lexi-Uncensored_V2_F16.gguf

The reported GGUF Arch is: llama
Arch Category: 0

---
Identified as GGUF model: (ver 6)
Attempting to Load...
---
Using automatic RoPE scaling for GGUF. If the model has custom RoPE settings, they'll be used directly instead!
It means that the RoPE values written above will be replaced by the RoPE values indicated after loading.
System Info: AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | AMX_INT8 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | RISCV_VECT = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | 

Initializing CUDA, please wait, this might take a while for first run...
ggml_cuda_init: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
  Device 1: NVIDIA GeForce GTX 1080, compute capability 6.1, VMM: yes
llama_load_model_from_file: using device CUDA0 (NVIDIA GeForce RTX 3090) - 23887 MiB free
llama_load_model_from_file: using device CUDA1 (NVIDIA GeForce GTX 1080) - 7998 MiB free
llama_model_loader: loaded meta data with 28 key-value pairs and 292 tensors from /home/loge/llm/models/Llama3/Llama-3.1-8B-Lexi-Uncensored_V2_F16.gguf (version GGUF V3 (latest))
llm_load_vocab: special tokens cache size = 256
llm_load_vocab: token to piece cache size = 0.7999 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 128256
llm_load_print_meta: n_merges         = 280147
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 131072
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 500000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 131072
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: ssm_dt_b_c_rms   = 0
llm_load_print_meta: model type       = 8B
llm_load_print_meta: model ftype      = Q4_0_4_8
llm_load_print_meta: model params     = 8.03 B
llm_load_print_meta: model size       = 14.96 GiB (16.00 BPW) 
llm_load_print_meta: general.name     = Meta Llama 3.1 8b Instruct
llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
llm_load_print_meta: EOS token        = 128009 '<|eot_id|>'
llm_load_print_meta: EOT token        = 128009 '<|eot_id|>'
llm_load_print_meta: EOM token        = 128008 '<|eom_id|>'
llm_load_print_meta: PAD token        = 128004 '<|finetune_right_pad_id|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_print_meta: EOG token        = 128008 '<|eom_id|>'
llm_load_print_meta: EOG token        = 128009 '<|eot_id|>'
llm_load_print_meta: max token length = 256
llm_load_tensors: tensor 'token_embd.weight' (f16) (and 0 others) cannot be used with preferred buffer type CUDA_Host, using CPU instead
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading output layer to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:   CPU_Mapped model buffer size =  1002.00 MiB
llm_load_tensors:        CUDA0 model buffer size = 14315.02 MiB
.........................................................................................
Applying Tensor Split...Automatic RoPE Scaling: Using (scale:1.000, base:500000.0).
llama_new_context_with_model: n_seq_max     = 1
llama_new_context_with_model: n_ctx         = 8448
llama_new_context_with_model: n_ctx_per_seq = 8448
llama_new_context_with_model: n_batch       = 512
llama_new_context_with_model: n_ubatch      = 512
llama_new_context_with_model: flash_attn    = 1
llama_new_context_with_model: freq_base     = 500000.0
llama_new_context_with_model: freq_scale    = 1
llama_new_context_with_model: n_ctx_per_seq (8448) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
llama_kv_cache_init:      CUDA0 KV buffer size =  1056.00 MiB
llama_new_context_with_model: KV self size  = 1056.00 MiB, K (f16):  528.00 MiB, V (f16):  528.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     0.49 MiB
llama_new_context_with_model: pipeline parallelism enabled (n_copies=4)
llama_new_context_with_model:      CUDA0 compute buffer size =   356.52 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    74.02 MiB
llama_new_context_with_model: graph nodes  = 903
llama_new_context_with_model: graph splits = 2
Load Text Model OK: True
Embedded KoboldAI Lite loaded.
Embedded API docs loaded.
Starting Kobold API on port 12000 at http://localhost:12000/api/
Starting OpenAI Compatible API on port 12000 at http://localhost:12000/v1/
======
Please connect to custom endpoint at http://localhost:12000
```

**Comment by LostRuins** [comment]
Don't worry about it. it's just 1 layer (the weights of a single tensor) that is using CPU instead. It's not an error just a warning.

**Comment by loge-gh** [comment]
For me it looks like some bug in underlying llama.cpp. The current build of llama.cpp does not show this warning. Anyway, thank you for the clarification.

**Comment by duynt575** [comment]
I have that warning for all models as well (version 1.79.1).

`llm_load_print_meta: model params     = 9.24 B
llm_load_print_meta: model size       = 6.19 GiB (5.75 BPW)
llm_load_print_meta: general.name     = Gemma 2 9B It SPPO Iter3
llm_load_print_meta: BOS token        = 2 '<bos>'
llm_load_print_meta: EOS token        = 1 '<eos>'
llm_load_print_meta: EOT token        = 107 '<end_of_turn>'
llm_load_print_meta: UNK token        = 3 '<unk>'
llm_load_print_meta: PAD token        = 0 '<pad>'
llm_load_print_meta: LF token         = 227 '<0x0A>'
llm_load_print_meta: EOG token        = 1 '<eos>'
llm_load_print_meta: EOG token        = 107 '<end_of_turn>'
llm_load_print_meta: max token length = 48
llm_load_tensors: tensor 'token_embd.weight' (q6_K) (and 244 others) cannot be used with preferred buffer type CUDA_Host, using J)}o^s(This is not an error, it just means some tensors will use CPU instead.)`

Some other warnings: for Mistral Small it's '344 others', for Qwen 2.5 Coder 14B it's '362 others'...

**Comment by otherroch** [comment]
I'm seeing something similar, but perhaps I'm wrong..... and it could be a completely different problem. 

But llamacpp (from this docker image: **ghcr.io/ggerganov/llama.cpp:server-cuda**)  cannot even load a tiny model 
into my **NVIDIA 4060ti** (8GB and wish I had 20GB) ...  this is what I see:

[tiny model URL(MiniCPM-Llam3-V-2_5)](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5-gguf/blob/main/ggml-model-Q4_K_M.gguf)

If you look at the traces I attached you'll see that **llamacpp** doesn't use my GPU. Here's the summary:

llm_load_tensors: tensor 'token_embd.weight' (q4_K) (**and 290 others**) cannot be used with preferred buffer type CPU_AARCH64, using CPU instead
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/33 layers to GPU
llm_load_tensors:   CPU_Mapped model buffer size =  4685.30 MiB

[llama-focus.log](https://github.com/user-attachments/files/18032895/llama-focus.log)

======================


while **localai** with it's own version of llamacpp fully loads  the same model in my GPU. Here's the summary:

[0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: tensor 'token_embd.weight' (q4_K) (**and 0 others**) cannot be used with preferred buffer type CPU_AARCH64, using CPU instead 
[0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: offloading 32 repeating layers to GPU
[0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: offloading output layer to GPU
[0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: offloaded 33/33 layers to GPU
[0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors:   CPU_Mapped model buffer size =   281.81 MiB
[0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors:        CUDA0 model buffer size =  4403.49 MiB

[localai-focus.log](https://github.com/user-attachments/files/18032896/localai-focus.log)

**Comment by devashishraj** [comment]
@otherroch any updates on this ?

**Comment by LostRuins** [comment]
In future versions i'll hide the warning unless more than 1 tensor is affected, otherwise people will get a lot of false positives.

The way the ggml backend works now is it tries to offload every single tensor to a GPU backend if possible. This is not always possible and some tensors are meant to be on CPU, e.g. such as the input layer, but they are only a minority. Because of this people get false positives.

**Comment by loond0l** [comment]
> I'm seeing something similar, but perhaps I'm wrong..... and it could be a completely different problem.
> 
> But llamacpp (from this docker image: **ghcr.io/ggerganov/llama.cpp:server-cuda**) cannot even load a tiny model into my **NVIDIA 4060ti** (8GB and wish I had 20GB) ... this is what I see:
> 
> [tiny model URL(MiniCPM-Llam3-V-2_5)](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5-gguf/blob/main/ggml-model-Q4_K_M.gguf)
> 
> If you look at the traces I attached you'll see that **llamacpp** doesn't use my GPU. Here's the summary:
> 
> llm_load_tensors: tensor 'token_embd.weight' (q4_K) (**and 290 others**) cannot be used with preferred buffer type CPU_AARCH64, using CPU instead llm_load_tensors: offloading 0 repeating layers to GPU llm_load_tensors: offloaded 0/33 layers to GPU llm_load_tensors: CPU_Mapped model buffer size = 4685.30 MiB
> 
> [llama-focus.log](https://github.com/user-attachments/files/18032895/llama-focus.log)
> 
> ======================
> 
> while **localai** with it's own version of llamacpp fully loads the same model in my GPU. Here's the summary:
> 
> [0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: tensor 'token_embd.weight' (q4_K) (**and 0 others**) cannot be used with preferred buffer type CPU_AARCH64, using CPU instead [0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: offloading 32 repeating layers to GPU [0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: offloading output layer to GPU [0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: offloaded 33/33 layers to GPU [0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: CPU_Mapped model buffer size = 281.81 MiB [0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: CUDA0 model buffer size = 4403.49 MiB
> 
> [localai-focus.log](https://github.com/user-attachments/files/18032896/localai-focus.log)

I hava similar problem, i use a gpu rtx 4070

**Comment by LostRuins** [comment]
I can't speak for llama.cpp, but KoboldCpp's latest release should not have this issue anymore.

**Comment by MertcanTekin** [comment]
I use llamacpp in colab and here is how I download:
! pip install -q --no-cache-dir llama-index-llms-llama-cpp --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu122

here is what the model uses:

`llama_model_loader: loaded meta data with 37 key-value pairs and 258 tensors from /content/drive/MyDrive/Modeller/aya-expanse-8b-Q5_K_M.gguf (version GGUF V3 (latest))
llm_load_tensors: tensor 'token_embd.weight' (q6_K) (and 258 others) cannot be used with preferred buffer type CPU_AARCH64, using CPU instead
llm_load_tensors:   CPU_Mapped model buffer size =  5524.33 MiB
.......................................................................................
llama_new_context_with_model: n_seq_max     = 1
llama_new_context_with_model: n_ctx         = 8192
llama_new_context_with_model: n_ctx_per_seq = 8192
llama_new_context_with_model: n_batch       = 512
llama_new_context_with_model: n_ubatch      = 512
llama_new_context_with_model: flash_attn    = 0
llama_new_context_with_model: freq_base     = 10000.0
llama_new_context_with_model: freq_scale    = 1
llama_kv_cache_init: kv_size = 8192, offload = 1, type_k = 'f16', type_v = 'f16', n_layer = 32, can_shift = 1
llama_kv_cache_init:        CPU KV buffer size =  1024.00 MiB
llama_new_context_with_model: KV self size  = 1024.00 MiB, K (f16):  512.00 MiB, V (f16):  512.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.98 MiB
llama_new_context_with_model:        CPU compute buffer size =   560.01 MiB
llama_new_context_with_model: graph nodes  = 968
llama_new_context_with_model: graph splits = 1
CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | AVX512 = 1 | LLAMAFILE = 1 | OPENMP = 1 | AARCH64_REPACK = 1 | 
`

**Comment by rplescia** [comment]
> I'm seeing something similar, but perhaps I'm wrong..... and it could be a completely different problem.
> 
> But llamacpp (from this docker image: **ghcr.io/ggerganov/llama.cpp:server-cuda**) cannot even load a tiny model into my **NVIDIA 4060ti** (8GB and wish I had 20GB) ... this is what I see:
> 
> [tiny model URL(MiniCPM-Llam3-V-2_5)](https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5-gguf/blob/main/ggml-model-Q4_K_M.gguf)
> 
> If you look at the traces I attached you'll see that **llamacpp** doesn't use my GPU. Here's the summary:
> 
> llm_load_tensors: tensor 'token_embd.weight' (q4_K) (**and 290 others**) cannot be used with preferred buffer type CPU_AARCH64, using CPU instead llm_load_tensors: offloading 0 repeating layers to GPU llm_load_tensors: offloaded 0/33 layers to GPU llm_load_tensors: CPU_Mapped model buffer size = 4685.30 MiB
> 
> [llama-focus.log](https://github.com/user-attachments/files/18032895/llama-focus.log)
> 
> ======================
> 
> while **localai** with it's own version of llamacpp fully loads the same model in my GPU. Here's the summary:
> 
> [0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: tensor 'token_embd.weight' (q4_K) (**and 0 others**) cannot be used with preferred buffer type CPU_AARCH64, using CPU instead [0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: offloading 32 repeating layers to GPU [0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: offloading output layer to GPU [0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: offloaded 33/33 layers to GPU [0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: CPU_Mapped model buffer size = 281.81 MiB [0m DBG GRPC(minicpm-llama3-v-2_5-127.0.0.1:38973): stderr llm_load_tensors: CUDA0 model buffer size = 4403.49 MiB
> 
> [localai-focus.log](https://github.com/user-attachments/files/18032896/localai-focus.log)

Same issue with the docker image

**Comment by LostRuins** [comment]
That docker image you linked above isn't made by koboldcpp, you can try https://hub.docker.com/r/koboldai/koboldcpp instead. It definitely should work with GPU.

**Comment by StepOnBucket** [comment]
I get this issue not in kobaldcpp but in oogabooga and it makes my model load infinitely. Simple fix I found that works for me is to literally unload and reload and the model loads perfectly fine with no issues.

**Comment by lostmsu** [comment]
@LostRuins can you clarify why would you want to run the embed layer on CPU? Why can't it run on GPU? It is just a matmul, isn't it?

**Comment by LostRuins** [comment]
The decision was made upstream, I think it's due to the dimension size of the layer often being an odd shape, and it being relatively small tensors, so they decided to just do it on CPU for simplicity.
