### ISSUE TITLE
Memory leak in v1.78

### ISSUE THREAD

**Issue by jojorne** [LostRuins/koboldcpp#1227]
If you open and close it a few times, eventually the system will crash. In v1.77 this behavior does not exist. The memory returns to the value before launch.

Operating System: Linux 
KDE Plasma Version: 6.2.3
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.0
Kernel Version: 6.11.9 (64-bit)
Graphics Platform: X11

**Comment by LostRuins** [comment]
It's not possible for an executable to leak memory beyond it's lifespan.  

if you run `htop`, can you see exactly what processes are using the memory? If a process is killed, the memory is always returned to the system.

**Comment by jojorne** [comment]
![image](https://github.com/user-attachments/assets/e9dc7c4e-da0f-4867-8200-5b89ba578246)

Yea... The python3 was stuck even on reboot. I had to do a cold reset.
I cleared the build cache and rebuilt it. So far, so good.

Probably it was a symptom of my [previous issue](https://github.com/LostRuins/koboldcpp/issues/1211), sorry.
