### ISSUE TITLE
Unable to load model using "5bit method"

### ISSUE THREAD

**Issue by cgessai** [LostRuins/koboldcpp#123]
Using 1.14, model is here and does not load:
https://huggingface.co/TheBloke/wizardLM-7B-GGML/blob/main/wizardLM-7B.GGML.q5_1.bin

Doesn't load - "**error loading model: unrecognized tensor type 7**"
Model using some kind of new [5bit method](https://i.imgur.com/7JtIIb7.png)?

Does [this](https://github.com/ggerganov/llama.cpp/commit/574406dc7e350ddbffaeca33bf0392b7bfeb1436) hold the fix?

Also, https://huggingface.co/TheBloke/wizardLM-7B-GGML/blob/main/wizardLM-7B.GGML.q5_0.bin may suffer from same issue.

T/Y!

**Comment by LostRuins** [comment]
yes q5_0 support has not yet been integrated. It will be in the next release

**Comment by LostRuins** [comment]
Hi all, q5_0 support is now integrated for all model types. However, you have to use OpenBLAS as support within CLBlast has not yet been added.

**Comment by LostRuins** [comment]
CLBlast support should work for q5_0 and q5_1 in the latest version. Closing this issue for now.
