### ISSUE TITLE
Not changing GPU layers count after relaunching

### ISSUE THREAD

**Issue by Denplay195** [LostRuins/koboldcpp#1236]
![image](https://github.com/user-attachments/assets/4431a8e7-360d-45f1-9274-6cd6120ae4d2)
This is the difference between "offloading" 8 and 50 layers of a 70b model on VRAM, so I've figured out that relaunching koboldcpp instantly loads the models that was used before, ignoring the changed count of layers.

The temporary user solution is changing the model to another and back, reseting the cache, but probably it should check on the difference before deciding if it should load "pre-cached" one and not bypass the settings change initially

**Comment by Denplay195** [comment]
![image](https://github.com/user-attachments/assets/ed6ee97d-24b3-447d-ba53-c76f733c7dc7)
Actually now I don't know if that's the model's problem or not, even after change it behaves the same, the model is: Midnight-Miqu-70B-v1.5.i1-IQ2_S

**Comment by wh33t** [comment]
This (or perhaps a similar issue) happened to me the other day. I don't normally let my machine suspend/sleep but it did this time while the model was fully loaded into my GPUs. When I woke the machine and attempted to produce an output, kcpp crashed (expected), however when relaunching KCPP it refused to move any models into the GPU and dumped it into all into system ram. 

A reboot of my machine fixed the issue. Maybe your issue is similar? I'm using Linux Mint 22.

**Comment by LostRuins** [comment]
Double check your config/settings and the terminal output to see what model is loaded. When KoboldCpp is closed, all loaded resources will be freed and nothing should persist for a subsequent run. If the resource remains, it's likely the process did not terminate - check task manager in windows or `ps -aux` in linux for running processes.

**Comment by Denplay195** [comment]
> This (or perhaps a similar issue) happened to me the other day. I don't normally let my machine suspend/sleep but it did this time while the model was fully loaded into my GPUs. When I woke the machine and attempted to produce an output, kcpp crashed (expected), however when relaunching KCPP it refused to move any models into the GPU and dumped it into all into system ram.
> 
> A reboot of my machine fixed the issue. Maybe your issue is similar? I'm using Linux Mint 22.

![image](https://github.com/user-attachments/assets/d1b4f7aa-5d7c-4866-8e85-e5cf9f2bf436)

It's still the same, but turns out it is the model weird stuff is happening with, offloading the same amount despite the initial value


> Double check your config/settings and the terminal output to see what model is loaded. When KoboldCpp is closed, all loaded resources will be freed and nothing should persist for a subsequent run. If the resource remains, it's likely the process did not terminate - check task manager in windows or `ps -aux` in linux for running processes.

Haven't found any process happening to be koboldcpp, but the same model subsequent run loading speed is actually insane compared to first (I load them from an old HDD), from minutes to just 15 seconds, ram gets filled again in moments too. 

I haven't noticed any difference on drives either, guess that's more plus than issue so far.
About offloading on my Vulcan backend, will try other 70b models and if everything is gonna be okay (at least on any type of quants), I'll keep this issue closed
