### ISSUE TITLE
GGML_ASSERT failed

### ISSUE THREAD

**Issue by sardior** [LostRuins/koboldcpp#1238]
Currently I'm learning this tool, I'm probably just missing some settings but I don't know which one. While trying to set up image generation I ran into this problem.

Version: KoboldCpp - Version 1.78
OS: 6.6.54-2-MANJARO # 1 SMP PREEMPT_DYNAMI

I launch using:
```
./koboldcpp --usevulkan 0 --gpulayers 33 --contextsize 32768 \
			--model "$HOME/Games/koboldcpp/Meta-Llama-3.1-8B-Instruct-f32.gguf" \
			--sdmodel "$HOME/Games/koboldcpp/sd3.5_large_turbo.safetensors"
```
or just `./koboldcpp` and configure the gui. Both cases end up with this failed assert.

```
ImageGen Init - Load Model: /home/slawo/Games/koboldcpp/sd3.5_large_turbo.safetensors
ggml/src/ggml.c:1568: GGML_ASSERT(type >= 0 && type < GGML_TYPE_COUNT) failed
/home/slawo/bin/koboldcpp: line 17: 163560 Aborted                 (core dumped) ./koboldcpp --usevulkan 0 --gpulayers 33 --contextsize 32768 --model "$HOME/Games/koboldcpp/Meta-Llama-3.1-8B-Instruct-f32.gguf" --sdmodel "$HOME/Games/koboldcpp/sd3.5_large_turbo.safetensors"

```
Is there a setting that corresponds to GGML_TYPE_COUNT ? I could not find anything in the wiki.

**Comment by LostRuins** [comment]
Could you link a download to this model so I can take a look

**Comment by sardior** [comment]
sure, I tried both of these with the same result:

- https://huggingface.co/stabilityai/stable-diffusion-3.5-large-turbo/blob/main/sd3.5_large_turbo.safetensors
- https://huggingface.co/city96/stable-diffusion-3.5-large-turbo-gguf/blob/main/sd3.5_large_turbo-F16.gguf

**Comment by LostRuins** [comment]
Hi, just tried it on the latest version and it seems to be working now. Could you check again on 1.79.1?

Files used
Image Model: https://huggingface.co/city96/stable-diffusion-3.5-large-turbo-gguf/blob/main/sd3.5_large_turbo-Q4_0.gguf
T5-XXL, ClipL and ClipG - https://huggingface.co/Comfy-Org/stable-diffusion-3.5-fp8/tree/main/text_encoders
VAE: https://civitai.com/models/880017/stable-diffusion-35-vae-sd35

Euler sampling, BigSquare (768x768), 20 steps, prompt: cool cat, no negative prompt

![image](https://github.com/user-attachments/assets/f397866d-1803-4f21-8ec7-fb905d00bea3)

**Comment by sardior** [comment]
Yes, 1.79.1 works on my side as well
