### ISSUE TITLE
GGML_ASSERT Error

### ISSUE THREAD

**Issue by th-neu** [LostRuins/koboldcpp#124]
Using the latest git version (git pull) and build the Programm with the w64devkit. Did a "make clean" before make and the Binary won't load any models (vicuna, alpaca etc). Build wen't fine without any errors.
Error msg it get is not telling me anything:

GGML_ASSERT: ggml.c:5454: ggml_is_matrix(a) && ggml_is_vector(b) && b->type == GGML_TYPE_I32

OS: Windows 10
not sure how i can provide more information. But let me know if there is anything i can do. Thanks for you work.

**Comment by LostRuins** [comment]
Does the same model work with the prebuilt binaries from Releases?

**Comment by th-neu** [comment]
Yes the binary works. Guess i broke something in my enviroment.

**Comment by th-neu** [comment]
My from source compiled version of CLBlast is breaking it. I would close the issue then. Thanks!
