### ISSUE TITLE
Location of pre-made chatcompletions json files changes.

### ISSUE THREAD

**Issue by KraiiFox** [LostRuins/koboldcpp#1247]
**Describe the Issue**
Not sure if this is intended behaviour but if I pick a pre-made chatcompletions adapter file and save the config, the next time I launch the program the json files are no longer there because the program uses the temp folder to store the json files.

e.g.
First run:
C:/Users/[name]/AppData/Local/Temp/_MEI251602/kcpp_adapters/ChatML.json

Second run:
C:/Users/[name]/AppData/Local/Temp/_MEI293282/kcpp_adapters/ChatML.json

And since the config file saves the exact path to the json file, if I run the model it does not load the instruct tags.

**Additional Information:**

- OS: Windows 11
- KoboldCPP ver: 1.79.1

**Comment by LostRuins** [comment]
The adapters is unpacked to a temporary directory that gets cleared on exit. In future versions, i'll find a way to fix the paths.

**Comment by LostRuins** [comment]
Will be fixed in https://github.com/LostRuins/koboldcpp/commit/d0d1d922de240feb2b2e2a3a9a6030aa9f0b396f

**Comment by LostRuins** [comment]
This is now fixed in v1.80

**Comment by KraiiFox** [comment]
Works great now, thanks!
