### ISSUE TITLE
[Feauture request] Allow inserting user scripts JS on web page interface

### ISSUE THREAD

**Issue by janvarev** [LostRuins/koboldcpp#125]
Idea:
- If folder "koboldcpp_userscripts" exists,
- insert code from all files inside it to user web interface.

This allow user to adjust web interface for it's own needs: for example, make translations, automatization etc.

**Comment by LostRuins** [comment]
Unfortunately Kobold Lite does not support userscripts. But you can try to use them by connecting via the main kobold client API.
