### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by Mixersound122** [LostRuins/koboldcpp#1250]
Im not sure if i am correct putting this here but when i start up with remote connection it would say "this app can't run on your PC".
   Is this my problem or the new update broke it?, i used to be able to use it but then i updated.

**Comment by LostRuins** [comment]
Try deleting the old cloudflared.exe and retry

**Comment by Mixersound122** [comment]
dose it matter if i download the cul version or the regular version?.

**Comment by LostRuins** [comment]
There is only a cli version of cloudflared that exists.

The file is located at https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe and koboldcpp will rename it to cloudflared.exe

**Comment by Mixersound122** [comment]
no i made a mistake i meant in the releases dose it matter if i download the koboldcpp_cu12.exe  or the  koboldcpp.exe dose, it make a difference?.

**Comment by Mixersound122** [comment]
Never mind i solved it i moved to1.79.1 from 1.78 and use the  cu12.exe, also tried your suggestion, i don't know witch one worked but one of them did it might have been your suggestion, i don't know, but thank you for helping.

**Comment by LostRuins** [comment]
Alright, do reopen this issue if its still not working.
