### ISSUE TITLE
On windows do I need to install cuda toolkit from nvidia?

### ISSUE THREAD

**Issue by delebash** [LostRuins/koboldcpp#1252]
**Describe the Issue**
1. I see that there is a cuda executable, do I still need to download the 12.x toolkit and if so any specific version or the latest 12.6?

2. Should I also be setting the preset to CuBlast?

**Comment by LostRuins** [comment]
If you're just running the binary, you do not need to download anything else. The single exe is all you need. It will set itself to cublas automatically.

![image](https://github.com/user-attachments/assets/b6976259-794c-405f-9ec0-8b1b38b8f9c2)

**Comment by delebash** [comment]
Thanks!
