### ISSUE TITLE
Method to override: llm_load_print_meta: n_expert_used    = 2

### ISSUE THREAD

**Issue by David-AU-github** [LostRuins/koboldcpp#1257]
Hi

I want to run MOEs with KoboldCPP, (and/or using it as a back-end with Sillytavern) and wondered if there is a way to override the:

llm_load_print_meta: n_expert_used    = 2

Can this be set in a "kccp" file? other? 
Command Line start?

For LLAMA-SERVER.EXE the (override) method is:

--override-kv llama.expert_used_count=int:6

NOTE:
This is not only for my own use, but also to inform model users at my repo how to change the "number of experts"
using Koboldcpp for MOE models.

Thanks in advance.

**Comment by LostRuins** [comment]
Hi, can you please try the latest version 1.80, this has been added!

**Comment by David-AU-github** [comment]
Thank you! ; works perfectly.
Updated 10 model cards at my repo with the info , and link to koboldcpp too.
