### ISSUE TITLE
[feature request] Additional parameters for Speculative decoding

### ISSUE THREAD

**Issue by elter-tef** [LostRuins/koboldcpp#1258]
It is very exciting to see the addition of a function for Speculative decoding! I would like to be able to use these parameters from llamaserver to more precise configuration on multi GPU system and for CPU offloading for draft model.

```
-devd, --device-draft <dev1,dev2,..>    comma-separated list of devices to use for offloading the draft model
                                        (none = don't offload)
                                        use --list-devices to see a list of available devices
-ngld, --gpu-layers-draft, --n-gpu-layers-draft N
                                        number of layers to store in VRAM for the draft model
```

**Comment by LostRuins** [comment]
Hi, can you please try the latest version 1.80? I've added more launch parameters!

**Comment by elter-tef** [comment]
The parameters work as needed, thank you!
