### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by PixelForg** [LostRuins/koboldcpp#126]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

So I switched to v1.15 locally and did ``make LLAMA_OPENBLAS=1 LLAMA_CLBLAST=1`` and then I tried running koboldcpp.py like I always do
```
python koboldcpp.py models/ggml-vicuna-13b-4bit-rev1.bin 3000  --threads 12 --useclblast 0 0
```
and I expected it to start on port 3000

# Current Behavior

It fails to start
```
Traceback (most recent call last):
  File "/home/pixelforg/Documents/gitrepos/koboldcpp/koboldcpp.py", line 9, in <module>
    from tkinter.constants import LEFT, RIGHT
ModuleNotFoundError: No module named 'tkinter'
```

# Environment and Context

```
CPU - i7-12700k
GPU - AMD 6600XT
OS - Gentoo Linux ( I followed the same instructions as Arch Linux, just had to change OS name in the MAKEFILE) 

$ python3 --version
Python 3.10.10

$ make --version
GNU Make 4.4.1
Built for x86_64-pc-linux-gnu

$ g++ --version
g++ (Gentoo 12.2.1_p20230304 p13) 12.2.1 20230304

**Comment by nicholasChieftain** [comment]
have you tried installing the tkinter package?

**Comment by LostRuins** [comment]
Oops no that is my bad. tkinter is an optional package, I dont know how those constants got pushed up there. My IDE has gone rogue. You can remove that import line - I have already fixed it in the latest commit. Thanks!

**Comment by PixelForg** [comment]
No worries! I installed tkinter package through system package manager and it worked but good to know that you've made it optional, I'll close the issue now since it's solved. Thanks!
