### ISSUE TITLE
Throws an error when using Qwen2-vl On Mac

### ISSUE THREAD

**Issue by chigkim** [LostRuins/koboldcpp#1273]
There was a bug that prevents from Qwen2-vl to run on Mac. The fix has been merged to llama.cpp yesterday.
https://github.com/ggerganov/llama.cpp/pull/10896
Thanks!

**Comment by chigkim** [comment]
Here's the error:

```bash
ggml_metal_encode_node: error: unsupported op 'ROPE'
ggml/src/ggml-metal/ggml-metal.m:1263: unsupported op
```

**Comment by LostRuins** [comment]
I don't think wholesale disabling the GPU is a good idea. I'll wait and see if upstream develops a better solution - otherwise I'll only run clip on CPU for this specific model on macOS.

**Comment by chigkim** [comment]
Isn't that what the fix did for now? Only run clip on cpu  on mac?

**Comment by LostRuins** [comment]
Fixed, please update

**Comment by chigkim** [comment]
Thanks it works now.
