### ISSUE TITLE
666

### ISSUE THREAD

**Issue by Past-Tang** [LostRuins/koboldcpp#1274]
**Your code is just as stupid as yours

The latest version of the illusion problem is still unresolved, and there is no maximum truncation setting,**

**Comment by Luro223** [comment]
> **Your code is just as stupid as yours
> 
> The latest version of the illusion problem is still unresolved, and there is no maximum truncation setting,**

Heavily depends on user settings, try experimenting with DRY, but leave XTC at 0.

**Comment by Luro223** [comment]
@Past-Tang try experimenting with DRY, but with 0 XTC.
