### ISSUE TITLE
Sending Image Request via OpenAI API

### ISSUE THREAD

**Issue by chigkim** [LostRuins/koboldcpp#1275]
If I send an image for a model to describe along with text prompt via OpenAI api, the log says "content": null.
However the same request works fine if I send it to openai.com as well as Ollama via OpenAI api.
If I send text prompt only without image to the same model, it works fine.

**Comment by chigkim** [comment]
Sorry, I think I'm doing something wrong. I'll investigate more and reopen if necessary.

**Comment by LostRuins** [comment]
Make sure the correct "Vision" mode is used - for openai you would want to use "OpenAI" for the vision mode when you click on the image.
