### ISSUE TITLE
Model sometimes continues outputting beyond EOS token when speculative decoding is used

### ISSUE THREAD

**Issue by yam-m** [LostRuins/koboldcpp#1276]
When speculative encoding is enabled, if the EOS token is encountered somewhere other than the end of a batch of drafts, the remaining draft tokens that match the main model's output get generated even if they occur after the EOS token.

![output_beyond_eos](https://github.com/user-attachments/assets/8f0efc2f-c03b-465f-b873-fe026422ce6e)

This is happening in both 1.80 and 1.80.1, but it does not seem to occur in 1.79.1.

**Comment by LostRuins** [comment]
Currently, drafting is not stopped early even if EOS is generated. This is because there are a few scenarios where the main model would want to continue even after EOS is generated (such as when EOS is set to bypass mode). This was also the case in 1.79.1 although the drafted tokens were not shown. This approach can probably be improved in future.

**Comment by yam-m** [comment]
I see. Whether they're processed and shown in the debug logs or not probably doesn't matter much, but having seemingly random tokens sent back to the client and show up in the UI can be a bit inconvenient since I have to go back and clean up the model's text after most responses.

![ui](https://github.com/user-attachments/assets/2c4aa424-ef78-4a5b-aa73-72540e945505)

**Comment by LostRuins** [comment]
Oh, that has nothing to do with drafting. If a drafted token is used it means the main model generated the same thing too.

Make sure that EOS is set to Auto or Unbanned
![image](https://github.com/user-attachments/assets/fe6267eb-28d7-4d2b-bc91-12e50ef989e8)

Then make sure "Amount to generate" is large enough for the whole response.

If you like, you can enable trim sentences too.

**Comment by yam-m** [comment]
Hmm... I do have "EOS Token Ban" set to Auto, and my max output is set to 300 which should be enough at least for this prompt.

I'm pretty sure what I'm seeing IS actually connected to use of a draft model since the problem goes away if I stop using the draft model (and it didn't occur in 1.79.1 even with a draft model).

I had looked through the commit log a bit, and based on the timing and the files changed, I was assuming that it was a side effect of the changes to gpttype_adapter.cpp made in commit 00a686f, though I could certainly be mistaken on that.

I should note that it doesn't just keep generating tokens indefinitely or anything. It just generates the remaining draft tokens that match the real model's output in the batch where the EOS token appeared. If the EOS token was the last token of a batch, or the next draft token after the EOS token fails to match, then everything is fine. But if one or more draft tokens after the EOS token match the real model, they get output in the UI (and returned via the API) even if EOS Token Ban is set to Auto.

**Comment by LostRuins** [comment]
Alright, I'll take a look

**Comment by LostRuins** [comment]
My apologies, you are correct. There was a regression that caused the EOS to not work correctly. I'll prepare a patch

**Comment by LostRuins** [comment]
Fixed in 1.80.2

**Comment by yam-m** [comment]
Thanks, the issue that I was having seems to be fixed now!

**Comment by yam-m** [comment]
Thanks, the issue that I was having seems to be fixed now!

**Comment by yam-m** [comment]
Thanks, the issue that I was having seems to be fixed now!
