### ISSUE TITLE
Error when running under Windows 7, DLL load failed while importing pyexpat

### ISSUE THREAD

**Issue by lonchura** [LostRuins/koboldcpp#1280]
**Describe the Issue**
Error when running under Windows 7, DLL load failed while importing pyexpat.
![1734945314925](https://github.com/user-attachments/assets/637ef781-b986-44ce-a786-5d45b8318fa8)

**Additional Information:**
windows iso: cn_windows_7_enterprise_with_sp1_x64_dvd_u_677685.iso

**Comment by LostRuins** [comment]
Add `--failsafe` flag to use windows 7

**Comment by lonchura** [comment]
It might be because the system is too old. I tried updating with the Windows6.1-KB3063858-x64.msu patch and it worked.

**Comment by LostRuins** [comment]
Glad you got it working. Did it work only with failsafe, or others too?
