### ISSUE TITLE
WHEA_UNCORRECTABLE_ERROR upon attempting benchmark

### ISSUE THREAD

**Issue by adrian52999** [LostRuins/koboldcpp#1285]
So I got a new PC with 3x RTX 3090, but right now only one of them is active.

Upon attempting to run benchmark, I get BSOD with the error code WHEA_UNCORRECTABLE_ERROR every single time, without fail. Anyone else run into this? When I try to run it normally it works, but when I try to benchmark it just BSODs on me.

**Comment by Luro223** [comment]
@adrian52999 Maybe it is related to drivers from Microsoft? Check if your iGPU/dGPU drivers are from official website instead from Windows Update.

**Comment by LostRuins** [comment]
@adrian52999 indeed do update your graphics drivers, but also provide your launcher args and system specs so we can take a closer look.

BSODs are often caused by memory allocation issues, so you can try with fewer layers offloaded first as well.

**Comment by adrian52999** [comment]
It would appear that my RAM was not settled properly into the mobo slot. Reslotting it fixed the BSODs and allowed me to do the benchmark.
