### ISSUE TITLE
Make a List of Characters instead of AI Name

### ISSUE THREAD

**Issue by Vladonai** [LostRuins/koboldcpp#130]
Now the AI Name parameter is added to the end of each Prompt. I propose to improve the system and make a List of Characters instead of a single name. Each prompt should be treated this way: it looks for a name from the List of Characters, and if a name is found at the beginning or end of the prompt and there is a comma next to it, it is assumed that this is a direct reference to a character and this is the name you should add to the end of the prompt. Examples of List of Characters:
Bill
John
Michael

Bill's name is listed first and will be used by default. But if the prompt has this form:
"John, how are you doing?" or "How are you doing, John?", then obviously you have to add John's name to the end of the Prompt to get him to respond. It would be even better if, after addressing John, his name was placed at the top of the list to continue the dialogue with him even without a direct mention. If the user additionally writes Bill, John, and Michael's descriptions and personalities in the Context, it should make a good group chat. This is a huge problem right now.

**Comment by LostRuins** [comment]
I think you'll find group convo's a little bit difficult as most of the models are only trained on a 1 to 1 conversion.

Currently, I think you have 3 options for simulating a group chat.
1. In Chat mode, you carry on a normal conversation, then before you send the next message, use the settings to change the AI name to whoever you want to respond to your message. That user will then be the one to reply to you. You'd have to change the name each time you want a different person to reply.
2. You can try instruct mode. Since by default the AI has no name in instruct mode, it might be able to simulate multiple personalities better.
3. You can try Story mode, and then manually set a list of bot names to trigger stopping tokens on. It will be a bit more clunky but it should work.

**Comment by LostRuins** [comment]
Hi, this feature has been added in the latest release. Dynamic group conversations are now possible. Add your chat participants with the `||$||` delimiter. For now, a random participant will be selected to respond to the chat. In future, this may be improved.

**Comment by Vladonai** [comment]
> Hi, this feature has been added in the latest release. Dynamic group conversations are now possible. Add your chat participants with the `||$||` delimiter. For now, a random participant will be selected to respond to the chat. In future, this may be improved.

Thank you. I tested it on Llama, with the "Multiline" mode turned on. Very good chats turn out (even with 4 characters), but direct address does not work.  You ask a character by name, but another character answers for him. I understand that he is just randomly selected from a list, but for direct address should make an exception. "John, how are you doing?" or "How are you doing, John?" - search from the beginning of the Prompt for the lines "{char}," and ", {char}" and if they are found, the first character in the dialog should be that one. However, it would be more interesting if in this case greatly increase the chance of randomness for this character. Then the "Multiline" mode will work almost naturally.

And by the way, I should note that the --highpriority flag in my case noticeably increased the speed of generation.

**Comment by Polosat1y** [comment]
> For now, a random participant will be selected to respond to the chat. In future, this may be improved.

I see that often several characters try to answer at once, but this is interrupted by a stopping sequence. Can we add the ability to exclude stopping sequences so that multiple characters can respond at the same time?

Thank you. Multichat is really great.

**Comment by LostRuins** [comment]
@Polosat1y simply press submit again, and it should work
