### ISSUE TITLE
When selecting a stop sequence without API access, "GET /sw.js HTTP/1.1" returns 404 and soft-locks koboldcpp until the stop sequence is removed.

### ISSUE THREAD

**Issue by bucketcat** [LostRuins/koboldcpp#131]
Took a while to figure this out. Adding a string which outputs something like "Read the tooltip, dummy. Requires Kobold API..." to console, or having stop sequences be ignored if API authentication can't be established could be possible solutions.

Nevertheless, removing the stop sequence and refreshing the browser resolved the issue.

Mostly leaving this here since it might help someone trying to diagnose the same issue, _I.e. a tendency to ignore tooltips_. Feel free to close it as is, since this is technically user error on my end.

**Comment by LostRuins** [comment]
I don't really understand - adding a stop token should not soft lock koboldcpp. How does it happen and what did you use for the stop token?

**Comment by bucketcat** [comment]
I used "Chapter". It caused GET /sw.js HTTP/1.1 to 404 when loading the browser, restarting koboldcpp, swapping browser, trying in FF debugging mode, FF offline mode, cache clear + reload. No matter what I got GET /sw.js HTTP/1.1 404. Maybe unrelated, but the various JS files loaded in different orders every time.

I could load up the dev tools and monitor the network traffic if you want the specific packets/api calls?

I tried it several times and it was the stop sequence that broke the service worker. Be it in the middle of run time, or on boot. And it persisted through sessions/reboots until I removed it.

Any specific logs or info that you want while I'm at it?

**Comment by bucketcat** [comment]
Looking at the stack-trace, it fails compiling entirely immediately returning on pressing generate, reloading the page or doing anything besides editing the text.

```
Uncaught TypeError: _.stop_sequence is undefined
    submit_generation http://localhost:26001/:29
    onclick http://localhost26001/:1
```

in console: 
```
127.0.0.1 - - [01/May/2023 22:23:00] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/May/2023 22:23:01] "GET /api/v1/model HTTP/1.1" 200 -
127.0.0.1 - - [01/May/2023 22:23:01] "GET /api/v1/info/version HTTP/1.1" 200 -
127.0.0.1 - - [01/May/2023 22:23:01] "GET /sw.js HTTP/1.1" 404 -

```

When refreshing the page, I don't get the error but sw.js still returns 404.

**Comment by bucketcat** [comment]
Will do! I'll edit this comment with the findings.
