### ISSUE TITLE
Unable to get streaming output

### ISSUE THREAD

**Issue by regstuff** [LostRuins/koboldcpp#132]
I'm running kobold.cpp with these flags: --threads 12 --blasbatchsize 1024 --stream --useclblast 0 0
Everything's working fine except that I don't seem to be able to get streaming to work, either on the UI or via API. Looking at the server's backend, I see the token generation counting up to the token limit, and then finally the output is displayed once the limit or stop sequence is reached.
Any clues what I'm doing wrong.

**Comment by LostRuins** [comment]
If you have the --stream flag it should definitely be working. But if you are using Aesthetic chat UI it may not show up. Try switching to non-aesthetic chat first?

**Comment by regstuff** [comment]
I'm using Kobold Lite. Bit weird. Seems to work sometimes, other times it won't. Sometimes I just re-run the kobold.py file (with --stream) and it works. After a while it seems to stop working.

Let me see if I can debug a little more and figure out a pattern.

**Comment by LostRuins** [comment]
Yep. make sure you see the ?streaming=1 in the url.
