### ISSUE TITLE
Windows build unusually slower than Linux on same hardware

### ISSUE THREAD

**Issue by rabidcopy** [LostRuins/koboldcpp#133]
Sorry for this being a bit informal but it's a bit of an odd issue I just noticed. When running Koboldcpp and llama.cpp on Linux, I get roughly 130-140ms per token on a 7B model. Using the same command and model on Windows, I get much slower speeds, as slow as 250ms+ per token. I'm honestly not sure why. And I double checked and it is using AVX2 on Windows for me.
```
Initializing dynamic library: koboldcpp_openblas.dll
==========
Overriding thread count, using 6 threads instead.
Loading model: S:\models\ggml-vicuna-7b-1.1-new-q4_0.bin
[Threads: 6, SmartContext: True]

---
Identified as LLAMA model: (ver 3)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
```
`Generation:1.9s (240ms/T)`

Edit: It might not have much to do with Koboldcpp though. Upon further testing, using llama.cpp on Windows for me in general is slower. 130-140ms per token on Linux, 170-180ms per token on Windows.

**Comment by rabidcopy** [comment]
Honestly can't say, I've only had very brief experience using either koboldcpp or llama.cpp on Windows. Though I do remember weeks ago llama.cpp was slower on Windows for me and could never match the speeds I get on Linux. I just don't remember it being so pronounced. Especially here and having 220-260ms per token.

**Comment by rabidcopy** [comment]
I think I figured it out, it seems process priority plays a HUGE role here. Upping the priority to high/realtime speeds things up dramatically for me. If I set it to realtime, I get speeds much more comparable to Linux.
`Time Taken - Processing:0.1s (141ms/T), Generation:1.1s (136ms/T), Total:1.2s`

**Comment by LostRuins** [comment]
That is strange. I have tried that myself and do not notice a difference. How many threads are you using? Does this change if you increase/decrease threads?

**Comment by rabidcopy** [comment]
6 threads on a Ryzen 2600. (6 cores, 12 threads) On Windows for me, increasing the threads beyond physical cores makes it hang and/or process generation very very slowly. Decreasing the threads below physical core count just makes it slower. Same process priority behavior. If I up thread count beyond 6 on Linux, no speed increase, but no hanging either.

**Comment by LostRuins** [comment]
Hi, I've integrated this suggestion into python. You can run with the flag `--highpriority` and it should try to allocate a higher CPU priority, on all OS, via the `nice()` function in python..

**Comment by Enferlain** [comment]
So how many threads would you run on 16 core? 16?

**Comment by LostRuins** [comment]
16 core or 8 core 16 hyperthread? Probably 7 or 8 is my guess

**Comment by Enferlain** [comment]
32 threads

**Comment by LostRuins** [comment]
Yep in that case 16 physical cores should use about 16 threads
