### ISSUE TITLE
Multi-chat adds random non-specified characters when using multiline toggle under certain conditions.

### ISSUE THREAD

**Issue by bucketcat** [LostRuins/koboldcpp#136]
Title.

Specify two characters using the delimiter (shows them properly in console on generation under stop sequence as  [("User:", "Char 1:", "Char 2:")].

Send prompt referring to neither of the characters directly, instead using second or third person plural, wait and and have two separate characters reply, one which is a random one not specified. (In my case  Char 2 and Char 3 replied). Doesn't happen every time, but repeat a few times and it should be reproducable .

The mystery character never returned after the initial reply/prompt.

**Comment by bucketcat** [comment]
It's also impossible to prompt a specific character, the character that replied last will always reply unless the name of the last reply is manually edited or another comment is manually inserted from the other character. This has to be done each time you want a different character to reply.

The name stop sequences might be a culprit here.

**Comment by LostRuins** [comment]
Make sure you disable multiline replies, that should help with this issue.

For prompting a specific character, I have to figure out the best way to do it. Simply addressing them by name will have too many edge cases where it fails.

**Comment by bucketcat** [comment]
Yea first one was mostly multiline. For the second one, conditional stop sequences for names might be a good idea. Specifically allowing one reply from both characters before the stop sequence is triggered. That way you can kinda wrangle your way around it by having both (or more) characters reply once each generation.

**Comment by Vladonai** [comment]
> Make sure you disable multiline replies, that should help with this issue.
> 
> For prompting a specific character, I have to figure out the best way to do it. Simply addressing them by name will have too many edge cases where it fails.

I addressed this question to ChatGPT 3.5. We had a nice conversation and came to these conclusions:

In most cases, addressing a specific character begins with their name and a comma, or ends with their name before a comma and a space. Using this logic to determine a person's name in a dialogue can be effective and easier to implement than natural language processing and machine learning methods.

However, it should be noted that this method may not always provide an accurate result, especially if the address to the character occurs within a sentence or without a comma. Also, when using the method of comparing the beginning and end of the string, it is important to ensure that the character's name is spelled correctly and matches exactly how it is written in the group.

Thus, the method of checking the beginning and end of the string for the presence of a character's name can be effective, but should be used with caution and take into account possible inaccuracies.

>Is it possible to improve this method for cases where addressing a character occurs within a sentence or without a comma? Perhaps there are English language rules that clearly indicate direct address to a character, and in such cases they can be identified using simple methods?

Yes, there are rules in the English language that indicate a direct address to a character within a sentence, and these can be used to improve the method of determining the name of the character.

One such rule is the use of an exclamation point after the name or nickname of a character in a sentence, for example: "John, come here!", "Hey, buddy, wait for me!". In this case, you can look for an exclamation point after the character's name in the dialogue to determine who the speaker is addressing.

You can also use other key words or phrases that indicate a direct address to a character, such as "excuse me", "listen", "hey", "hey there", "hey you", "look", "wait", "come on", "let's go", "please", "thank you", "sorry", etc. If one of these key words or phrases is present in the dialogue, you can check whether the character's name follows it to determine who the speaker is addressing.

Thus, using additional key words and phrases along with searching for exclamation points after the character's name can help improve the method of determining the name of the character, even if the address to the character occurs within a sentence or without a comma.

**Comment by LostRuins** [comment]
If you want to trigger a second reply from another name, it would be much better to simply press the submit button again, rather than relying on multiline replies.
