### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by paryska99** [LostRuins/koboldcpp#139]
Yesterday i downloaded koboldcpp for windows in hopes of using it as an API for other services on my computer, but no matter what settings i try or the models i use, kobold seems to always generate weird output that has very little to do with the input that was given for inference. (kobold also seems to generate only a specific amount of tokens, it doesn't seem to generate a token to stop generating)

The same models behave correctly with similar settings on Oobabooga and llamacpp.

Example of generation using pygmalion7b:
![image](https://user-images.githubusercontent.com/77459670/236252525-6e1e0412-5f8f-4434-b8df-2c445621d9c6.png)

The output is either that or loads of random links, hashes, imgur links, or weird comments.

Any amount help is greatly appreciated.

**Comment by LostRuins** [comment]
That is very strange, I have not seen any issues with Pygmalion. Have you tried using a blank chat prompt (new chat) instead of the koboldgpt example? Also, try launching with the flag `--unbantokens` to allow the EOS token to work.

**Comment by LostRuins** [comment]
Can anyone else reproduce this bug? I don't think I have made any changes between 1.17 and 1.18 that would cause this issue.

**Comment by Zyril-8204** [comment]
@paryska99 I know you recently installed it and I don't know your experience with it so far so I'll ask a few questions to help further investigations on this. My try/error with pygmalion 7b has not had this issue using 1.18. What I am seeing here leads me to wonder if you are using an incorrect 7b model of have your settings just cranked to a very odd point that generates this. 

1. Which model version of pygmalion7b are you using for this in 1.18? (an actual link to it for testing would be best.) 
2. Do the pygmalion 6b quantized 4bit models listed in the [pygmalion docs - pygcpp](https://docs.alpindale.dev/local-installation-(cpu)/pygcpp/) behave the same in 1.18 as the model you are using? 
3. Has the pygmalion 7b model you are using be quantized for 4bit use?
4. Finally for clarity with kobaldAI UI, can we see a screenshot of the settings to show what the token generation settings are set to so we can mimic them?

**Comment by paryska99** [comment]
I use pretty similar options on the first screenshot as in the secound one. I've already experimented with a lot of settings. When im home tomorrow i might do more experimentation and detailed screenshots to help with the issue.

**Comment by Ar57m** [comment]
I was running this [xzuyn/RedPajama-INCITE-Chat-v1-3B-ggml-q5_1](https://huggingface.co/xzuyn/RedPajama-INCITE-Chat-v1-3B-ggml-q5_1) on termux for android, and I had this same issue, with random stuff in the output

**Comment by LostRuins** [comment]
Hi @Ar57m please try the latest release (currently version 1.20), RedPajama support has been added

@paryska99 are you still experiencing issues?

**Comment by paryska99** [comment]
Hi, sorry for not responding on the issue for a while. I have been experimenting between different versions and i don't know what caused it but once i ran the 1.17 version, the bug was still present, but then disappeared once i restarted my laptop. I am very confused for what the cause of the issue could be. I've also tried out the 1.19 version which was also working correctly.

**Comment by Ar57m** [comment]
Thanks it worked, I tested now on q4_0 and q4_2

**Comment by LostRuins** [comment]
That's just the model encountering text input that it could not parse, as the token you used does not exist inside the vocab. May be some sort of obscure unicode or control character. It shouldn't really be an issue.
