### ISSUE TITLE
Useclblast Always uses device 0

### ISSUE THREAD

**Issue by Eltrion** [LostRuins/koboldcpp#144]
No matter which number I enter for the second argument, CLBlast attempts to use Device=0
This is a problem for me as I have both an AMD CPU and GPU, so the GPU is likely Device=1

Platform: Linux (Manjaro)
CPU: 5900X
GPU RX 6650 XT

```
 > python ./koboldcpp.py ../llama.cpp/models/30B/Alpacino.bin --smartcontext --useclblast 1 7                                                                                                                               
Welcome to KoboldCpp - Version 1.18
Attempting to use CLBlast library for faster prompt ingestion. A compatible clblast will be required.
Initializing dynamic library: koboldcpp_clblast.so
/ai/Text/koboldcpp-1.18/koboldcpp_clblast.so
/ai/Text/koboldcpp-1.18/koboldcpp_clblast.so
==========
Loading model: /ai/Text/llama.cpp/models/30B/Alpacino.bin 
[Threads: 11, SmartContext: True]

---
Identified as LLAMA model: (ver 3)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 
llama.cpp: loading model from /ai/Text/llama.cpp/models/30B/Alpacino.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 6656
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 52
llama_model_load_internal: n_layer    = 60
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 17920
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 30B
llama_model_load_internal: ggml ctx size = 110.30 KB
llama_model_load_internal: mem required  = 21695.46 MB (+ 3124.00 MB per state)

Initializing CLBlast (First Run)...
Attempting to use: Platform=1, Device=0 (If invalid, program will crash)

```

**Comment by cgessai** [comment]
Anecdotally and just as a random interloper, I found that the successful --useclblast settings wound up being "1 0" for my AMD IGPU and "0 0" for my NVidia card.  The Platform ID changing as unintuitive.  FWIW.

**Comment by Eltrion** [comment]
Well, I've tried dozens of combinations, and haven't got past the crash. I've done every possible combo with Platform ID < 6 i think.

**Comment by LostRuins** [comment]
Just a reminder that the GPU selection starts from index 0, not 1. 
So you can try these: 
`0 0`
`0 1`
`1 0`

i agree it's not very intuitive. the problem is it's not standardized .. different systems with the same GPU can have their values set differently.

**Comment by Eltrion** [comment]
Yep. Tried all those. I'm pretty sure my GPU should be at 0 1, but as you can see from the example it always tries device 0 regardless of what I enter from the second parameter.

**Comment by LostRuins** [comment]
Wow  good catch. I have found the a bug. Building a fix now

**Comment by LostRuins** [comment]
Hi @Eltrion can you please try 1.19.1 updated

**Comment by Eltrion** [comment]
1.19 gives me the same behavior. Source code seems to still be 1.19 not 1.19.1 Only windows exes seem to have updated so far.

**Comment by Eltrion** [comment]
Cloned the git. Going to attempt to find my Gpu again.

**Comment by LostRuins** [comment]
Okay but at least the device is set correctly now? Yeah I haven't updated the source code in the release, I thought you were on windows.

**Comment by Eltrion** [comment]
No. I am on Manjaro Linux as stated in the initial post. I have tried multiple configurations, and noted that some people used clinfo --list to get the platform and device id.  This program simply hangs for me. 

ROCm 5.4 is installed. and rocminfo runs fine.

**Comment by LostRuins** [comment]
Generally you only need to try 0 0 / 0 1 / 1 0 if you have 2 or fewer gpus. Now that you mention it, I notice you said the program hangs but not crashes, which is unusual. Normally it will crash with a segfault error if the GPU is invalid. Might have something to do with clinfo failing too 

Hmm if clinfo fails

**Comment by Eltrion** [comment]
Issue was related to the intel-oneapi file /etc/OpenCL/vendors. Apparently causes OpenCL to hang if you have and AMD CPU on Arch Linux. Deleting it solved the problem and I can use CLBlast now.
