### ISSUE TITLE
Feature Request: Show model name in UI

### ISSUE THREAD

**Issue by cgessai** [LostRuins/koboldcpp#148]
Would be nice to have the name of the currently loaded model displayed in the UI, either at the bottom of the screen near the "Last request served by..." text, on the top right hand side in the dead space, or on the Settings menu.  Anywhere, really, but preference for main UI.  Those just seem like the two most intuitive places for it.  I frequently load different models and, after using them for a while, forget which model I'm using.  This would be a nice way to help remember.

**Comment by LostRuins** [comment]
Agree this will be nice to have, though for compatibility reasons it's likely not to be in the standard kobold API. Because the main kobold will have errors if the model doesn't actually exist on huggingface.

**Comment by CorentinWicht** [comment]
Any news on this feature request? 
I believe it would be a big enhancement to know what model is currently being loaded.

**Comment by alicat22** [comment]
Would love this feature! It's really difficult to remember when you use a lot of models, as there's no way to really check if your console's context gets pushed past the load model name.

**Comment by LostRuins** [comment]
There's a roundabout way to get it set (and displayed), you just need to run --hordeconfig with 1 parameter, the model name, which will replace the default name. If you set it in the UI launcher, it will default to the model's filename. If you don't set the horde API key that wont trigger the embedded worker so you can use the model name locally.

**Comment by alicat22** [comment]
This was implemented -> https://github.com/LostRuins/koboldcpp/releases/tag/v1.46.1
