### ISSUE TITLE
Support `--ctx_size` to set context size.

### ISSUE THREAD

**Issue by JHawkley** [LostRuins/koboldcpp#150]
_This is a feature from llama.cpp that kobold.cpp currently does not support._

The recently released [Bluemoon RP model](https://huggingface.co/reeducator/bluemoonrp-13b) was trained for 4K context sizes, however, in order to make use of this in llama.cpp, you must use the `--ctx_size 4096` flag to enable larger contexts without seg-faulting.

kobold.cpp has no support for this flag, and so this model cannot be utilized to its fullest potential.  You can check [this comment/discussion on HuggingFace](https://huggingface.co/reeducator/bluemoonrp-13b/discussions/1#6457f3da5fc3b8a21ea4826e) going over this for more context.

_Note: it does appear that a LLaMA model must be finetuned for 4k, otherwise you just get gibberish.  Unfortunately, this will not automagically expand the context of all LLaMA models, but it's pretty cool that a **finetune can add this capability**. We may see more models tuned like this in the future._

**Comment by LostRuins** [comment]
Fyi Koboldcpp *already* supports sending any context size you want by manually editing the value inside the Lite UI (it's a text input) 
![image](https://user-images.githubusercontent.com/39025047/236720759-96efd9d9-4107-4442-bcc8-ba877a714a01.png)

However, looking at the llama.cpp code they are still using fixed sized scratch buffers for the context, and they are also fixing the memory allocation at load time.
![image](https://user-images.githubusercontent.com/39025047/236720946-e923dc13-b920-4681-8ee6-f6cfe3eca116.png)

Can you confirm that this model works correctly in llama.cpp at 4096 context?

**Comment by LostRuins** [comment]
Hi, this has been added as of version 1.20. You can toggle a larger context with the `--contextsize` launch parameter.

**Comment by JackJollimore** [comment]
> Hi, this has been added as of version 1.20. You can toggle a larger context with the `--contextsize` launch parameter.

Hi, I am using koboldcpp on my android device. My prompt is like this, python ~/koboldcpp/koboldcpp.py ~/llama.cpp/models/RWKV-4-Raven-3B-v11-Eng99-Other1-20230425-ctx4096-ggml-q5_1.bin --threads 6 --blasbatchsize 32 --contextsize 4096

But when I send a message through kobold lite, I can see "max_context_length": 2048", being passed.

Am I missing something? This should reflect my specificed context, right?

**Comment by JHawkley** [comment]
Aye, you do need to do both `--contextsize` and change the config in Kobold Lite's settings to get the full context use.  For others dropping in here for help, even though the slider only goes up to 2048, you can click the number and input any value you like.

Me and a roommate have tested it and we are seeing it work great!  I guess I'll close this issue.  Thanks for putting it in so quick.
