### ISSUE TITLE
Anyway to see tokens as there being generated

### ISSUE THREAD

**Issue by TingTingin** [LostRuins/koboldcpp#16]
Is there a setting  that allows for tokens to appear in the UI as there being generated as of right now you only see messages after the entire thing is generated

**Comment by LostRuins** [comment]
Currently I do not print out the tokens while they are being generated as that clutters the console and slows down generation speed. Instead, you might find enabling streaming mode helpful by running with the stream flag using this link: http://localhost:5001?streaming=1
