### ISSUE TITLE
[Enhancement] Multiple instances of koboldcpp at a time using the same model, also using different models simultaneously.

### ISSUE THREAD

**Issue by AB0x** [LostRuins/koboldcpp#163]
Picture this, koboldcpp UI window with 4 different partitions each running different model or same one but with separate memory, you inter a prompt and all 4 fire up your PC to generate results simultaneously -heck even sequentially- and just compare.

**Comment by LostRuins** [comment]
You could probably already do that - you just need to run them on different ports, and then write a program to forward the generate requests to each server

**Comment by CorentinWicht** [comment]
We have installed koboldcpp on a Linux RHEL9 server and would like that multiple users can perform indepent local inference using the model without seing others requests (see for [similar question](https://www.reddit.com/r/LocalLLaMA/comments/12jl9sx/question_on_setting_up_local_inference_server_for/)). Currently, koboldcpp returns an error saying that the server is busy (while it is processing a first user's request when another user asks a second request).

Would there be a way to implement that?

The only option I currently see would be to have each user run koboldcpp within a container by sharing the same model but that would need a massive server instructure in case many users try to run it simultaneously.

Best,

C.

**Comment by LostRuins** [comment]
KoboldCpp doesn't support request queueing out of the box currently, so you would have to implement it on the client side. There are a few possible approaches - but first, are you using the Kobold Lite UI or a different client?

I am considering adding support for a limited queue system.

**Comment by LostRuins** [comment]
Good news , I have implemented a queue mode for koboldcpp which will be available in the next release. It will work out of the box.

**Comment by CorentinWicht** [comment]
> Good news , I have implemented a queue mode for koboldcpp which will be available in the next release. It will work out of the box.

Wonderful, many thanks for your reactivity and I am thrilled to test this new functionality!

Best,

C.

**Comment by LostRuins** [comment]
It's available in v1.44, which has just been released. Enjoy.
