### ISSUE TITLE
DDR5 required?

### ISSUE THREAD

**Issue by openMolNike** [LostRuins/koboldcpp#167]
I have CPU usage 55%.
Looks like RAM speed is performance bottleneck. Is **DDR5** required for best performance? PC4-25600 (DDR-4) is not enough?

**Model:** [alpaca-lora-65B.ggml.q5_1.bin](https://huggingface.co/TheBloke/alpaca-lora-65B-GGML/blob/main/alpaca-lora-65B.ggml.q5_1.bin)

My **PC** is:
CPU: AMD Ryzen 5 4650G PRO OEM (6 cores) 
RAM: **DDR4** 64Gb 3200MHz - Kingston FURY (KF432C16BBK2 / 64) PC4-25600
Board: MSI MPG B550I GAMING EDGE WIFI

**Comment by gustrd** [comment]
@openMolNike ,

I'm not the specialist here, but I use the software for some time and noticed that it uses only the physical cores, but to reach 100% CPU you have to use the virtual cores also.

Using the virtual cores doesn't increase the speed in this case, so I don't think memory bus is the bottleneck.

Play with the threads number and you will find out.

**Comment by openMolNike** [comment]
> Play with the threads number and you will find out.

I compared --threads 6 and --threads 12.

> to reach 100% CPU you have to use the virtual cores also
You are right. 12 threads makes CPU works 100% but text speed generations seems stay same

**Comment by AlphaAtlas** [comment]
It's quite possible that kobloid.cpp is RAM speed bound, but CPU usage won't reflect it. You have to look at more specialized hardware counters to see how bandwidth-starved the cores are.
