### ISSUE TITLE
Building with the new CUBLAST

### ISSUE THREAD

**Issue by AlphaAtlas** [LostRuins/koboldcpp#169]
Building the latest commit for CUBLAS seems to end in success, but trying to load a model results in the following error:

```
python koboldcpp.py --gpulayers 32 --model /home/alpha/Storage/AIModels/textui/metharme-7b-4bit-ggml-q4_1/ggml-model-q4_1.bin --port 5003 --stream
Welcome to KoboldCpp - Version 1.22
Warning: OpenBLAS library file not found. Non-BLAS library will be used.
Initializing dynamic library: koboldcpp.so
Traceback (most recent call last):
  File "/home/alpha/AI/koboldcpp/koboldcpp.py", line 648, in <module>
    main(args)
  File "/home/alpha/AI/koboldcpp/koboldcpp.py", line 552, in main
    init_library() # Note: if blas does not exist and is enabled, program will crash.
    ^^^^^^^^^^^^^^
  File "/home/alpha/AI/koboldcpp/koboldcpp.py", line 130, in init_library
    handle = ctypes.CDLL(os.path.join(dir_path, libname))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/alpha/AI/koboldcpp/koboldcpp.so: undefined symbol: ggml_cuda_mul_mat_get_wsize
```

Are there any extra steps that need to be taken? I can build and run the latest commit of Llama.cpp with CUBlast on this machine.

**Comment by AlphaAtlas** [comment]
Hmm, building with clang yields the same error. gcc-12 yields a different but similar error.

**Comment by x-legion** [comment]
anyway to set auto detect gpu layers and avoid cuda run out of memory. and also is it possible for cuda compatible version 5.0 old nvidia gpus like gtx 750ti @LostRuins

**Comment by LostRuins** [comment]
Please note that the CUDA build is an experimental special edition and long term support is not intended as we focus on better cross platform alternatives. 

That said - right now you have to estimate the number of layers to use through trial and error. Also yes I heard it does not work very well on linux with ggml_cuda_mul_mat_get_wsize for some reason, but I have no way to build and test CUDA on linux. Are you building via cmake or the makefile? If one fails, you can try the other.

**Comment by AlphaAtlas** [comment]
Yep, cmake works :+1: 

Apparently others on Arch Linux are able to build with `make` just fine :shrug: 

Some options (like llama native) are not enabled that probably should be enabled, but clearly that cmake file is a test file and this is a feature request for another issue.
