### ISSUE TITLE
Anti-virus alert at quantize.exe

### ISSUE THREAD

**Issue by gustrd** [LostRuins/koboldcpp#17]
Windows Defender and VirusTotal alerts that quantize.exe is infected by a trojan.

https://www.virustotal.com/gui/url/b38ef64324fc663d2248897a9fd82fed69588f2f1fb0221eee62a0184938e3a0?nocache=1

Windows Defender: Trojan:Win32/Wacatac.B!ml

Can someone check if it is a false positive?

I have not found another copy of quantize.exe to compare.

**Comment by LostRuins** [comment]
This is certainly a false positive - the quantize.exe is being rebuilt from source each time. 

What about the quantize.exe in [the parent repo](https://github.com/ggerganov/llama.cpp/releases/tag/master-eeaa7b0), is that being flagged for you too? 

https://github.com/ggerganov/llama.cpp/releases/download/master-eeaa7b0/llama-master-eeaa7b0-bin-win-avx2-x64.zip

**Comment by gustrd** [comment]
I checked both the quantize.exe at https://github.com/ggerganov/llama.cpp/releases/download/master-eeaa7b0/llama-master-eeaa7b0-bin-win-avx2-x64.zip and https://github.com/ggerganov/llama.cpp/releases/download/master-eeaa7b0/llama-master-eeaa7b0-bin-win-avx-x64.zip . 

Neither of then triggers Windows Defender, but Virus Total gives 2 warnings: https://www.virustotal.com/gui/file/887d960d684d7a4431afabe3327c34bab6bd11279c8d6f120dd53d0421a48ac4/detection

Cynet
Malicious (score: 100)
MaxSecure
Trojan.Malware.300983.susgen

**Comment by gustrd** [comment]
I checked again the quantize.exe at this repo and it doesn't triggers Windows Defender anymore also. Maybe it was a false positive of last version.

**Comment by LostRuins** [comment]
Possible. Anti viruses do not like small exe files with many types of instructions inside I guess.

In any case, it is all open source and can be rebuilt by anybody, so if you are concerned you can recompile it from the source code in this repo.

**Comment by gustrd** [comment]
Thanks by your attention! I will close the issue. Congratulations by the great project.
