### ISSUE TITLE
New CUDA version crashes without log

### ISSUE THREAD

**Issue by NovNovikov** [LostRuins/koboldcpp#172]
# Expected Behavior

It should load the model and not crash

# Current Behavior

When I try to load a model with --gpulayers any number it just crashes, just closes the window without any log attempt or error shown.

# Environment and Context

I use a wizardLM-13B-Uncensored.ggml.q4_0 newly quantized model from here 
https://huggingface.co/TheBloke/WizardLM-13B-Uncensored-GGML

My specs are 64 gb ddr5, i5 13600kf, Nvidia RTX 3060 ti

**Comment by Ed-ward** [comment]
Perhaps my actions were redundant, but everything works well. The first step was to download visual studio for windows. Then I downloaded and installed nvidia cuda driver. And after that, I began to select the number of model layers that fit in the video memory (the value of the --gpulayers parameter).

**Comment by LostRuins** [comment]
Check your drivers. At minimum, CUDA 11.8 support is required for the CUDA version

**Comment by NovNovikov** [comment]
Yes, now it works after I installed the newest CUDA. I will close the issue
