### ISSUE TITLE
[User] Concedo branch doesn't build main on Linux

### ISSUE THREAD

**Issue by lee-b** [LostRuins/koboldcpp#178]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

The default branch should build on linux, per the documentation.  Would suggest switching the default branch back to master until Concedo is fixed.

# Current Behavior

Default branch fails to build ./main, and instead builds kobold.so etc.

# Environment and Context

Native ubuntu 23.04, x86-64.

```
$ lscpu
...
Model name:                      AMD Ryzen 9 7950X 16-Core Processor
...
```

* Operating System, e.g. for Linux:

```$ uname -a
Linux (hostname withheld) 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

* SDK version, e.g. for Linux:

```
$ python3 --version
Python 3.11.2
$ make --version
GNU Make 4.3
...
$ g++ --version
g++ (Ubuntu 12.2.0-17ubuntu1) 12.2.0
...
```

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

# Steps to Reproduce

Clone the repo on Linux, cd, run `make`, per the Linux instructions.

# Failure Logs

[build.log](https://github.com/LostRuins/koboldcpp/files/11495993/build.log)

**Comment by LostRuins** [comment]
What is the error? I don't see anything failing to build from your log. Can you pull latest and try again?

**Comment by lee-b** [comment]
There is no error, the Makefile appears to not build the correct things on that branch.

**Comment by lee-b** [comment]
I have tried multiple times with clean checkouts, and even switched to a new PC and tried again, only to find that the main branch is fine, and the problem is that this branch is the default.

**Comment by LostRuins** [comment]
The master branch is not used, that one is originally created during the fork and used to pull upstream changes.

So even when running make with no flags, the koboldcpp.so is not generated?

**Comment by LostRuins** [comment]
Are you running the koboldcpp.py script? What error does the python script show when it loads the koboldcpp.so file?

**Comment by lee-b** [comment]
My bad, I was not doing that.  Should have read the instructions more closely.
