### ISSUE TITLE
[Feature request] add act plugin for reason-act

### ISSUE THREAD

**Issue by bobwen-dev** [LostRuins/koboldcpp#183]
Please add an act plugin that allows the AI to execute predetermined commands.

For example, if the curl command corresponding to `/search` is set, then the AI can send `/search llama 30b ggml site:huggingface.co`, then the act plugin receives the text starting with the `/search` prefix, executes the curl command then sends `Observation: <result text>`, then AI can make a better answer.

By setting a set of commands, AI can have more capabilities, such as sensing time through `/date`, sensing weather through `/weather`, `/iot` controlling home appliances or obtaining information about appliances, `/sqlite` query a database, and so on, and even being a programmer in a sandbox, developing and testing projects.

**Comment by LostRuins** [comment]
Sounds like you might want to check out https://github.com/LostRuins/koboldcpp/issues/55 where @simulanics is exploring similar features.

**Comment by bobwen-dev** [comment]
It's a similar feature, and I noticed that 'examples/reason-act.sh' is already doing this, but the part that executes commands is still missing, so I feel that handling responses requires a plugin with a customizable command list
