### ISSUE TITLE
new opencl --gpu-layers error. 

### ISSUE THREAD

**Issue by x-legion** [LostRuins/koboldcpp#184]
![image](https://github.com/LostRuins/koboldcpp/assets/97628039/a482a060-f009-44f9-bbff-c60e8868b24d)

.\koboldcpp.exe G:\LLM_MODELS\LLAMA\Manticore-13B.ggmlv2.q5_1.bin --unbantokens --smartcontext --psutil_set_threads --useclblast 0 0 --stream --gpulayers 1

**Comment by LostRuins** [comment]
Yeah that means the matrix multiplication on device failed. Maybe your device may not support gpu offloading.
