### ISSUE TITLE
Converting models. Still claim to be version 3.

### ISSUE THREAD

**Issue by Ph0rk0z** [LostRuins/koboldcpp#185]
I tried to use convert.py on a quantized GPTQ model. When I went back to load it, it said that it was an old version 3 model and didn't support offloading.

Is there some sort of sorcery here that I am missing?

**Comment by AlphaAtlas** [comment]
Was it a q8_0 model?

**Comment by Ph0rk0z** [comment]
No, it's just q4_0.. from what I'm seeing I have to requantize from FP32 to get GPU layers working. Good thing I didn't do any because it seems I have to do it yet AGAIN.

**Comment by AlphaAtlas** [comment]
Hmm I dont think thats right, I quantized from FP16.

I did notice that I got this error with the Q8_0 model, but not the Q5_1 model.

**Comment by Ph0rk0z** [comment]
In either case it needs the pytorch model and starting from scratch :(

**Comment by LostRuins** [comment]
try using the v1.23.1 which should have fixed this issue. You can also wait for tomorrow where I am planning to make a new release if everything goes well.

**Comment by LostRuins** [comment]
This should also be fixed in the latest version 1.24 which is just released. Let me know if it still doesn't work.

**Comment by Ph0rk0z** [comment]
well anything pre-quantized I convert with convert.py still says it is v3. So I guess it does have to be done from scratch.
