### ISSUE TITLE
[User] Modify/specify prompt for stable horde?

### ISSUE THREAD

**Issue by ThatDocBoi** [LostRuins/koboldcpp#186]
I am not sure if I am missing it, but how can I manually select a portion of the text for the prompt for stable horde? The autogenerated one is too complex usually for image generation algorithms. And if that feature is not implemented yet, will it be in the future please?

Thanks.

**Comment by LostRuins** [comment]
You cannot specify a direct prompt, but you can add additional words to use. This is done with the "Styles" option inside settings , click on the paintbrush icon.

**Comment by ThatDocBoi** [comment]
Ah I see, is there any reason for this limitation? It'd be great to select parts manually.

**Comment by LostRuins** [comment]
Probably mainly just generating single standalone images is a bit out of scope for this. If I find a good way to add it in in future I might consider. 

Have you tried the "Styles" option yet? Adding the words you want there before generating may give you the results you want.
![image](https://github.com/LostRuins/koboldcpp/assets/39025047/b9c54cc3-b71a-44e3-88b3-b7a081605dda)

**Comment by LostRuins** [comment]
You can now specify a prompt manully by Long Pressing on "Add Img"
