### ISSUE TITLE
[Bug] Can't set seed via HTTP API in koboldcpp.py

### ISSUE THREAD

**Issue by WeirdConstructor** [LostRuins/koboldcpp#189]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Sending the seed via POST HTTP Request to the API should not be ignored.

# Current Behavior

Sending the seed via POST HTTP Request to the API in koboldcpp.yp is ignored.
See this source code:

https://github.com/LostRuins/koboldcpp/blob/concedo/koboldcpp.py#L335-L351

# Environment and Context

I'm using Linux, but the environment is not the cause for the bug.

# Failure Information (for bugs)

Here is a simple patch:

```diff
diff --git a/koboldcpp.py b/koboldcpp.py
index d7d0519..0e925f2 100644
--- a/koboldcpp.py
+++ b/koboldcpp.py
@@ -332,7 +332,7 @@ class ServerRequestHandler(http.server.SimpleHTTPRequestHandler):
                     tfs=genparams.get('tfs', 1.0),
                     rep_pen=genparams.get('rep_pen', 1.1),
                     rep_pen_range=genparams.get('rep_pen_range', 128),
-                    seed=-1,
+                    seed=genparams.get('seed', -1),
                     stop_sequence=genparams.get('stop_sequence', [])
                     )
                 utfprint("\nOutput: " + recvtxt)
@@ -348,7 +348,7 @@ class ServerRequestHandler(http.server.SimpleHTTPRequestHandler):
                     tfs=genparams.get('tfs', 1.0),
                     rep_pen=genparams.get('rep_pen', 1.1),
                     rep_pen_range=genparams.get('rep_pen_range', 128),
-                    seed=-1,
+                    seed=genparams.get('seed', -1),
                     stop_sequence=genparams.get('stop_sequence', [])
                     )
                 utfprint("\nOutput: " + recvtxt)
```

**Comment by LostRuins** [comment]
This is now added via the API in the newest version. You may select a seed with the field `sampler_seed` (not seed) when submitting to the /generate endpoint
