### ISSUE TITLE
KoboldLite - Markdown: Trim Sentences setting removes final markdown formatting

### ISSUE THREAD

**Issue by shimaowo** [LostRuins/koboldcpp#191]
Thanks for the markdown support!

Minor nit with it:

If the "Trim Sentences" setting is enabled, and the final output token (excluding EOS) is the closing triple-backtick, KoboldLite will strip those backticks, leaving the markdown block unterminated. The backticks do show up in the console log, they are just removed from the UI output.

You then lose the markdown block and the preformatted spacing. Worse is that if you have multiple generations with markdown and this issue, the inferred markdown block will span across chats and really confuse the UI.

That's confusing so [here's an example](https://imgur.com/legMaAK). You can see that the user chat is included in the markdown block. Ignore the internal escaping (and awful code), that's just an issue with this model.

The main issue, though, is that I feel like "Trim Sentences" should not treat markdown formatting/markup as incomplete sentences to be removed.

**Comment by LostRuins** [comment]
Good point, I'll see what I can do

**Comment by LostRuins** [comment]
This should be fixed in the latest version
