### ISSUE TITLE
Optionally lengthen the pseudo streaming mode chunk size for better performance. 

### ISSUE THREAD

**Issue by AlphaAtlas** [LostRuins/koboldcpp#195]
Pseudo streaming mode in 8-token chunks requires extra prompt processing overhead and results in CPU/GPU utilization "gaps" like this:

![239135014-768cff54-0e8f-467e-b734-8fbce597801d](https://github.com/LostRuins/koboldcpp/assets/46462706/7bbd1e7a-dd0e-4864-9e9c-3df5fcbf875b)

Could we have a setting in the UI to increase the streaming "chunk" size from 8 to 16-24? I have manually edited it to 24 myself, and it makes streaming mode feel faster while still getting the "speed" benefit of reading text as it comes in. 

---

A separate request/idea for the farther future: maybe the text from a single large generation could be buffered in python and fed to the kobold UI in chunks without any significant changes to the web UI itself. llama-cpp-python does something similar... but with performance/utilization issues of its own that still need investigation.

**Comment by LostRuins** [comment]
I can see how this would be useful, but at the same time I don't want to clutter the UI further. I'll add it in as a URL parameter that power users can set when launching the lite UI.

**Comment by AlphaAtlas** [comment]
Yeah that would  be perfect :+1:
