### ISSUE TITLE
--port 80 doesn't work

### ISSUE THREAD

**Issue by nomonkeynodeal** [LostRuins/koboldcpp#196]
Port 80 specifically doesn't work. Tested on two machines. Here's the error. It's trying to use 5000 for some reason when it is definitely set to 80.

![image](https://github.com/LostRuins/koboldcpp/assets/84220428/5e615639-ed11-448f-b4a5-ffebf4854d90)

It's kind of annoying if you don't like having ports on your internal domains.

**Comment by LostRuins** [comment]
Are you on Linux? You must be a root user to bind to ports under 1024 if you are on Linux. On windows, it could be some admin firewall permissions that are blocking it.

**Comment by nomonkeynodeal** [comment]
This is happening on a Windows 10 VM and a Windows 11 laptop. The Windows firewall is disabled on both.

**Comment by LostRuins** [comment]
Try if port 81/82/83 works. If so, you may already have something else running on port 80.

**Comment by nomonkeynodeal** [comment]
Port 81 works. I guess it is Windows, but it's weird. Netstat -a -b shows nothing on port 80, then I run koboldcpp. It doesn't work and I close it. Netstat then shows svchost using port 80. I spent a while trying to find some service using that port and disabled a lot of them, but it's still happening.

**Comment by LostRuins** [comment]
Yeah then my guess is something is either using port 80, or BLOCKING port 80 for some reason. No reason for 81 to work and 80 to fail. There is no special rules in kobold that would affect this.

**Comment by koalaeagle** [comment]
I ran into the same thing. I have built koboldcpp into a docker container and am running on a Linux host. The docker container is using macvlan networking with its own IP so all ports are available to the container. I got this error when using --port 80, decided to revert to using --port 5001 and everything works as expected. In my environment I don't really need to use port 80 so no big deal, but it does seem like a bug.

**Comment by LostRuins** [comment]
On further investigation it does seem to be a bug. Please try specifying the port explicitly first, I will try to fix it in the next release.

http://localhost/?&port=80

**Comment by LostRuins** [comment]
Ah I remembered why I had to do it this way - because the default launch with no arguments is supposed to connect to port 5000, which is what main kobold client needs to use. So yes, please launch with this URL instead: http://localhost/?&port=80

**Comment by nomonkeynodeal** [comment]
That works but it's even worse than just adding a port number.

**Comment by LostRuins** [comment]
That's the best way to use port 80, since leaving port unspecified uses port 5000
