### ISSUE TITLE
Feature Request: Add real-time token counter to prompt entry box a-la Automatic1111

### ISSUE THREAD

**Issue by cgessai** [LostRuins/koboldcpp#207]
Crafting prompts around some set value of tokens (512, 1024, whatever) is currently a hassle and requires trial and error.  A real-time token counter for the text entry box would be an extremely useful feature.

**Comment by LostRuins** [comment]
There's a character counter in the ui at the bottom right corner. Exact token counts are not possible as the UI does not have a tokenizer built in.

**Comment by VL4DST3R** [comment]
I noticed the console outputs what prompt it is currently using when generating a response, which I'm assuming is however many tokens it can handle going back through the text you've generated so far (ignoring memory and world info).

Couldn't that be used as some kind of indicator in the web ui to gauge how far back does your current "memory" stretch? This is assuming I didn't get this all wrong as to how it operates.

**Comment by LostRuins** [comment]
The webui doesn't have that info, only the server.
