### ISSUE TITLE
[Question] Is there a way to enable streaming in chat-mode?

### ISSUE THREAD

**Issue by AllesMeins** [LostRuins/koboldcpp#208]
It seems that streaming works only in the normal story mode, but stops working once I change into chat-mode. Since my machine is at the lower end, the wait-time doesn't feel that long if you see the answer developing. So: Is there a trick to enable it or do you know an UI that works with kobold.cpp and supports streaming in a chat mode?

**Comment by LostRuins** [comment]
Yes. Simply disable the "Aesthetic chat UI" in Settings, and use chat mode with the regular Lite UI, which supports streaming.

**Comment by LostRuins** [comment]
Hi, this should be added in aesthetic chat mode as well in the latest version.
