### ISSUE TITLE
Error while submitting prompt: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data?

### ISSUE THREAD

**Issue by CallMeAl1973** [LostRuins/koboldcpp#210]
I'm frequently getting this while attempting to use the Linux version of Koboldcpp, recently cloned as of an hour or so ago. I can successfully connect to the endpoint and enter a prompt. I can also watch the console and see Koboldcpp generating tokens after I have entered a prompt. The console also displays the text that should be output back to the endpoint. Sometimes that text is output to the endpoint but more often than not, the endpoint doesn't receive the text, and throws the error  indicated in the title.
I am deploying on an Ubuntu Runpod and have seen this with several 30b parameter models, Wizard LM and Guanaco variants if that matters. Am I causing this somehow on my end or is there an issue? If there is an issue, happy to provide whatever info I can to help diagnose.

**Comment by LostRuins** [comment]
Can you open the "Network" tab of your browser and see what data is sent back in the JSON response?
![image](https://github.com/LostRuins/koboldcpp/assets/39025047/e37f3ee7-77c1-4922-83d1-9187a5c04b76)

**Comment by CallMeAl1973** [comment]
Closing as I am no longer able to reproduce.
