### ISSUE TITLE
[Enhancement] Add support for Metal inference

### ISSUE THREAD

**Issue by beebopkim** [LostRuins/koboldcpp#216]
Please make enabled Metal inference for GGML weight models.

Now, llama.cpp can generate texts using Metal inference on Apple Silicon computers. It is very good news for M1/M2 users, and I can run LLaMA 65B GGML q4_0 model on my M1 Max computer at the speed of 4 ~ 5 tokens/s. It is awesome and really fantastic!

koboldcpp repository already has related source codes from llama.cpp like ggml-metal.h, ggml-metal.m, and ggml-metal.metal. So please make them available during inference for text generation. It would be a very special present for Apple Silicon computer users.

**Comment by LostRuins** [comment]
Sure, I can try that, but I will need someone who can test it for me as I don't have a mac to test myself.

I have added the flags to the makefile. Can you please try building with `make LLAMA_METAL=1` and tell me if it works? If not, please detail what errors there are. Thanks

**Comment by MeeTee55** [comment]
Does kobold.cpp use metal by default when you compile it with LLAMA_METAL=1? In llama.cpp you need to start main with "-ngl 1" to use it.

**Comment by LostRuins** [comment]
You should use the koboldcpp command line arg --gpulayers which sets the same value.

**Comment by Dusterwald** [comment]
I've got an M2 Max MacBook that I've just tried it on. Ran `make clean` followed by `make LLAMA_METAL=1`.
It throws the following error for me:
```
Undefined symbols for architecture arm64:
  "_ggml_metal_add_buffer", referenced from:
      _llama_init_from_file in gpttype_adapter_failsafe.o
  "_ggml_metal_get_tensor", referenced from:
      llama_eval_internal(llama_context&, int const*, int, int, int, char const*) in gpttype_adapter_failsafe.o
  "_ggml_metal_graph_compute", referenced from:
      llama_eval_internal(llama_context&, int const*, int, int, int, char const*) in gpttype_adapter_failsafe.o
  "_ggml_metal_init", referenced from:
      _llama_init_from_file in gpttype_adapter_failsafe.o
ld: symbol(s) not found for architecture arm64
```
Not sure if I'm missing something or what. This is with the latest commit to the `concedo_experimental` branch (commit 6635f7e).
Hope that helps @LostRuins. Happy to do more testing if needed.

**Comment by LostRuins** [comment]
I've made a new commit to that branch to add the flags, can you see if it works now?

**Comment by Dusterwald** [comment]
That fixed the build problem, thanks. Will need to evaluate the performance a bit later.

**Comment by Dusterwald** [comment]
Tried running it with Metal enabled (on a 65B model) using this `python3 koboldcpp.py --gpulayers 80 models/VicUnlocked-Alpaca-65B.ggmlv3.q4_0.bin`

But that throws an error during initialization:
```
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 8192
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 64
llama_model_load_internal: n_layer    = 80
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 22016
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 65B
llama_model_load_internal: ggml ctx size =    0.18 MB
llama_model_load_internal: mem required  = 38610.46 MB (+ 5120.00 MB per state)
.
llama_init_from_file: kv self size  = 5120.00 MB
ggml_metal_init: allocating
ggml_metal_init: using MPS
ggml_metal_init: loading '(null)'
ggml_metal_init: error: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid."
```

Unfortunately looks a bit cryptic to me, no idea what it means.

**Comment by beebopkim** [comment]
> ```ggml_metal_init: allocating
> ggml_metal_init: using MPS
> ggml_metal_init: loading '(null)'
> ggml_metal_init: error: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid."
> ```
> 
> Unfortunately looks a bit cryptic to me, no idea what it means.

This error is happened when codes in ggml-metal.m tried to load 'ggml-metal.metal' at line 102, though ggml-metal.metal file was existed in same directory, it threw an error. I have no idea how to deal with this.
```
101:        //NSString * path = [[NSBundle mainBundle] pathForResource:@"../../examples/metal/metal" ofType:@"metal"];
102:        NSString * path = [[NSBundle mainBundle] pathForResource:@"ggml-metal" ofType:@"metal"];
103:        fprintf(stderr, "%s: loading '%s'\n", __func__, [path UTF8String]);
```
https://github.com/LostRuins/koboldcpp/blob/6635f7efce3389a0b15d3a01cdc85c4e65c8bccc/ggml-metal.m#LL102C97-L102C97

**Comment by kmilner** [comment]
I'm not familiar enough with objective c to tell why the NSBundle pathForResource works in the llama.cpp repo but not here, however if you want a work around you could change those lines to use the relative path directly:
e.g. comment out line 102 and 103, and change 105 to be

```        
NSString * src  = [NSString stringWithContentsOfFile:@"./ggml-metal.metal" encoding:NSUTF8StringEncoding error:&error];
```

**Comment by LostRuins** [comment]
Hmm I have not tried the metal implementation at all, nor have I modified any of the files. If you have recommendations to change them do let me know or send a PR, as I am not familiar with it at all.

**Comment by beebopkim** [comment]
Finally, I have made a pull request #221 using a patch file to change the path of ggml-metal.metal file in ggml-metal.m

**Comment by Dusterwald** [comment]
I applied the fix manually and can confirm that it works. Getting ~3.5 T/sec on the 65B model with my M2 Max. Pretty damn good, and fast enough for chat. Prompt processing is the biggest bottleneck now, I hope that can be sped up with Metal too at some point.

**Comment by LostRuins** [comment]
The patch from the PR has been merged directly into the metal file itself, along with the further Metal enhancements from upstream. Can you confirm if everything works now?

**Comment by Dusterwald** [comment]
@LostRuins I just tried the latest commit (d28ed99). Builds okay, but crashes on run with the following:
```
ggml_metal_init: allocating
ggml_metal_init: using MPS
ggml_metal_init: loading './ggml-metal.metal'
ggml_metal_init: error: Error Domain=MTLLibraryErrorDomain Code=3 "program_source:92:32: error: use of undeclared identifier 'tanhf'; did you mean 'tanh'?
    dst[tpig] = 0.5f*x*(1.0f + tanhf(SQRT_2_OVER_PI*x*(1.0f + GELU_COEF_A*x*x)));
                               ^~~~~
                               tanh
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/31001/Libraries/lib/clang/31001.722/include/metal/metal_math:4662:18: note: 'tanh' declared here
METAL_FUNC float tanh(float x)
                 ^
program_source:335:28: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
        for (int i = 16; i < nth; i += 16) sum[0] += sum[i];
                         ~ ^ ~~~
program_source:905:28: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
        for (int i = 16; i < nth; i += 16) sum[0] += sum[i];
                         ~ ^ ~~~
program_source:1006:28: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
        for (int i = 16; i < nth; i += 16) sum[0] += sum[i];
                         ~ ^ ~~~
" UserInfo={NSLocalizedDescription=program_source:92:32: error: use of undeclared identifier 'tanhf'; did you mean 'tanh'?
    dst[tpig] = 0.5f*x*(1.0f + tanhf(SQRT_2_OVER_PI*x*(1.0f + GELU_COEF_A*x*x)));
                               ^~~~~
                               tanh
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/31001/Libraries/lib/clang/31001.722/include/metal/metal_math:4662:18: note: 'tanh' declared here
METAL_FUNC float tanh(float x)
                 ^
program_source:335:28: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
        for (int i = 16; i < nth; i += 16) sum[0] += sum[i];
                         ~ ^ ~~~
program_source:905:28: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
        for (int i = 16; i < nth; i += 16) sum[0] += sum[i];
                         ~ ^ ~~~
program_source:1006:28: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
        for (int i = 16; i < nth; i += 16) sum[0] += sum[i];
                         ~ ^ ~~~
}
```

**Comment by beebopkim** [comment]
> @LostRuins I just tried the latest commit ([d28ed99](https://github.com/LostRuins/koboldcpp/commit/d28ed99e5916fb9755edf53f78beca3f02aa0050)). Builds okay, but crashes on run with the following:
> 
> ```
> program_source:1006:28: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
>         for (int i = 16; i < nth; i += 16) sum[0] += sum[i];
>                          ~ ^ ~~~
> }
> ```

Looks like ggml-metal.metal in koboldcpp has some bugs. To copy from llama.cpp's latest version will solve this bug. I guess bugs in koboldcpp will be disappeared soon as LostRuins merge latest version files from llama.cpp.

**Comment by beebopkim** [comment]
> The patch from the PR has been merged directly into the metal file itself, along with the further Metal enhancements from upstream. Can you confirm if everything works now?

@LostRuins ggml-metal.metal has some bugs as above comment described. And the most recent version from llama.cpp solves the bugs. Please merge Apple metal related files from llama.cpp b33dee28.

**Comment by LostRuins** [comment]
Okay I've merged the upstream Metal changes - does it work now?

**Comment by beebopkim** [comment]
<img width="682" alt="Screenshot 2023-06-09 at 9 35 40 PM" src="https://github.com/LostRuins/koboldcpp/assets/8567128/5b0127bb-8e3b-4029-a2a5-13fda3d7367b">
It works well now. 👍

**Comment by Dusterwald** [comment]
I can also confirm that it works now, and it does seem to be a bit faster from the new changes (around 4T/s now, up from 3.5T/s, though limited testing so it could just be variance).

**Comment by KizzyCode** [comment]
Ok, does not work for me:
```
Processing Prompt [BLAS] (200 / 200 tokens)
Generating (1 / 80 tokens)GGML_ASSERT: ggml-metal.m:629: false && "not implemented"
[1]    28456 abort      python3 koboldcpp.py --threads 8 --gpulayers 1 --port 8080 --host 127.0.0.1  
```

- Built with: `make LLAMA_METAL=1`
- Revision: `507939c135328e15ccb1ec7e1259408197b899bf`
- Commandline: `python3 koboldcpp.py --threads 8 --gpulayers 1 --port 8080 --host 127.0.0.1 --model ./Wizard-Vicuna-13B-Uncensored.ggmlv3.q4_1.bin --skiplauncher`
- Model: `M1 Pro`, 8 cores, 16 GB memory
- OS: `macOS Ventura 13.4 (22F66)`

However please note that I'm pretty new to all this AI-stuff, so it might very well be an error on my side^^

**Comment by helgur** [comment]
I get: 

`buffer 'data' size 18300780544 is larger than buffer maximum of 17179869184 llama_init_from_file: failed to add buffer`

When loading a 30b model on my 32gb m1 max. Shouldn't my hardware be able to support that a large of a model?

**Comment by LostRuins** [comment]
Maybe there is some overhead? Unfortunately I know nothing about the Metal implementation, so you should ask the devs in the llama.cpp issues page.

**Comment by helgur** [comment]
Yeah, good idea. Thanks!

**Comment by beebopkim** [comment]
> I get:
> 
> `buffer 'data' size 18300780544 is larger than buffer maximum of 17179869184 llama_init_from_file: failed to add buffer`
> 
> When loading a 30b model on my 32gb m1 max. Shouldn't my hardware be able to support that a large of a model?

@helgur My M1 Max has integrated memory of 64GB, and from 64GB of RAM, up to 48GB can be used as VRAM. Looks like 32GB's VRAM limit is up to 16GB.

**Comment by helgur** [comment]
@beebopkim ah, that explains it :(

**Comment by LostRuins** [comment]
Hey all, I just saw an upstream update that applied a similar fix for Metal: https://github.com/ggerganov/llama.cpp/pull/1782 which I merged.

Can you all see if this fix works too or does it break?

**Comment by phiharri** [comment]
Hey, I just pulled fb67506 and Metal works here, very cool 👍 Seeing around ~9T/s generation on 16GB M1 Pro using a 13B Q4_0 model.

**Comment by beebopkim** [comment]
With commit fb67506, everything is okay. Now, llama.cpp supports Metal MPS inference for f16, q4_0, q4_1, q2_k, q4_k(q4_k_m), q4_k_s, and q6_k. but it looks that f16 does not work for Metal inference with commit fb67506. I tested every known quantized formats for Metal inference and only f16 is not using Metal. But it is okay that it's not koboldcpp's problem. llama.cpp has exactly same problem.

**Comment by beebopkim** [comment]
I confirmed that GGML F16 is not accelerated with Metal in koboldcpp.

With most recent master commit of llama.cpp, GGML F16 is using Metal inference.
https://github.com/LostRuins/koboldcpp/assets/8567128/c722c792-55a1-4110-99ce-6aa7bdea7ceb

But with commit 120851d of koboldcpp, Metal inference is not working.
https://github.com/LostRuins/koboldcpp/assets/8567128/dc833b25-60ce-49f8-9333-853595de9988

The model weight used in this test is LLaMA 13B GGML F16.

**Comment by LostRuins** [comment]
To confirm, this is a known issue with upstream and not from KoboldCpp? If so, let me know when upstream has fixed it, and I will pull the fix.

**Comment by beebopkim** [comment]
@LostRuins For F16 Metal MPS acceleration, now llama.cpp supports it, but koboldcpp does not support it.

**Comment by LostRuins** [comment]
That is strange as I did not modify any of the metal files - so the behavior should be identical to upstream. Unfortunately I cannot debug it myself as I have no compatible mac device. If you figure out what to change, let me know and I can update it.

I think generally nobody really uses f16 format though.

**Comment by beebopkim** [comment]
@LostRuins What I have spotted is that, the source file including "Warning: Your model may be an OUTDATED format" is not existed in llama.cpp, and I found gpttype_adapter.cpp from koboldcpp has this string. So I guess I need to investigate pttype_adapter.cpp soon.

<img width="682" alt="llama_13b_f16-llama_cpp" src="https://github.com/LostRuins/koboldcpp/assets/8567128/9def2e2a-ed9f-466e-a098-370c70cbf6b8">

<img width="682" alt="llama_13b_f16-koboldcpp" src="https://github.com/LostRuins/koboldcpp/assets/8567128/acbd54df-3358-4650-9397-5520a71cbd47">

**Comment by beebopkim** [comment]
I think I should close this discussion because Apple Metal inference is well supported on koboldcpp. ```ggjt v1 f16``` is still not supported but it is minor issue because f16 is hardly used.

Now I found that I need to change expose.cpp and gpttype_adapter.cpp, maybe including the header files, but the code is very complex, and nowadays I am too busy to analyze and change the code soon.

I will make a new pull request for supporting Apple Metal Inference of ```ggjt v1 f16```.

Thanks for changing to support most Apple Metal inferences. 👍

**Comment by LostRuins** [comment]
You're welcome. Thanks for helping to debug metal, since I cannot run it myself.

**Comment by thhung** [comment]
With the new version, is there a way to confirm that it actually use GPU on Macos? In my machine, I didn't see the log that it is using MPS like the above comments.
