### ISSUE TITLE
Add support for the RWKV world tokenizer

### ISSUE THREAD

**Issue by xiaol** [LostRuins/koboldcpp#225]
According this commit https://github.com/saharNooby/rwkv.cpp/commit/82c4ac78f4d10ef1af87104fc051ea2119eaaddf

how can it merge into koboldcpp? 
BTW, world model is far more better and easy use for old one, and support 100+ languages.

Can test it here: https://u2-afba-82371503.westa.seetacloud.com:8443/   7B world 64% version

**Comment by LostRuins** [comment]
KoboldCPP already uses a very good tokenizer which should support any language or text. It should work for the world model too

**Comment by xiaol** [comment]
do you mean ggml share the same tokenizer? 

as world model trained on different tokenizer and vocabulary,  should use the same for inference

**Comment by latestissue** [comment]
It doesn't work for the world model, it's generating gibberish actually. I think it's the embedded rwkv vocab file that needs to be changed. Either way, something needs to changed because in the current stage the world models just won't work on koboldcpp.

**Comment by LostRuins** [comment]
Okay yes I think the vocab may be different. Can someone point me to the smallest possible RWKV ggml model that uses this new tokenizer?

**Comment by latestissue** [comment]
https://huggingface.co/latestissue/rwkv-4-world-ggml/blob/main/fp16-RWKV-4-World-0.1B-v1-20230520-ctx4096.bin
