### ISSUE TITLE
CUBLAS has been removed from llama_v2.cpp

### ISSUE THREAD

**Issue by logikstate** [LostRuins/koboldcpp#226]
is this intentional? it appears that recent llama.cpp changes change how this works, ggml_cuda_set_tensor_split, GGML_BACKEND_CPU, GGML_BACKEND_GPU, GGML_BACKEND_GPU_SPLIT have been added 

I image CLBLAS is also broken too?

**Comment by LostRuins** [comment]
That was intentional at that time, as I was trying to fix the support for clblast during the format change. I will see if I can add it back.

**Comment by LostRuins** [comment]
This should now be fixed. Please try
