### ISSUE TITLE
[Feature Request] Generate forever

### ISSUE THREAD

**Issue by Kaiten10** [LostRuins/koboldcpp#228]
Please add a "Generate forever" feature: once a generation ends, say after 512 tokens, it automatically starts generating the next 512 tokens.

This would really help when using 65B models which could take tens of minutes per generation. I am doing a creative writing/story prompt and would be amazing if we can leave it running in the background while at work or asleep, and come back to pages of text to read.

Example implementation in Automatic1111 Stable Diffusion UI (right click the generate button):
![image](https://github.com/LostRuins/koboldcpp/assets/55956659/0dd73635-8ab9-498e-97c5-8f799cc3750b)

**Comment by LostRuins** [comment]
The amount to generate is actually editable from the  ui. What you can do for now is to manually edit the text box. It can be set to as high as 1 less than the max context size. For infinite generation, it's currently not supported through the lite ui but can be done via custom uis or the api.

**Comment by LostRuins** [comment]
As a stopgap, you might be able to find a browser macro tool to periodically press the submit button

**Comment by VL4DST3R** [comment]
> but can be done via custom uis or the api.
How would one go about using those? The app seems to be quite self-contained.

**Comment by TravelingMan** [comment]
KoboldCpp can emit an API for other frontends, that's how a lot of people use it actually. Something like SillyTavern for the frontend and KoboldCpp for the backend is a fun combo!

**Comment by neph1** [comment]
If you use "Chat mode", and a bot to generate the story, you can use "Idle responses" in the UI to make it keep producing generations.
