### ISSUE TITLE
--contextsize 512 causing crashes?

### ISSUE THREAD

**Issue by cgessai** [LostRuins/koboldcpp#229]
Latest version, 1.29.  Including "--contextsize 512" to the command line prompt frequently leads to crashes during longer (Instruct, at least) outputs.  

To reproduce:
1. In app, click New Game button and Accept button
2. Click Scenarios, New Instruct, and Confirm button
3. Click Settings button, change "Amount to Gen" to 512 and click OK button
4. Enter a prompt such as "Write 40 long paragraphs about the history of England." and hit Submit

RESULT: While it doesn't happen 100% of the time, KoboldCPP will frequently error out after successful prompt ingestion and after some substantial portion of generated tokens.  In the UI, a ['failed to fetch' error dialog box](https://i.imgur.com/EeiCgdN.png) will pop up.  In the CMD window, the same [exception message](https://i.imgur.com/wrmnCtc.png) will be produced with the exception of those items in red boxes, which will sometimes read different values.  The only way to continue it to restart the whole program.

I've reproduced this in both [Wizard-Vicuna-7B-Uncensored Q4_0](https://huggingface.co/TheBloke/Wizard-Vicuna-7B-Uncensored-GGML/blob/main/Wizard-Vicuna-7B-Uncensored.ggmlv3.q4_0.bin) and [Wizard-Vicuna-13B-Uncensored Q5_1](https://huggingface.co/TheBloke/Wizard-Vicuna-13B-Uncensored-GGML/blob/main/Wizard-Vicuna-13B-Uncensored.ggmlv3.q5_1.bin)

Testing URL was always:  http://10.0.0.155:5001/?streaming=1#
CMD argument for launch (7B and 13B were similar) was: 
koboldcpp1.29.exe --stream --smartcontext --host 10.0.0.155 --threads 6 --useclblast 0 0 --launch --model "G:\GPT2-MODELS\TheBloke.Wizard-Vicuna-7B-Uncensored-GGML\Wizard-Vicuna-7B-Uncensored.ggmlv3.q4_0.bin" --unbantokens --blasbatchsize -1 --gpulayers 24 --contextsize 512

The only change to cmd line args during testing was --contextsize 512.  When it was not present the error was not observed.

**Comment by LostRuins** [comment]
That is because prompt processing also requires some vram that the GPU uses, apart from the offloaded layers. To get a safe estimate, you should run a test prompt at max context and see if the number of layers you picked has enough memory for that.

**Comment by DocShotgun** [comment]
Can't you just reduce the max tokens within the settings panel of the UI itself (or within the UI of SillyTavern or another frontend used to access via API) rather than limiting it from the commandline? 

IIUC the --contextsize parameter is meant for increasing the max context beyond the default 2048 for models that support longer context.

Also I'm of the opinion that you're better off just offloading fewer GPU layers so that you don't OOM during prompt processing. I've found through trial and error that I can get 31 layers of a 13B q4_0 onto my 8gb vram and not OOM during prompt ingestion.

**Comment by cgessai** [comment]
Thanks for the responses.  I don't have a link but last night I saw "setting to limit prompt tokens to X" feature request was already logged against llamacpp so maybe it'll eventually come from upstream.  

Re: _Can't you just reduce the max tokens..._
@DocShotgun  UI behavior automatically lowers "Amount to Generate" as "Max Tokens" is lowered.
