### ISSUE TITLE
--port argument not functional

### ISSUE THREAD

**Issue by na-na-hi** [LostRuins/koboldcpp#23]
When launched with `--port [port]` argument, the port number is ignored and the default port 5001 is used instead:
```text
$ ./koboldcpp.exe  --port 9000 --stream
[omitted]
Starting Kobold HTTP Server on port 5001
Please connect to custom endpoint at http://localhost:5001?streaming=1
```
Positional port argument (`./koboldcpp.exe  [model_file] [port]`) works as intended.

**Comment by LostRuins** [comment]
This should be fixed in the latest version.
