### ISSUE TITLE
[Request] Run safetensors model WizardLM on koboldcpp

### ISSUE THREAD

**Issue by nidjan** [LostRuins/koboldcpp#230]
Please say me. how to, if it maybe, run or convert https://huggingface.co/TheBloke/WizardLM-30B-Uncensored-GPTQ model

**Comment by cgessai** [comment]
You need the GGML version.  Try here: https://huggingface.co/TheBloke/WizardLM-30B-Uncensored-GGML

**Comment by nidjan** [comment]
thank you :)
