### ISSUE TITLE
GPU acceleration no longer possible on WSL

### ISSUE THREAD

**Issue by actually-a-cat** [LostRuins/koboldcpp#231]
Hi, 

as I understand it, CUDA is now only supported on Windows, and it's recommended to use OpenCL on Linux.

Unfortunately, I run Linux on WSL2, which does not support OpenCL. So if the above is correct, this means that GPU acceleration in kobold.cpp, which worked fine in 1.28 and earlier and works in llama.cpp, is no longer possible for me.

I understand that this is a niche setup and I don't expect support for it, I'll work around this issue, but I just wanted to make sure that this it is known.

**Comment by LostRuins** [comment]
Where did you read that cuda is only supported on windows? It should work on linux too. I just moved it from the make file to the cmake file which on hindsight I should revert. What errors are you getting?

**Comment by actually-a-cat** [comment]
The top of CMakeLists says 

`# DO NOT USE THIS FILE. 
# IT'S ONLY FOR CUBLAS BUILD PURPOSES ON WINDOWS VISUAL STUDIO. 
# IT WILL NOT BE UPDATED OR MAINTAINED !!!`

So I didn't investigate building with CMake any further 😂

I'll try it later, then.

**Comment by LostRuins** [comment]
Yeah I should probably modify that. It is generally aimed at visual studio but should work on wsl if you somehow manage to get cuda working there.
