### ISSUE TITLE
Cuda, linux, v1.30.1

### ISSUE THREAD

**Issue by 7erminalVelociraptor** [LostRuins/koboldcpp#233]
With the latest release (1.30.1) there is also another CUDA build beside to normal one. However there is only a windows .exe provided. For Linux there is just the single source .tar that doesn't appear to be for CUDA.  Is there a undocumented build flag we need to run 'make' with?

**Comment by LostRuins** [comment]
Okay so I reverted the LLAMA_CUBLAS flag into the makefile, didn't realize people were actually using that before. However, you may still have better results building with the cmake inside.

**Comment by ycros** [comment]
Hi I fixed a problem with the Makefile in a PR https://github.com/LostRuins/koboldcpp/pull/241

@7erminalVelociraptor `make LLAMA_CUBLAS=1` works for me with my fix - I also had to make sure CUDA's bin was on my path so the `Makefile` can find `nvcc`. If your CUDA isn't at `/usr/local/cuda` or `/opt/cuda` you should also set CUDA_PATH

**Comment by noneabove1182** [comment]
"you may still have better results building with the cmake inside"

what do you mean by that? If I were building from source and wanted to do the CUDA build, how would I best do this?

I'm trying to improve speed of generation, my processing is blazing fast but generation is still ~150ms/T, does the CUDA build help with that?

**Comment by LostRuins** [comment]
CUDA and clblast generation speed is about the same.

**Comment by noneabove1182** [comment]
fair, is there a good way to speed up generation on kobold atm? I know with text-generation-webui I get much faster inferencing but less model compatibility so trying to figure out how to build koboldcpp the same speed

**Comment by LostRuins** [comment]
Have you offloaded layers with --gpulayers yet? (combine with --useclblast)

**Comment by noneabove1182** [comment]
> Have you offloaded layers with --gpulayers yet? (combine with --useclblast)

Yup, I can tell it's working cause prompt ingestion is stupid fast, but generation is still slow as hell. The GPU loads it into memory cause I can see it getting used

**Comment by neph1** [comment]
I seem to have the same issue. It parses the prompt very fast, then takes quite a while to generate tokens. ~30ms/T vs ~500ms/T
It also definitely finds the GPU:
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060

But I also seem to have the issue of the whole model not being loaded into the GPU. I've specific --gpulayers 64 (and tried loads more than that), but only about 2.8GB is loaded into VRAM.

**Comment by LostRuins** [comment]
@neph1 Have you compared to the non-cuda (clblast) version?

**Comment by 7erminalVelociraptor** [comment]
I've seen some talk online that the latest Nvidia drivers caused some memory performance regression. It can be wortwhile to look in that direction.

**Comment by neph1** [comment]
> @neph1 Have you compared to the non-cuda (clblast) version?

Sadly no. I didn't get it up and running before discovering that CUDA was a thing. :)

This is without --useclblast:

Processing:184.5s (117ms/T), Generation:52.2s (408ms/T)
(1581 tokens and 128 tokens)

**Comment by noneabove1182** [comment]
@LostRuins is it possible that GPU layer offloading doesn't work for models that don't support llama.cpp? I found that running for instance https://huggingface.co/TheBloke/robin-13B-v2-GGML runs very fast and uses as much VRAM as I can give it, but running https://huggingface.co/TheBloke/WizardCoder-15B-1.0-GGML offloads only 2GB even with i try to put all 40 layers on the GPU

so maybe I'm misunderstanding the model limitations? It says on thebloke's page it's for cpu+gpu inferencing but maybe that's a copy paste error

**Comment by neph1** [comment]
I just rebuilt from master and now the offloading works OK! :+1:

**Comment by LostRuins** [comment]
@noneabove1182 that is correct, gpu offloading does not apply to non-llama models currently.

**Comment by LostRuins** [comment]
GPU offloading now applies to Non-LLAMA models as well, in the latest version

**Comment by 7erminalVelociraptor** [comment]
Offtopic, but I find this thread amusing. It went from a request for clarification to a bug report to a miniature changelog :)
