### ISSUE TITLE
Bug . generate check function trigger mode to generate random answers.

### ISSUE THREAD

**Issue by UnsGentoals** [LostRuins/koboldcpp#236]
Version 1.30.1 
Just try any model, you will see it

**Comment by UnsGentoals** [comment]
Because it was called, before the backend handle the real user prompt.
Maybe add some delay before calling this?

**Comment by UnsGentoals** [comment]
Just tested, even steam mode is off . This Bug still exist.
Maybe the code is broken.

**Comment by UnsGentoals** [comment]
The only way to make this version to work is to set streaming=1 and streamamount=8

**Comment by LostRuins** [comment]
Can you show some screenshots of what you mean? Are you referring to the idle responses?

**Comment by UnsGentoals** [comment]
Not idle response.  
This version is broken. 💔

**Comment by UnsGentoals** [comment]
Reason to this is,
i load conversation from older versions.
