### ISSUE TITLE
Unable to offload layers on GPU (Linux Manjaro)

### ISSUE THREAD

**Issue by Thangzy** [LostRuins/koboldcpp#239]
Hello

I'm trying to offload layers to my gpu but it doesn't work, I get: 
_ggml_opencl: clGetPlatformIDs(NPLAT, platform_ids, &n_platforms) error -1001 at ggml-opencl.cpp:782
You may be out of VRAM. Please check if you have enough._

Here is my config:

- Linux Kernel 6.1.31-2-MANJARO (64-bit)
- Windows 11 (Dual boot)
- Ryzen 5600X
- R9 Furry 4Gb Vram
- 16 Gb DDR4

What I did:

1. Downloaded the latest version (1.30.2)
2. Build using _make LLAMA_OPENBLAS=1 LLAMA_CLBLAST=1_ 
3. Launched with the following arguments (the output is bellow) _--threads 10 --useclblast 0 0 --gpulayers 15_

Without _--useclblast 0 0 --gpulayers 15_ it works and use OpenBLAS instead.

On Windows 11 it works just fine, layers are offloaded to the GPU.

I tried different combination of parameters for _--useclblast_ but I still get the same error in the end.

Here is the output:

```
>>python koboldcpp/koboldcpp.py Downloads/Wizard-Vicuna-13B-Uncensored.ggmlv3.q5_K_M.bin --threads 10 --useclblast 0 0 --gpulayers 15

Welcome to KoboldCpp - Version 1.30.1
Attempting to use CLBlast library for faster prompt ingestion. A compatible clblast will be required.
Initializing dynamic library: koboldcpp_clblast.so
==========
Loading model: /home/user/Downloads/Wizard-Vicuna-13B-Uncensored.ggmlv3.q5_K_M.bin 
[Threads: 10, BlasThreads: 10, SmartContext: False]

---
Identified as LLAMA model: (ver 5)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 
llama.cpp: loading model from /home/user/Downloads/Wizard-Vicuna-13B-Uncensored.ggmlv3.q5_K_M.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 17 (mostly Q5_K - Medium)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
ggml_opencl: clGetPlatformIDs(NPLAT, platform_ids, &n_platforms) error -1001 at ggml-opencl.cpp:782
You may be out of VRAM. Please check if you have enough.
```

**Comment by Thangzy** [comment]
Answering myself for whoever encounter this problem. 

You need to build opencl-mesa using _pamac build opencl-mesa_

I have been looking for days to make it work and now everything run fin, sorry for the ticket, should have looked a bit more before opening.

Thanks for your work.

**Comment by KizzyCode** [comment]
Have you ensured that a) your GPU is detected correctly in Arch and b) that `--useclblast 0 0` is referring to the correct GPU (and not the iGPU or similar)?
