### ISSUE TITLE
Question: Is there any way to increase the max number of tokens generated from 512?

### ISSUE THREAD

**Issue by dogjamboree** [LostRuins/koboldcpp#24]
Maybe this is a dumb question, but why is the limit 512? The model I'm using has a limit that's much higher (vicuna), if not unlimited. If this something hard-coded in the program or could it be modified?

**Comment by LostRuins** [comment]
It can be increased in the webui settings. It is not fixed.

**Comment by dogjamboree** [comment]
> It can be increased in the webui settings. It is not fixed.

It can be set to a maximum of 512 while the models support more. Is there a way to change this via coding or is this a hard-coded limit?

**Comment by LostRuins** [comment]
Perhaps you are editing the wrong field. You should be changing the "Max Context Length" which has a slider range to 2048, and not the "Amount to Generate".

It's also possible to override the max slider values by manually editing the text number on the input.

**Comment by dogjamboree** [comment]
You're right,the "Max Context Length" slider does go to 2048 and I have it to that maximum number, but I'm interested in getting the "Amount to Generate" as high as possible.

For "Amount to Generate", I just realized what you meant about manually editing that number and again, you're right, you can override the slider number of 512 by manually typing a number there but it even if I type 5000 or 10000 or some other number that I know is supported through both the model and llama.cpp it cuts it back to 1024 when I go back into the settings again. (llama.cpp even allows -1 for no limit whatsoever and I can attest that sometimes it returns a ridiculous amount of text, which is great as someone who is generating stories).

So I guess my question remains -- is there a way you as a developer can get past that limit of 1024 or is it something hardcoded into Kobaldai?

Thanks for all your work on this BTW!!

**Comment by LostRuins** [comment]
Uh yeah, I hard limited it to cap at 1024 as larger numbers may cause issues running OOM. I can probably increase that limit further - but is there a reason why simply hitting the "Generate" button a second time to continue is less preferred?

**Comment by dogjamboree** [comment]
When I'm writing a story and using llama.cpp, I set the limit to -1 (infinite), which means sometimes it will generate a ridiculous amount of text, like 5000 tokens, 10,000 tokens, or just keep going forever (and I have to control-c the program of course)

You're right, this does cause my swap to go crazy BUT there's a real advantage to this over hitting generate again and that is the entire story is completely coherent within the context of the original prompt. Because I use very long prompts and so eventually that context is lost and I start getting worse stories.

Anyway, Unfortunately I'm still using llama.cpp instead of your excellent implementation because of this limitation. Because I love having more control over all the parameters. 

Which brings up something else which I should prob just open another question / suggestion for, but is there any way to pass llama.cpp flags into kobaldai? Because as you know there a several more esoteric flags that can''t be triggered via the kobaldai interaface like --keep, repeat last, etc (Unless I'm just missing them?).

**Comment by LostRuins** [comment]
KoboldAI handles context is a different way from llama.cpp. While they have a few options to control the textgen, almost everything we have regarding prompt shaping is powered from within the UI itself. So a --keep option would not make sense, that is already done (at a dynamic level) by editing the "Memory" field within the UI.

 As for your example, actually if you look through the llama.cpp source code for infinite generation and long prompts you'll realize it's no different too - it simply cuts away the first half of the story from the context, shifts the rest up, and regenerates everything from that point.

**Comment by dogjamboree** [comment]
Thanks for the explanation. Obviously I don't understand how KobaldAI works, I was just guessing about how both programs worked based on what I observed.

Is there documentation for this stuff anywhere? I quick search didn't turn anything up. I would love to know how that memory field works for example (because it didn't seem to do anything when I trired it).

Maybe you could tell me if you get a free second, how to accomplish what I need. Basically my prompts are quite long and consists of a short paragraph with a few sentences, followed by a long numbered list of plot elements of things I want to include. My problem is I find that many of those plot elements get ignored by the model (not every time but randomly) regardless of whether I use straight llama.cpp or KobaldAI, although I have to say I seem to have slightly better luck with llama.cpp. 

So if there's something I could be doing differntly I would love to hear it. Like I said, I tried using that memory field before by putting my list there and just giving a very short prompt but it didn't take ANY of those elements into consideration when it generated the story. Not sure if maybe it's only used in certain modes?

Anyway, sorry for the long comment, and thanks again for all your work!

**Comment by LostRuins** [comment]
Hmm may I suggest joining the KoboldAI discord? We have plenty of helpful guides on the best ways to format your prompts/stories, and the people here are generally helpful and glad to assist.

https://koboldai.org/discord

**Comment by dogjamboree** [comment]
I joined the discord but for some reason I only see 2 channels, 1)rules and 2)AI safety. I'm on at least a dozen discord servers and never had this problem. Any ideas? (And sorry to bother you about this here!)

**Comment by Midaychi** [comment]
Alpacino is an example of an odd edge case that would make sense to uncap the generation output for.
It is a model optimized for a very specific use of instruct, caps its own generation off, and set up for for "~680 or greater" token output using godlike, or storywriter+1.1 temp outputs.

And I suppose there's nothing stopping you from just continuing the prompts; it's just annoying because of how the instruct mode is setup.

**Comment by Midaychi** [comment]
I legit did not know that was an editable field until you pointed it out.

**Comment by Midaychi** [comment]
Works great at 1024 tokens and doesn't even tend to generate all of them. Though this is all kind of moot because I guess I mis-read the instructions and its meant to be used in chat mode; just with an instruct setup... instructions unclear reboot cucumber.

**Comment by gustrd** [comment]
> Works great at 1024 tokens and doesn't even tend to generate all of them. Though this is all kind of moot because I guess I mis-read the instructions and its meant to be used in chat mode; just with an instruct setup... instructions unclear reboot cucumber.

@midaychi, give a look at my PR and fork, I implemented parameters to upper cap tokens and context. I was able the run at KoboldAI max.

**Comment by Midaychi** [comment]
> > Works great at 1024 tokens and doesn't even tend to generate all of them. Though this is all kind of moot because I guess I mis-read the instructions and its meant to be used in chat mode; just with an instruct setup... instructions unclear reboot cucumber.
> 
> @midaychi, give a look at my PR and fork, I implemented parameters to upper cap tokens and context. I was able the run at KoboldAI max.

I saw and I tried but they didn't seem to do anything?
I guess I'm not joining any horde?

**Comment by gustrd** [comment]
No, it work with the embedded Kobold Lite and United KoboldAI also.

What are the parameters you are passing? Did you look the updated --help?

**Comment by Midaychi** [comment]
yeah I tried setting them via the commandline switches and it launched fine but it didn't change the respective values? Does it get overwritten by a save/cached browser data maybe?

**Comment by LostRuins** [comment]
What values are you trying to change? For context length, you should set it in the web ui editor settings
![image](https://user-images.githubusercontent.com/39025047/233528840-1393a7e7-2711-4ec6-85c8-9237476c7cb3.png)

**Comment by Midaychi** [comment]
Not sure I understand the purpose of the console switches you wanted me to test, then.

**Comment by gustrd** [comment]
> Not sure I understand the purpose of the console switches you wanted me to test, then.

There is an upper cap at the code, the parameters raise them, but you still need to select the desired amount at the UI.

**Comment by gustrd** [comment]
@Midaychi , sorry, I tried again and saw that at Concedo's KoboldCPP the webui always override the default parameters, it's just at my fork that them are upper capped . My bad.

@LostRuins , do you believe that the possibility of generating token over 512 is worth mentioning at the Readme? I never imagined that.

**Comment by LostRuins** [comment]
Kobold Lite has the defaults set to 1024, but they can adjusted to any value between 1 and 2048 from the settings in UI.

**Comment by sunshine69** [comment]
Max output 512 is too small. qwq32b thought process is well over that and I use ollama set num_predict -1 having no problem generating huge text. So pretty disspointed here to see it is hardcoded and in flexible. IMHO devs should be able to set it with help text wanring if settings and let them make a decision rather than baby sitting them.

**Comment by LostRuins** [comment]
This was from 2 years ago. 
It is flexible now. It can be set both the API as well as a launch parameter (default gen amount)

**Comment by alex-ie** [comment]
> It is flexible now. It can be set both the API as well as a launch parameter (default gen amount)

@LostRuins , hi. Now in 1.110 when I set default gen amount in launcher to e.g. 4000 when Web GUI is started I see 1564 in max output and max 2048 slider (linux nocuda). I think it is more proper to pass the parameter to web interface. Interestingly context at default in launcher (8192) resulted in 12152 in GUI grey box for number and 8192 max slider. Maybe I better open a new feature request.

**Comment by LostRuins** [comment]
the Max slider should show whatever you loaded koboldcpp as. If it doesn't, refresh the page. Then you can adjust the slider.

**Comment by Namesarenames** [comment]
same here, cant really go above 2048, no matter what I put there, is there a start parameter like --max_token_output or something?

(I dont want to be picky either, this is amazing work here!! Thank you)

**Comment by LostRuins** [comment]
There's only 2 places you need to adjust for any of this:

1. In the KoboldAI Lite settings, you can increase the "Max Output" parameter. You can *edit* this field to be any number you want. 

<img width="718" height="215" alt="Image" src="https://github.com/user-attachments/assets/3da1318e-8bee-4e97-a7ab-83d93898b165" />

2. In the launcher, you can set `--defaultgenamt`, this sets the amount to generate IF its not specified by a frontend.

<img width="466" height="162" alt="Image" src="https://github.com/user-attachments/assets/c977cd4b-5748-4018-9d2d-80c2df5531fd" />
