### ISSUE TITLE
[Deepire] Help Please, I am new to it 

### ISSUE THREAD

**Issue by Deepire** [LostRuins/koboldcpp#242]
I am currently trying to load Alpaca via Koboldcpp on Google Colab.
This is my code in Colab:
%cd /content
!git clone https://github.com/LostRuins/koboldcpp.git
%cd koboldcpp
!git clone https://github.com/artidoro/qlora
%cd /content/koboldcpp
!bash install_requirements.sh "CUDA"
!make LLAMA_CLBLAST=1
!pip install -r requirements.txt
!sudo apt-get install libclblast-dev libopenblas-dev
!mkdir /content/koboldcpp/models
!apt-get -y install -qq aria2
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/Pi3141/gpt4-x-alpaca-native-13B-ggml/blob/main/ggml-model-q8_0.bin -d /content/koboldcpp/models/gpt4-x-alpaca-13b-native-4bit-128g-cuda -o ggml-model-q8_0.bin

!python koboldcpp.py  --lora /content/koboldcpp/qlora --model models/gpt4-x-alpaca-13b-native-4bit-128g-cuda/ggml-model-q8_0.bin

I get this: 
Unknown Model, cannot load.
Load Model OK: False

Tell me please what am i doing wrong?

**Comment by LostRuins** [comment]
I'm not sure if that lora is compatible. Can you try removing `--lora /content/koboldcpp/qlora` and try again?

**Comment by Deepire** [comment]
> I'm not sure if that lora is compatible. Can you try removing `--lora /content/koboldcpp/qlora` and try again?

Status Legend:
(OK):download completed.
Welcome to KoboldCpp - Version 1.30.3
Warning: OpenBLAS library file not found. Non-BLAS library will be used.
Initializing dynamic library: koboldcpp.so
==========
Loading model: /content/koboldcpp/models/gpt4-x-alpaca-13b-native-4bit-128g-cuda/ggml-model-q8_0.bin 
[Threads: 1, BlasThreads: 1, SmartContext: False]

---
Identified as LLAMA model: (ver 0)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 

Unknown Model, cannot load.
Load Model OK: False
Could not load model: /content/koboldcpp/models/gpt4-x-alpaca-13b-native-4bit-128g-cuda/ggml-model-q8_0.bin

**Comment by Deepire** [comment]
> I'm not sure if that lora is compatible. Can you try removing `--lora /content/koboldcpp/qlora` and try again?

same story

**Comment by KosRud** [comment]
Is the file size correct?
![image](https://github.com/LostRuins/koboldcpp/assets/36504423/be786aac-a0e2-47ef-83dc-9c48d915dc4f)

If you have unreliable internet connection, the download could have interrupted early, leaving you with only a part of the file. It could be that the header (identifying the model type as `LLAMA model: (ver 0)`) was in the beginning, but the end of the file is missing.

**Comment by Deepire** [comment]
> Is the file size correct?
> 
> ![image](https://user-images.githubusercontent.com/36504423/246239550-c3c0073e-0354-482c-bdcf-29b807089f1b.png)
> 
> If you have unreliable internet connection, the download could have interrupted early, leaving you with only a part of the file. It could be that the header (identifying the model type as `LLAMA model: (ver 0)`) was in the beginning of the file, but the end of the file is missing.
> 
> **Note**: the screenshot is just an example, check the page from which you downloaded the model to see the correct size.

Thanks it helps, by the way is there anyway to create a shared link like in Llama --share ?

**Comment by KosRud** [comment]
Are you using the same settings? (number of CPU threads, CLBlast, number of gpu offload layers)

**Comment by Deepire** [comment]
> Are you using the same settings? (number of CPU threads, CLBlast, number of gpu offload layers)

yep, same, i even tested with adding --gpulayers 12 but nothing changes, it was insanely slow

**Comment by LostRuins** [comment]
If you want gpu acceleration, try adding --useclblast (platform) (device)
