### ISSUE TITLE
Autoscroll not autoscrolling

### ISSUE THREAD

**Issue by Nabokov86** [LostRuins/koboldcpp#244]
Not sure why no one has reported it yet, but I think the autoscroll function is broken with the new streaming.

**Comment by LostRuins** [comment]
Should be fixed in the latest version, please try

**Comment by Nabokov86** [comment]
It works perfectly! 

By the way, is it possible to make streaming updates less frequent? I've noticed it now updates more frequently than in the previous version.
![image](https://github.com/LostRuins/koboldcpp/assets/26260168/0b516d5c-433d-482c-8c0a-0bd95414b278)

**Comment by LostRuins** [comment]
I've added an update to only show the polling logs if --debugmode is set. This should reduce clutter

**Comment by Nabokov86** [comment]
@LostRuins Wow, it's perfect now! Thanks a lot for your hard work, you are awesome ❤
