### ISSUE TITLE
Strange formatting issue on older Firefox versions

### ISSUE THREAD

**Issue by VL4DST3R** [LostRuins/koboldcpp#245]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Current Behavior

I have noticed a few inconsistencies when using an older FF ESR version, the biggest and most annoying being the fact that whenever you cut/paste something from the text block back into itself, it seems to create something of a ghost indentation that cannot be deleted. Further testing revealed it creates a new `span.txtchunk` inline with the already existing one, causing this behavior:

![image](https://github.com/LostRuins/koboldcpp/assets/32654378/b73b7059-dd1c-4160-afff-37ae9b79a7eb)

You can somewhat mitigate this by refreshing the page or unfocusing the textbox, at which point it gets reformatted properly (into a single textblock).

# Expected Behavior

Merge properly with the already existing row of text, like it does in other browsers (tested as working properly on chrome and edge).

# Environment and Context

Windows 10 running Waterfox G3, fork based on Firefox 78 ESR.

# Steps to Reproduce

1. Write anything either by hand or generated into the main output area.
2. copy/paste something from it, e.g. a word.
3. an extra txtchunk is now created, (you can use inspector to highlight it).

**Comment by Nabokov86** [comment]
This issue also applies to the latest version of Firefox. Can't reproduce it on chromium.

**Comment by VL4DST3R** [comment]
Oh, glad to know at least it's not me clinging to an old-ass version for the sake of backwards-compatibility XD

**Comment by Nabokov86** [comment]
> story and action images not showing up at all

I don't use this feature.

**Comment by LostRuins** [comment]
Should be fixed in the latest version, please try

**Comment by Nabokov86** [comment]
Great, it works perfectly.

**Comment by VL4DST3R** [comment]
Can confirm my issue is fixed as well, closing. However i still have the action/story icons missing when in adventure mode.

![image](https://github.com/LostRuins/koboldcpp/assets/32654378/6360b676-28eb-41a7-b719-74273e2c64bc)

It seems to simply not be there. Should i make another ticket?

**Comment by LostRuins** [comment]
I tried running it in firefox and the icons do show for me. Anyone else has this issue?
