### ISSUE TITLE
Prompt is always reported as generating 1536 tokens at most

### ISSUE THREAD

**Issue by dogjamboree** [LostRuins/koboldcpp#25]
After the prompt is sufficiently large, I always get the same message:
Processing Prompt [BLAS] (1536 / 1536 tokens)

I don't know if it's actually processing more or if it's incorrectly cutting of at 1536 when I have the context set to 2048 (that's what should dictate this setting, correct? Or is that wrong?)

It's hard to tell from the responses what it's considering in the prompt sometimes as is the nature of these models.

**Comment by LostRuins** [comment]
It could be the settings inside the kobold lite UI itself. You can try increasing the max context length in the settings of Lite.

**Comment by dogjamboree** [comment]
I verified that I have it set to 2048 in the UI. Is there more than one place to change it?

**Comment by LostRuins** [comment]
In that case, it's more likely that it is reusing tokens from a part of your previous prompt (e.g. the Memory).

You can verify this by saving the file, starting a brand new game and generating a line, then reloading the file and generating again,

**Comment by dogjamboree** [comment]
I got openblas working and now I can't really tell how many context tokens it's processing because it's so fast...anyway, closing.
