### ISSUE TITLE
Generates fixed token size EVERY TIME

### ISSUE THREAD

**Issue by PedzacyKapec** [LostRuins/koboldcpp#256]
How come it doesnt adjust automatically to as many tokens as it needs instead always fixed amount of tokens ?

Eg.
When i generate for instance code i dont exactly know how many tokens I will need but if the option is set to 50 tokens it always generates 50 tokens but if i set it to 512 and the code is short I just waste my time sitting waiting for the code to be generated twice with the manual...

**Comment by 7erminalVelociraptor** [comment]
Basically, Language Models work by trying to predict the next token after looking at the previous tokens in the context. At the base level it can't tell the difference between it's output and input, and it has no actual understanding of the text, it only understands the probabilities of what the next piece of text will be. It doesn't inherently know that it's done and without giving it a hard limit when to stop, it will often go on indefinitely.

**Comment by PedzacyKapec** [comment]
> Basically, Language Models work by trying to predict the next token after looking at the previous tokens in the context. At the base level it can't tell the difference between it's output and input, and it has no actual understanding of the text, it only understands the probabilities of what the next piece of text will be. It doesn't inherently know that it's done and without giving it a hard limit when to stop, it will often go on indefinitely.

GPT4ALL nor Oobabooga apps dont seem to have problem with that.

**Comment by LostRuins** [comment]
Probably because they don't ban the EOS token by default.
