### ISSUE TITLE
[Feature Request] Context scaling support.

### ISSUE THREAD

**Issue by Sumanai** [LostRuins/koboldcpp#257]
There is information that for Llama-based models, you can simply increase the context to 4/8k tokens, and with a minimum of fine-tune make it work smoothly with that much context. If it is possible to transfer these changes to the CPP version, it will give a great improvement in the user experience.
Here's the corresponding article by the author (I'm not the author, I just brought the link)
https://kaiokendev.github.io/til#extending-context-to-8k
Full code for the pytorch
https://github.com/vihangd/alpaca-qlora/blob/239d13e8e56695b78d6c2d602b8f60bd190fb7b0/experiments/llama_rope_scaled_monkey_patch.py

**Comment by DocShotgun** [comment]
Would be interesting to try this - method used by the new superhot lora. 

There’s a few merged models now on HF but as far as I’ve seen there’s only transformers and GPTQ versions so far requiring the monkey patch the stretch the sinusoidal.

**Comment by LostRuins** [comment]
This has been added via `--ropeconfig` some time back
