### ISSUE TITLE
WizardCoder doesnt work

### ISSUE THREAD

**Issue by PedzacyKapec** [LostRuins/koboldcpp#258]
When I enter for instance:
"Write a code in python to read btc price" i get an error in the main console:

Processing Prompt [BLAS] (49 / 49 tokens)ggml_new_tensor_impl: not enough space in the context's memory pool (needed 1221854448, available 268435456)
exception: access violation writing 0x0000000000000000

My specs:
16Gb ram, CPU: I7 10700, Win10

Model:
WizardCoder-15B-1.0.ggmlv3.q4_0.bin

**Comment by richardr1126** [comment]
This is an out of RAM memory error for the context size. I had the same error running on my Mac with 16gb, the error didn't show when I just typed "Hello". WizardCoder uses around 11GB and your os (Windows) is probably taking up the rest of the memory, macOS probably uses less memory which is why I could send "Hello".

**Comment by TheMachineThinker** [comment]
I'm having the same issue on Linux with koboldcpp v1.32 and LLAMA_OPENBLAS=1.
`Processing Prompt [BLAS] (165 / 165 tokens)ggml_new_tensor_impl: not enough space in the context's memory pool (needed 1253214816, available 268435456)`
To fix this issue, I had to use the `--noblas` flag, which results in a similar prompt processing speed as koboldcpp v1.31.2, but generation speed is worse by about 127 ms/T (450ms vs 323ms). 
I was also able to prevent this error by modifying line 400 in `gpt2_v3.cpp` to increase the buffer size:
`static size_t buf_size = 1280u*1024*1024;` and recompiling, resulting in a slight improvement in processing speed (~15 ms/T) but generation speed is still the same as using the `--noblas` flag, which is again about 127 ms/T slower than v1.31.2.

**Comment by h3ndrik** [comment]
Also Segmentation fault and not enough memory with mpt 40b instruct. (linux, openblas)

**Comment by Wingie** [comment]
Processing Prompt [BLAS] (79 / 79 tokens)ggml_new_tensor_impl: not enough space in the context's memory pool (needed 1464812096, available 268435456) in m2 mac 64GB

**Comment by PedzacyKapec** [comment]
Guys.
It has absolutely nothing to do with memory. You can run the model in oobabooba app no problem.

**Comment by LostRuins** [comment]
I'm quite sure ooba does not have any support for non-llama ggml, unless something has changed very recently.

**Comment by LostRuins** [comment]
@TheMachineThinker yes, the old generation ms/T calculations were wrong, as it also counted tokens that were not generated. 

You can see from total time that it is about the same.

**Comment by h3ndrik** [comment]
MPT40b is working now. It dialed down the batch size from 512 to 256 on its own.
