### ISSUE TITLE
Several Characters or Words  at End of Output show up in the Terminal but not in the web UI?

### ISSUE THREAD

**Issue by CallMeAl1973** [LostRuins/koboldcpp#259]
Hi everyone,
When I compare the output I  see from koboldcpp in the console to the output that gets sent to the lite web UI, I notice that often, there is a bit of output in the console, always at the end of the generation,   that does not get sent to the web UI. This output usually consists of one to several words and I'm not exactly sure what the pattern is. I'd be happy to upload some examples if necessary but in my experience, this is very easy to reproduce. It happens with most, if not all of my generations.
Is this behavior intended? If so, does it have to do with the "trim sentences" setting?
Thanks,
--Al

**Comment by LostRuins** [comment]
You probably have the setting "Trim to Sentence" selected, which trims partially completed sentences.

Otherwise, you may be using chat mode, which automatically truncates replies.

**Comment by CallMeAl1973** [comment]
Okay that explains it. The "trim to sentence" setting is selected. But then when that setting is selected, are those trimmed words actually still in the context even though you don't see them in the web UI? If so, I assume they could skew subsequent outputs in a way you might not be expecting.

**Comment by LostRuins** [comment]
Nope, if the words are trimmed, they are removed from context. So they will be discarded before the next generation.

**Comment by CallMeAl1973** [comment]
Thanks. Makes sense!
