### ISSUE TITLE
stop-sequence token 'endoftext' is not removed from the output

### ISSUE THREAD

**Issue by MartinRJ** [LostRuins/koboldcpp#266]
# Expected Behavior

The stop-sequence token <|endoftext|> should be removed from the chat window.

# Current Behavior

The chat window displays <|endoftext|> (that stop-sequence will be generated when you call koboldcpp with the flag --unbantokens at the end of the response).

# Environment and Context

Version 1.32.3, koboldcpp.exe standalone version
![image](https://github.com/LostRuins/koboldcpp/assets/3988789/019590ea-338f-47f0-ad0c-c8e1a218f952)

**Comment by MartinRJ** [comment]
I found that enabling the options "Trim Sentences" and "Trim Whitespace" in Settings fixes this.

**Comment by LostRuins** [comment]
Closing this issue as resolved as a solution has been found, please reopen if problems persist.
