### ISSUE TITLE
llama.cpp's server example

### ISSUE THREAD

**Issue by akshitgaur2005** [LostRuins/koboldcpp#271]
Hi, is there any particular reason why llama.cpp's server example is not being utilised. Atleast for me, llama.cpp through server example gives me about 6 t/s but with koboldcpp it is at around 2 t/s.
This is with a 7b model, 15 layers offloaded to gtx 1650 and rest on cpu, ryzen 5 4600h on  a laptop with 8gb ram.

**Comment by LostRuins** [comment]
Perhaps your launch parameters are different, there shouldn't be much reason why the server has such a difference in performance. Are you using cublas or clblast?

**Comment by akshitgaur2005** [comment]
Llama.cpp - ngl-17, t-6, context length - 2048, generation speed- 4.37 t/s
koboldcpp - ngl - 17, t-6, context length - 2048, gen speed - 2.68 t/s, (using clblast)
koboldcpp - ngl - 24, t - 6, con length - 2048, gen speed -  3.2 t/s (using clblast)

**Comment by LostRuins** [comment]
koboldcpp uses `--gpulayers` not `-ngl` so do check if the offload is done correctly. Also make sure the clblast selects the correct GPU, if you have more than 1, it may select the integrated GPU by mistake (check names in console)

**Comment by LostRuins** [comment]
There are no plans to incorporate the llama.cpp http server into koboldcpp officially at this time.

**Comment by akshitgaur2005** [comment]
> koboldcpp uses `--gpulayers` not `-ngl` so do check if the offload is done correctly. Also make sure the clblast selects the correct GPU, if you have more than 1, it may select the integrated GPU by mistake (check names in console)

Yes, I am aware of that, --gpulayers was used for koboldcpp and I have verified that it is being loaded into the gtx 1650

**Comment by LostRuins** [comment]
hm interesting. personally I have not really noticed any speed decreases. Perhaps you can look into it, on why koboldcpp is slower for you compared to llamacpp.

**Comment by akshitgaur2005** [comment]
I have no idea where I would start, if you could provide a few pointers, that would really help
