### ISSUE TITLE
Smart Context broken since version 1.31

### ISSUE THREAD

**Issue by AllesMeins** [LostRuins/koboldcpp#273]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x ] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Current Behavior

The smart context function stopped working when I updated to version 1.31 and still isn't working in the latest version. Everytime I my chat or story gets longer I eventually reach a point where koboldcpp says "Processing Promt BLAS [512/1536]" (its always 1536) and after that with every new input it again starts with BLAS [512/1536]. Also if I start fresh with a very long text I also get a BLAS [512/1536] even though my context size is set to 2048.

With version 1.29 and before this didn't happen. Instead the context window initially started with a bigger size e.g [512/1872] and after that only every few prompts needed to read the whole context again. With the new version it is somehow stuck at those 1536.

**Comment by LostRuins** [comment]
Smartcontext has not been changed and is still working for me. Are you saying it doesn't trigger for you anymore? Or does it trigger but not reuse it?

**Comment by AllesMeins** [comment]
I think it does not trigger. I did two test runs - one with 1.29 and than with the same text with 1.32. Ive attached both logs. Notice how the 1.32 only processes 1536 tokens while the older one processes the whole text. It seems that the problem only occurs when I request a large number of tokens to be generated - when I tried to do a quick demo with only 20 tokens to generate it didn't happen and 1.32 ingested more than those 1536 tokens.

Also note that I aborted the answer generation because I didn't want to wait for it to generate the whole 512 tokens - so this is not the bug.

[output_129.txt](https://github.com/LostRuins/koboldcpp/files/11905029/output_129.txt)
[output_132.txt](https://github.com/LostRuins/koboldcpp/files/11905030/output_132.txt)
[saved_story_132.json.txt](https://github.com/LostRuins/koboldcpp/files/11905031/saved_story_132.json.txt)

**Comment by LostRuins** [comment]
Again, I've tried with the latest version and smartcontext is triggering fine. Please try this:

Launch the latest version, making sure `--smartcontext` is set. Launch the smallest model you have.

Load this json file, and import its settings. It uses 2048 ctx with 512 gen length, like you do.

[two_cities.zip](https://github.com/LostRuins/koboldcpp/files/11905133/two_cities.zip)

Try generating twice, and see if smartcontext triggers.

If it is **still** not working, please send me a json story file with this issue so I can take a better look.

**Comment by AllesMeins** [comment]
Hmm, it seems I was wrong in claiming the aborting the answer generation has nothing to do with it. I did several more tests. Your story works fine if I let it generate the whole 512 tokens, but the problem occurs after I added a stop-word like it is done when using chat-mode. For your story I added "King" as a manual stop-word and with that the smart context did not trigger. The same happens if I manually abort the generation midways. I've attched the log and the json-file:

[twoCities_with_stopword.zip](https://github.com/LostRuins/koboldcpp/files/11906200/twoCities_with_stopword.zip)
[output_twoCities_132_with_stopword.txt](https://github.com/LostRuins/koboldcpp/files/11906220/output_twoCities_132_with_stopword.txt)

I ran kobold-cpp with the following command: _koboldcpp.exe --useclblast 0 0 --gpulayers 8 --highpriority --launch --stream --contextsize 2048 --smartcontext_

**Comment by LostRuins** [comment]
Okay I tried again with stop tokens, and smart context is still working fine.

Something to check - are you using world info? Smart context does not work well with dynamic world info.

**Comment by Nabokov86** [comment]
I have the same problem https://github.com/LostRuins/koboldcpp/issues/269. Similar issue also occurs even without smart context. But it's very confusing, sometimes it works, sometimes it doesn't.

Here is an example of how to reproduce this:

1) I use this command to load the model >koboldcpp.exe --threads 4 --blasthreads 2 rwkv-169m-q4_1new.bin
2) The maximum number of tokens is 2024; the number to generate is 512.
3) Just generate 2-4 times.

For some reason it starts processing whole context again at 969 tokens, and after that it processes each generation again until it reaches 1536 tokens. 
![image](https://github.com/LostRuins/koboldcpp/assets/26260168/131b9a07-a765-42f9-ae68-8022484e46f1)
![image](https://github.com/LostRuins/koboldcpp/assets/26260168/a3c3e88a-82fe-42bb-866b-b5a0ac22ee78)
![image](https://github.com/LostRuins/koboldcpp/assets/26260168/864aa06f-05a5-4875-a00f-8a016ed9f915)
After that, each generation starts by processing 1536 tokens. The same thing happens when smartcontext is enabled.

**Comment by Nabokov86** [comment]
I thought it was because I was generating 512 tokens (2048-512=1536). But why it processes the whole context again even before 1536 tokens and why smartcontext doesn't work is very confusing.

**Comment by LostRuins** [comment]
RWKV does not work with smart context. Pick a different model.

**Comment by Nabokov86** [comment]
Now I can't reproduce it with lama models.

**Comment by LostRuins** [comment]
So I guess it is working, then.

**Comment by AllesMeins** [comment]
> Okay I tried again with stop tokens, and smart context is still working fine.

That is really strange...

> Something to check - are you using world info? Smart context does not work well with dynamic world info.

No, I did not use world info. Is there anything else I could do to help you figure this out? Maybe some kind of debug-mode/debug-build that could give you additional info why smart context is not triggering? Or any other way I could provide you with insights what is going on?

**Comment by LostRuins** [comment]
You can view all the tokens being generated, as well as the current context, by launching with the `--debug` flag.

**Comment by AllesMeins** [comment]
I did another run with the newest version 1.33 and --debug enabled. The problem still persist, as you can see in the attached output log. I did several prompts and SmartContext did not trigger as long as I had the stopword active. 

For the last two tries I removed the stopword, let it do a full generation of 512 tokens and after that SmartContext started working, even if I put the stopword back in.

[output_twoCities_debug_133.txt](https://github.com/LostRuins/koboldcpp/files/11940745/output_twoCities_debug_133.txt)
[twoCities_133.json.txt](https://github.com/LostRuins/koboldcpp/files/11940746/twoCities_133.json.txt)

**Comment by LostRuins** [comment]
I tried that prompt, but still could not repro the error. Does anyone else have the same issue?
