### ISSUE TITLE
new_token not found

### ISSUE THREAD

**Issue by GatorGamer** [LostRuins/koboldcpp#274]
![image](https://github.com/LostRuins/koboldcpp/assets/130500031/08893c11-254d-4f27-a80a-b5faba9a10b7)
the same thing happens to the rest of the handle thing
![image](https://github.com/LostRuins/koboldcpp/assets/130500031/8d1f5bc4-acaa-46b3-ac3b-46e3dc90bac5)
Im trying to run the koboldcpp.py in this project and I don't know how to compile any .lib files or what's going wrong

**Comment by LostRuins** [comment]
What platform are you on? Have you managed to build the project yet?

**Comment by GatorGamer** [comment]
If you mean my os im on windows and I built the project by running the pyinstaller bat file but nothing came out

**Comment by LostRuins** [comment]
Okay, just grab the latest exe build from here: https://github.com/LostRuins/koboldcpp/releases/latest 

and it should work.

**Comment by GatorGamer** [comment]
Well I know I can do that but I want to run it with python on my visual studio code. I think the problem is that I have an outdated dll but the repository doesn't have the kobolcpp.dll and the other ones

**Comment by GatorGamer** [comment]
Sorry im kind of dumb
how do I do that?
ive never really built a dll and im not sure if I can find the right youtube video

**Comment by LostRuins** [comment]
There's a readme in the repo you can refer to. Otherwise, if you just need to test, i'll zip up some of the latest dlls for you here.

[koboldcpp_v1.33.zip](https://github.com/LostRuins/koboldcpp/files/11907885/koboldcpp_v1.33.zip)

**Comment by GatorGamer** [comment]
Tysm
