### ISSUE TITLE
Can't build on mac after I pull the latest version(1.33)

### ISSUE THREAD

**Issue by crowcc** [LostRuins/koboldcpp#280]
The previous version could build successfully, but after I pulled the latest code(1.33), executing make would report an error.

<img width="824" alt="image" src="https://github.com/LostRuins/koboldcpp/assets/11046769/583b911c-30aa-417d-a736-edcfe57ed3d8">

**Comment by beebopkim** [comment]
In ```Makefile```, change CUBLAS_FLAGS to blank or comment out the line, your build will not fail.

https://github.com/LostRuins/koboldcpp/blob/1347d3acc08f802aa681f84ccc7bbfad5b138779/Makefile#L56 

I think the same problem will be happened for non NVIDIA GPU users like AMD, INTEL Arc or etc.

**Comment by beebopkim** [comment]
I just made a pull request for this problem - https://github.com/LostRuins/koboldcpp/pull/282

**Comment by crowcc** [comment]
> In `Makefile`, change CUBLAS_FLAGS to blank or comment out the line, then your build will(将) not fail.
> 
> https://github.com/LostRuins/koboldcpp/blob/1347d3acc08f802aa681f84ccc7bbfad5b138779/Makefile#L56
> 
> I think the same problem will(将) be happened for non NVIDIA GPU users like AMD, INTEL Arc or etc.

Thank you! That works.

**Comment by LostRuins** [comment]
Merged, please let me know if there are any further issues.
