### ISSUE TITLE
Access violation reading 0xFFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by LukasBrauschHFU** [LostRuins/koboldcpp#281]
After generating around 1600 Tokens, the generation fails with the error
 "Generating (1685 / 3000 tokens)exception: access violation reading 0xFFFFFFFFFFFFFFFF"
 This happened with multiple models (chronos-hermes-13b-superhot-8k.ggmlv3.q5_1, airoboros-13b-gpt4-1.4.ggmlv3.q5_0 and wizard-mega-13B.ggml.q5_1), both using OpenBLAS and CuBLAS.
My settings were:
![settings](https://github.com/LostRuins/koboldcpp/assets/48796514/c0c17c25-ffeb-42db-870d-1e72f7ebc878)

I have 32GB Ram and a 3070 with 8GB VRAM, running Windows 10

**Comment by LostRuins** [comment]
What are your launcher parameters? Did you launch with `--contextsize 8192` ?

**Comment by LukasBrauschHFU** [comment]
Oh, that cozld bve it.I launched it using the .exe directly. I will test using the command line tomorrow and report back

**Comment by LukasBrauschHFU** [comment]
Yes, it works if I start using commandline with the contextsize parameter. Thank you
