### ISSUE TITLE
The scratch buffer size

### ISSUE THREAD

**Issue by Vladonai** [LostRuins/koboldcpp#283]
koboldcpp.exe --usecublas normal --smartcontext --contextsize 8192 --blasbatchsize 512 --gpulayers 10 --usemirostat 2 5.0 0.1 --threads 10 --highpriority --stream --model gplatty-30b-superhot-8k.ggmlv3.q3_K_L.bin

ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3050
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 17714.58 MB (+ 3224.00 MB per state)
llama_model_load_internal: allocating batch_size x 1 MB = 512 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 10 repeating layers to GPU
llama_model_load_internal: offloaded 10/63 layers to GPU
llama_model_load_internal: total VRAM used: 3217 MB
llama_new_context_with_model: kv self size  = 12480.00 MB

--blasbatchsize 512 and 512 MB VRAM for the scratch buffer

koboldcpp.exe --usecublas normal --smartcontext --contextsize 8192 --blasbatchsize 1024 --gpulayers 10 --usemirostat 2 5.0 0.1 --threads 10 --highpriority --stream --model gplatty-30b-superhot-8k.ggmlv3.q3_K_L.bin

ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3050
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 17714.58 MB (+ 3224.00 MB per state)
llama_model_load_internal: allocating batch_size x 1 MB = 512 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 10 repeating layers to GPU
llama_model_load_internal: offloaded 10/63 layers to GPU
llama_model_load_internal: total VRAM used: 3217 MB
llama_new_context_with_model: kv self size  = 12480.00 MB

--blasbatchsize 1024 and 512 MB VRAM for the scratch buffer. Is that how it should be?

**Comment by LostRuins** [comment]
VRAM scratch buffer size currently assumes a fixed 512 blas batch size for the KV buffer. I am considering changing this but I'm not sure if it would be a good idea. Is it crashing for you?

**Comment by Vladonai** [comment]
No, everything works fast and frankly I don't notice any difference between blasbatchsize 512 and 1024 before or now. If increasing the buffer size will give some gain in speed, you can try to do it, but of course this is not a fact.
