### ISSUE TITLE
[Feature Request] Add support for 16K context

### ISSUE THREAD

**Issue by EliEron** [LostRuins/koboldcpp#287]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

With models like [LongChat](https://huggingface.co/lmsys/longchat-13b-16k) emerging that are designed for 16K contexts it would be nice if that was supported in Kobolcpp.

# Current Behavior

Currently the context maxes out at 8K

**Comment by LostRuins** [comment]
Will KIV, but increasing max ctx also requires increasing other stuff like the KV buffers and scratch buffers, which need to be done with trial and error.
