### ISSUE TITLE
How do i enable streaming in chat  mode (aesthetic chat ui)

### ISSUE THREAD

**Issue by x-legion** [LostRuins/koboldcpp#29]

**Comment by LostRuins** [comment]
put streaming in the url, e.g. http://localhost:5001?streaming=1 and it should work.

**Comment by henk717** [comment]
In addition it only shows streaming text when you are not using the Aestethic Text UI.

**Comment by faisalhr1997** [comment]
> In addition it only shows streaming text when you are not using the Aestethic Text UI.

exactly.

**Comment by faisalhr1997** [comment]
> put streaming in the url, e.g. http://localhost:5001?streaming=1 and it should work.
but it doesnt work on aesthetic chat ui

**Comment by LostRuins** [comment]
Yes, currently streaming does not work in the aesthetic chat UI... it may be added in future but is not a high priority for now.

**Comment by Enferlain** [comment]
@LostRuins By the way, I haven't checked since last time, but do you know if streaming is possible through sillytavern? I think oobabooga works with streaming, not sure about koboldcpp though.

**Comment by LostRuins** [comment]
It depends on how they implemented streaming. The Kobold API emulates it by breaking it up into small requests - this is not true streaming which is not implemented.

**Comment by LostRuins** [comment]
True streaming is now available in newest versions.
