### ISSUE TITLE
Koboldcpp doesn't free ram after offloading layers to GPU

### ISSUE THREAD

**Issue by goodglitch** [LostRuins/koboldcpp#290]
# Expected Behavior

When I offload model's layers to GPU it seems that koboldcpp just copies them to VRAM and doesn't free RAM as it is expected for new versions of the app. Behavior is consistent whether I use --usecublas or --useclblast. I also tried with different model sizes, still the same. I have rtx 3090 and offload all layers of 13b model into VRAM with 

koboldcpp.exe --model C:\AI\llama\Wizard-Vicuna-13B-Uncensored.ggmlv3.q5_K_M.bin --threads 14 --usecublas --gpulayers 100
But after that I also see that ram usage go up by almost the same amount as VRAM.

* Physical (or virtual) hardware you are using, e.g. for Linux:

Ryzen 5950x
Palit GamingPro rtx 3090
RAM: 32Gb

Loading model: C:\AI\llama\Wizard-Vicuna-13B-Uncensored.ggmlv3.q5_K_M.bin
[Threads: 14, BlasThreads: 14, SmartContext: False]

---
Identified as LLAMA model: (ver 5)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from C:\AI\llama\Wizard-Vicuna-13B-Uncensored.ggmlv3.q5_K_M.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 17 (mostly Q5_K - Medium)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 2155.52 MB (+ 1608.00 MB per state)
llama_model_load_internal: allocating batch_size x 1 MB = 512 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 40 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 43/43 layers to GPU
llama_model_load_internal: total VRAM used: 10794 MB
llama_new_context_with_model: kv self size  = 1600.00 MB
Load Model OK: True
Embedded Kobold Lite loaded.
Starting Kobold HTTP Server on port 5001
Please connect to custom endpoint at http://localhost:5001

![image](https://github.com/LostRuins/koboldcpp/assets/49197548/ea8e04a7-e407-4f6c-b6da-b1e4cc3835d0)
![image](https://github.com/LostRuins/koboldcpp/assets/49197548/2242f126-3d3f-4151-ac57-d6f7e5386037)

**Comment by goodglitch** [comment]
The issue is especially pressing for me, since offloading some layers to GPU is the only way I can run 60B model with 32Gb of RAM.

**Comment by LostRuins** [comment]
If you want KoboldCPP to free RAM after offloading to GPU, then you cannot use mmap. To do this, launch with the `--nommap` parameter.

**Comment by goodglitch** [comment]
> If you want KoboldCPP to free RAM after offloading to GPU, then you cannot use mmap. To do this, launch with the `--nommap` parameter.

It seems to have no effect for ggmlv3. Am I right that it works not for all models. If yes, can you please tell for which model formats it will work.

**Comment by LostRuins** [comment]
It should work for all llama models in the newest format

**Comment by goodglitch** [comment]
> It should work for all llama models in the newest format

Very strange. I have tried offloading with llamacpp the same behavior. Can you please post verified command line, for which you are certain it works, may be I am doing something wrong.

**Comment by LostRuins** [comment]
`--useclblast 1 0 --gpulayers 30 --nommap`

**Comment by goodglitch** [comment]
> `--useclblast 1 0 --gpulayers 30 --nommap`

I can confirm it frees RAM with layers offloading to GPU when you use --useclblast and doesn't work with --usecublas. 

Unfortunately, for me it is not an option as speed with --useclblast is even lower than CPU only option. It is so slow that TavernAI throws a connection error, since it thinks that server went offline((

**Comment by DocShotgun** [comment]
> I confirm it frees RAM with layers offloading to GPU when you use --useclblast and doesn't work with --usecublas. It is slightly slower than cuda realization, but it is perfectly workable. Thanks for help!

Hmm this seems to line up with my experience of cublas offloading using significantly more CPU ram than the same model+gpulayers in clblast, if somehow the "offloaded" layers are still duplicated in CPU ram.

**Comment by LostRuins** [comment]
Perhaps there's something different about the way cuda handles data. Unfortunately I don't really have the resources to look into it, but if someone figures out a fix, do share it here.
