### ISSUE TITLE
[Enhancement] UI support for CFG scaling/negative prompts.

### ISSUE THREAD

**Issue by AlphaAtlas** [LostRuins/koboldcpp#292]
CFG scaling is being looking into in llama.cpp. The jist of the issue is better explained here, and in the original paper: https://github.com/ggerganov/llama.cpp/issues/2083#issuecomment-1619160151

For instruct models, sounds like Koboldcpp's "Memory" window would need changing. Maybe special syntax could be added for the negative prompt replacement, or maybe a second window for the negative prompt could be added?

This isn't even implemented in transformers/llama.cpp yet, and maybe its actually an upstream Kobold issue, bit I figure its best to bring attention to the feature sooner rather than later.

**Comment by AlphaAtlas** [comment]
Support was just merged upstream:

https://github.com/ggerganov/llama.cpp/commit/c9c74b4e3f9dcfab8b0032749ff8a579ab4e4d8d

**Comment by LostRuins** [comment]
Maintaining a separate context is actually a non trivial thing for koboldcpp, due to the way it handles context-fast forwarding. It would have impacts beyond just the UI, requiring the program to maintain and upkeep a second context in memory to provide the guidance. At the moment I am not sure what the best approach would be, or if it's within scope for kobldcpp.

**Comment by henk717** [comment]
On fast implementations like cuBlas context processing is very fast, so perhaps we can make this optional and disable forwarding if its used?

**Comment by AlphaAtlas** [comment]
Could the negative context be accessed as a diff or modification of the original context? In the paper, instruct negative conexts were very similar to the original prompt.

**Comment by LostRuins** [comment]
Planned yes, but not prioritized. Lots of bugs need fixing first.

**Comment by LostRuins** [comment]
I did a few experiments with Classifier Free Guidance and it was super underwhelming, with poor coherency in addition to double context and double evaluation required. I don't think I'll be adding it anytime soon

**Comment by Reithan** [comment]
Is this still backburnered? Was reading through this feature in other places and seemed like it was worth trying out.
With the last update to this thread nearly 1y/o now, has anything changed?

**Comment by LostRuins** [comment]
Sorry, still no plans for CFG at the moment.
