### ISSUE TITLE
New to Koboldcpp, Models won't load. Please Help

### ISSUE THREAD

**Issue by nmieao** [LostRuins/koboldcpp#297]
Hello, I downloaded the koboldcpp exe file an hour ago and have been trying to load a model but it just doesn't work.
I created a folder specific for koboldcpp and put my model in the same folder. I tried to use a ggml version of pygmalion 7b (here's the link: https://huggingface.co/waifu-workshop/pygmalion-7b-ggml-q5_1/discussions), I also tried other ggml models but none work .
Here's what cmd tells me when i try to load a model:
<img width="861" alt="Screenshot 2023-07-07 033726" src="https://github.com/LostRuins/koboldcpp/assets/120758876/de01310e-12f5-49fe-8913-416b1a7110a5">

**Comment by LostRuins** [comment]
Seems like that model is defective, as it got detected as a version 0 model. Try one of these instead: https://huggingface.co/Yoshiii/pygmalion-7b-ggml/tree/main

**Comment by nmieao** [comment]
> Seems like that model is defective, as it got detected as a version 0 model. Try one of these instead: https://huggingface.co/Yoshiii/pygmalion-7b-ggml/tree/main

It does not work too, it gives me the same message in the cmd window

**Comment by LostRuins** [comment]
No worries. Also remember to set the current path to the model when loading the .bin file, it should be selecting the file, not the folder name!

**Comment by Sazu-bit** [comment]
Turned out the model I thought I downloaded had in fact failed as a 0byte... came to this issue wondering why my model wasn't loading! Worth checking if the file has in fact downloaded properly.

**Comment by foychermin** [comment]
so im having this exact same issue, im very new to this, started about two weeks ago and im not even sure im downloading the right folders, i see most models will have a list of sizes saying recommend don't recommend but im not sure if i need the little red download box one or the down arrow box one. ive been using stable diffusion and have safetensors but im not sure how to see if they are supported by kobold, when they failed i tried regular gguf and still the same results. im on windows 10, 64gb ram, 4070 super 16gb, 9 7950x3d. it loads great with just the gguf model for chats but i figured id try the image gen out, better than using a local sd web-ui instance. its a great program so far and ive always wanted to run a zorg style adventure with pictures from time to time, just wish there was a more relatable guide for this.

**Comment by LostRuins** [comment]
Here's a good model to try: https://huggingface.co/admruul/anything-v3.0/resolve/main/Anything-V3.0-pruned-fp16.safetensors 

Make sure you select it in the "Image Model" selection! 

![image](https://github.com/user-attachments/assets/6029d1e3-0790-45c0-987b-d6a7555be424)
