### ISSUE TITLE
vLLM implementation [NEW FEATURE]

### ISSUE THREAD

**Issue by PedzacyKapec** [LostRuins/koboldcpp#300]
Hi

Would love to see vLLM in the future release.
More here:
https://github.com/vllm-project/vllm

Thanks !

**Comment by AlphaAtlas** [comment]
You mean PagedAttention and batching?

I think this is an issue for upstream llama.cpp

**Comment by LostRuins** [comment]
Agreed with AlphaAtlas. Seems out of scope for koboldcpp
