### ISSUE TITLE
http://localhost:5001 is not loading

### ISSUE THREAD

**Issue by FrankDMartinez** [LostRuins/koboldcpp#301]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

I expect localhost:5001 to load and not timeout.

# Current Behavior

When I try to open localhost:5001, I receive "This site can’t be reached; localhost took too long to respond."

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

~~`$ lscpu`~~ From `/usr/sbin/sysctl -a` => Excluded because it resulted in a comment too long to be accepted by GitHub and I don't know what from it you require.

* Operating System, e.g. for Linux:

`$ uname -a` => Darwin MacBook-Pro-2.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

* SDK version, e.g. for Linux:

```
$ python3 --version => Python 3.10.9
$ make --version => GNU Make 3.81
$ g++ --version => Apple clang version 14.0.3 (clang-1403.0.22.14.1)
```

# Failure Information (for bugs)

http://localhost:5001 is not loading, despite the message "Please connect to custom endpoint at http://localhost:5001"

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Build;
2. Run `koboldcpp.py`;
3. Choose model;
4. Navigate to the specified URL ... or, at least, try;

# Failure Logs

```
llama.cpp$ git log | head -1
commit ddaa4f2a264820b4379baeba0318c5e89951e1a5

md5sum ../llama.cpp/chronos-hermes-13b.ggmlv3.q4_0.bin
cb1b8054ddb5c3db089d79429d3f4a57  ../llama.cpp/chronos-hermes-13b.ggmlv3.q4_0.bin
```

Command-line output
```
⋊> ~/L/M/c/o/koboldcpp on concedo ◦ ./koboldcpp.py chronos-hermes-13b.ggmlv3.q4_0.bin                                                                                                                                          (base) 20:43:10
***
Welcome to KoboldCpp - Version 1.34.2
Warning: OpenBLAS library file not found. Non-BLAS library will be used.
Initializing dynamic library: koboldcpp.so
==========
Namespace(model=None, model_param='chronos-hermes-13b.ggmlv3.q4_0.bin', port=5001, port_param=5001, host='', launch=False, lora=None, threads=3, blasthreads=3, psutil_set_threads=False, highpriority=False, contextsize=2048, blasbatchsize=512, stream=False, smartcontext=False, unbantokens=False, bantokens=None, usemirostat=None, forceversion=0, nommap=False, usemlock=False, noavx2=False, debugmode=0, skiplauncher=False, hordeconfig=None, noblas=False, useclblast=None, usecublas=None, gpulayers=0)
==========
Loading model: ./chronos-hermes-13b.ggmlv3.q4_0.bin
[Threads: 3, BlasThreads: 3, SmartContext: False]

---
Identified as LLAMA model: (ver 5)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from ./chronos-hermes-13b.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: mem required  = 9031.71 MB (+ 1608.00 MB per state)
llama_new_context_with_model: kv self size  = 1600.00 MB
Load Model OK: True
Embedded Kobold Lite loaded.
Starting Kobold HTTP Server on port 5001
Please connect to custom endpoint at http://localhost:5001
```

**Comment by Ar57m** [comment]
Did you try it in another browser?

**Comment by FrankDMartinez** [comment]
Yes, same result. "http://localhost" is fine with an "It's works" but not when I specify the port.

**Comment by FrankDMartinez** [comment]
@Ar57m Curiously, if I run `python3 -m http.server 5001`, I can get a directory listing on `localhost:5001`. So, I'm even less sure where the issue resides.

**Comment by LostRuins** [comment]
Sounds like you might have something blocking or using that port, or some sort of firewall restrictions. Can you see if a different port works?  E.g. `--port 5002`

**Comment by FrankDMartinez** [comment]
@LostRuins That was my first thought, 5002 and 4999 don't work either. So, I ran `nc -vnzu 127.0.0.1 1-65535` and each of the ports had a result of the form "Connection to 127.0.0.1 port PORT_NUMBER_GOES_HERE [udp/*] succeeded!".

**Comment by FrankDMartinez** [comment]
When I leave off the `u` option to test with TCP instead of UDP, every port results in a "Connection refused" response except the following:

```
Connection to 127.0.0.1 port 80 [tcp/*] succeeded!
Connection to 127.0.0.1 port 3306 [tcp/*] succeeded!
nc: connectx to 127.0.0.1 port 4999 (tcp) failed: Operation timed out
Connection to 127.0.0.1 port 5000 [tcp/*] succeeded!
Connection to 127.0.0.1 port 7000 [tcp/*] succeeded!
Connection to 127.0.0.1 port 33060 [tcp/*] succeeded!
Connection to 127.0.0.1 port 49377 [tcp/*] succeeded!
nc: connectx to 127.0.0.1 port 62357 (tcp) failed: Operation timed out
```

For the record, my MacOS firewall is off.

**Comment by LostRuins** [comment]
@FrankDMartinez yes it is a regular HTTP tcp connection. Maybe try binding to a specific interface.

`--port 5002 --host 127.0.0.1` and then connect to http://127.0.0.1:5002

**Comment by FrankDMartinez** [comment]
That was it! Thanks!
