### ISSUE TITLE
UI limits context size to 2048 tokens

### ISSUE THREAD

**Issue by Angela-BC** [LostRuins/koboldcpp#303]
When started with the --contextsize 8192 the model is loaded with the 8192 context size. The UI however still limits the context at 2048. 

![image](https://github.com/LostRuins/koboldcpp/assets/77929808/13701232-91ab-4bb3-b518-7038f252b34b)

Running koboldcpp.exe on Windows 11

**Comment by LostRuins** [comment]
You can manually increase the context by clicking on the number. It is an editable text box.

**Comment by Angela-BC** [comment]
oh, I never noticed. Thank you.

**Comment by Fr0d0Beutl1n** [comment]
I wouldn't consider this *resolved*, as it is not intuitive. Most users will not know that the box is editable.
