### ISSUE TITLE
[Feature Request/UX] Save last-used settings in the new UI.

### ISSUE THREAD

**Issue by digiwombat** [LostRuins/koboldcpp#304]
Currently, when double click the .exe, you have to re-apply all the settings and re-select the model.

It would be ideal if the last-used settings could be automatically loaded to help speed up launching the program in the case of a crash or just wanting to do a model swap.

**Comment by VL4DST3R** [comment]
I believe the intended way to do this is with a bat script where you can store your desired settings for future runs. Here is an example of what i currently have:

```
title koboldcpp
:start
koboldcpp ^
--model llama-65b.ggmlv3.q5_1.bin ^
--usecublas normal ^
--gpulayers 12 ^
--threads 11 ^
--smartcontext ^
--usemirostat 2 0.1 0.1 ^
--stream
pause
goto start
```

Adapt `gpulayers`, `threads` and `model` for your specs/needs

**Comment by digiwombat** [comment]
That is currently what I do. Since the UI is presumably to help less-technically minded users, I'd think batch files are probably not the intended concept for those users in particular.

If the UI simply saves my last-used settings, then instead of editing a .bat file (assuming they know what one is) they click Browse, maybe slide a slider, change a number in a text box. It's much more friendly to non-technical end-users and is going to be more akin to the workflows they're familiar with.

It's not a huge deal for me one way or another, but it is a UX nice-to-have that will help people who aren't necessarily remembering the settings for every model and size since they can see what they loaded last and adjust from there if there's an issue.

Alternatively, the UI could save settings per model, but that might be too much.

**Comment by VL4DST3R** [comment]
I agree, don't get me wrong, I'd like to do all this like civilized people using the UI as well :P I was just offering a solution in case you weren't aware. Also don't mean to be presumptuous but i don't imagine average users to be interested in LLMs to this degree while not being at least somewhat technically inclined.

While we're at it I would also like the UI to save story setups as a whole, so i don't have to import/export .json files if i want to change what story I'm working on, similar to how chatgpt does it with its sidebar.

**Comment by LostRuins** [comment]
Yeah if dev time permits, one thing i might add is just an autosave for last used settings, with an option reset to default. but been kinda busy lately.

**Comment by LostRuins** [comment]
Will be included in next version.

**Comment by LostRuins** [comment]
This is now implemented in 1.35

**Comment by digiwombat** [comment]
You're a hero. A handsome, talented hero.

Working as expected. Thanks for the hard work.

**Comment by Matthew-X** [comment]
Hey, was it implemented? Or is it yet to be? I see that you can save and load but you have to load it every time you open the program and you have to save every time you change something. Wasn't it supposed to be automatic?

**Comment by weakset** [comment]
> Hey, was it implemented? Or is it yet to be? I see that you can save and load but you have to load it every time you open the program and you have to save every time you change something. Wasn't it supposed to be automatic?

You can drag&drop saved KCPP-file to the exe and it will lauch with those settings.

**Comment by BenMcD0nald** [comment]
Hey, so I was just looking at this myself and this seems to work. Basically create a .bat file with the following...

"<path>\KoboldCpp.exe" --config "<path>\Settings.kcpps"

Only thing is it launches directly rather than to the options screen, so you cant really load default settings and then change the model dynamically. You have to save the model in with the settings (though I guess you can create a new .bat for each model you might want to use

**Comment by VL4DST3R** [comment]
> you cant really load default settings and then change the model dynamically.

You can if you use `--admin` mode combined with profiles for each model you intend to use/swap between. Also while indeed annoying, having a "default" set of settings doesn't really work given how models differ in size and the various optional mmproj extensions some support.

What I personally use in an attempt to achieve this is a bat file where I store and generate every individual `.kcpps` file I then use via a headless (`--nomodel`) kcpp instance. Having every set of model options effectively in one place allows me to streamline some of the boilerplate arguments I use across the board, while also allowing me to define things specific to a particular model, without having to deal with the slow gui or modifying every individual config file after the fact.

**Comment by LostRuins** [comment]
@BenMcD0nald you can also use the --showgui flag
