### ISSUE TITLE
Bad results when using cublas 

### ISSUE THREAD

**Issue by VL4DST3R** [LostRuins/koboldcpp#306]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

`cublas` work the same as `clblast` (in terms of results)

# Current Behavior

Reading the changelog for the latest version i noticed the addition of alternative blas versions, and since i have an Nvidia gpu i figured i should switch to Cuda: replaced `--useclblast 0 0` with `--usecublas normal` and gave it a spin, but the results are horrible. The text begins reasonably well, but after a few words it exponentially becomes more disjointed, dropping any kind of grammar or punctuation, eventually getting stuck repeating one or a few words over and over until stopped. Am i missing something?

# Environment and Context

W10 on a Ryzen 9 5900X (12c/24t) 64 gb of ram and an RTX 3070 (8gb vram).

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

# Steps to Reproduce

No matter the input, model or settings from the UI, it seems to act in the same manner. Example:

`Her feet involuntarily halted midstep instinctively refusing entry into unknown territory fraugeign territory unknown territory foreign territory foreign territory foreign territory foreign territory foreign territory foreign territory foreign territory foreign territory foreign`

**Comment by VL4DST3R** [comment]
AAAND i missed the fact that a hotfix was released since it had the exact same size and i figured i already had it. It works properly on 1.32.**2** Closing.

**Comment by LostRuins** [comment]
you mean 1.34.2 right? that's the newest.

**Comment by VL4DST3R** [comment]
Yep, sorry, meant to say 1.34.2.

**Comment by 7erminalVelociraptor** [comment]
I was wondering if I was imagining things. My results werent as bad as OP's but somehow previously high quality models suddenly became more repetitive for a few days.

**Comment by LostRuins** [comment]
@7erminalVelociraptor make sure you're not using a poor sampler order, since that was implemented recently. You're recommended to reset to the "Default" sampler order as displayed in Lite.

**Comment by VL4DST3R** [comment]
> @7erminalVelociraptor make sure you're not using a poor sampler order

What constitutes a bad sampler order? From what i understand (at least for the lite ui) those are controlled by the presets and not directly by the user. [Reading ](https://www.reddit.com/r/KoboldAI/comments/vcgsu1/1181_has_been_released_featuring_more_sampling/)stuff on it is confusing at best.

**Comment by LostRuins** [comment]
Yeah unfortunately, some of the sampler orders were carried over from the past, where they were not well understood.

Generally, you always wan Rep Pen first and Temperature last.

**Comment by VL4DST3R** [comment]
Provided as command-line arguments when starting the UI? or how exactly would one set those? I can't seem to find a way for lite ui
