### ISSUE TITLE
Performance drop in the latest version.

### ISSUE THREAD

**Issue by Nabokov86** [LostRuins/koboldcpp#307]
In the latest release, I noticed some performance degradation. I tested it several times, the difference is about 5, 6 percent.

**koboldcpp32_3.exe**  --threads 4 --useclblast 0 0 --blasthreads 2 --stream --highpriority WizardLM-13B-1.0.ggmlv3.q4_K_M.bin
Processing Prompt [BLAS] (179 / 179 tokens)
Generating (160 / 160 tokens)
Time Taken - Processing:33.8s (189ms/T), Generation:46.4s (290ms/T), **Total:80.2s (2.0T/s)**

**koboldcpp34.exe**  --threads 4 --useclblast 0 0 --blasthreads 2 --stream --highpriority WizardLM-13B-1.0.ggmlv3.q4_K_M.bin
Processing Prompt [BLAS] (179 / 179 tokens)
Generating (160 / 160 tokens)
Time Taken - Processing:34.8s (194ms/T), Generation:49.9s (312ms/T), **Total:84.7s (1.9T/s)**

I noticed this because I use high priority, and before during text generation the cursor and windows was laggy and not responsive. But it's much smoother on the latest version. It feels like it's no longer using all possible cpu resources.

**Comment by Nabokov86** [comment]
The priority is set correctly.
![image](https://github.com/LostRuins/koboldcpp/assets/26260168/c9d10f44-3511-4460-bf05-f9963b5e2640)

**Comment by Nabokov86** [comment]
The CPU utilization graphs are a bit different for kernel times usage.
![Annotation 2023-07-09 193054_test](https://github.com/LostRuins/koboldcpp/assets/26260168/01c858b5-7e11-4026-9bc4-1addea217ec5)

**Comment by LostRuins** [comment]
Hmm... Have not made an explicit changes to CL, but it's possible some changes were added to the library from upstream. All flags should be working same as before.

**Comment by Nabokov86** [comment]
Same model, same number of tokens
![image](https://github.com/LostRuins/koboldcpp/assets/26260168/04162a82-298e-4977-8c76-84eca96b31ab)

**Comment by LostRuins** [comment]
I have compared both versions you mentioned on a variety of models, and I do not observe any measurable difference on my device. Does anyone else experience this performance drop? If so, please provide some details to help troubleshoot.

Processing Prompt [BLAS] (272 / 272 tokens)
Generating (32 / 32 tokens)

Old:
Time Taken - Processing:4.9s (18ms/T), Generation:3.3s (103ms/T), Total:8.2s (3.9T/s)

New:
Time Taken - Processing:4.9s (18ms/T), Generation:3.0s (95ms/T), Total:7.9s (4.1T/s)

**Comment by Nabokov86** [comment]
On my system, I don't even have to look at the generation time. The difference is very noticeable. While using the new version with high priority the system is much more responsive and allows multitasking.


Some additional information.

1. I discovered that the **performance degradation started with version 1.33**. I highly confident that the issue is related to some changes between 1.32.3 and 1.33

2. During generation the new version uses about 5% less CPU resources. Which explains why generation also takes about 5% longer. The interesting thing is the "system idle process" takes some CPU, which means that **the system has free CPU resource that is not being utilized in any way despite the high priority.**

Which could mean that the performance in the new version is limited not by CPU but by something else, because the process is clearly not using all available cpu resource.
![1 32 3](https://github.com/LostRuins/koboldcpp/assets/26260168/abd3e531-81e1-4491-b1a0-61b351a450cb)![1 33](https://github.com/LostRuins/koboldcpp/assets/26260168/d97ce39e-2e7e-438c-9564-ac7043c31488)![llama](https://github.com/LostRuins/koboldcpp/assets/26260168/30542dfe-4968-467a-9029-2f3499b28966)

**Comment by Polosat1y** [comment]
For me in version 1.33 the generation is faster on the contrary.

--thread 12 --blasthreads 8 --useclblas 0 0 --smartcontext --highpriority

Processing Prompt [BLAS] (499 / 499 tokens)
Generating (150 / 150 tokens)

30B WizardLM-Uncensored-SuperCOT-Storytelling.ggmlv3.q5_K_S.bin
1.31.2:
Time Taken - Processing:79.6s (159ms/T), Generation:68.2s (454ms/T), Total:147.7s (1.0T/s)
1.32.3:
Time Taken - Processing:80.2s (161ms/T), Generation:68.1s (454ms/T), Total:148.2s (1.0T/s)
1.33:
Time Taken - Processing:78.7s (158ms/T), Generation:64.5s (430ms/T), Total:143.2s (1.0T/s)
1.34:
Time Taken - Processing:78.1s (157ms/T), Generation:64.6s (431ms/T), Total:142.7s (1.1T/s)

koala-13B.ggmlv3.q4_0.bin
1.31.2:
Time Taken - Processing:31.8s (64ms/T), Generation:25.8s (172ms/T), Total:57.7s (2.6T/s)
1.32.3:
Time Taken - Processing:32.2s (64ms/T), Generation:26.1s (174ms/T), Total:58.3s (2.6T/s)
1.33:
Time Taken - Processing:31.6s (63ms/T), Generation:24.1s (161ms/T), Total:55.8s (2.7T/s)
1.34:
Time Taken - Processing:31.3s (63ms/T), Generation:23.9s (159ms/T), Total:55.3s (2.7T/s)

**Comment by LostRuins** [comment]
@Polosat1y you seem to be comparing a 30B model to a 13B model heh.

**Comment by Polosat1y** [comment]
@LostRuins I compared 30b and 13b in the last 4 versions of koboldcpp. Each one separately. Please look a little more closely at my post. :)
In both cases 1.33 and 1.34 turns out to be slightly faster.

**Comment by LostRuins** [comment]
Whoops, I misread it haha.

**Comment by LostRuins** [comment]
Hi @Nabokov86 , 1.35 was just released, with some speedups for CUDA. Do give it a try.

**Comment by Nabokov86** [comment]
To avoid confusion, I don't use CUDA. So I can't say anything about CUDA acceleration.
But the latest update fixed the generation speed for me. It's now the same as it was on version 1.32.3 🎉

**Unfortunately, in the new version I noticed quite a significant regression of prompt processing speed using OpenCL**. Please take a look:

KoboldCpp - Version 1.32.3
Time Taken - Processing:**33.7s (188ms/T)**, Generation:45.0s (281ms/T), Total:78.7s (2.0T/s)

KoboldCpp - Version 1.34.2
Time Taken - Processing:**34.2s (191ms/T)**, Generation:49.4s (309ms/T), Total:83.6s (1.9T/s)

KoboldCpp - Version 1.35
Time Taken - Processing:**39.8s (222ms/T)**, Generation:45.6s (285ms/T), Total:85.3s (1.9T/s)

| 1.32.3 | 188ms/T | 5.31 tokens per second |
|---|---|---|
| 1.34.2 | 191ms/T | 5.23 tokens per second |
| 1.35 | 222ms/T | 4.50 tokens per second |

**Comment by LostRuins** [comment]
I tested on the listed versions again and found no significant difference between any of them on CLBlast. This makes sense because there were no significant CLBlast changes recently either. Perhaps your testing approach may need to account for other factors - such as CPU load from other programs, model selection and format, and prompt length. I'd recommend running the tests multiple times to get a more accurate average, as there can be fluctuations from run to run.

**Comment by Nabokov86** [comment]
@LostRuins Yeah, I ran the test a few times of course. Same settings, same process priority, same model, no active background processes.

KoboldCpp - Version 1.35
Processing Prompt [BLAS] (179 / 179 tokens)
Generating (160 / 160 tokens)
Time Taken - Processing:39.8s (222ms/T), Generation:45.6s (285ms/T), Total:85.3s (1.9T/s)
Time Taken - Processing:38.9s (217ms/T), Generation:10.0s (278ms/T), Total:48.9s (0.7T/s)
Time Taken - Processing:39.8s (222ms/T), Generation:45.6s (285ms/T), Total:85.4s (1.9T/s)

KoboldCpp - Version 1.34.2
Processing Prompt [BLAS] (179 / 179 tokens)
Generating (1 / 1 tokens)
Time Taken - Processing:33.9s (189ms/T), Generation:48.1s (301ms/T), Total:82.0s (2.0T/s)
Time Taken - Processing:34.2s (191ms/T), Generation:47.0s (294ms/T), Total:81.2s (2.0T/s)
Time Taken - Processing:34.2s (191ms/T), Generation:0.0s (5ms/T), Total:34.2s (0.0T/s)

Just ran the test again to be sure, unfortunately the result is the same as it was a couple hours ago.

KoboldCpp - Version 1.32.3
Processing Prompt [BLAS] (179 / 179 tokens)
Generating (1 / 1 tokens)
Time Taken - Processing:34.1s (191ms/T), Generation:0.0s (5ms/T), Total:34.1s (0.0T/s)

KoboldCpp - Version 1.35
Processing Prompt [BLAS] (179 / 179 tokens)
Generating (1 / 1 tokens)
Time Taken - Processing:40.4s (226ms/T), Generation:0.0s (30ms/T), Total:40.4s (0.0T/s)

**Comment by Nabokov86** [comment]
Same thing with the generation speed. I've done literally dozens of tests just to be sure before reporting.

I'm using this command:
koboldcpp_35.exe  --threads 4 --useclblast 0 0 --stream --blasthreads 2 --highpriority WizardLM-13B-1.0.ggmlv3.q4_K_M.bin

Let me check with other models just in case.

**Comment by Nabokov86** [comment]
Nope, same thing sadly.

koboldcpp_35.exe  --threads 4 --useclblast 0 0 --stream --blasthreads 2 --highpriority airoboros-7b-gpt4-1.4.ggmlv3.q4_K_S.bin
Processing Prompt [BLAS] (179 / 179 tokens)
Generating (160 / 160 tokens)
Time Taken - Processing:18.7s (105ms/T), Generation:23.6s (148ms/T), Total:42.3s (3.8T/s)
Time Taken - Processing:18.7s (104ms/T), Generation:23.6s (147ms/T), Total:42.3s (3.8T/s)

koboldcpp_32.exe --threads 4 --useclblast 0 0 --stream --blasthreads 2 --highpriority airoboros-7b-gpt4-1.4.ggmlv3.q4_K_S.bin
Processing Prompt [BLAS] (179 / 179 tokens)
Generating (160 / 160 tokens)
Time Taken - Processing:15.0s (84ms/T), Generation:24.4s (153ms/T), Total:39.4s (4.1T/s)
Time Taken - Processing:15.0s (84ms/T), Generation:24.4s (153ms/T), Total:39.5s (4.1T/s)

**Comment by BeHappy2021** [comment]
I'm finding similar to above. Performance from 1.35 is noticeably slower compared to 1.32 which seems to have had the best performance so far. I'm using Debian Linux and the nous-hermes-13b.ggmlv3.q4_K_S.bin model. On the system I'm running I've noticed that with 1.35 the RAM usage is significantly higher even though I'm using all the same options. With 1.34 I see RAM usage at about 7Gb but with 1.35 it is about 12Gb. This is including the same other stuff running in the background.

**Comment by LostRuins** [comment]
Yes that is a known issue. Seems like some thread sync stuff does not have uniform performance on all devices

**Comment by Polosat1y** [comment]
> Unfortunately, in the new version I noticed quite a significant regression of prompt processing speed using OpenCL

I'm confirming. In version 1.35 the processing time using clblas has deteriorated. I repeated the tests several times, the result is the same.

koala-13B.ggmlv3.q4_0.bin
--thread 12 --blasthreads 8 --useclblas 0 0 --smartcontext --highpriority

Processing Prompt [BLAS] (499 / 499 tokens)
Generating (150 / 150 tokens)

**1.34.2**
Time Taken - Processing:31.8s (64ms/T), Generation:23.9s (160ms/T), Total:55.7s (2.7T/s)
**1.35**
Time Taken - Processing:39.8s (80ms/T), Generation:23.9s (159ms/T), Total:63.7s (2.4T/s)

**Comment by Ar57m** [comment]
I've noticed this on my 6gb ram android phone too(no blas, only cpu), in the version 1.34.2 I was able to run Pygmalion-7b-q4_K_M, Pygmalion-7b-q3_K_M and airoboros-7b-gpt4-1.4.ggmlv3.q2_K. But now on 1.35 I can't, it crashes in the loading due to ram usage.

**Comment by Enferlain** [comment]
I'm on 1.3.5 and the speed is noticeably slower, but I don't remember if I was on 1.3.5 last time so I can't say if that's the issue. But I didn't do anything on my end. Guess I'll try a previous version

.\koboldcpp.exe --useclblast 0 0 --smartcontext --threads 16 --blasbatchsize 1024 --blasthreads 24 --stream --gpulayers 43 --contextsize 4096

**Comment by LostRuins** [comment]
1.35 has a known issue with sched_yield that may be the cause of this regression - it will be reverted in 1.36

**Comment by LostRuins** [comment]
Hi, 1.36 is out which should have hopefully fixed this issue. Please let me know.

**Comment by Nabokov86** [comment]
@LostRuins Processing speed is fixed in 1.36 for me. But now koboldcpp does not utilize all CPU resources again.
![35](https://github.com/LostRuins/koboldcpp/assets/26260168/cc02cbd9-0f25-494e-bb35-24fa381b608d) ![36](https://github.com/LostRuins/koboldcpp/assets/26260168/2fe72eda-b40a-4e98-865a-bf81f382b114)

**Comment by Nabokov86** [comment]
In the screenshots below, I've recorded the average CPU utilization during generation. I also used windows exlporer a bit just to show how CPU usage drops during generation while using 1.36. 

It almost feels like Windows is not using a high priority for the process. Basically the same thing that I already reported about 1.33 and 1.34.
![35-2](https://github.com/LostRuins/koboldcpp/assets/26260168/70969415-fd36-45f6-bcb5-ccee829506fd) ![36-2](https://github.com/LostRuins/koboldcpp/assets/26260168/12a7e5a5-c2a6-47b8-8b46-b0bcdb5b06c3)

**Comment by BeHappy2021** [comment]
Thanks for your work @LostRuins. Performance much improved for me and the RAM usage is back to pre-1.35.

**Comment by LostRuins** [comment]
@Nabokov86 I think your process prioritization may be a separate unrelated issue to the individual versions. 

Because there is no reason why the CPU usage should fluctuate and change so wildly for you between v1.32 to v1.36, especially without changes to any process prioritization code. 

Could it be other factors? Thermal throttling due to temperature maybe? Automatic CPU scaling, background processes, power settings? Or maybe even the filesystem itself?

Also I don't actually think a 5% difference in CPU usage is a measurably significant difference, my CPU usage for normal processes fluctuate all the time.
