### ISSUE TITLE
Is it possible to add support for other models as well?

### ISSUE THREAD

**Issue by Omniphantasm** [LostRuins/koboldcpp#31]
Is it possible to add support for https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g/blob/main/gpt-x-alpaca-13b-native-4bit-128g.pt by any chance? 

If not, not a big deal. Just curious if it can be done or not.

**Comment by LostRuins** [comment]
It already exists. Check out the models by these users: 
https://huggingface.co/Black-Engineer 
https://huggingface.co/Pi3141

**Comment by Omniphantasm** [comment]
You're goated, I'd give you Github silver if it existed.
