### ISSUE TITLE
v1.3.5 of KoboldCPP is broken, due to sampler order?

### ISSUE THREAD

**Issue by SabinStargem** [LostRuins/koboldcpp#314]
The model I am using is Airoboros 65b, v1.4.1-PI GGML.  It worked on the last version of Kobold.  Below is the message window.  I am guessing the sampler order is the issue?

I also tried v1.4, which is a less experimental version of Airoboros.  Same result.

> ***
Welcome to KoboldCpp - Version 1.35
For command line arguments, please refer to --help
***
Attempting to use OpenBLAS library for faster prompt ingestion. A compatible libopenblas will be required.
Initializing dynamic library: koboldcpp_openblas.dll
==========
Namespace(bantokens=None, blasbatchsize=1024, blasthreads=5, contextsize=8192, debugmode=False, forceversion=0, gpulayers=0, highpriority=False, hordeconfig=None, host='', launch=False, linearrope=False, lora=None, mirostat=None, model=None, model_param='C:/Users/Janus/Desktop/GAMING/0 - Frontends/KoboldCPP/airoboros-65b-gpt4-1.4.1-PI-8192.ggmlv3.q4_K_M.bin', noavx2=False, noblas=False, nommap=False, port=5001, port_param=5001, psutil_set_threads=False, skiplauncher=False, smartcontext=False, stream=False, threads=5, unbantokens=False, useclblast=None, usecublas=None, usemirostat=None, usemlock=False)
==========
Loading model: C:\Users\Janus\Desktop\GAMING\0 - Frontends\KoboldCPP\airoboros-65b-gpt4-1.4.1-PI-8192.ggmlv3.q4_K_M.bin
[Threads: 5, BlasThreads: 5, SmartContext: False]

---
Identified as LLAMA model: (ver 5)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from C:\Users\Janus\Desktop\GAMING\0 - Frontends\KoboldCPP\airoboros-65b-gpt4-1.4.1-PI-8192.ggmlv3.q4_K_M.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 8192
llama_model_load_internal: n_embd     = 8192
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 64
llama_model_load_internal: n_layer    = 80
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 15 (mostly Q4_K - Medium)
llama_model_load_internal: n_ff       = 22016
llama_model_load_internal: model size = 65B
llama_model_load_internal: ggml ctx size =    0.19 MB
llama_model_load_internal: mem required  = 45204.67 MB (+ 5120.00 MB per state)
llama_new_context_with_model: kv self size  = 20480.00 MB
Load Model OK: True
Embedded Kobold Lite loaded.
Starting Kobold HTTP Server on port 5001
Please connect to custom endpoint at http://localhost:5001

Input: {"prompt": "Megumin's Persona: Megumin is an Arch Wizard of the Crimson Magic Clan. Megumin is 14 years old girl. Megumin's height 152 cm. Megumin has shoulder-length dark brown hair, fair skin, flat chest, light complexion and doll-like features, crimson eyes. Megumin wears black cloak with gold border, choker, wizard\u2019s hat, fingerless gloves, eyepatch, orange boots. Megumin's weapon is a big black staff. Megumin is a loud, boisterous, and eccentric girl with a flair for theatrics. Megumin has chuunibyou tendencies. Megumin is very intelligent, but has very little self-control. Megumin love explosion magic. Megumin is generally calm and cheerful, but she can easily become aggressive when she feels slighted or challenged. Megumin has only one but a powerful ability, once a day she can use powerful explosion magic after which she cannot move for a while.\nPersonality: loud, intelligent, theatrical, hyperactive sometimes\nScenario: Megumin went out of city to train explosion magic\n<START>\nYou: Hi, I heard you're the best mage in town.\nMegumin: nods Indeed. I am the greatest user of Explosion magic in all the land. And you are?\nYou: I'm a new adventurer and I need your help to defeat a powerful demon.\nMegumin: smirks A demon, you say? That sounds like quite the challenge. I'll help you, but only if you can keep up with me.\nYou: I'll do my best, let's go.\nMegumin: nods Very well. Follow me and be prepared for a show of the most powerful magic in existence! starts walking\n<START>\nMegumin: *It was day, the weather was sunny and windless. We accidentally crossed paths near the city in a clearing, I was going to train explosion magic. When I noticed you i stand up in a pretentious and personable pose, and say loudly* I'm Megumin! The Arch Wizard of the Crimson Magic Clan! And i the best at explosion magic!! What are you doing here?\nYou: Just loafing around.  I take it you are responsible for the earth-shattering kaboom?\nMegumin:", "use_story": false, "use_memory": false, "use_authors_note": false, "use_world_info": false, "max_context_length": 8192, "max_length": 1024, "rep_pen": 1.15, "rep_pen_range": 2048, "rep_pen_slope": 3.4, "temperature": 0.8, "tfs": 1, "top_a": 0, "top_k": 100, "top_p": 0.9, "typical": 1, "sampler_order": [0, 1, 2, 3, 4, 5, 6], "singleline": false, "stop_sequence": ["\nYou:", "\nYou:"]}

(Warning!!! Poor sampler_order detected! You will have reduced quality. Recommended values are [6,0,1,3,4,2,5])

Processing Prompt [BLAS] (546 / 546 tokens)

**Comment by LostRuins** [comment]
Yes, you're recommended to change it to [6,0,1,3,4,2,5]. It's just a recommendation

**Comment by SabinStargem** [comment]
I wasn't aware those values could be manually changed by hand in KoboldLite - they don't look interactive.  Anyhow, I just tried a several prompts in Silly Tavern, using GUI Kobold AI as my preset.  If I understand it rightly, Silly would inherit the settings from Kobold.  So far it has been working.

To boil it down:  Kobold v1.35 does work, but is less tolerant of a user who isn't familiar with its workings.

**Comment by LostRuins** [comment]
Changing sampler settings in Kobold Lite will only affect Kobold Lite. You'd need to change the samplers in Silly Tavern for it to work there.

**Comment by VraethrDalkr** [comment]
The last KoboldCPP update breaks SillyTavern responses when the sampling order is not the recommended one. The first bot response will work, but the next responses will be empty, unless I make sure the recommended values are set in SillyTavern. It's as if the warning message was interfering with the API. I can open submit new issue if necessary.

**Comment by LostRuins** [comment]
Noted, that should not be the case, will investigate it in a few days, in the meantime please use 1.34.2

**Comment by VraethrDalkr** [comment]
Thank you! I'll continue using v1.35 anyways, but with recommended settings. I just noticed the same issue happens if I elect to use GUI KoboldAI settings withing SillyTavern, even if the correct recommended sampling order is set in KoboldAI Lite. SillyTavern has not been updated since before 1.35 came out.

**Comment by FitzWM** [comment]
Somewhat related to this issue, KoboldCPP seems to report my sampler order from SillyTavern as [0, 1, 2, 3, 4, 5, 6] regardless of the order I have set in ST. It seems to be numbering them in order of the list in ST, rather than by the numeric codes I found in the tooltip in the Kobold Lite interface. 

In fact, if I reorder the samplers in ST in response to the warning KoboldCPP gives, and then generate another response, it will output a new array that matches the changes. For example, if I move Temperature from position 6 to position 0 (bottom of the list in ST to the top) the array in the new output will change from [0, 1, 2, 3, 4, 5, 6] to [6, 0, 1, 2, 3, 4, 5] even though the numeric code in the Kobold Lite GUI for Temperature is 5.

I'm just getting used to KoboldCPP after using Ooba for a while, so please let me know if I'm just missing something or if I should open a new issue for this. And thanks! I seriously can't go back now that you've given me the ability to run 30B models at a reasonable speed.

**Comment by LostRuins** [comment]
Can you see if this is still causing issues in 1.36?

**Comment by VraethrDalkr** [comment]
It fixed it for me with SillyTavern. ST will output the responses even if the order isn't 6,0,1,2,3,4,5.

As for the reordering issue FitzWM mentioned, it's a problem with ST. We can see in the terminal that it is not passing the correct order unless we reposition the sampler order in ST webui.
