### ISSUE TITLE
Release 1.35 - CuBLAS preset not utilizing Nvidia GPU

### ISSUE THREAD

**Issue by StripedPuppy** [LostRuins/koboldcpp#315]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [✅] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [✅] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [✅] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [✅] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

KoboldCPP is supposed to offload layers to my Nvidia RTX 3060 GPU.

# Current Behavior

All devices (CPU, RAM, Disk) are used instead of the GPU. The GPU isn't touched at all.

# Environment and Context

KoboldCPP 1.35 - default release exe

* Physical (or virtual) hardware you are using, e.g. for Windows:

Nvidia RTX 3060, Intel i7

# Failure Information (for bugs)

N/A

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Set preset to CuBLAS
2. Configure amount of layers to offload to GPU and model
3. Launch

# Failure Logs

```
***
Welcome to KoboldCpp - Version 1.35
For command line arguments, please refer to --help
***
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.dll
==========
Namespace(bantokens=None, blasbatchsize=512, blasthreads=9, contextsize=2048, debugmode=False, forceversion=0, gpulayers=43, highpriority=False, hordeconfig=None, host='', launch=False, linearrope=False, lora=None, mirostat=None, model=None, model_param='D:/ChatGPT/0_ MODELS/13b - Pygmalion-13b/pygmalion-13b-ggml-q5_1.bin', noavx2=False, noblas=False, nommap=False, port=5001, port_param=5001, psutil_set_threads=False, skiplauncher=False, smartcontext=False, stream=False, threads=9, unbantokens=True, useclblast=None, usecublas=['normal', '0'], usemirostat=None, usemlock=False)
==========
Loading model: D:\ChatGPT\0_ MODELS\13b - Pygmalion-13b\pygmalion-13b-ggml-q5_1.bin
[Threads: 9, BlasThreads: 9, SmartContext: False]

---
Identified as LLAMA model: (ver 5)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from D:\ChatGPT\0_ MODELS\13b - Pygmalion-13b\pygmalion-13b-ggml-q5_1.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 9 (mostly Q5_1)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 2165.28 MB (+ 1608.00 MB per state)
llama_model_load_internal: allocating batch_size x (640 kB + n_ctx x 160 B) = 480 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 40 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 43/43 layers to GPU
llama_model_load_internal: total VRAM used: 11282 MB
llama_new_context_with_model: kv self size  = 1600.00 MB
Load Model OK: True
Embedded Kobold Lite loaded.
Starting Kobold HTTP Server on port 5001
Please connect to custom endpoint at http://localhost:5001
```
![2023-07-12 12_33_16](https://github.com/LostRuins/koboldcpp/assets/34108520/d63d334e-fcff-4bb7-a0c5-6b20fbb0c790)
![2023-07-12 12_36_36](https://github.com/LostRuins/koboldcpp/assets/34108520/ac7f07b2-83fe-4e0d-b7d4-2c2d1c62a884)

**Comment by LostRuins** [comment]
Your task manager is looking at your Intel card, not your nvidia card. See the name "Intel UHD Graphics 770"

Click the GPU below it.

**Comment by StripedPuppy** [comment]
I was wrong, thanks. I see my dedicated is near-full now.

Is there any reason why it's still reserving 70% of my memory if all layers are offloaded? I don't think I'm understanding this.

**Comment by cgessai** [comment]
@StripedPuppy Could [this](https://github.com/LostRuins/koboldcpp/issues/290#issuecomment-1616564008) have something to do with it?  I'm not sure it's referenced anywhere else.
