### ISSUE TITLE
Is there an API endpoint?

### ISSUE THREAD

**Issue by MKware00** [LostRuins/koboldcpp#32]
When I try to access API endpoint (like with TavernAI) it throws this:
![kobold](https://i.imgur.com/CwP1TPT.png)
And on Tavern logs this:
![tavern](https://i.imgur.com/96tQSNW.png)
Same thing when trying to access `localhost:5001/api` with browser:
![browser](https://i.imgur.com/rcZTzDT.png)

Does that mean that there's no API endpoint to connect from other programs? Using noavx2 build, just in case.

**Comment by Kagamma** [comment]
It should. Try to send POST request to `/api/latest/generate`

**Comment by LostRuins** [comment]
Ah i see what is happening, somehow this fork of TavernAI is requesting from a new endpoint that I did not implement. It will be added in the next release of KoboldCpp.

**Comment by henk717** [comment]
This is also bad design on the fork's part, they should never request /latest/ in case we change things up. They should target a version we specifically defined for future compatibility.

**Comment by LostRuins** [comment]
This should be fixed in the latest version, currently v1.3 at time of writing.
https://github.com/LostRuins/koboldcpp/releases/latest

**Comment by LostRuins** [comment]
Closing issue as it seems to be resolved. Please open a new one if there are other problems
