### ISSUE TITLE
[BUG] Stream API dumps HTTP Header into body after closely consecutive requests

### ISSUE THREAD

**Issue by duncannah** [LostRuins/koboldcpp#321]
**When two consecutive generation with streaming requests are sent closely (just AFTER the previous one, not during), the second request doesn't get token streaming, and some HTTP Header is also dumped into the body.**

**Debugging the API using the Insomnia app.**

<details><summary>First request, everything fine</summary>
<p>
<img src="https://github.com/LostRuins/koboldcpp/assets/38371914/a6eabe9c-338a-41ae-96b7-1fdb3be82ca8"/>
</p>
</details>

<details><summary>Second request, sent just after the previous one</summary>
<p>
<img src="https://github.com/LostRuins/koboldcpp/assets/38371914/f636e7f9-769f-4606-8aff-6b6b47ee7b0e"/>
</p>
</details>

**As you can see, there's some random HTTP Header dumped into the body, and the tokens weren't streamed.**

<details><summary>Dumping the raw response of the second request, we can see that the headers are sent twice, the dates being different too.</summary>
<p>
<img src="https://github.com/LostRuins/koboldcpp/assets/38371914/f48f916d-73cb-46bb-bc2c-a9b57ce1ec69"/>
</p>
</details>

<details><summary>It's not a problem with Insomnia or the network, here's curl on the same machine</summary>
<p>
<img src="https://github.com/LostRuins/koboldcpp/assets/38371914/ede978ad-e38d-4452-9593-893c3cbb9581"/>
</p>
</details>

**Comment by ycros** [comment]
FWIW I can take a stab at fixing this one since we discussed the problem on discord, and I also use the streaming API and can repro the bug.

**Comment by LostRuins** [comment]
Sure, send a PR if you're able to fix it, would be great. I'll need some time to catch up on all the other issues too.

**Comment by Angela-BC** [comment]
Is this the reason why sometimes a stop followed by a retry does not work in the UI, while the application is still generating?

**Comment by LostRuins** [comment]
Possibly. It has been merged, and will be in the next ver
