### ISSUE TITLE
Text generation is broken when using --gpulayers on Mac

### ISSUE THREAD

**Issue by Hapurubok** [LostRuins/koboldcpp#325]
Hello! I was trying to use GPU offload on M1 Max with 32Gb of Ram to see if it will speed up things or not. Replies generating indeed faster (I think about 3 times as faster), but they are nonsensical at all, like on this pic:

<img width="1728" alt="Blah" src="https://github.com/LostRuins/koboldcpp/assets/139910021/87bc5029-22b7-4e1c-8d21-76a82579548f">

I tried --gpulayers 50, 100 and 2000000. Without this argument chat works absolutely fine. I was building with LLAMA_METAL=1 parameter and using model for larger context size with --contextsize 8192.

Console log:

Welcome to KoboldCpp - Version 1.35
Warning: OpenBLAS library file not found. Non-BLAS library will be used.
Initializing dynamic library: koboldcpp.so
==========
Namespace(model=None, model_param='/Users/hapuru/Documents/Git/text-generation-webui/models/manticore-13b-chat-pyg-guanaco-superhot-8k.ggmlv3.q4_K_M.bin', port=5001, port_param=5001, host='', launch=False, lora=None, threads=4, blasthreads=4, psutil_set_threads=False, highpriority=False, contextsize=8192, blasbatchsize=512, linearrope=False, stream=False, smartcontext=False, unbantokens=False, bantokens=None, usemirostat=None, forceversion=0, nommap=False, usemlock=False, noavx2=False, debugmode=0, skiplauncher=False, hordeconfig=None, noblas=False, useclblast=None, usecublas=None, gpulayers=100)
==========
Loading model: /Users/hapuru/Documents/Git/text-generation-webui/models/manticore-13b-chat-pyg-guanaco-superhot-8k.ggmlv3.q4_K_M.bin
[Threads: 4, BlasThreads: 4, SmartContext: False]

---
Identified as LLAMA model: (ver 5)
Attempting to Load...
---
System Info: AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 |
llama.cpp: loading model from /Users/hapuru/Documents/Git/text-generation-webui/models/manticore-13b-chat-pyg-guanaco-superhot-8k.ggmlv3.q4_K_M.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 8192
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 15 (mostly Q4_K - Medium)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: mem required  = 11596.94 MB (+ 1608.00 MB per state)
llama_new_context_with_model: kv self size  = 6400.00 MB
ggml_metal_init: allocating
ggml_metal_init: using MPS
ggml_metal_init: loading '/Users/hapuru/Documents/Git/koboldcpp/ggml-metal.metal'
ggml_metal_init: loaded kernel_add                            0x126f28650
ggml_metal_init: loaded kernel_mul                            0x126f289d0
ggml_metal_init: loaded kernel_mul_row                        0x126f28d50
ggml_metal_init: loaded kernel_scale                          0x126f290d0
ggml_metal_init: loaded kernel_silu                           0x126f29450
ggml_metal_init: loaded kernel_relu                           0x126f297d0
ggml_metal_init: loaded kernel_gelu                           0x126f29b50
ggml_metal_init: loaded kernel_soft_max                       0x126f2a060
ggml_metal_init: loaded kernel_diag_mask_inf                  0x126f2a520
ggml_metal_init: loaded kernel_get_rows_f16                   0x126f2aa00
ggml_metal_init: loaded kernel_get_rows_q4_0                  0x126f2aee0
ggml_metal_init: loaded kernel_get_rows_q4_1                  0x126f2b3c0
ggml_metal_init: loaded kernel_get_rows_q2_K                  0x126f2b8a0
ggml_metal_init: loaded kernel_get_rows_q3_K                  0x126f2bd80
ggml_metal_init: loaded kernel_get_rows_q4_K                  0x126f2c260
ggml_metal_init: loaded kernel_get_rows_q5_K                  0x126f2c740
ggml_metal_init: loaded kernel_get_rows_q6_K                  0x126f2cc20
ggml_metal_init: loaded kernel_rms_norm                       0x126f2d130
ggml_metal_init: loaded kernel_norm                           0x126f2d640
ggml_metal_init: loaded kernel_mul_mat_f16_f32                0x126f2dd00
ggml_metal_init: loaded kernel_mul_mat_q4_0_f32               0x126f2e240
ggml_metal_init: loaded kernel_mul_mat_q4_1_f32               0x126f2e780
ggml_metal_init: loaded kernel_mul_mat_q2_K_f32               0x126f2ecc0
ggml_metal_init: loaded kernel_mul_mat_q3_K_f32               0x126f2f3a0
ggml_metal_init: loaded kernel_mul_mat_q4_K_f32               0x126f2f8e0
ggml_metal_init: loaded kernel_mul_mat_q5_K_f32               0x126f2fe20
ggml_metal_init: loaded kernel_mul_mat_q6_K_f32               0x126f30360
ggml_metal_init: loaded kernel_rope                           0x126f30cb0
ggml_metal_init: loaded kernel_alibi_f32                      0x126f313d0
ggml_metal_init: loaded kernel_cpy_f32_f16                    0x126f31ac0
ggml_metal_init: loaded kernel_cpy_f32_f32                    0x126f321b0
ggml_metal_init: loaded kernel_cpy_f16_f16                    0x126f328a0
ggml_metal_init: recommendedMaxWorkingSetSize = 21845.34 MB
ggml_metal_init: hasUnifiedMemory             = true
ggml_metal_init: maxTransferRate              = built-in GPU
llama_new_context_with_model: max tensor size =   128.17 MB
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  7501.30 MB, ( 7501.69 / 21845.34)
ggml_metal_add_buffer: allocated 'eval            ' buffer, size =  1024.00 MB, ( 8525.69 / 21845.34)
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  6402.00 MB, (14927.69 / 21845.34)
ggml_metal_add_buffer: allocated 'scr0            ' buffer, size =  1536.00 MB, (16463.69 / 21845.34)
ggml_metal_add_buffer: allocated 'scr1            ' buffer, size =  1536.00 MB, (17999.69 / 21845.34)
Load Model OK: True
Embedded Kobold Lite loaded.
Starting Kobold HTTP Server on port 5001
Please connect to custom endpoint at http://localhost:5001

**Comment by LostRuins** [comment]
I suspect the original implementation of linear rope for long contexts on metal is not correct. I am updating it to a newer implementation upstream that should hopefully fix this issue in the next version.

**Comment by LostRuins** [comment]
Next update is out, could you let me know if it works for you?

**Comment by Hapurubok** [comment]
Yes, I lunch app with --contextsize 8192 --gpulayers 100  --stream --smartcontext arguments and everything works fast and flawless. Thank you!

**Comment by Hapurubok** [comment]
Gonna close it then.
