### ISSUE TITLE
In many cases, the message displayed in the terminal is longer than in the web interface

### ISSUE THREAD

**Issue by Hapurubok** [LostRuins/koboldcpp#326]
I have noticed over time, that text outputted to terminal are usually longer then the one in chat. 

<img width="1216" alt="Pic" src="https://github.com/LostRuins/koboldcpp/assets/139910021/da5bab3d-1856-44ac-ac1a-588f946d839e">

Yes, sometimes it can be out of context or try to speak for another character or for me, or be just unfinished, but mostly I find it more or less fine. So maybe these is a way to keep it in web-interface too? 

I have already tried change settings such as Trim Sentences and Trim Whitespace, but they do nothing. I'm using version 1.35 on M1 Mac.

Also, I do not know, is it should be another issue or not, but maybe there is a way to make response gradually typed into web-interface, as it done in oobabooga's Web UI?

**Comment by mrdevolver** [comment]
> I have noticed over time, that text outputted to terminal are usually longer then the one in chat.
> <img alt="Pic" width="1216" src="https://user-images.githubusercontent.com/139910021/254364030-da5bab3d-1856-44ac-ac1a-588f946d839e.png">
> 
> Yes, sometimes it can be out of context or try to speak for another character or for me, or be just unfinished, but mostly I find it more or less fine. So maybe these is a way to keep it in web-interface too?
> 
> I have already tried change settings such as Trim Sentences and Trim Whitespace, but they do nothing. I'm using version 1.35 on M1 Mac.
> 
> Also, I do not know, is it should be another issue or not, but maybe there is a way to make response gradually typed into web-interface, as it done in oobabooga's Web UI?

I believe this is not a bug, it's probably just running out of tokens for generating. Once it runs out of tokens, it stops generating new text and the unfinished sentence (if any) are completely cut out by default. You can disable this in the settings, but disabling it doesn't seem to have any effect on my end, so perhaps that is a bug, but that doesn't affect your issue. If you want the AI to generate longer responses, you need to increase the number of generated tokens. By default this number is set to 80, but that won't solve the 'issue' you're describing here, it will work the same way, it will just generate more text, but some of the text will be still cut out in the end.

Regarding the last part, it's already implemented in KoboldCpp and it's called stream. To enable it, you need to run with --stream parameter. You may also consider using --smartcontext along with it, for more details on what these parameters do, just run KoboldCpp with --help parameter and look them up there.

**Comment by LostRuins** [comment]
That's correct. Chat mode will trim off incomplete responses. If you want the *raw* text, you should use Story mode or Instruct mode.

**Comment by mrdevolver** [comment]
> That's correct. Chat mode will trim off incomplete responses. If you want the _raw_ text, you should use Story mode or Instruct mode.

For me, incomplete sentences are getting cut off in story mode as well. I haven't tried instruction mode enough to draw conclusion there, but I already felt like I had to generate one thing in several just to finish it, so it's possible it's practically the same behavior across the board.

**Comment by Hapurubok** [comment]
@LostRuins @mrdevolver Thanks for both answers and suggestion about --stream! I increased amount of maximum generated tokens, but it's still kinda hit or miss, sometimes it can cut around 80% of what it generated. Also I noticed that sometimes size of a reply depends on a character itself.  And maybe, I'm not sure, but it's still possible to add minimum amount of tokens too in next updates?

**Comment by henk717** [comment]
Make sure to check your settings, there are two different trim options and chat mode also requires multiline chst enabled if you dont want things trimmed as aggressively like that.

But of course there is also the part where the model tries to speak on your behalf which the chat Ui nicely filters out.

**Comment by LostRuins** [comment]
Also, if the AI uses multiple lines to respond, make sure Multiline Replies is enabled for chat. Though do note that multiline replies do have a probability of glitching certain models when they try to reply as the user.

**Comment by Hapurubok** [comment]
@henk717 @LostRuins Yes, that was the whole problem, I apparently disabled this feature, thinking that it relates to timed replies setting below. Thanks!

**Comment by LostRuins** [comment]
Increase "amount to generate"

**Comment by LostRuins** [comment]
you can also simply press "Generate More"

**Comment by marco-trovato** [comment]
Yes I know you can generate more, but why Llama.cpp, ollama, and all others do not have this problem and are able to finish their paragraphs and code?

**Comment by henk717** [comment]
Because they probably have a higher gen amount by default. Its a non issue because you can change the slider as lostruins mentioned. If you don't do so thats not the fault of our software.
