### ISSUE TITLE
[BUG, v1.3.5-H3]  Airoboros 33b v1.4.1, 16k GGML doesn't work.

### ISSUE THREAD

**Issue by SabinStargem** [LostRuins/koboldcpp#329]
When it finishes a prompt, no text is created.  This is for both KoboldLite's window and the command prompt.  Should be noted that it also seems to not work on Oogabooga. My guess is that 16k GGMLs don't have compatibility yet.  Otherwise, something went wrong when it got built.   Here is the link to Ycros's repository.

[ycros/airoboros-33b-gpt4-1.4.1-lxctx-PI-16384-GGML](https://huggingface.co/ycros/airoboros-33b-gpt4-1.4.1-lxctx-PI-16384-GGML)

**Comment by ycros** [comment]
Not yet, but looking at upcoming commits the next release should let you set the 0.125 scale for these models to work properly. Though 8192 is still the current max context size limit I believe.

**Comment by LostRuins** [comment]
Yes, the next commit will allow for any arbitrary combination of freq base and scale, as upstream does.

**Comment by digiwombat** [comment]
16384 isn't manually settable via the UI or via the command line in 1.36. Is that intended and custom rope settings should be used instead? I assume not since when I skip setting context and just set the rope the n_ctx is still reported as 2048 and it crashes with the following error as soon as I hit 2049 tokens:

GGML_ASSERT: .\koboldcpp\ggml.c:14871: tensor->src[0] == NULL || tensor->src[0]->backend == GGML_BACKEND_CPU

**Comment by LostRuins** [comment]
@digiwombat no, unfortunately a full 16384 context is not supported natively yet. 
What you should do is instead:
- Set `--contextsize 8192`
- Set `--ropeconfig 0.125 10000` which provides 8x RoPE scaling.
- Run the model, setting the max context length to 8192 inside the UI

 You won't be able to use the full 16k tokens currently, but this should work and be coherent up to 8000 tokens.

**Comment by callMeMakerRen** [comment]
> 16384 isn't manually settable via the UI or via the command line in 1.36. Is that intended and custom rope settings should be used instead? I assume not since when I skip setting context and just set the rope the n_ctx is still reported as 2048 and it crashes with the following error as soon as I hit 2049 tokens:
> 
> GGML_ASSERT: .\koboldcpp\ggml.c:14871: tensor->src[0] == NULL || tensor->src[0]->backend == GGML_BACKEND_CPU
> 
> Edit: There is some discussion on the closed RoPE scaling PR on llama.cpp about CUDA issues, so this is possibly related to that more than the 16k, not sure.

@LostRuins in my issue, i just mean this strange assert crash. and by the way ,i wonder what is the relationship of --contextsize  and --ropeconfig, i mean your code offer --contextsize for 8192 already in v1.3.5. and the --ropeconfig is introduced in v1.3.6. did we really have --contextsize for 4096/8192 in v1.3.5 ?  and recently meta released llama-2 model, some people say it context size is already 4096 ? will this so called RoPE scaling effect the new llama-2 model?  do we need this RoPE anymore? thx

**Comment by LostRuins** [comment]
Maybe to clear some misconception. The main purpose of `--contextsize` is to ensure sufficient memory is allocated for the buffers in RAM so that the program does not crash. As a ease-of-use, it also scales the RoPE by default for llama, gptJ and gpt-neoX so that models can work with this longer context automatically without hassle for the user. 

However, using --ropeconfig overrides this rope scaling with your own custom values, allowing you to set it to anything you want.

**Comment by SabinStargem** [comment]
> @digiwombat no, unfortunately a full 16384 context is not supported natively yet. What you should do is instead:
> 
>     * Set `--contextsize 8192`
> 
>     * Set `--ropeconfig 0.125 10000` which provides 8x RoPE scaling.
> 
>     * Run the model, setting the max context length to 8192 inside the UI
> 
> 
> You won't be able to use the full 16k tokens currently, but this should work and be coherent up to 8000 tokens. Let me know if this works for you.

I think something went wrong?  Ever since switching to v1.3.6, the 8k and 16k versions of Airoboros has become very unreliable or lack narrative skill.

I tried Airoboros v1.4 65b, using Kobold Godlike as my preset with corrected sampling.  The text is a good deal better.

**Comment by LostRuins** [comment]
@SabinStargem what parameters are you using for your ropeconfig?

**Comment by SabinStargem** [comment]
> @SabinStargem what parameters are you using for your ropeconfig?

I tried out the one you suggested, with questionable results.   --ropeconfig 0.125 10000

That didn't work, and I went to default rope.  Still bad.   Then I tried switching to a different model,  Airoboros v1.4, since it wasn't a model that had increased context.   The results improved.

Now here is the thing:  for v1.3.5, the 8k/16k models worked roughly around the same level of effectiveness as Airoboros v1.4.  That is why I think the rope implementation had something go awry, since there was an abrupt downgrade in reliability and quality.

**Comment by LostRuins** [comment]
Okay try this instead: `--ropeconfig 1.0 82684`

**Comment by SabinStargem** [comment]
That one works.  Five different presets worked in KoboldCPP, and a trial run in Silly Tavern succeeded.  :)

**Comment by ycros** [comment]
This is weird, it should work with linear scaling only as that's what it's finetuned on. I wonder if the implementation is off, I'll have to do some testing. I made the 65B finetune and it should work with `--ropeconfig 0.25 10000` - I tested this on older kobold (where I had the old linear scaling code hardcoded in for 0.25), and I've tested that and the 16k on exllama where the appropriate 0.25/0.125 (or as they call them, 4 and 8) values work correctly.

**Comment by LostRuins** [comment]
Yeah i'm not doing anything special with the linear scaling, it is literally just applied to the final theta scale as done before. Would be good to double check against the finetune - unfortunately I cannot run models this big myself, so someone else may need to look into it.

**Comment by SabinStargem** [comment]
A brief record of rope configs.  Failure either produces no text or just a single line.   'Good' is a decent set of dialogue, but suffers from incorrect details.  Ideal has no discernible flaws.  I am including the preset and test prompt, for those who want to try it out.

**Airoboros 33b 16k, Midnight Enigma preset.**
FAIL  --ropeconfig 0.125, 10000
FAIL --ropeconfig 1.0, 82684
GOOD -- ropeconfig 0.25, 10000

**Airoboros 65b 8k, Midnight Enigma preset**
FAIL  --ropeconfig 0.125, 10000
GOOD --ropeconfig 1.0, 82684
IDEAL -- ropeconfig 0.25, 10000


> (Chat) "Midnight Engima"
> Temperature 	                - 0.98
> Top P 		                        - 0.37
> Repetition Penalty 	        - 1.18
> Top K					- 100
> Top A 					- 0.0
> Typical Sample			- 1
> TFS					- 1
> Repetion Penalty Range 	- 0.0
> Repetition Penalty Slope	- 2048


Below is my test prompt.  It is what I use for figuring out presets and testing the rope scaling.  A common issue is the hallucination of an extra person, which helps sort bad presets from smart ones.

> OOC:  Describe the attempted escape of the subordinates.  Any number may die, in gruesome fashion.  Any survivors should have their respective life paths explained, in terms of events, feelings, and motivations for their way of life.  Each survivor will give an ending monologue or speech about their fallen squad leader.  Their opinion of the commander may range freely.
> 
> /OOC
> 
> There was a war, and I am one of the casualties.  Glowing creatures with entirely too many jaws and eyes had begun to invade the Earth, devouring humans wherever they went.  I was just one of many conscripts thrust into a struggle against the extinction of humanity.   During one of the battles, I and my three subordinates were accosted by a particularly large abomination.  These things are malicious, known for mutilating their victims alive.  To protect my comrades, I ordered them to retreat while I distracted the creature.  Moments later, the corpses of myself and the beast lay scattered across the floor of an abandoned grocery store. Feeling left my body, and the world faded away. With my final thoughts, I hoped those three had escaped...

**Comment by LostRuins** [comment]
I suppose it really depends on how the models were finetuned
