### ISSUE TITLE
Code in python not formatted....at all.

### ISSUE THREAD

**Issue by PedzacyKapec** [LostRuins/koboldcpp#339]
ver 1.36, win10, model: HermesCoder GGML, LLama7b and others.

Example:

Pete
write a code in python to calc age based on user entered birthdate

KoboldAI
Sure, here's some sample code that you can use:
```python
from datetime import date
def calculate_age(birthdate):
today = date.today()
return today.year - birthdate.year - ((today.month, today.day) < (birthdate.month, birthdate.day))
# Example usage

user_birthdate = input("Enter your birthdate in the format of mm/dd/yyyy
")
birthdate = date(*map(int, user_birthdate.split('/')))
age = calculate_age(birthdate)
print("You are", age, "years old.")
```
This function takes a string `birthdate` in the format of mm/dd/yyyy as input and returns the calculated age as an integer value. The example usage shows how to call this function with a user-entered birthdate.

**Comment by mrdevolver** [comment]
As far as I could see, no code was ever formatted, not just the python. It would be nice if the output was like ChatGPT with a nice code block with indentation, code highlighting and a nice little button for quick code copy, but hey it's what it is. Maybe we will get there one day, right?

**Comment by LostRuins** [comment]
If you look into the console, is the output formatted correctly within there? (i.e. is it a model issue, or a UI issue)?

**Comment by certainexception** [comment]
It looks to be a UI issue. 

```
Input: {"n": 1, "max_context_length": 8292, "max_length": 4096, "rep_pen": 1.1, "temperature": 0.7, "top_p": 0.72, "top_k": 0, "top_a": 0, "typical": 1, "tfs": 1, "rep_pen_range": 300, "rep_pen_slope": 0.7, "sampler_order": [6, 0, 1, 3, 4, 2, 5], "prompt": "Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nWrite a python function to parse a CSV and output the fourth column to disk.\n\n### Response:\n\n\n", "quiet": true}

Processing Prompt (25 / 25 tokens)
Generating (112 / 4096 tokens)
Generation Aborted
Generating (4097 / 4096 tokens)
Time Taken - Processing:12.7s (507ms/T), Generation:72.6s (648ms/T), Total:85.3s (1.3T/s)
Output: ```python
import csv
with open('input.csv') as infile:
    reader = csv.reader(infile)
    for row in reader:
        print(row[3])
```

---
```

The code in the UI isn't formatted, but the console's is.

**Comment by LostRuins** [comment]
It seems that in order for indentations to work proper, it needs to be within a code block. Try adding code blocks to the start of the AI response (using triplequotes ``` )

**Comment by certainexception** [comment]
My mistake, the code block messed up the triple quote code blocks. The model is actually outputting those, the UI just doesn't take them into account it seems.

![image](https://github.com/LostRuins/koboldcpp/assets/134816454/d73a2b2d-9442-4e61-bb3c-5d803f432418)
![image](https://github.com/LostRuins/koboldcpp/assets/134816454/d08515ae-d152-4c72-92b3-aaedad025527)

**Comment by PedzacyKapec** [comment]
> My mistake, the code block messed up the triple quote code blocks. The model is actually outputting those, the UI just doesn't take them into account it seems.
> 
> ![image](https://user-images.githubusercontent.com/134816454/256830182-d73a2b2d-9442-4e61-bb3c-5d803f432418.png) ![image](https://user-images.githubusercontent.com/134816454/256830297-d08515ae-d152-4c72-92b3-aaedad025527.png)

Yes, there is smth wrong with kobold app.

**Comment by LostRuins** [comment]
Did you 
- enable markdown in settings 
- turn off edit mode? 

Markdown for code only applies when edit mode is off and it is enabled. Please reload the same example with the settings changed.

![image](https://github.com/LostRuins/koboldcpp/assets/39025047/d355c3d4-b7c1-4e11-8436-7c5d50f4b519)

**Comment by certainexception** [comment]
Ah, you're absolutely right, I didn't see the markdown checkbox because I was on Story mode.

![image](https://github.com/LostRuins/koboldcpp/assets/134816454/91d3674c-3a8f-4d5a-b289-0893eaf79543)
