### ISSUE TITLE
Return completion reason from generate api

### ISSUE THREAD

**Issue by EdwardBonnett** [LostRuins/koboldcpp#340]
It would be nice to get extra metadata returned from the generate api, without this it's currently impossible to establish whether a prompt has finished generating because it maxed out the length or because it's hit it's EOL / stop sequence. 

Being able to get the tokens per second and token count returned from this would be amazing too.

**Comment by LostRuins** [comment]
For the second one, you can do it, the latest version has support for the `/api/extra/perf` endpoint which contains this information, token counts and stopping reason will be added in the next version. They won't be available in the `/generate` API for now as these fields are not compatible with the main koboldAI client.

**Comment by LostRuins** [comment]
Added in 1.37, please try.
