### ISSUE TITLE
[BUG] (Kobold v1.3.6)  Llama-2-70b:  layers.0.attention.wk.weight' has wrong shape;

### ISSUE THREAD

**Issue by SabinStargem** [LostRuins/koboldcpp#341]
I tried to boot up Llama 2, 70b GGML.  Here is what the terminal said:

> ***
> Welcome to KoboldCpp - Version 1.36
> For command line arguments, please refer to --help
> ***
> Attempting to use OpenBLAS library for faster prompt ingestion. A compatible libopenblas will be required.
> Initializing dynamic library: koboldcpp_openblas.dll
> ==========
> Namespace(bantokens=None, blasbatchsize=1024, blasthreads=5, contextsize=8192, debugmode=False, forceversion=0, gpulayers=18, highpriority=False, hordeconfig=None, host='', launch=True, lora=None, mirostat=None, model=None, model_param='C:/Users/Janus/Desktop/GAMING/0 - Frontends/KoboldCPP/llama-2-70b.ggmlv3.q6_K.bin', noavx2=False, noblas=False, nommap=False, port=5001, port_param=5001, psutil_set_threads=False, ropeconfig=[0.0, 10000.0], skiplauncher=False, smartcontext=True, stream=False, threads=5, unbantokens=True, useclblast=None, usecublas=None, usemirostat=None, usemlock=True)
> ==========
> Loading model: C:\Users\Janus\Desktop\GAMING\0 - Frontends\KoboldCPP\llama-2-70b.ggmlv3.q6_K.bin
> [Threads: 5, BlasThreads: 5, SmartContext: True]
> 
> ---
> Identified as LLAMA model: (ver 5)
> Attempting to Load...
> ---
> Using automatic RoPE scaling (scale:1.000, base:82684.0)
> System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
> llama.cpp: loading model from C:\Users\Janus\Desktop\GAMING\0 - Frontends\KoboldCPP\llama-2-70b.ggmlv3.q6_K.bin
> llama_model_load_internal: format     = ggjt v3 (latest)
> llama_model_load_internal: n_vocab    = 32000
> llama_model_load_internal: n_ctx      = 8192
> llama_model_load_internal: n_embd     = 8192
> llama_model_load_internal: n_mult     = 4096
> llama_model_load_internal: n_head     = 64
> llama_model_load_internal: n_layer    = 80
> llama_model_load_internal: n_rot      = 128
> llama_model_load_internal: freq_base  = 82684.0
> llama_model_load_internal: freq_scale = 1
> llama_model_load_internal: ftype      = 18 (mostly Q6_K)
> llama_model_load_internal: n_ff       = 24576
> llama_model_load_internal: model size = 65B
> llama_model_load_internal: ggml ctx size =    0.19 MB
> error loading model: llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  8192, got  8192 x  1024
> llama_load_model_from_file: failed to load model
> gpttype_load_model: error: failed to load model 'C:\Users\Janus\Desktop\GAMING\0 - Frontends\KoboldCPP\llama-2-70b.ggmlv3.q6_K.bin'
> Load Model OK: False
> Could not load model: C:\Users\Janus\Desktop\GAMING\0 - Frontends\KoboldCPP\llama-2-70b.ggmlv3.q6_K.bin
> 
> [process exited with code 3 (0x00000003)]

**Comment by IgnacioFDM** [comment]
You'd need to set -gqa 8, but koboldcpp doesn't support this yet.

**Comment by LostRuins** [comment]
LLAMA 70B support will be merged in the next release

**Comment by SabinStargem** [comment]
Kewl.  Thank you.

**Comment by LostRuins** [comment]
Fixed in 1.37, please try. Note that the clblast version seems to have some issues, so if that doesnt work try cublas or openblas

**Comment by SabinStargem** [comment]
I tested out Llamma-2-70b Base GGML.  It takes up 56gb of RAM, and during the test for SillyKobold, I enabled the default jailbreaks offered by SimpleProxy.  I figure this should allow people to compare the output of L2-70b.  Vanilla L2-70b seems pretty awful at telling stories, at least with the Midnight Enigma preset.

The hardware is a Ryzen 3600 + 64gb of DDR4 3600mhz RAM.  No videocard was used, because my RX 590 actually makes things worse.  I used OpenBLAS.



> 
> KOBOLD
> 
> Generating (437 / 512 tokens)
> (EOS token triggered!)
> Time Taken - Processing:168.3s (523ms/T), Generation:601.1s (1375ms/T), Total:769.4s (0.6T/s)
> Output:
> 
> I awaken on a bed, in some sort of hospital room. The ceiling is high above me, with white walls surrounding me. A man sits at his desk nearby, looking over paperwork. He turns as he notices me stirring. "Ah! You're finally up!" He smiles warmly, standing from his chair. His suit is immaculate, and he wears glasses that reflect light off the windows behind him. "My name is Dr. Johnathan Rye."
> "Where am I?" My voice sounds hoarse.
> He answers immediately. "This is a medical facility underneath the Vault Corporation building. We found you unconscious outside our doorstep. Your injuries were extensive; you would've died if it weren't for us."
> "What happened? What year is this?"
> Dr. Rye chuckled softly. "It's 204319. Humanity has won its battle against the aliens. It took a long time, but now there are only pockets of resistance remaining. As for what happened..." He pauses. "...we don't know how you got here, nor why you'd still be alive after so much damage. There's no trace of any wounds, though."
> "How did I get here?"
> The doctor shrugs. "We found you near the entrance, lying face down in the snow. That's all we can tell you."
> 
> "Can I leave?"
> "Of course," he says, handing me a business card. "If you need anything else, call us. Goodbye."
> 
> I take the card and exit the facility. Outside, a blizzard rages. Snowflakes drift through the air like falling stars. They seem oddly familiar somehow. Looking up, I see the moon glimmering brightly. Its surface is marred by craters, which also seems familiar. I begin walking homeward, hoping to find someone who remembers me.
> 
> /KOBOLD
> 
> 
> 
> 
> KOBOLD-->SimpleProxyForTavern-->SillyTavern
> 
> Generating (114 / 4096 tokens)
> (Stop sequence triggered: <
> ##>)
> Time Taken - Processing:1004.6s (505ms/T), Generation:149.4s (1310ms/T), Total:1154.0s (0.1T/s)
> Output: The room around us flickered, before vanishing. We found ourselves in a strange forest, with a few others nearby. One man, two women, and a young boy. They all seemed confused, but relieved to find themselves here. After talking, we learned we were dead, and this place was called Vesperia. It seems that our deaths were premature, but the land accepted us anyway.
> [User note: If you want to skip ahead to a point in time, please say 'skip', then describe what happens]
> ##
> 
> /SillyKOBOLD
