### ISSUE TITLE
Pass the currently loaded model name to Kobold API

### ISSUE THREAD

**Issue by jacob1218** [LostRuins/koboldcpp#343]
Currently, the model name loaded is always reported as concedo/koboldcpp regardless of what model is actually loaded.
Is there any way this could be synced to show the model that is currently loaded (if not in hf format, maybe just local/model_name?)

**Comment by gustrd** [comment]
There is a horde config parameter, check at --help.

**Comment by jacob1218** [comment]
i didn't know that was there. colsing
