### ISSUE TITLE
[BUG] (v1.3.6) - KoboldCPP doesn't properly report memory usage to task manager.

### ISSUE THREAD

**Issue by SabinStargem** [LostRuins/koboldcpp#344]
When I was trying out the q6 version of Airoboros through Kobold, the memory use on my 64gb of RAM reached 99% in the task manager.  The strange thing is that KoboldCPP was listed as consuming only 12gb.

This might make it harder to spot memory leaks in Kobold.

**Comment by SabinStargem** [comment]
I use MLOCK.

**Comment by LostRuins** [comment]
Actually this is a property of mmap, which allows the model to be loaded into memory on demand from disk. You can disable it with `--nommap`

**Comment by SabinStargem** [comment]
I have begun combining MLOC with NOMAP, and the terminal has this error.  It seems like that I can use KoboldCPP just fine, but I am putting the error here just in case:

> warning: failed to VirtualLock 39347507200-byte buffer (after previously locking 0 bytes): Invalid access to memory location.
