### ISSUE TITLE
Which methods to call when compiled into godot

### ISSUE THREAD

**Issue by st4rl1ght1337** [LostRuins/koboldcpp#350]
Trying to get in touch with concedo, message me on discord if you can. What would I do to go about compiling support for Pygmalion 6B model method support into godot engine? See https://docs.godotengine.org/en/3.1/development/cpp/custom_modules_in_cpp.html . That is, I'm not sure which C++ files to include. Also, not sure what methods to call for the equivalent of /generate api endpoint within the game engine (needs to be a exposed c++ method) - looked at your python script and confused because I don't understand how all of this is working together. I'd use llama.cpp but apparently they are not developing with a view to backwards compatibility, lmk.

**Comment by LostRuins** [comment]
There is a makefile included in the project that compiles all the files you need, and outputs a `.dll` file that exposes the functions to be called in the library. You can refer to the ctypes bindings at the top of the koboldcpp.py file to see how I used it. However, this library is meant for internal use and not documented, the function arguments and names are subject to change. 

Instead, I'd recommend using the web API instead as it is far more user friendly. You start the server in the background and then simply make REST api calls to generate text and parse the response.

**Comment by st4rl1ght1337** [comment]
How do .dll files work on linux

**Comment by LostRuins** [comment]
llama.cpp doesn't work with pygmalion 6b because pygmalion 6b is a GPT-J model. It's a completely different architecture. unfortunately you do need to have different builds for different platforms as use a different instruction set, some intrinsics used by x86 will be very different from ARM for example. 

For reference, the function methods exposed are all inside the `expose.cpp` file

**Comment by st4rl1ght1337** [comment]
I'm not exactly sure how the build process is going to work for the game, but I'm guessing that the build only needs to occur once for Gnu+Linux. To clarify, I need to build the Godot engine for linux, but the Godot engine itself handles building for a variety of platforms. If I don't compile the modules internally, then I have to make a separate build process for all of those classes, whereas if built internally likely I do not need to handle building at runtime

**Comment by st4rl1ght1337** [comment]
Talked to Concedo, the necesary methods to invoke are in expose.cpp, there are methods in gptj_v3.cpp but they cannot be invoked without helper functions for graph, buffer allocation, memory management, etc. Expose.cpp methods are invoked with the expose.h data structure, and memory must be allocated in the sense of https://github.com/LostRuins/koboldcpp/blob/concedo/koboldcpp.py#L233
`ctypes.create_unicode_buffer(ctypes.sizeof(generation_outputs))` (koboldcpp.py)` - koboldcpp expects python to do this, but can be done in C++. Will post if I discover anything else
