### ISSUE TITLE
[FEATURE REQUEST] (Kobold v1.3.7) - Improve the usability of Mirostat.

### ISSUE THREAD

**Issue by SabinStargem** [LostRuins/koboldcpp#351]
I think that Mirostat could be easier to use.  There are four things that I believe would make it better.

1:  The ability to change Mirostat values while Kobold is running.  This would allow for faster testing of Mirostat configurations.

2:  Darkening unrelated parameters while in Mirostat mode.  Far as I know, only temperature is used.

3:  Tool-tips or "?" that explains the settings for Mirostat.  What are the modes, tau, and eta, and what ranges do these have?

4:  Extend the temperature slider to accept up to 5.  I have found that by manually inputting 3.5 temperature, my Mirostat worked better in L2-70b Airoboros.  Kobold's slider caps at 2.

That is all.  Thank you for reading this suggestion.  :)

**Comment by LostRuins** [comment]
Mirostat is actually supported via the API, it's just that lite doesnt currently have the UI for it. I do plan to add it in eventually

**Comment by LostRuins** [comment]
Mirostat is available in the UI now
