### ISSUE TITLE
[User] Emoticons used by the AI aren't being streamed correctly

### ISSUE THREAD

**Issue by StefanDanielSchwarz** [LostRuins/koboldcpp#353]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

When the AI generates emoticons, they should be displayed properly in the backend, e. g. SillyTavern, also when streaming is enabled.

# Current Behavior

When the AI generates emoticons, the KoboldCpp console window displays them properly as part of the output, but they aren't streamed correctly to SillyTavern.

# Environment and Context / Failure Information (for bugs)

[According to the SillyTavern author](https://github.com/SillyTavern/SillyTavern/issues/821): "Koboldcpp problem, not ours. Emojis are usually two tokens, but they are being streamed as two separate decoded pieces of text which mess the formatting. Report this to koboldcpp. Oobabooga does this correctly."

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Have the AI send emoticons, either by asking for it or using examples messages with emoticons for the AI to mimic.
2. Check koboldcpp command line window and see that the output includes emoticons.
3. SillyTavern's chat doesn't show the emoticons, though.

**Comment by LostRuins** [comment]
Fixed in 1.38, please try

**Comment by StefanDanielSchwarz** [comment]
Thank you, works perfectly!
