### ISSUE TITLE
[Enhancement] Kobold Petals Inference Horde

### ISSUE THREAD

**Issue by bennmann** [LostRuins/koboldcpp#360]
Hello,

I have an AMD GPU with 16GB VRAM. There is some research that suggests that offloading between CPU+GPU is not as ideal as a multi-node server (see: petals https://github.com/bigscience-workshop/petals) 

For example, petals shows the below chart

The benchmarks below are for BLOOM-176B:

Offloading, max. possible speed on 1x A100
256 Gbit/s |   | 0.18 | 0.18 | 2.7 | 170.3
128 Gbit/s |   | 0.09 | 0.09 | 2.4 | 152.8

Petals on 14 heterogeneous servers across Europe and North America
Real world | 0.83 | 0.79 | 32.6 | 179.4

Petals on 3 servers, with one A100 each
1 Gbit/s | < 5 ms | 1.71 | 1.54 | 70.0 | 253.6

This means any user can run a larger private (Kobold Petals Inference Horde?) koboldcpp from one GPU server to another with 1 Gbit/s and find meaningful improvement to inference. It would be ideal if I could connect my home GPU instance to a private free Google colab t4 instance for larger, faster inference. Friends could start a private kobold petals horde.

If anyone else is interested in this use case for koboldcpp, please upvote this issue.

Petals supports llama2 today.

Kind regards,

B

**Comment by LostRuins** [comment]
You can definitely run a "private horde" cluster, since the AI horde repo is open source, so anyone can run their own private horde instance. What you're describing is "distributed inference" over multiple devices, which is not currently available for KoboldCpp.

Henk has actually managed to get koboldcpp running over colab - check out https://github.com/henk717/koboldcpp/blob/concedo/colab.ipynb

**Comment by mrdevolver** [comment]
> What you're describing is "distributed inference" over multiple devices, which is not currently available for KoboldCpp.

Even though this is in Issues section and not discussions, seeing "[Enhancement]" in the title and the last part of his post which says "If anyone else is interested in this use case for koboldcpp, please upvote this issue." makes me feel like the user is actually suggesting that KoboldCpp should support this distributed inference through that Petals project he linked to in his post.

I can't lie, I have to admit that like the idea of being able to play with 70B+ models when my own hardware can handle only 13B ones. Bigger models are always more capable, so if this ever was a thing in KoboldCpp, it would probably be one of my most favorite features. 😊
