### ISSUE TITLE
[BUG] (v1.3.8) - Inconsistent model selection behavior in GUI launcher.

### ISSUE THREAD

**Issue by SabinStargem** [LostRuins/koboldcpp#363]
I have no error logs for this one.  When using the load button to select my model, it sometimes only shows the Kobold profiles, not models.  That is all.

**Comment by LostRuins** [comment]
Do you have a screenshot? I don't really understand what you mean.

**Comment by SabinStargem** [comment]
I was being dumb.  When selecting models, all items in the model's folders will show up - shortcuts, the kobold.exe, kccps profiles, and so on.  So it can look like this:


![image](https://github.com/LostRuins/koboldcpp/assets/38871546/7dbbcba4-5cdc-40ae-a111-4e949b947743)


I am now giving the models their own folder.  Unfortunately, using the profile load button will direct itself to where the models are, if the browse model button was previously used to pick a model.
