### ISSUE TITLE
[BUG] (v1.3.8) -  layers.0.attention.wk.weight' has wrong shape; expected  8192 x  1024, got  8192 x  8192

### ISSUE THREAD

**Issue by SabinStargem** [LostRuins/koboldcpp#370]
I was trying to load up airoboros-65b-gpt4-2.0.ggmlv3.q5_K_M.bin, but got this error.  Here is the whole report.

> 
> ***
> Welcome to KoboldCpp - Version 1.38
> For command line arguments, please refer to --help
> ***
> Attempting to use OpenBLAS library for faster prompt ingestion. A compatible libopenblas will be required.
> Initializing dynamic library: koboldcpp_openblas.dll
> ==========
> Namespace(bantokens=None, blasbatchsize=512, blasthreads=5, contextsize=2048, debugmode=False, forceversion=0, gpulayers=0, highpriority=False, hordeconfig=None, host='', launch=True, lora=None, model=None, model_param='C:/KoboldCPP/airoboros-65b-gpt4-2.0.ggmlv3.q5_K_M.bin', noavx2=False, noblas=False, nommap=False, port=5001, port_param=5001, psutil_set_threads=False, ropeconfig=[0.0, 10000.0], skiplauncher=False, smartcontext=False, stream=False, tensor_split=None, threads=5, unbantokens=False, useclblast=None, usecublas=None, usemirostat=None, usemlock=False)
> ==========
> Loading model: C:\KoboldCPP\airoboros-65b-gpt4-2.0.ggmlv3.q5_K_M.bin
> [Threads: 5, BlasThreads: 5, SmartContext: False]
> 
> ---
> Identified as LLAMA model: (ver 5)
> Attempting to Load...
> ---
> Using automatic RoPE scaling (scale:1.000, base:10000.0)
> System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
> llama.cpp: loading model from C:\KoboldCPP\airoboros-65b-gpt4-2.0.ggmlv3.q5_K_M.bin
> llama_model_load_internal: Applying KCPP Patch for 70B model, setting GQA to 8
> llama_model_load_internal: warning: assuming 70B model based on GQA == 8
> llama_model_load_internal: format     = ggjt v3 (latest)
> llama_model_load_internal: n_vocab    = 32000
> llama_model_load_internal: n_ctx      = 2048
> llama_model_load_internal: n_embd     = 8192
> llama_model_load_internal: n_mult     = 5504
> llama_model_load_internal: n_head     = 64
> llama_model_load_internal: n_head_kv  = 8
> llama_model_load_internal: n_layer    = 80
> llama_model_load_internal: n_rot      = 128
> llama_model_load_internal: n_gqa      = 8
> llama_model_load_internal: rnorm_eps  = 5.0e-06
> llama_model_load_internal: n_ff       = 33024
> llama_model_load_internal: freq_base  = 10000.0
> llama_model_load_internal: freq_scale = 1
> llama_model_load_internal: ftype      = 17 (mostly Q5_K - Medium)
> llama_model_load_internal: model size = 70B
> llama_model_load_internal: ggml ctx size =    0.21 MB
> error loading model: llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  1024, got  8192 x  8192
> llama_load_model_from_file: failed to load model
> gpttype_load_model: error: failed to load model 'C:\KoboldCPP\airoboros-65b-gpt4-2.0.ggmlv3.q5_K_M.bin'
> Load Model OK: False
> Could not load model: C:\KoboldCPP\airoboros-65b-gpt4-2.0.ggmlv3.q5_K_M.bin
> 
> [process exited with code 3 (0x00000003)]

**Comment by LostRuins** [comment]
Thank for letting me know. This model was incorrectly detected as a LLAMA2 model. I will make a few adjustments to hopefully prevent this from happening.

**Comment by LostRuins** [comment]
Fixed. Please try the latest version 1.39

**Comment by Angela-BC** [comment]
Now deepnight-llama-2-70b-inst.ggmlv3.q4_K_M.bin gets detected as a llama 1 model in 1.39.1. Works fine in 1.39.

**Comment by Angela-BC** [comment]
Hopefully these kind of issues are gone when they finish the GGUF file format.

**Comment by LostRuins** [comment]
Yes it's a bit of a mess. I need to fix it :(

**Comment by LostRuins** [comment]
Apologies for the inconvenience. Please the v1.40
