### ISSUE TITLE
The repository is missing important libraries

### ISSUE THREAD

**Issue by Arty666** [LostRuins/koboldcpp#376]
Bat requires files like:
koboldcpp_openblas.dll
koboldcpp_failsafe.dll
koboldcpp_noavx2.dll
koboldcpp_clblast.dll
The files are not in the repository, where are they?

**Comment by askmyteapot** [comment]
https://github.com/LostRuins/koboldcpp/tree/concedo_experimental#compiling-on-windows

You have to compile them yourself. If you dont feel comfortable doing that, just download the release version. 
https://github.com/LostRuins/koboldcpp/releases/download/v1.39.1/koboldcpp.exe

**Comment by askmyteapot** [comment]
Also, i highly recommend reading the Readme or Wiki (https://github.com/LostRuins/koboldcpp/wiki) before asking questions.
