### ISSUE TITLE
1.39.1 (light and cuda) doesn't open 70b llama2 models

### ISSUE THREAD

**Issue by kex243** [LostRuins/koboldcpp#377]
llama-2-70b-guanaco-qlora.ggmlv3.q2_K, upstage-llama-2-70b-instruct-v2.ggmlv3.q2_K, (all 70b llama2) were working with 1.38.1
Other models work fine.

System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from C:\nf\deepnight-llama-2-70b-inst.ggmlv3.q2_K.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 4096
llama_model_load_internal: n_embd     = 8192
llama_model_load_internal: n_mult     = 7168
llama_model_load_internal: n_head     = 64
llama_model_load_internal: n_head_kv  = 64
llama_model_load_internal: n_layer    = 80
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 5.0e-06
llama_model_load_internal: n_ff       = 28672
llama_model_load_internal: freq_base  = 32000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 10 (mostly Q2_K)
llama_model_load_internal: model size = 65B
llama_model_load_internal: ggml ctx size =    0.21 MB
error loading model: llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  8192, got  8192 x  1024
llama_load_model_from_file: failed to load model
gpttype_load_model: error: failed to load model 'C:\nf\deepnight-llama-2-70b-inst.ggmlv3.q2_K.bin'
Load Model OK: False
Could not load model: C:\nf\deepnight-llama-2-70b-inst.ggmlv3.q2_K.bin
my pc contains 32gb ram if it is important, it had an opportunity to run q2 70b models.

**Comment by boi-led-egg** [comment]
Same here with airoboros-l2-70b-gpt4-m2.0.ggmlv3.q5_0.bin:

error loading model: llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  8192, got  8192 x  1024
llama_load_model_from_file: failed to load model

**Comment by boi-led-egg** [comment]
I did a little check, seems to be working just before commit [improve detection for 70B.](https://github.com/LostRuins/koboldcpp/commit/0e41b94f40e1d10893d6ac29c727482573ef1652) but doesn't work on that commit.

**Comment by kallewoof** [comment]
Reverting that change made it work for me as well.

**Comment by LostRuins** [comment]
Apologies for the inconvenience. Please try v1.40

**Comment by boi-led-egg** [comment]
Can confirm, works fine now. Thank you very much.
