### ISSUE TITLE
How to substitute username and AI in prompt? 

### ISSUE THREAD

**Issue by intulint** [LostRuins/koboldcpp#379]
Now I have to edit the entire text of the hint. I don’t understand if it’s possible or not to specify something like {username} here and it will be inserted into the hint while it is being read by the neural network. Take user and AI names from UI settings.

**Comment by LostRuins** [comment]
Just set your chat name/bot name in the settings before you load the character card.

**Comment by intulint** [comment]
@LostRuins If I just change my nickname and botname, then this will not change the already existing hint, the bot will respond according to the example of the dialogue, by the name that is indicated to it in the description of the person. 
It will turn out to be nonsense. 

If I load a previously saved session, the settings will be taken from there. Upload character card? If this is not a download from ready-made examples, from my save storys or from the site, then I don’t know how character cards are made.

The ability to take nicknames from the interface settings would be much more convenient. I saw something like this somewhere, in the prompt instead of names they put something like {username} and {botname}. 

As I understand it, there is no way to pull out the names from the settings in a similar way?

**Comment by LostRuins** [comment]
Yeah that is what Tavern does. I may consider adding variables like that in future, but currently kobold doesnt support it

**Comment by intulint** [comment]
@LostRuins  Thanks for your answers
