### ISSUE TITLE
[User] Insert summary of your issue or enhancement..

### ISSUE THREAD

**Issue by KogasaLover22** [LostRuins/koboldcpp#383]
# Expected Behavior

Terminal and launcher open, I select model using launcher, launcher closes and terminal stays open

# Current Behavior

Terminal and launcher open, I select model using launcher, launcher closes and so does the terminal, meaning the program simply closed.

This occurs with both pygmalion-6b-v3-ggml-ggjt-q4_0.bin and pygmalion-6b-v3-q4_0.bin

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

CPU: AMD FX(tm)-6300
GPU: AMD Radeon (tm) R9 390 Series

* Operating System

using windows

**Comment by LostRuins** [comment]
Is it a crash? If not, this should not be a problem. Is the terminal blank when it remains open? Do you see text being output?
