### ISSUE TITLE
[User] KoboldCPP with Multi AMD GPUs?

### ISSUE THREAD

**Issue by mattiasghodsian** [LostRuins/koboldcpp#384]
The documentation only mentions NVIDIA GPUs specifically to run models cross multi GPUS. Is it possible to use KoboldCPP with Multi AMD GPUs? Will it work with CLblast ?

**Comment by LostRuins** [comment]
Not currently, for AMD via CLBlast only 1 GPU is supported, which can be selected at runtime

**Comment by mattiasghodsian** [comment]
Any info when this will be available ?

**Comment by LostRuins** [comment]
probably not unless someone implements it for clblast. You can try this rocm fork: https://github.com/YellowRoseCx/koboldcpp-rocm
