### ISSUE TITLE
When editing response, reprocessing prompt length varies randomly

### ISSUE THREAD

**Issue by ThatDocBoi** [LostRuins/koboldcpp#385]
Koboldcpp V 1.40.1, CUDA, smart context on, LLAMA 2 based model, 4096 context length, 2048 generation length, QMM on, low VRAM on.

Sometimes when I edit a sentence in the end of the generation, it'll reprocess 8-20 tokens. However, sometimes editing the same amount will make it process hundreds and even more tokens even though I only altered the last sentence or 2. I couldn't find anything about it in the wiki. How can I make it so that it doesn't reprocess large chunks and just the tokens modified in the ending? (Obviously if I edit something at begging of the text it'll have to process from there to the last part, but I'm talking about just the last sentence or 2).

**Comment by LostRuins** [comment]
If you send context longer than the max tokens, it will start trimming off the starting part, which can trigger a full reprocessing. Alternatively, it may also be triggered by author's note, modifying the story memory, or world info.

**Comment by ThatDocBoi** [comment]
Thanks for the response. I understand what you're saying, but I'm referring to the processing before the context reaches max tokens. What I mean is sometimes I'll add a word (not in memory/authors/world sections) at the very end to lets say an existing context of 1580 (out of max 2048) and it'll process the full thing or a few hundred and sometimes 8-10, and it's hard to tell when is when. Is there anywhere I can read up on how the prompt processed amount is determined?

**Comment by LostRuins** [comment]
You can determine the actual prompt sent by clicking on the "Last Request" button after generation is complete (bottom left corner) this will show exactly what context was sent to the AI.
