### ISSUE TITLE
[Question] Confused about how / why full BLAS processing happens

### ISSUE THREAD

**Issue by FitzWM** [LostRuins/koboldcpp#386]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

When under the max context I have set, I send a message to the bot, and KoboldCPP processes that message for a response, not the full context so far.

# Current Behavior

I'm using Airochornos 33B 5_K_M right now, but I've also encountered this issue with Chronos-Hermes 13B 5_K_M, as well as various LLaMA 2 models. I'm not even sure if it's a problem, or if I just don't know how the processing...process works. I'm using 4096 context pretty much all the time, with appropriate RoPE settings for LLaMA 1 and 2. I'm using SillyTavern's staging branch as my frontend.

The problem I'm having is that KoboldCPP / llama.cpp seems to process the full chat when I send new messages to it, but not always. Sometimes, it will just say `Processing Prompt [BLAS] (204 / 204 tokens)` or whatever, and just process that message, resulting in quick responses. A lot of the time, though, it appears to reprocess the whole chat, reading something like `Processing Prompt [BLAS] (2093 / 2093 tokens)`. BLAS still chunks through them pretty quickly at 1024 batch size, but it's obviously  still noticeably slower, especially as the chat grows toward the 4096 context limit.

My question is this: Is this supposed to happen? Does the bot just need to re-process the whole chat each time to make its responses make sense? But, if so, why only part of the time?

Also, how does smart context affect this? I tried setting my context size to 8192 and using smart context, and it was great for a while, but then it seemed to start reprocessing very often, as well.

Please excuse me if this is expected behavior and my expectations are just all wrong.

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

CPU: AMD 5800X (8 threads, 8 BLAS threads)
GPU: RTX 3080 Ti 12 GB
RAM: 64 GB DDR4-4000
SSD: WD_Black SN850

* Operating System, e.g. for Linux:

Windows 11 22621.2134

* SDK version, e.g. for Linux:

Python 3.10.6

**Comment by Vladonai** [comment]
I will add from myself that the model (Llama2-tuned, 4k context) after communication can forget what was in the prompt earlier, but if you reload the model it remembers. That is, the results of buffering and fresh loading are different.

**Comment by kalomaze** [comment]
> I'm using SillyTavern's staging branch as my frontend.
I wonder if this is a SillyTavern issue and not necessarily kobold.

**Comment by FitzWM** [comment]
> @FitzWM try increasing token padding in your formatting settings (start with 200)

Thanks! I'll give it a go.

**Comment by LostRuins** [comment]
@Cohee1207 that's not a bad idea, so something that you call that just returns the total number of tokens in a string will be good?

**Comment by LostRuins** [comment]
@Cohee1207 I've added a new endpoint, check out `/api/extra/tokencount`

you send it JSON prompt like so
`{"prompt":"Hello world"}`

and it returns you the exact number of tokens counted based on the tokenizer for that architecture. 
`{"value":100}`

I hope this works for you, let me know if there's any issues.
