### ISSUE TITLE
[User] Load config from kcpps during startup

### ISSUE THREAD

**Issue by poppeman** [LostRuins/koboldcpp#388]
Right now it's possible to save and load config files (.kcpps) using the GUI. It would be very practical if one could supply a kcpps as an command-line argument to koboldcpp.py during startup.

Something like `python koboldcpp.py config/my-config.kcpps` (but in a way that doesn't break compatibility).

**Comment by CorentinWicht** [comment]
I have looked everywhere but can't seem to find any information on this `.kcpps` format? 
When I press the "Save" button in the UI it offers to save a `.json` file:
![image](https://github.com/LostRuins/koboldcpp/assets/52161904/7b653f11-f88b-4f1d-bad6-a819e416f053)

Can I load a `.json` this file with the `--config` parameter?

**Comment by LostRuins** [comment]
The .kcpps file represets launcher configs such as number of layers, GPU settings, thread counts etc. You load it via the GUI launcher. 

![image](https://github.com/LostRuins/koboldcpp/assets/39025047/7365e6e5-36e8-4c22-a365-4c291e4f3ce7)


For the json saves they must be loaded via the UI after launching it.

**Comment by CorentinWicht** [comment]
> The .kcpps file represets launcher configs such as number of layers, GPU settings, thread counts etc. You load it via the GUI launcher.
> 
> ![image](https://user-images.githubusercontent.com/39025047/272605015-7365e6e5-36e8-4c22-a365-4c291e4f3ce7.png)
> 
> For the json saves they must be loaded via the UI after launching it.

Many thanks for your prompt reply.

Actually, I am running koboldAI Lite from command line on a Linux virtual machine which has no Graphical Interface, hence I cannot access the GUI launcher. Any way I can download the default .kcpps file to see who it is structured? 
Still I find it quite confusion that the parameters from the GUI launcher and the main GUI somehow overlap (e.g. "Unban Tokens") but the format of the files is not the same...
Best,
C.

**Comment by CorentinWicht** [comment]
> Here's an example config file, save it as a .kcpps file and you can load it with `--config`. The parameters match the ones used inside the argparse - for info run it with `--help`
> 
> ```
> {"model": null, "model_param": "E:/LLaMA/models/airoboros-l2-7b-2.2.1.Q4_K_S.gguf", "port": 5001, "port_param": 5001, "host": "", "launch": false, "lora": null, "config": null, "threads": 5, "blasthreads": null, "psutil_set_threads": false, "highpriority": false, "contextsize": 2048, "blasbatchsize": 512, "ropeconfig": [0.0, 10000.0], "stream": false, "smartcontext": false, "unbantokens": false, "bantokens": null, "usemirostat": null, "forceversion": 0, "nommap": false, "usemlock": false, "noavx2": false, "debugmode": false, "skiplauncher": false, "hordeconfig": null, "noblas": false, "useclblast": null, "usecublas": ["normal", "0", "mmq"], "gpulayers": 99, "tensor_split": null, "onready": "", "multiuser": true, "foreground": false}
> ```
Many thanks for the explanations!

> 
> Currently the WebUI is completely independent from the server, and thus has its own individual configurations (such as chat mode, story settings etc) that are not configurable from the server. Would it be possible for you to provide your users with the .json containing your desired settings, as a separate download link for them to load?
> 
> Remote save file loading is something I am considering, but have no immediate plans to add right now.

Very well, I wasn't aware of the distinction between the server and the WebUI. Unfortunately, I cannot provide them with a .json file as our institution has >1000 collaborators (often with short-term contracts)...
I will thus be waiting for your implementation of the remote save file loading, can you keep me updated in this thread?
Many thanks and best regards,
C.

**Comment by alicat22** [comment]
I would love it if the last used settings were saved. So if I reopened the GUI, it would use the last used settings instead of default.

I keep 99% of my settings the same, but change only 1 or two, so this would be a huge time saver, as I don't want to be having to "load" a setting every time or make dozens of different settings to load via the GUI or launch command.

**Comment by CorentinWicht** [comment]
> I would love it if the last used settings were saved. So if I reopened the GUI, it would use the last used settings instead of default.
> 
> I keep 99% of my settings the same, but change only 1 or two, so this would be a huge time saver, as I don't want to be having to "load" a setting every time or make dozens of different settings to load via the GUI or launch command.

As I suggested, being able to load the .json GUI config file when running koboldcpp from command line might also save you some time :)

**Comment by LostRuins** [comment]
Hi @CorentinWicht not sure if you're still following this project, but this feature has finally been added in 1.49. You can now specify a .json file which the server will host and all clients will download on launch with `--preloadstory`

**Comment by CorentinWicht** [comment]
> Hi @CorentinWicht not sure if you're still following this project, but this feature has finally been added in 1.49. You can now specify a .json file which the server will host and all clients will download on launch with `--preloadstory`

Hi @LostRuins many thanks for implementing the feature in 1.49, it works wonders !

Best wishes,
C.
