### ISSUE TITLE
Feature request: Connect to horde as worker

### ISSUE THREAD

**Issue by rondlite** [LostRuins/koboldcpp#39]
# Expected Behavior

using API-key and be able to turn on share with horde

# Current Behavior

option not there 

would love to be able to use as worker so koboldcpp becomes multi-user

**Comment by LostRuins** [comment]
There are no horde features directing in KoboldCpp. 

If you want to use models on the horde, you can use https://lite.koboldai.net

If you want to share it with the horde, you'll have to use the Horde Bridge here: https://github.com/db0/KoboldAI-Horde-Bridge

**Comment by rondlite** [comment]
I will have a look if it is feasable to integrate the horde bridge into hordecpp myself. currently running a private horde with united branch so got place to test easy

**Comment by rondlite** [comment]
Turns out that the horde bridge repo works with koboldcpp out of the box
