### ISSUE TITLE
[Enhancement] Auto GPU layers option

### ISSUE THREAD

**Issue by kalomaze** [LostRuins/koboldcpp#390]
A setting that automatically gauges available VRAM and compares it with the size of the model being loaded into memory and selects the 'safe max' would be a nice QoL feature for first time users. Currently available VRAM would be a good way to gauge it

**Comment by SabinStargem** [comment]
I definitely would like to reserve some VRAM for non-AI tasks.  4gb out of my 3060's 12gb would be enough to feed video and most of the games that I play.

**Comment by LostRuins** [comment]
It's hard to estimate how much VRAM exactly will be used since its also affected by current context - the best way is really to trial and error (you can see vram usage from task manager) and tweak the layers offloaded. And then you can save that as known good settings

**Comment by kalomaze** [comment]
Is there no way to gauge how much the context size has an impact and consider that when deciding the number? Is it non-linear or unpredictable in any fashion?

**Comment by VL4DST3R** [comment]
At the very least an automated script that tests this and reports back to the user the first valid amount it finds.

Something along the lines of loading the desired model and testing a prompt (to take into consideration the extra usage when using cublas and whatnot) and see if it generates properly, if not then reduce assigned layers by one and retry until it works.

This may actually be doable externally via a python script, but at this point it kinda defeats the purpose of having it part of the package.

**Comment by LostRuins** [comment]
There's a rudimentary layer estimator in recent versions. It's not very accurate though.

**Comment by LostRuins** [comment]
Open the model in the GUI, and it will show it when you select the file.

**Comment by VL4DST3R** [comment]
> I think a simple plaintext or .ini file with the MB/layer for each model would be an acceptable solution, comparing that to the GPU available memory would make it possible to somehow automate the correct amount.

If you are like me and rotate around a number of models with different sizes, you can just make a bat file with a menu selection and pre-populate it with all the desired settings for each model.

**Comment by marco-trovato** [comment]
> If you are like me and rotate around a number of models with different sizes, you can just make a bat file with a menu selection and pre-populate it with all the desired settings for each model. 

That sounds like an awesome solution! Would you be so kind to share the script here? I will try to adapt it to my situation, THANK YOU!!!

**Comment by LostRuins** [comment]
Update on this: The newest version 1.73 (at this time) now has reasonably good auto GPU layers estimation. Give it a try!
