### ISSUE TITLE
[ENHANCEMENT] (1.42.1+) --> 128k context.

### ISSUE THREAD

**Issue by SabinStargem** [LostRuins/koboldcpp#392]
Things are changing at a breakneck pace.  There is already a Llama 13b pytorch with 32k context.   I figure it would be appropriate to ask for compatibility to be added into Kobold, when time permits.

[Giraffe v2 - 13b 32k](https://huggingface.co/abacusai/Giraffe-v2-13b-32k)

**Comment by kalomaze** [comment]
How do they even test that these things work? Recaps? Doing numbered outputs like 1, 2, 3 etc and then asking it way later "repeat Line 20" or something? Insane

**Comment by SabinStargem** [comment]
In my case, I would use my entire world setting and quiz the AI about it.  "Who is the protagonist?"  "Between a harpy, mermaid, and a siren, which of them are considered to be human?"  "Describe character X",  and so on.   One of my character sheets is about 1,500+ context, and the lore for creatures is at least 8,000+ at this point.   I don't even have really detailed cities and cultures, rules and mechanics.

32k is the mildew at the bottom of a barrel, I suspect.

**Comment by Vladonai** [comment]
From a practical point of view, 4k contexts of models like Llama2 are a good intermediate result. The context is quickly processed on medium class computers and its size already allows to fill the communication with some depth. But even this size of context is not fully perceived by the model - the model "forgets" details, although there is a noticeable progress compared to Llama1 type models. But yes, I would like to see progress in context size - qualitative, not just quantitative.

**Comment by SabinStargem** [comment]
@Vladonai 
> But yes, I would like to see progress in context size - qualitative, not just quantitative.

You might want to check out Bhenrym's pytorches.  They got charts on their model repositories regarding how perplexity is affected by context size.  Models that go out of bounds get 50+ perplexity, but the 8k and 16k editions are less than 5.  Dunno if I can casually convert pytorch into GGML, otherwise I would take the latest Airophins out for a ride.

[Airophin v2 13b-PI-8k](https://huggingface.co/bhenrym14/airophin-v2-13b-PI-8k-fp16)

**Comment by LostRuins** [comment]
I will keep this in view for now, if it gains wider adoption i will figure something out. 32k is very hard for me to test locally, even 16k takes forever to run. And i dont want to add something I cannot test.

**Comment by SabinStargem** [comment]
> I will keep this in view for now, if it gains wider adoption i will figure something out. 32k is very hard for me to test locally, even 16k takes forever to run. And i dont want to add something I cannot test.

There has been other 32k models, for 7b.  The above 32k is notable for being a 13b.  Here is one of the 7b-32k models.  Hopefully, that would be small enough for you to work with.

[Llama 2 7b-32k GGML](https://huggingface.co/TheBloke/Llama-2-7B-32K-Instruct-GGML)

**Comment by digiwombat** [comment]
So... CodeLLaMa can scale out to 100k (they say).

😀 Just go ahead and update the title. What's the harm? How much do A100s cost?

**Comment by bennmann** [comment]
According to the Llama2 paper, context size can be scaled with some ROPE settings up to 100K with some perplexity that is usable.

Yet --contextsize and the GUI do not scale these values are limited much lower.

May the constraints be increased?

**Comment by SabinStargem** [comment]
Code Llama 34b potentially allows for 100,000 context.  Dunno if that is actually viable in practice.

**Comment by SabinStargem** [comment]
We now got a 7b 64k YARN...

[YARN L2-7b 64k](https://huggingface.co/TheBloke/Yarn-Llama-2-7B-64K-GGUF)
