### ISSUE TITLE
GGUF - Not printing code correctly (latest code llama)

### ISSUE THREAD

**Issue by PedzacyKapec** [LostRuins/koboldcpp#395]
Check out the lines:

root = Tk()
root.withdraw()

def convert():
 ▁▁ jfif_file_path, _ = filedialog.askopenfilename(initialdir=".", title="Select JFIF File", filetypes=(("JFIF Files", "*.jfif"), ("All files", "*.*"))))
 ▁▁ if not jfif_file_path:
 ▁▁▁▁▁▁ return None
 ▁▁ return str(jfif_file_path))
 ▁▁▁
if __name__ == "__main__":
 ▁▁ converted = convert()
 ▁▁ if not converted:
 ▁▁▁▁▁▁ print("No file selected")
 ▁▁▁▁▁▁ exit(1))
 ▁▁ else:
 ▁▁▁▁▁▁ print("Successfully converted file")
 ▁▁▁▁▁▁ exit(0))

**Comment by LostRuins** [comment]
That's more of a ui issue. It will display code correctly only in code blocks, in normal text indentation is stripped out. Try asking the AI to use markdown instead (and enable markdown)

**Comment by PedzacyKapec** [comment]
The markdown was enabled !

**Comment by LostRuins** [comment]
Please try again in the latest version - I have fixed a lot of whitespace handling and should be able to handle Code Indentations correctly now!
