### ISSUE TITLE
Another problem with codellama (13b this time) ggml 

### ISSUE THREAD

**Issue by PedzacyKapec** [LostRuins/koboldcpp#396]
﻿﻿write code in python to read btc price

Output: <pre>
<code>
import asyncio
from pytelegra.pyrogra import TelegramClient

api_id = 1234567890
api_hash = 'f2ebe3270c5d75e3d428e395'
client = TelegramClient('Session', api_id, api_hash)
client = TelegramClient(String session, int apiId, String apiHash),

async def main():
    # Get the channels you need
     Channel = await client.get_entity('')
      # send message to channel that your user will
                                       .sendMessage({'price': price}),
     # add callback for update chat
                                              .addCallback(updateChatCallback)))
   print(price))

async def updateChatCallback(_, __):
    pass

if __name__ == "__main__":
    with TelegramClient("user_session",
                                api_id, api_hash).connect() as user:
        loop = asyncio.get_event_loop()
        try:
            loop.run_until_complete(main())
        except Exception as e:
            print(str(e)))))))))
</code>
</pre>

Does this code look like smth that would read btc price ?
I tried it in another GUI AI app and it worked fine. Looks like kobold has some major problem with codellama models.

**Comment by LostRuins** [comment]
Code formatting and handling has been greatly improved in recent versions. Please try using the Scenario in Kobold Lite "Coding Assistant", and make sure markdown in enabled for best results.
