### ISSUE TITLE
Enabling AVX512?

### ISSUE THREAD

**Issue by Z95070** [LostRuins/koboldcpp#397]
I've recently thrown together a workstation to use with koboldcpp, and despite the Xeon 2175 inside supporting it, AVX512 is still zeroed out as unused once the program starts. Is there a toggle or command line I'm missing, or does it normally kick on automatically?

I'm using the current premade 1.41 beta .exe from the release page, if that matters.

**Comment by mirek190** [comment]
I tested avx512 vs avx2 ( ryzen 7950x3d ) - no performance deference ...

**Comment by Z95070** [comment]
Ahh, if there's no meaningful difference on or off, I suppose it isn't much of an issue then.
