### ISSUE TITLE
Incompatable lOpenCL

### ISSUE THREAD

**Issue by theheraldofstory** [LostRuins/koboldcpp#401]
Running Opensuse 

 getting this output when building make LLAMA_OPENBLAS=1 LLAMA_CLBLAST=1 LLAMA_CUBLAS=1

I llama.cpp build info: 
I UNAME_S:  Linux
I UNAME_P:  x86_64
I UNAME_M:  x86_64
I CFLAGS:   -I.              -I./include -I./include/CL -I./otherarch -I./otherarch/tools -Ofast -DNDEBUG -std=c11   -fPIC -DGGML_USE_K_QUANTS -pthread -s -pthread -march=native -mtune=native
I CXXFLAGS: -I. -I./common -I./include -I./include/CL -I./otherarch -I./otherarch/tools -Ofast -DNDEBUG -std=c++11 -fPIC -DGGML_USE_K_QUANTS -pthread -s -Wno-multichar -Wno-write-strings -pthread
I LDFLAGS:  
I CC:       cc (SUSE Linux) 13.2.1 20230803 [revision cc279d6c64562f05019e1d12d0d825f9391b5553]
I CXX:      g++ (SUSE Linux) 13.2.1 20230803 [revision cc279d6c64562f05019e1d12d0d825f9391b5553]

g++ -I. -I./common -I./include -I./include/CL -I./otherarch -I./otherarch/tools -Ofast -DNDEBUG -std=c++11 -fPIC -DGGML_USE_K_QUANTS -pthread -s -Wno-multichar -Wno-write-strings -pthread  ggml.o ggml_v2.o ggml_v1.o expose.o common.o gpttype_adapter.o k_quants.o ggml-alloc.o -shared -o koboldcpp_default.so 
g++ -I. -I./common -I./include -I./include/CL -I./otherarch -I./otherarch/tools -Ofast -DNDEBUG -std=c++11 -fPIC -DGGML_USE_K_QUANTS -pthread -s -Wno-multichar -Wno-write-strings -pthread ggml_failsafe.o ggml_v2_failsafe.o ggml_v1_failsafe.o expose.o common.o gpttype_adapter_failsafe.o k_quants_failsafe.o ggml-alloc.o -shared -o koboldcpp_failsafe.so 
g++ -I. -I./common -I./include -I./include/CL -I./otherarch -I./otherarch/tools -Ofast -DNDEBUG -std=c++11 -fPIC -DGGML_USE_K_QUANTS -pthread -s -Wno-multichar -Wno-write-strings -pthread ggml_openblas.o ggml_v2_openblas.o ggml_v1.o expose.o common.o gpttype_adapter.o k_quants.o ggml-alloc.o  -lopenblas -shared -o koboldcpp_openblas.so 
g++ -I. -I./common -I./include -I./include/CL -I./otherarch -I./otherarch/tools -Ofast -DNDEBUG -std=c++11 -fPIC -DGGML_USE_K_QUANTS -pthread -s -Wno-multichar -Wno-write-strings -pthread ggml_noavx2.o ggml_v2_noavx2.o ggml_v1_failsafe.o expose.o common.o gpttype_adapter_failsafe.o k_quants_noavx2.o ggml-alloc.o  -lopenblas -shared -o koboldcpp_noavx2.so 
g++ -I. -I./common -I./include -I./include/CL -I./otherarch -I./otherarch/tools -Ofast -DNDEBUG -std=c++11 -fPIC -DGGML_USE_K_QUANTS -pthread -s -Wno-multichar -Wno-write-strings -pthread ggml_clblast.o ggml_v2_clblast.o ggml_v1.o expose.o common.o gpttype_adapter_clblast.o ggml-opencl.o ggml_v2-opencl.o ggml_v2-opencl-legacy.o k_quants.o ggml-alloc.o -lclblast -lOpenCL  -lopenblas -shared -o koboldcpp_clblast.so 
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: cannot find -lclblast: No such file or directory
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: skipping incompatible /lib/libOpenCL.so when searching for -lOpenCL
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: skipping incompatible /usr/lib/libOpenCL.so when searching for -lOpenCL
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: cannot find -lOpenCL: No such file or directory
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: skipping incompatible /lib/libOpenCL.so when searching for -lOpenCL
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: skipping incompatible /usr/lib/libOpenCL.so when searching for -lOpenCL
collect2: error: ld returned 1 exit status
make: *** [Makefile:393: koboldcpp_clblast] Error 1

**Comment by LostRuins** [comment]
Did you install clblast from your package manager?

**Comment by theheraldofstory** [comment]
my package manager doesn't have clblast but does provide all the files from other packages that are installed

**Comment by theheraldofstory** [comment]
I found the problem. some how /usr/lib64/libOpenCL.so was linked to a file that doesn't exist. running ln -s /usr/lib64/libOpenCL.so.1 /usr/lib64/libOpenCL.so fixed it

**Comment by LostRuins** [comment]
Awesome, hopefully this information helps other linux users in future.

**Comment by theheraldofstory** [comment]
as a side note along similar lines on opensuse you also need to manually link libclblast.so by running ln -s /usr/local/lib64/libclblast.so /usr/lib/libclblast.so 
and it seems you also have to manually link libclblast.so.1 but I so far haven't found out where to it's not /usr/lib
