### ISSUE TITLE
[Bug] (Kobold v1.4.1) -> Detected unimplemented GGUF Arch, for Airoboros 2.1 L2-70b

### ISSUE THREAD

**Issue by SabinStargem** [LostRuins/koboldcpp#406]
This is the version of Airo 2.1 70b with the updated weights.  I am guessing it uses GGUF v2, which apparently has 64-bit something or another.

> ***
> Welcome to KoboldCpp - Version 1.41
> For command line arguments, please refer to --help
> ***
> Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
> Initializing dynamic library: koboldcpp_cublas.dll
> ==========
> Overriding thread count, using 6 threads instead.
> Namespace(bantokens=None, blasbatchsize=2048, blasthreads=6, config=None, contextsize=4096, debugmode=False, forceversion=0, gpulayers=5, highpriority=False, hordeconfig=None, host='', launch=True, lora=None, model=None, model_param='C:/KoboldCPP/Models/airoboros-l2-70b-2.1.Q5_K_M.gguf', noavx2=False, noblas=False, nommap=False, port=5001, port_param=5001, psutil_set_threads=True, ropeconfig=[0.0, 10000.0], skiplauncher=False, smartcontext=False, stream=False, tensor_split=None, threads=6, unbantokens=False, useclblast=None, usecublas=['lowvram', '0', 'mmq'], usemirostat=None, usemlock=True)
> ==========
> Loading model: C:\KoboldCPP\Models\airoboros-l2-70b-2.1.Q5_K_M.gguf
> [Threads: 6, BlasThreads: 6, SmartContext: False]
> 
> ERROR: Detected unimplemented GGUF Arch:
> 
> ---
> Identified as LLAMA model: (ver 6)
> Attempting to Load...
> ---
> Using automatic RoPE scaling (scale:1.000, base:32000.0)
> System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
> Traceback (most recent call last):
>   File "koboldcpp.py", line 1786, in <module>
>   File "koboldcpp.py", line 1698, in main
>   File "koboldcpp.py", line 240, in load_model
> OSError: exception: access violation writing 0x000001DF9D217000
> [246744] Failed to execute script 'koboldcpp' due to unhandled exception!
> 
> [process exited with code 3221226356 (0xc0000374)]

**Comment by LostRuins** [comment]
Yes GGUF (the new format) recently upgraded to GGUFv2 (even newer format) so I will have to merge their changes in too

**Comment by LostRuins** [comment]
Hi, this should be fixed in v1.42.
