### ISSUE TITLE
[Oversight] (Kobold v1.42) -> Settings panel too low.

### ISSUE THREAD

**Issue by SabinStargem** [LostRuins/koboldcpp#408]
The panel is now a bit on the low side, that the apply and cancel buttons are below the task bar.

![image](https://github.com/LostRuins/koboldcpp/assets/38871546/dea0e338-6895-4272-890a-5999ec5b9960)

**Comment by LostRuins** [comment]
Good catch, let me think of a fix

**Comment by LostRuins** [comment]
Alright the UI has been completely reworked and should be much neater now.
