### ISSUE TITLE
Invalide pointer with GGUF and clBLAST (Koboldcpp 1.42.1)

### ISSUE THREAD

**Issue by Thangzy** [LostRuins/koboldcpp#409]
When using GGUF model if I use flags --useclblast 0 0 --gpulayers 15 (which I normally use with GGML model and works fine with them) will not work and prints
` ................................................................free(): invalid pointer`

Then it stays like that and my system freezes during 10 to 20 seconds and comes back to normal then freezes again as long as the python process is running.

If I remove those two flags the model loads perfectly.

I'm on Manjaro, did the usual setup when new version come out.
-Delete Koboldcpp folder
-Clone from git
-cd koboldcpp
-make LLAMA_OPENBLAS=1 LLAMA_CLBLAST=1

OS: Manjaro Linux x86_64 
Kernel: 6.1.49-1-MANJARO 
CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz 
GPU: AMD ATI Radeon R9 FURY / NANO Series 
Memory: 32019MiB

**Comment by jacob1218** [comment]
even without CLBlast, no GGUF inference works on Windows either, at least for me. tried several GGUF models and got the same access violation. GGML models work however

**Comment by LostRuins** [comment]
@Thangzy @jacob1218 can you point me to the GGUF models you were using so I can try?

**Comment by Thangzy** [comment]
Tried those two, same result:
[Kimiko](https://huggingface.co/TheBloke/Kimiko-v2-13B-GGUF)
[Mythical Destroyer V2](https://huggingface.co/TheBloke/Mythical-Destroyer-V2-L2-13B-GGUF)

**Comment by jacob1218** [comment]
Kimiko was the one i tried. Also tried one i made myself for Falcon 40B and that didn't work either, same error

**Comment by LostRuins** [comment]
Tried both models you linked and they work fine for me. Does it work with gpulayers set to 0?

**Comment by Thangzy** [comment]
I found where the issue is.

The main command was this one:
`python koboldcpp/koboldcpp.py Downloads/kimiko-v2-13b.Q6_K.gguf --threads 8 --useclblast 0 0 --gpulayers 15 --stream --nommap --unbantokens --contextsize 4096 --ropeconfig 0.5`
And gave me this output:
` ................................................................free(): invalid pointer`

When removing `--useclblast 0 0 --gpulayers 15` -> works
When changing `--gpulayers` from 1 to 15 values -> don't works
When changing `--useclblast` values -> dont works, no gpu available

So I started removing all flags and tested one by one.
At the end it seems `--nommap` is giving me the error because when it's set I get the error above but if I load the model without that flag it works.

So apparently either I have `--useclblast 0 0 --gpulayers 15` or `--nommap` but both of them together don't work.

**Comment by LostRuins** [comment]
Nice, thanks for the feedback and glad you caught the issue. I'll take a closer look soon but if anyone else has issues, hope this helps.

**Comment by Thangzy** [comment]
Did some more testing, still with GGUF model.

Got the same problem on Windows 11 (same hardware) and the same fix works on it too.

Also tested using `--useclblast 0 0` with `--nommap` without offloading to VRAM and it works.

So in final there is something happening between flags `--gpulayers` and `--nommap`.

Thanks for your work !

**Comment by frontenbrecher** [comment]
confirmed, using nommap leads to exit (no printed error for me).

koboldcpp.exe --model mythomax-l2-13b.ggmlv3.q4_K_S.gguf --blasbatchsize 2048 --contextsize 4096 --highpriority --gpulayers 28 --ropeconfig 1.0 10000 --unbantokens --useclblast 0 0 --usemirostat 2 5.0 0.1 

works, but adding --nommap parameter does not.

**Comment by d000b** [comment]
[Llama-2-70B-Chat-GGML](https://huggingface.co/TheBloke/Llama-2-70B-Chat-GGML/blob/main/llama-2-70b-chat.ggmlv3.q5_K_M.bin)
All combinations of options when testing variants in the GUI were reduced to "model not found". Is it a problem of the model itself, its coding (type) or is there a chance that kobold does not accept the ggmlv3 format? 
[llama-70b-low-16.kcpps.txt](https://github.com/LostRuins/koboldcpp/files/12803702/llama-70b-low-16.kcpps.txt)
The approximate settings are these, they have been used as defaults for other ggml encoding models. During variant testing, I changed flag combinations as well as token size values.

**Comment by LostRuins** [comment]
Seems like you didn't select the filename correctly. In your settings, the file was named `E:/Leaks/LLama-2-70B-chat/llama-2-70b-chat.ggmlv3.q5_K_M.binv3.q5_K_M.bin` looks like the name was duplicated?
