### ISSUE TITLE
Adding flake.nix support.

### ISSUE THREAD

**Issue by hakan-demirli** [LostRuins/koboldcpp#410]
[Nix](https://nixos.org/) offers a reproducible build environment. I have compiled koboldcpp on Ubuntu and Arch before. It was always a chore especially when I had CUDA version dependencies conflicting with other projects. So, I wonder if  you can add flake.nix to streamline the build process?

This is the flake I am using to install all dependencies. I have successfully compiled the project on both Ubuntu, Nixos and Arch. Nix claims it should also work on Mac and WSL2 but I haven't tested.
```nix
{
  description = "Kobold cpp flake.";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {
        inherit system;
        config.allowUnfree = true;
        config.cudaSupport = true;
        config.cudaVersion = "12";
      };
    in
    {
      devShells.${system}.default = pkgs.mkShell {
        buildInputs = with pkgs; [
          pkgs.bashInteractive

          (python311.withPackages (ps: with ps; [ tkinter ]))

          cudaPackages.cudnn
          cudaPackages.cudatoolkit
          cudaPackages.cuda_nvcc
          pkgs.cudaPackages.libcublas
          pkgs.clblast
          pkgs.openblas
          pkgs.clblast
        ];

        shellHook = ''
          export LD_LIBRARY_PATH="${pkgs.linuxPackages.nvidia_x11}/lib"
        '';
      };
    };
}
```
There are no auto build targets, called derivations in nix. I run `nix develop` and `make <flags> -j16`. If it is something you are interested in I can write a proper nix flake which automatically compiles based on host CPU architecture.

**Comment by LostRuins** [comment]
I am not familiar with nix, that's why I removed the nix files from upstream as I don't know to to maintain it. However if you'd like to send a PR and it does not conflict with other build processes, I would be happy to merge it.

**Comment by hakan-demirli** [comment]
I see, I understand the maintenance problem. I think adding extra build tools without a maintainer would be a disservice to community and I don't think I can maintain them in the long term. The upstream flakes look quite self explanatory. Anyone who wants to use them in koboldcpp can extend them easily.

**Comment by FlameFlag** [comment]
If anyone stumbles upon this issue in the future, koboldcpp is already in nixpkgs and can be installed by adding `koboldcpp` to `environment.systemPackages`.

You can find the nix file for koboldcpp here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/ko/koboldcpp/package.nix

As of this writing, CUDA support is enabled if `config.cudaSupport` is `true`. OpenBLAS and CLBlast are enabled by default on Linux. Metal is enabled by default on macOS if you have an Apple Silicon.

To override these options, please read the following nix pill: [Nixpkgs Overriding Packages](https://nixos.org/guides/nix-pills/17-nixpkgs-overriding-packages#overriding-nixpkgs-packages)

PR Reference: [Nixpkgs PR #314450](https://github.com/NixOS/nixpkgs/pull/314450)
