### ISSUE TITLE
[Enhancement] better Jupyter notebook compatibility without the use of 3rd party tunnels

### ISSUE THREAD

**Issue by bennmann** [LostRuins/koboldcpp#415]
ngrok and cloudflare are not always free and timely to create tunnels for Colab notebooks, which increases the barrier to entry for larger models that can run quantized on Colab free t4 instances.

It would be good to add a few lines into koboldcpp.py to allow notebooks the ability to render the local page within the jupyter notebook

Some of the updates lines or arguments within koboldcpp.py might look like this:

perser.add_argument("--jupyter_ipython_colab_notebooks
asyncio.run(from IPython.display import IFrame ; IFrame(src='http://127.0.0.1:5001', width=700, height=600))

the above method "should" display the normal lite GUI within a jupyter notebook (colab etc)

i am not sure of the best style guidelines or places to put this in a pull request, and i haven't explicitly tested this (it should be quick to test with small models). i have noticed that many of the colabs throughout wikis and discord do not function for me at this time because the tunnel services are very slow or require a 3rd party login.

**Comment by LostRuins** [comment]
If you're trying to run a model on colab, this will not work, since the IP 127.0.0.1 is a loopback IP and only references the same device that the server is running on. If you want a simple solution to running koboldcpp on colab, there's already an existing notebook you can check out, https://github.com/LostRuins/koboldcpp/blob/concedo/colab.ipynb

**Comment by bennmann** [comment]
> If you're trying to run a model on colab, this will not work, since the IP 127.0.0.1 is a loopback IP and only references the same device that the server is running on. If you want a simple solution to running koboldcpp on colab, there's already an existing notebook you can check out, https://github.com/LostRuins/koboldcpp/blob/concedo/colab.ipynb

I understand this method uses a 3rd party VPN/TLS connection. It would be good to have a non-3rd party way

**Comment by bennmann** [comment]
https://github.com/LostRuins/koboldcpp/pull/431/commits/f0ab790e8fea6510effbcc88e3b653aa5b4e8a42 semi-related
https://github.com/LostRuins/koboldcpp/tree/v1.44 --onready flag added to arg launchers, haven't gotten it to work yet with colab, but it's a great addition that "should" allow a colab instance to launch an iframe for GUI with the appropriate command (still unsuccessful on my part though)

**Comment by LostRuins** [comment]
Yeah let me know if you have any issues. It runs as a shell command, but for ease of use i'd recommend putting all your code into a shell script or python file and then just doing something like `--onready "python setupstuff.py"`

for a quick test, you can see `--onready "echo hello world how are you"` which should print a line after the server starts.
