### ISSUE TITLE
Only symbols as generated output when using CUBLAS on Linux.

### ISSUE THREAD

**Issue by TomKraut** [LostRuins/koboldcpp#420]
# Expected Behavior

Generated output with CUBLAS should be similar or the same to using CPU inference.

# Current Behavior

Output generated with CUBLAS is garbled.

# Environment and Context

Using a custom built docker image with nvidia/cuda:11.8.0-devel-ubuntu20.04 as base.
Python version is 3.10.
koboldcpp command line is: koboldcpp.py --stream --smartcontex --contextsize 4096 --model /app/models/airoboros-c34b-2.1.Q6_K.gguf --port 5001 --threads 30 --blasbatchsize 512 --usemlock --gpulayers 83

Ubuntu 22.04 (should not be relevant, as koboldcpp is containerized)
2x 3090, AMD Epyc 7551p, 128GB RAM

# Failure Information

I am trying to upgrade to the latest version of koboldcpp to be able to run GGUF models. I was using noneabove1182's docker container, but it has not yet been updated. 

Building kobodcpp with "make -j 16 LLAMA_OPENBLAS=1 LLAMA_CUBLAS=1" is successful. I can load the model and the web UI. When I enter a prompt, the response is completely garbled. Example:

Prompt: The quick brown fox 
Output:
The quick brown fox
jdS,E0qdf[TFi+:tCkNB<SV LiCl.

When I run the container without --usecublas, the output is fine:

Prompt: The quick brown fox
Output:
The quick brown fox
Jumped over the fence,
In a rhythmic dance.
To the music of night,
Underneath the stars' light.
(..... it continues until 100 tokens have been generated)

Are there any known issues with CUDA support on Linux right now? I know that this is something of an edge case, not only Linux but also Docker, but if there are known bugs I will just wait instead of going through the trouble of testing hundreds of combinations of CUDA, OS, different hardware etc.

It still works with the docker container from noneabove1182, but that is too old to support GGUF.

# Steps to Reproduce

Build koboldcpp with CUBLAS on Linux and load a model (I tested with airoboros-c34b-2.1.Q6_K.gguf, other models show the same behavior). Use parameter --usecublas. 
Connect via web UI. Enter a prompt, for example 'The quick brown fox ' and click submit.

**Comment by TomKraut** [comment]
Quick update: using --gpulayers 0, the output is fine. So it seems to be a problem with generation, not BLAS?

**Comment by LostRuins** [comment]
Can you try `--usecublas mmq`

**Comment by LostRuins** [comment]
Also what is the displayed value of n_gqa when launching

**Comment by TomKraut** [comment]
`llm_load_print_meta: n_gqa          = 8`

Unfortunately, using --usecublas mmq did not seem to do anything.

**Comment by TomKraut** [comment]
Okay, I rebuilt the container with different, older versions. All of them had the same problem, so it seems to be some issue with my environment or the image I am basing this on. This is not an issue of koboldcpp itself.

I would still be grateful for any advice from someone who has successfully built koboldcpp with cublas support in Linux.

**Comment by TomKraut** [comment]
So, it turned out that the build did not succeed, even though a container was created.

For someone finding this down the road: 

First, do not make my mistake and try to build using make. Use cmake if you can. If you cannot, replace `NVCCFLAGS += -arch=native` in the makefile with whatever is right for your system. `native` is invalid.

Second, even though my CUBLAS build did not succeed, there was no indication that something was wrong when loading koboldcpp. Everything worked, except that whatever layer should have been executed on GPU did not put out anything. That resulted in completely useless output when 100% offloading, completely normal output when 0% offloading, and a spectrum of worse and worse nonsense in between, depending on the split between GPU and CPU.

**Comment by LostRuins** [comment]
Try export the ENV value CUDA_DOCKER_ARCH=all during the docker build
