### ISSUE TITLE
possible de/quant optimization.

### ISSUE THREAD

**Issue by Swight1423** [LostRuins/koboldcpp#425]
think I found a potential quant optimization but there is a possibility for it to be worse instead of better depending on the model and this is untested got this much by reading code on github. 

for 4_0 and 5_0 quants 
if d=0 then dequant =0 
for 4_1 and 5_1 quants
if d=0 the dequant = min.

the above could also be used to optimize the current quant and dequant calculations if the below part didn't work out.

so if we store if d=0 for **ALL** quant groups of the model in a bitarray(this is where we lose ground if there isn't enough to compress)
for 4_0 and 5_0 quants
d=0 bitarray is all we need to store for d=0 quant groups
for 4_1 and 5_1 quants
 d=0 bitarray and the min is all we need to store for the d=0  quant groups

a processing cost would be the need to do a pop count on the d=0 bitarray for every random access to determine the correct memory location of each group due to variable size. how well this works depends heavily on percentage of quant groups with d=0. think would possibly see ram/disk space savings starting at around 1%ish of quant groups with d=0 if using 4_0. I do not know how common models are that meet the 1%ish threshold. may work for other quants but I haven't looked into them sufficiently.

for models with lower than 1% of quant groups with d=0 it may be beneficial to store d normally instead of in the bitarray if you are expecting to access it sequentially since you could just check if d=0 to determine memory position of the next value and you could still generate the bitarray if needed.

**Comment by LostRuins** [comment]
For new improvements to quantization formats you should suggest upstream in llama.cpp, koboldcpp will inherit support from there
