### ISSUE TITLE
Llama-2-Chat Instruct Template

### ISSUE THREAD

**Issue by chigkim** [LostRuins/koboldcpp#428]
Can we have more advanced template for instruct?
For example, in order to make koboldcpp to follow the Llama-2 instruct template?

```
<s>[INST] <<SYS>>
{your_system_message}
<</SYS>>

{user_message_1} [/INST] {llama_message_1} </s><s>[INST] {user_message_2} [/INST] {llama_message_2} </s>...
```

Thanks~

**Comment by LostRuins** [comment]
Try this:

```
<s>[INST] <<SYS>>
{your_system_message}
<</SYS>>[/INST]
```

put the above in Memory

set instruct start tag to `[INST]` and instruct end tag to `[/INST]`

see how well that works?

**Comment by chigkim** [comment]
Not exactly. Looks like better templating system is needed.

**Comment by LostRuins** [comment]
How so? Is the "LLAMA2" template in Lite not working for you?
