### ISSUE TITLE
Location for Scenarios?

### ISSUE THREAD

**Issue by chigkim** [LostRuins/koboldcpp#432]
Where are stock files for Scenarios located?

**Comment by LostRuins** [comment]
Embedded Inside Lite itself

**Comment by chigkim** [comment]
Is there a way to edit it?

**Comment by LostRuins** [comment]
You have to modify the source code of lite.

https://github.com/LostRuins/lite.koboldai.net

is there any reason why you would want this? You can easily save your scenario to a .json file and just drag+drop it in to load it anytime.

**Comment by chigkim** [comment]
Can you save stock Scenarios as json, modify, and load  in future session?

**Comment by LostRuins** [comment]
Yes you can! They work like normal stories after loading. You can modify and save them and reload them any time.
