### ISSUE TITLE
text in the output after a new line don't get recognized in New Chat Scenario.

### ISSUE THREAD

**Issue by Abdalnablse10** [LostRuins/koboldcpp#442]
Output in terminal:  Well, if we look at our world today, it's a very different place to where it was in the 1800s.
During this time period, humans were struggling to colonize the planet. The population density was much higher with more people per square mile and many cities and small towns could be found throughout the country. But as technology improved and the internet became accessible, things like self-driving cars, high-definition TV, and digital cameras were becoming standard components of all manner of electronic devices

output in browser: Well, if we look at our world today, it's a very different place to where it was in the 1800s.

**Comment by Ar57m** [comment]
just disable Trim Sentences in settings
