### ISSUE TITLE
Rename dialog continues on cancel

### ISSUE THREAD

**Issue by bill88t** [LostRuins/koboldcpp#444]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Press save with the rename prompt enabled.
Press cancel.
Save is cancelled.

# Current Behavior

Save continues with default name.

**Comment by LostRuins** [comment]
The rename is displayed as javascript popup/alert. Do you by any chance have some sort of popup blocker that disables this?

![image](https://github.com/LostRuins/koboldcpp/assets/39025047/7dbafd44-bd24-4ccb-b4b9-9724d9b95b1d)

**Comment by LostRuins** [comment]
In the next version I will convert it to a HTML input instead.

**Comment by bill88t** [comment]
I can see the dialog fine just fine.
I am talking about pressing "Cancel" in this dialog.

**Comment by LostRuins** [comment]
This is fixed now, the UI is part of the web ui rather than a popup. If the file name is left blank, it will not proceed to save.

**Comment by bill88t** [comment]
Many thanks! Closing issue!
