### ISSUE TITLE
[Bug] Multi-user feature can lead to a person receiving another person's reply

### ISSUE THREAD

**Issue by Dirky14** [LostRuins/koboldcpp#449]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Yes ] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [Yes] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [Yes] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [Yes] I reviewed the [Discussions]
https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

Using the multi-user feature, two people who uses the same koboldcpp backend should only have the reply for their character, and not another character's reply.

# Current Behavior

A person can have the reply of another person's character instead of their character if they share the same koboldcpp backend with the multi-user feature activated.

# Environment and Context

Please provide detailed information about your computer setup. This is important in case the issue is not reproducible except for under certain specific conditions.

* Physical (or virtual) hardware you are using, e.g. for Linux:

`$ lscpu`

* Operating System, e.g. for Linux:

`$ uname -a`

* SDK version, e.g. for Linux:

```
$ python3 --version
$ make --version
$ g++ --version
```

# Failure Information (for bugs)

Nothing in the logs really show that.

# Steps to Reproduce

1. Having two persons sharing the same koboldcpp backend (same IP) with multi-user feature activated.
2. step 2 (I suppose ?) Sending a request while another person is waiting for their reply.

**Comment by LostRuins** [comment]
What version are you using? There was an issue with this in 1.44.1 but it should be fixed in 1.44.2 - does it still happen?

**Comment by LostRuins** [comment]
This should be completely fixed as of version 1.45
