### ISSUE TITLE
Any chance for an OpenAI compatible API?

### ISSUE THREAD

**Issue by teddybear082** [LostRuins/koboldcpp#450]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- XI am running the latest code. Development is very rapid so there are no tagged versions as of now.
- X I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- X I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- X I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

It would be amazing to have the option of an openAI compatible API to use kobald.cpp with.  I know that it has its own API, but this would make it a drop in replacement for OpenAI’s Chat Completion methods.  I am helping with an open source mod for Skyrim to create AI NPCs (Mantella) and we’re trying to keep the code as streamlined as possible to call local models.

# Current Behavior

There is a great API but you have to write separate code to use it instead of using existing f OpenAI compatible code and methods.

# Environment and Context

N/A

* Physical (or virtual) hardware you are using, e.g. for Linux:

`$ lscpu`

* Operating System, e.g. for Linux:  Windows

`$ uname -a`

* SDK version, e.g. for Linux:

```
$ python3 --version
$ make --version
$ g++ --version
```

# Failure Information (for bugs)

N/A this is a feature request / inquiry.

**Comment by LostRuins** [comment]
will be added in next version

**Comment by teddybear082** [comment]
Wow that’s awesome thanks!!

**Comment by LostRuins** [comment]
This has been added as of version 1.45. You can access this OpenAI Compatible Completions API at `/api/extra/oai/v1/completions` though you're still recommended to use the Kobold API as it has many more settings.

**Comment by teddybear082** [comment]
Wow! that was quick thank you.  I will check it out!!

**Comment by teddybear082** [comment]
LostRuins, thank you again so much for your work!!! Given the template you created for suppoting the openai completions endpoint, I made a version of koboldcpp.py today that supports a chat/completions openAI format, and am going to work on a chat/completions stream=true format.  In testing with the code given on the openai website, the chat completions query returns the proper openai-compliant format.  If I can get the streaming part working too, can I just share my file here for your review and consideration for implementation in a future release?

**Comment by LostRuins** [comment]
Sure! Btw, after some feedback I am planning to move the endpoint from `/api/extra/oai/v1/completions` to just `/v1/completions` so just keep that in mind

**Comment by teddybear082** [comment]
Thank you!

**Comment by teddybear082** [comment]
Ok I have it all working now for OpenAI chat completions and OpenAI chat completions stream = true endpoints.  I will test some more tonight / tomorrow and if I don’t encounter any issues will post the proposed revised koboldcpp.py for your review here.

**Comment by teddybear082** [comment]
Closing issue now that this support has been merged for inclusion in a future version.  Thanks very much!!

**Comment by dlaliberte** [comment]
FYI, the URL for using openai api appears to me to be "http://localhost:5001/v1", to which "/chat/completions" is added.  I found this out after finally turning on the `--debug 1` option and noticing the URL that was being requested, which resulted in a 404 error, which was not handled very well by the openai library.  

I'm using autogen, by the way, and koboldcpp is one of the (perhaps only) systems that support the --noavx2 mode.  Thanks for making this available.

**Comment by LostRuins** [comment]
That's correct - the OpenAI endpoint is expected to be under the /v1/ route, same as the official (real) openai api
