### ISSUE TITLE
Navigate GUI with keyboard-only, without mouse?

### ISSUE THREAD

**Issue by aleksusklim** [LostRuins/koboldcpp#456]
Currently (v 1.44.2) it is not possible to meaningfully use GUI without mouse, right?
Tab key is switching between "Presets", "Threads" and "Model" input fields where Enter does not do anything.

Naturally, `Tab` key should jump between all of GUI elements, including tabs!

If this will require a lot of work (for example, if current GUI internals never accounted for keyboard focus and navigation), you can at least implement a poor-man solution: let `Enter` key to work as `Load` (load config) button, and then immediately `Launch` it after the user chooses the config to load.

File-selection dialog window is system one, so keyboard is functional there. No separate "Launch" action needed because after loading a config with keyboard – there is still no meaningful way to tweak it without mouse. So, just choose and run!
(Do not run if the user did not select a file, hitting Escape/cancel in file-selection window). There is no need to handle `Escape` in GUI, because `Alt+F4` will exit just fine.

**Comment by LostRuins** [comment]
The tab focusing is a limitation with customtkinter that I have not yet been able to solve. If you're limited to keyboard, may I suggest launching via command line instead?

**Comment by aleksusklim** [comment]
> may I suggest launching via command line instead?

Is there any command that will "ask for .kcpps config interactively to launch it", because that's what I'm de-facto requesting.
Something like `--config -`

Oh, I have a better idea! You know, user can change `.kcpps` file association to "Open with…" – and point it to `koboldcpp.exe`
But unfortunately, currently is thinks this is a model file, and prints `Could not load model` when provided with config as default argument (without explicit `--config` argument which is kinda hard to put there).

So you cannot drag-and-drop .kcpps config to program executable for it to run. I think it worth to check the extension of the "model" and if it is kcpps – then use it as config and not as the model.

Moreover, you can add to GUI the button to install file association for config files (using proper icon) as many other programs are doing.
It is as simple as writing proper values to Registry at `HKCU\Software\Classes\.kcpps\shell\open\command` (and several others), and then firing `SHChangeNotify(SHCNE_ASSOCCHANGED, SHCNF_IDLIST, NULL, NULL)` notification for Explorer.

If you have never worked with that, I can prepare a code sample in C that is doing this, if you want.

**Comment by LostRuins** [comment]
> If this will require a lot of work (for example, if current GUI internals never accounted for keyboard focus and navigation), you can at least implement a poor-man solution: let Enter key to work as Load (load config) button, and then immediately Launch it after the user chooses the config to load.

I've added one of your suggestion in the latest version, 1.45.
Now when you launch with `--skiplauncher` it will show a GUI popup where you can either select a model or a kcpps file. If you select a kcpps file it will proceed to load all settings as specified there.

**Comment by aleksusklim** [comment]
It works, but it still does not allow to "drag-and-drop" the config onto koboldcpp.exe, and thus it is impossible to use "Open with..." on .kcpps, or manual file associations (via properties of any .kcpps file in Explorer).

But now it is certainly possible to send a shortcut on you desktop, open its properties and type there --skiplauncher after koboldcpp.exe (`…\koboldcpp.exe" --skiplauncher`) and then this shortcut would open config loading dialog (at its last-used folder, which is nice!)

Still, you allow to pick there both: either a model file, or a config. Can you do the same with "one default argument" so that `Open with…` would work for configs too?

**Comment by LostRuins** [comment]
That should be possible. Will take a look

**Comment by aleksusklim** [comment]
As of 1.46.1, this works perfectly, the user can assign "open with" for .kcpps file types to run koboldcpp and load that config at start flawlessly. Thank you!

I'm not sure whether this Issue should be closed now, given its title.
