### ISSUE TITLE
The command line argument "--stream" needs to be saved!

### ISSUE THREAD

**Issue by Vladonai** [LostRuins/koboldcpp#457]
I use my own client and output tokens in stream mode. With the performance of my system, waiting for a full response generation is unbearable :) I think this is relevant for any third party client.

Update: Sorry, I was very frightened by such a drastic change :) But looking at my code I remembered that I'm accessing the stream via API. Sorry again.

**Comment by LostRuins** [comment]
Yeah that's the thing --stream was only ever needed for the Lite client, other users have already had full control. Hence it's deprecation
