### ISSUE TITLE
aesthetic UI breaks "" for code

### ISSUE THREAD

**Issue by UmbraAtrox** [LostRuins/koboldcpp#463]
With aesthetic UI it writes "" as “” but those don't work. Workaround is to simply disable aesthetic UI when copying code, but i think it would be better when within codeblocks "" didn't get changed. 

![image](https://github.com/LostRuins/koboldcpp/assets/33509547/0159420f-c4e8-4cdd-a1f4-33820e4c0d23)
![image](https://github.com/LostRuins/koboldcpp/assets/33509547/f21aa8bc-ddf1-4cb3-befe-1e753bba3bce)
![image](https://github.com/LostRuins/koboldcpp/assets/33509547/6872c9d8-2c4f-4c4e-9c5e-4347659409ac)
![image](https://github.com/LostRuins/koboldcpp/assets/33509547/ecf749d0-8522-4987-9aea-ff91f396b6e6)

**Comment by LostRuins** [comment]
seems like the code you were copying wasn't from a code block though? or does it happen in code blocks as well

**Comment by LostRuins** [comment]
can you try asking the AI to use markdown instead

**Comment by UmbraAtrox** [comment]
My bad, initially i had the issue when copying from code blocks but when i took the screenshots i didn't pay attention. Here is a screenshot showing wrong "" in a code block
![image](https://github.com/LostRuins/koboldcpp/assets/33509547/e33cd278-e44d-4190-af1e-bbff6e1e9d90)

What is markdown? When i asked the ai it returned this
![image](https://github.com/LostRuins/koboldcpp/assets/33509547/362acb71-cd52-4639-a0f7-1ae7f47e6268)

**Comment by LostRuins** [comment]
For code blocks, it will be fixed in the next version.

You can also disable fancy quotes by unchecking "style text" in the aesthetic settings (gear icon).
