### ISSUE TITLE
[openblas] Blasthreads issue

### ISSUE THREAD

**Issue by Nabokov86** [LostRuins/koboldcpp#465]
I recently noticed some changes in how the threads behave. Right now, when I set blasthreads to 1, it only uses one core for processing tokens below 35 without BLAS. Previously, the blasthreads parameters only affected the speed of BLAS processing. 

The current behavior is much slower on my system because I need to utilize all cores for processing without BLAS, and just one thread when BLAS is activated.

I am using latest concedo and concedo_experimental on linux.

**Comment by LostRuins** [comment]
Are you using openblas?

**Comment by Nabokov86** [comment]
Yes.

**Comment by LostRuins** [comment]
I've found the issue, can you pull my latest experimental and see if it works?

**Comment by Nabokov86** [comment]
Yep, it works correct now. Thanks!
