### ISSUE TITLE
Trying to access KoboldCPP remotely through Cloudflare tunnel results in error: 'Failed to connect to custom Kobold endpoint!'

### ISSUE THREAD

**Issue by YajuShinki** [LostRuins/koboldcpp#472]
# Expected Behavior

After launching KoboldCPP on the default port (5001) and then running `./Remote-Link.cmd`, I expected the website to load as normal, and allow me to generate text after loading the custom endpoint.

# Current Behavior

When connecting to the provided trycloudflare link, the website loads, but won't let me generate text, instead showing an error that reads:
```
Failed to connect to Custom Kobold Endpoint!
Please check if KoboldAI is running at the url: http://<trycloudflare link>:5000
```
I tried setting the port in the KoboldCCP config and the Remote-Link script to 5000, but the same error message still shows up.

# Environment and Context

OS: Arch Linux x86_64, version 6.5.4-arch2-1
CPU: AMD Ryzen 5 5600
GPU: NVIDIA GeForce RTX 3060 12GB
Memory: 16GB
Python version: 3.11.5

# Steps to Reproduce

1. `$ python koboldcpp.py`
2. Wait for KoboldCPP to fully load and show UI on local machine
3. `$ ./Remote-Link.cmd`
4. Connect to provided trycloudflare link from a different device

**Comment by LostRuins** [comment]
If you're using the <trycloudflare link> you dont need to add port 5000

**Comment by YajuShinki** [comment]
> If you're using the `<trycloudflare link>` you dont need to add port number

I've tried following the link both with and without the port number.

**Comment by LostRuins** [comment]
Maybe it's blocked by your firewall? What do you see when visiting the trycloudflare link? Even with no server, you should see bad gateway

**Comment by LostRuins** [comment]
Please try v1.48, which has the feature `--remotetunnel`

**Comment by YajuShinki** [comment]
The issue seems to have fixed itself without the `--remotetunnel` fix; it now works with all of the browsers I tested.

**Comment by LostRuins** [comment]
Cloudflare has been extremely unreliable the past week. If it fails, usually you can try again in a few minutes and it will work.
