### ISSUE TITLE
Automatic settings

### ISSUE THREAD

**Issue by intulint** [LostRuins/koboldcpp#476]
I just want an “Auto-tune” button that can be clicked after selecting context size and the model. 
Just a script that will run some tests and select the fastest launch configuration. 
Automatic selection of the number of threads and layers. 
I’m just throwing out an idea, it shouldn’t be difficult, but it will improve the usability of the application.

**Comment by LostRuins** [comment]
Automatic GPU layer selection is available in v1.48 (it is not optimized, but it will provide decent nooby settings)

**Comment by intulint** [comment]
@LostRuins Thank you, I saw it. I hope this will be more convenient for beginners.
