### ISSUE TITLE
[OVERSIGHT] (Kobold v1.4.7) -> Wrong default ROPE for CodeLlama.

### ISSUE THREAD

**Issue by SabinStargem** [LostRuins/koboldcpp#487]
The ROPE is supposed to be 1,000,000.  The defaults used in KoboldCPP is 10,000.    Airoboros 34b repeats with KoboldCPP, unless the proper rope is used.

**Comment by LostRuins** [comment]
If it's a GGUF model, it needs to be correctly configured by the model creator. KoboldCpp sets it based on the n_train_ctx value.

**Comment by SabinStargem** [comment]
Going by what I am seeing in the terminal, the model places the 1,000,000 under "freq_base_train".


![image](https://github.com/LostRuins/koboldcpp/assets/38871546/36745d05-85a1-404c-b718-7bfa19e50d05)

Hm.  Maybe the Bloke isn't building it right?   That said, you would think Ooga and other clients would have complaints about the model not working.

**Comment by LostRuins** [comment]
That's the wrong parameter. The value that is important for rope scaling is n_ctx_train, aka. the training context. On this model, it is 16k, so it will use rope scaling of 1.0 10000 for 16k contextsize, aka. a 1 to 1 ratio. 

You can customize it with --ropeconfig, of course.

**Comment by LostRuins** [comment]
Can you find another model that uses freq_base_train? If it's a commonly set parameter, I can include it in my calculations

**Comment by SabinStargem** [comment]
Here is Airoboros L2-70b, which has 10,000 as freq_base_train.  Not sure if it is specific to the family.  The value is probably generated from rope_theta, going by what I see in the config.json for the pytorches.

![image](https://github.com/LostRuins/koboldcpp/assets/38871546/80c8fe30-98e9-43c2-8b32-2b732685f6ce)

1,000,000
![image](https://github.com/LostRuins/koboldcpp/assets/38871546/e540450d-6368-460a-addf-1710dd410757)

10,000
![image](https://github.com/LostRuins/koboldcpp/assets/38871546/bc0c2765-bebe-4b26-9887-43f4edcc2ea5)

**Comment by SabinStargem** [comment]
I found another 34b model, Synthia v1.2.   It has freq_base_train 1,000,000 in Kobold's terminal.  The output is similar to what Airoboros 34b has, if the ROPE isn't customized.


![image](https://github.com/LostRuins/koboldcpp/assets/38871546/a3f2ee46-c173-435e-8986-b9c4269486d5)

**Comment by LostRuins** [comment]
This should now be fixed, please try v1.48

**Comment by SabinStargem** [comment]
Airoboros 34b successfully generated.  :)
