### ISSUE TITLE
Where is the sources for koboldcpp.dll and etc

### ISSUE THREAD

**Issue by KrakenTales** [LostRuins/koboldcpp#49]
Maybe it's a silly question, but, where can I find the sources for:

- koboldcpp.dll
- koboldcpp_clblast.dll
- koboldcpp_noavx2.dll
- koboldcpp_openblas.dll
- koboldcpp_openblas_noavx2.dll
- clblast.dll

I've got an error for koboldcpp.exe running it on Windows 7 x64 and want to rebuild it from sources. The beginning of the problem is in the llama.cpp, in the fnPrefetchVirtualMemory.

**Comment by LostRuins** [comment]
It's all in the makefile. It's the same source code, just with different flags enabled (see screenshot) 
![image](https://user-images.githubusercontent.com/39025047/231637419-0885e478-3da0-4c4c-a8e5-6fe8c9e0a3c2.png)

Running `make` on windows should build all of the dlls.

**Comment by KrakenTales** [comment]
@LostRuins One more question. Is there any package that includes `make` for windows that you can recommend? I tried visual studio 2019 command line as well as cygwin which failed to install at all. Are there any other solutions for `make` on Windows?

**Comment by h-h-h-h** [comment]
I ran `make` in Cygwin on Windows and `cc` was missing. I ran `make CC=gcc.exe` according to [this](https://stackoverflow.com/a/65000762) and compilation stopped when trying to build some `*noavx*.o` file. I looked into `Makefile` and found the line

    default: llamalib llamalib_noavx2 llamalib_openblas llamalib_openblas_noavx2 llamalib_clblast

So, I removed the `noavx` stuff and ran

    make CC=gcc.exe llamalib llamalib_openblas llamalib_clblast

This worked. But running `make_pyinstaller.bat` afterwards had an error again. So I ran its content without the `noavx` stuff, which gave me `koboldcpp.exe`:

    pyinstaller --noconfirm --onefile --clean --console --icon "./niko.ico" --add-data "./klite.embd;." --add-data "./koboldcpp.dll;." --add-data "./koboldcpp_openblas.dll;." --add-data "./libopenblas.dll;." --add-data "./koboldcpp_clblast.dll;." --add-data "./clblast.dll;." "./koboldcpp.py" -n "koboldcpp.exe"

But when I run `koboldcpp.exe` or `python koboldcpp.py`, I get the error `FileNotFoundError: Could not find module '...\koboldcpp_openblas.dll' (or one of its dependencies). Try using the full path with constructor syntax.` `koboldcpp_openblas.dll` exists, so `(or one of its dependencies)` will be the problem. I guess the `noavx` DLLs which will probably be built are a necessity, even if the CPU supports AVX and AVX2.

**Comment by h-h-h-h** [comment]
I used [this script](https://github.com/extremecoders-re/pyinstxtractor) to unpack `koboldcpp.exe` from the releases page of this repo, found all DLLs in it to not trigger VirusTotal and copied them to my cloned `koboldcpp` repo, then ran `python koboldcpp.py`. This worked.

**Comment by LostRuins** [comment]
Great, glad you got it working for you. Generally it's a lot easier to just use the combined pyinstaller exe, but on some releases I do include a an extracted zip file containing the dlls and python scripts too. Do note that you cannot mix dlls between different versions, you'll get all sorts of weird errors. As for building, I personally use w64devkit, but any setup with the latest gcc and g++ should work. You can try MSYS2 or building on WSL2, some have managed that.

**Comment by KrakenTales** [comment]
@h-h-h-h thank you for sharing your experience! It was my mistake :see_no_evil: , I've forgot to add that I've couldn't even download cygwin. That's solved on another machine.

@LostRuins thank you for advice about `w64devkit`, I've rebuild all .dll and that helped to run the program on windows 7. Amazing!

**Comment by LostRuins** [comment]
Cool. Is that 32 bit windows 7? I would have thought the normal binaries would work too.

**Comment by KrakenTales** [comment]
@LostRuins Windows 7 x64, I've not test it on another yet.
