### ISSUE TITLE
[BUG] (v1.4.7) -> CausalLM 14b, CUDA error 9

### ISSUE THREAD

**Issue by SabinStargem** [LostRuins/koboldcpp#490]
When I tried to run CausalLM 14b, I got the following error message.  There is a 7b version of CausalLM, if you need something a little smaller to examine.

> Processing Prompt [BLAS] (4808 / 4808 tokens)
> Generating (1 / 1024 tokens)
> CUDA error 9 at C:\Users\HCH\Desktop\koboldcpp\ggml-cuda.cu:6858: invalid configuration argument
> current device: 0
> 
> [process exited with code 1 (0x00000001)]

**Comment by LostRuins** [comment]
Is that is a supported model architecture? Maybe try running it with clblast or openblas first. Does it happen with llama.cpp main.exe too?

**Comment by LostRuins** [comment]
Okay first, you're on  Version 1.47.1, try upgrading to  Version 1.47.2 just in case.

Next, the CUDA kernel failed during a matrix multiplication. You are using a rather large contextsize of 16k, perhaps try reduce that to 2k first and try on cuda, see if it works? May want to lower a few other parameters too.

**Comment by SabinStargem** [comment]
Still doesn't work with MM disabled and 2k context.

**Comment by LostRuins** [comment]
Please try v1.48, which should have fixed this issue.

**Comment by SabinStargem** [comment]
CausalLM worked without issue.  Good job.
