### ISSUE TITLE
Example messages are part of response in dialog return

### ISSUE THREAD

**Issue by Zyril-8204** [LostRuins/koboldcpp#51]
I am running kobaldcpp 1.5 on windows 11.

I am using the following model: 
pygmalion-6b-v3-ggml-ggjt-q4_0.bin

I am using SillyTavern latest and dev (appears to make no difference)

I am getting in my responses a <START> tag and then example message dialog after the character has completed actions/talking. It does not matter which character I seem to use or how large/small the tokens are. The default characters in tavern are behaving the same. Changing the presets from the drop down does not stop the <start> tags nor does tavern respect the generate X mount of tokens to try and stop the tag and example from showing up.

I moved back to version 1.4 and this issue is not present there with the same model and Tavern setup.

Let me know what more I can provide to help.

**Comment by LostRuins** [comment]
Can you provide some examples (e.g. screenshots) that demonstrate this issue? I'm not sure I understand what is wrong with the responses. What do you mean by " stop the tags"?

**Comment by Zyril-8204** [comment]
@LostRuins I'll admit I don't a lot about how this works **_yet_**. My area of software development expertise is over on the C# side with application/window service/web development. Then on DevOps side expertise in yaml/powershell scripting and working with Azure/AWS API. 

That being said I can state behavior witness and the attempted intention here during my testing/use of this application

Referring to the "stop the tags", that was an intention context. Stated in the attempts to limit the amount of tokens generated for the response by the AI so that the message doesn't try to create the following style of text below.

<START> 
{{char}} some message shows up here that is the example response message on the character card.

This was happening after every character's actions or responses on version 1.5. Using SillyTavern dev and latest release branch.

This morning, I saw a 1.6 release and grabbed it and attempted to reproduce the issue. I've not had a chance to deep dive into it with some custom cards. However, with the characters that ship with Tavern do not seem to respond with example messages after their text/actions. 

My next step here is to test with custom characters. I don't want to put things here into GitHub that will risk my GitHub account. If I do find anything with 1.6 this evening I'll respond here and we can discuss contact via discord to demo steps to produce via screen share. 

If I can't reproduce the issue with 1.6 then I will close this issue and mark it can't reproduce for 1.6+.

**Comment by LostRuins** [comment]
The text processing behavior has not changed for the last few versions. How it works in kobold is the server generates a fixed number of tokens based on the amount requested, and then the client will manually trim the message to a shorter length when processing the response.

**Comment by LostRuins** [comment]
In the latest version (v1.9 at time of writing) stopper tokens have finally been added to the API. The AI should now stop generating excess tokens in chat mode. Do try it out!

**Comment by Zyril-8204** [comment]
this looks like it's fixed in 1.9 appreciate the work you all have done on this!
