### ISSUE TITLE
1.48 Google Colab model launch

### ISSUE THREAD

**Issue by LegaciQuiet** [LostRuins/koboldcpp#510]
# Expected Behavior
Success launch of Colab version.
Model: 
Undi95/Unholy-v1.1-13B-GGUF

# Environment and Context

Google Colab

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Insert direct link to Undi95/Unholy-v1.1-13B-GGUF 5_K_M ;
2. Launch code block.

# Failure Logs

Welcome to the Official KoboldCpp Colab Notebook

It's really easy to get started. Just press the two Play buttons below, and then connect to the Cloudflare URL shown at the end. You can select a model from the dropdown, or enter a custom URL to a GGUF model (Example: https://huggingface.co/KoboldAI/LLaMA2-13B-Tiefighter-GGUF/resolve/main/LLaMA2-13B-Tiefighter.Q4_K_M.gguf)
<-- Tap this if you play on Mobile
v-- Enter your model below and then click this to start Koboldcpp
Model:
Layers:
ContextSize:

/content
Cloning into 'koboldcpp'...
remote: Enumerating objects: 14840, done.
remote: Counting objects: 100% (5680/5680), done.
remote: Compressing objects: 100% (631/631), done.
remote: Total 14840 (delta 5377), reused 5144 (delta 5049), pack-reused 9160
Receiving objects: 100% (14840/14840), 66.49 MiB | 15.64 MiB/s, done.
Resolving deltas: 100% (10432/10432), done.
/content/koboldcpp
Finding prebuilt binary for 1.48
--2023-11-04 09:00:01--  https://kcppcolab.concedo.workers.dev/?1.48
Resolving kcppcolab.concedo.workers.dev (kcppcolab.concedo.workers.dev)... 172.67.145.201, 104.21.71.155, 2606:4700:3036::ac43:91c9, ...
Connecting to kcppcolab.concedo.workers.dev (kcppcolab.concedo.workers.dev)|172.67.145.201|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://huggingface.co/concedo/koboldcpp/resolve/main/prebuilt_binaries/1.48.so [following]
--2023-11-04 09:00:01--  https://huggingface.co/concedo/koboldcpp/resolve/main/prebuilt_binaries/1.48.so
Resolving huggingface.co (huggingface.co)... 13.33.33.20, 13.33.33.102, 13.33.33.55, ...
Connecting to huggingface.co (huggingface.co)|13.33.33.20|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn-lfs.huggingface.co/repos/d2/2b/d22bcaf50ec2e655ec6dd5cef052361ab764809fb0e020f1f0128ab245ffe8e6/62a4fbe4518db9c73476368d3d0fded7c84b6974b75bd1c27fb1f08e392b7db7?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%271.48.so%3B+filename%3D%221.48.so%22%3B&response-content-type=application%2Foctet-stream&Expires=1699347601&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5OTM0NzYwMX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy9kMi8yYi9kMjJiY2FmNTBlYzJlNjU1ZWM2ZGQ1Y2VmMDUyMzYxYWI3NjQ4MDlmYjBlMDIwZjFmMDEyOGFiMjQ1ZmZlOGU2LzYyYTRmYmU0NTE4ZGI5YzczNDc2MzY4ZDNkMGZkZWQ3Yzg0YjY5NzRiNzViZDFjMjdmYjFmMDhlMzkyYjdkYjc%7EcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qJnJlc3BvbnNlLWNvbnRlbnQtdHlwZT0qIn1dfQ__&Signature=SSm6jpQPoyZRgK2SUzXhXsM1mc69shV%7E0Ib%7EQOY1DnujWtDfAwJRBXAzInLokeOtnXTbJCJHV3dB24QPKt%7EFqea7rh54rSxrfHrjCd97RpwRiI-luMH2Eb096mUKCW1DIipx5Tj1kK-ZZ5vbRsaEuQI1KKZz%7ExSPjhO2dXakP5cXmafASv8REvMl-aJk7DoQOrh5xEkkx7eXcWD6J%7EnopuEM3v6GIGb2rxub7NKHPlDcQEsKNnyrpHwlxb2uBMMN2DRlwKlRpte5kE0MoU%7EgtPaVAF3rADCcJxxmzlNAa1Bw63Nny2nm%7E-pHWkvji2IUHm3KMB6rWXRKhe6W1%7EoSXg__&Key-Pair-Id=KVTP0A1DKRTAX [following]
--2023-11-04 09:00:01--  https://cdn-lfs.huggingface.co/repos/d2/2b/d22bcaf50ec2e655ec6dd5cef052361ab764809fb0e020f1f0128ab245ffe8e6/62a4fbe4518db9c73476368d3d0fded7c84b6974b75bd1c27fb1f08e392b7db7?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%271.48.so%3B+filename%3D%221.48.so%22%3B&response-content-type=application%2Foctet-stream&Expires=1699347601&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5OTM0NzYwMX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy9kMi8yYi9kMjJiY2FmNTBlYzJlNjU1ZWM2ZGQ1Y2VmMDUyMzYxYWI3NjQ4MDlmYjBlMDIwZjFmMDEyOGFiMjQ1ZmZlOGU2LzYyYTRmYmU0NTE4ZGI5YzczNDc2MzY4ZDNkMGZkZWQ3Yzg0YjY5NzRiNzViZDFjMjdmYjFmMDhlMzkyYjdkYjc%7EcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qJnJlc3BvbnNlLWNvbnRlbnQtdHlwZT0qIn1dfQ__&Signature=SSm6jpQPoyZRgK2SUzXhXsM1mc69shV%7E0Ib%7EQOY1DnujWtDfAwJRBXAzInLokeOtnXTbJCJHV3dB24QPKt%7EFqea7rh54rSxrfHrjCd97RpwRiI-luMH2Eb096mUKCW1DIipx5Tj1kK-ZZ5vbRsaEuQI1KKZz%7ExSPjhO2dXakP5cXmafASv8REvMl-aJk7DoQOrh5xEkkx7eXcWD6J%7EnopuEM3v6GIGb2rxub7NKHPlDcQEsKNnyrpHwlxb2uBMMN2DRlwKlRpte5kE0MoU%7EgtPaVAF3rADCcJxxmzlNAa1Bw63Nny2nm%7E-pHWkvji2IUHm3KMB6rWXRKhe6W1%7EoSXg__&Key-Pair-Id=KVTP0A1DKRTAX
Resolving cdn-lfs.huggingface.co (cdn-lfs.huggingface.co)... 13.33.33.45, 13.33.33.119, 13.33.33.69, ...
Connecting to cdn-lfs.huggingface.co (cdn-lfs.huggingface.co)|13.33.33.45|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4033656 (3.8M) [application/octet-stream]
Saving to: ‘dlfile.tmp’

dlfile.tmp          100%[===================>]   3.85M  --.-KB/s    in 0.02s   

2023-11-04 09:00:01 (192 MB/s) - ‘dlfile.tmp’ saved [4033656/4033656]

Prebuilt Binary Exists
Build Skipped
--2023-11-04 09:00:02--  https://huggingface.co/Undi95/Unholy-v1.1-13B-GGUF/blob/main/Unholy-v1.1-13B.q5_K_M.gguf
Resolving huggingface.co (huggingface.co)... 13.33.33.20, 13.33.33.102, 13.33.33.55, ...
Connecting to huggingface.co (huggingface.co)|13.33.33.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 40564 (40K) [text/html]
Saving to: ‘model.ggml’

model.ggml          100%[===================>]  39.61K  --.-KB/s    in 0.001s  

2023-11-04 09:00:02 (28.1 MB/s) - ‘model.ggml’ saved [40564/40564]

***
Welcome to KoboldCpp - Version 1.48
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.so
==========
Namespace(model=None, model_param='model.ggml', port=5001, port_param=5001, host='', launch=False, lora=None, config=None, threads=1, blasthreads=1, highpriority=False, contextsize=4096, blasbatchsize=512, ropeconfig=[0.0, 10000.0], smartcontext=False, noshift=False, bantokens=None, forceversion=0, nommap=False, usemlock=False, noavx2=False, debugmode=-1, skiplauncher=False, hordeconfig=['concedo', '1', '1'], noblas=False, useclblast=None, usecublas=['0', 'mmq'], gpulayers=43, tensor_split=None, onready='', multiuser=True, remotetunnel=True, foreground=False)
==========
Loading model: /content/koboldcpp/model.ggml 
[Threads: 1, BlasThreads: 1, SmartContext: False, ContextShift: True]

---
Identified as LLAMA model: (ver 0)
Attempting to Load...
---
Using automatic RoPE scaling (scale:1.000, base:32000.0)
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 

Unknown Model, cannot load.
Load Model OK: False
Could not load model: /content/koboldcpp/model.ggml

**Comment by LostRuins** [comment]
Bad url. Make sure it's a DIRECT link to the gguf model, not just the page.

**Comment by LostRuins** [comment]
Correct

**Comment by LostRuins** [comment]
It's some weird intermittent bug with the prebuilt binaries. I've removed them for now - doing a fresh compile seems to work for some reason.

**Comment by LostRuins** [comment]
Should be fixed - please try again!

Note: Cloudflare tunnel issues are a separate known issue currently. If the tunnel fails to be created, just restart the colab and retry.
