### ISSUE TITLE
Prompt template

### ISSUE THREAD

**Issue by intulint** [LostRuins/koboldcpp#511]
The quality of the model's response depends on the prompt template. Is it possible to add a switch to the settings? Many good models have different prompt template that they are trained to respond to. Same ChatML

**Comment by LostRuins** [comment]
Already exists. 
![image](https://github.com/LostRuins/koboldcpp/assets/39025047/8ee81632-aec7-48e1-80da-697380e50508)

**Comment by intulint** [comment]
Strange, I can't find it. It's stupid not to believe you, but I don't see it in the settings. I updated the page.

**Comment by intulint** [comment]
Thank you, I thought this was not the case.
I didn’t find it at first, but after searching I understood. This is in the instruction mod. How it works? Only in it or in chat mode too? I don't quite understand how these templates work.

**Comment by LostRuins** [comment]
Templates are only for instruct mode. For chat mode, it just uses IRC style chat names.
```
User1: message
User2: message
```

**Comment by intulint** [comment]
I'm understood, thank you.
