### ISSUE TITLE
How to adjust the smart context's ratio?

### ISSUE THREAD

**Issue by fenixlam** [LostRuins/koboldcpp#516]
I have read the https://github.com/LostRuins/koboldcpp/wiki#what-is-smart-context
Seeing the smart context kicking 25 people off the bus and allowing every bus stop getting 5 ppl in. 
In fact, now I have 32000+ tokens buffer. I notice the game goes on after 10000 tokens and become crazy.
(the inference reply will become crazy, at least it appears in gguf model)
So that is meaningless for that 32000+ tokens. 
I have no choice but to switch on the smart context and add the 10240 tokens as limited (in Sillytavern)
It can trigger koboldcpp.exe to run smart context in 50:50 ratio when the story goes on over 10240 tokens. 
50% for reading old content, 50% for writing new content.
I think it would be better if that is 60:40 even 75:25. 
Because the reply logic is basic on the reading, if the reading buffer is too small, the reply cannot catch up the story.
I know it will increase the number of loading buffer frequently because the writing buffer is decreased, 
but it is worth for the logic and continuity of the story.
The important thing is, create a parameter for the API and console calling, so the user can choose their best ratio.

**Comment by LostRuins** [comment]
Try disabling smart context and using the new ContextShift feature which is much better.
