### ISSUE TITLE
Where i can find platform_id and device_id for command useclblast?

### ISSUE THREAD

**Issue by visteras** [LostRuins/koboldcpp#52]
OS: Windows 10
CPU: AMD Ryzen 7 5800X
GPU: Nvidia RTX 3070
I searched on Google, but I could not find an application or command to display these parameters ... where to look for them?

**Comment by visteras** [comment]
Ok, my bad, i see my device with 0 0, but i see only after start generate:
```
Attempting to use: Platform=0, Device=0 (If invalid, program will crash)
Using Platform: NVIDIA CUDA Device: NVIDIA GeForce RTX 3070
```

**Comment by Xeraster** [comment]
Beware if you're on Debian. I don't have clinfo --list on Debian. I tried to install it. I found a forum post that said to install boinc-client-opencl so i did that. It installed a bunch of old borked drivers, but it seems I killed it soon enough to avoid borking my system and I still have nvidia drivers after a reboot.

Brute force guessing is unfortunately better I guess.
