### ISSUE TITLE
TTS should not read out user input text and character names; how to add custom voices

### ISSUE THREAD

**Issue by pbz134** [LostRuins/koboldcpp#524]
Whenever I try chatting with the AI using TTS, not only the AI output but also the user input (and the character name) gets read out loud.

Is there a way to disable it so that only the output gets read out loud?

Also, how can I add more TTS voices?

Thanks in advance!

**Comment by LostRuins** [comment]
This has been added in the latest version, TTS now can be toggled into 2 modes, full narration or AI speech only.
