### ISSUE TITLE
Using 32-bit lora with GPU support

### ISSUE THREAD

**Issue by cuneyttyler** [LostRuins/koboldcpp#525]
I'm using llama.cpp's finetune script to create lora files for a model. It generates 32 bit loras. When I tried to load this lora along with the model to KoboldCpp, it says that only 16 bit loras can be used with GPU support. I wonder if you plan to support 32 bit loras with GPU support in the near future? Or is there any script/tool to fine-tune a model to generate 16 bit loras?

**Comment by LostRuins** [comment]
This one is not really under my control - it'll depend on upstream support

**Comment by cuneyttyler** [comment]
Okay thanks.
