### ISSUE TITLE
AI becoming stupid issue

### ISSUE THREAD

**Issue by kbuwel** [LostRuins/koboldcpp#528]
A problem occurred while using the chatbot. 
Xwin-Mlewd-13B 
ggml-ko-vicuna-7b-q4 
ggml-ko-vicuna-7b-q8 
You can download it from huggingface.
These are the models I used. 
Start a conversation. 
my question 
What does apple mean in Korean? 
AI answers 
Apple means Apple in Korean. 
my question 
What is a Jadoo? 
AI answers 
Plum in Korean means Jadoo, and it is my favorite fruit. 
my question 
Are you fluent in Korean?  Where did you learn Korean? 
AI answers 
Are you fluent in Korean?  Where did you learn Korean?  In Korean, you speak Korean fluently.  Where 
did you learn Korean?  No, I understand. 
It keeps repeating like this. 
Start a new chat. 
There are issues with requests to provide character descriptions and create novels: 
AI answers 
Mom tells her plum not to eat her snack.  She won on the baseball field. 
my conversation 
That's it? 
There is no dialogue and no information on how to win. 
AI answers 
Mom tells Jadoowav not to eat her snack.  She won on the baseball field. 
Mom tells Jadoo not to eat her snack.  She won on the baseball field. 
Keep repeating. 
I used version 1.4.9.

**Comment by LostRuins** [comment]
You'd probably need to get a model training with Korean texts, and setup the chat prompt in korean.
