### ISSUE TITLE
[Request] Escape the "Stop sequence triggered" for the console output

### ISSUE THREAD

**Issue by jojorne** [LostRuins/koboldcpp#529]
# Feature Description

Just escape the output of the console for "Stop sequence triggered" and maybe switch the "<" and ">" for double quotes just like "stop_sequence".

# Motivation

The console output stuff like:
```
(Stop sequence triggered: <
> >)
```
It's hard to understand which sequence it is especially when the actually "stop_sequence" data is formatted with quotation and escaped (e.g, "\n> ").

**Comment by jojorne** [comment]
https://github.com/LostRuins/koboldcpp/blob/6a4d9c26e1eeb2119171b3ea21444d940c7a8a14/gpttype_adapter.cpp#L1749

**Comment by LostRuins** [comment]
fixed in 1.50.1
