### ISSUE TITLE
KLite Abort Retry does continue instead and somewhat bugs the internal list

### ISSUE THREAD

**Issue by jojorne** [LostRuins/koboldcpp#531]
# Expected Behavior

- Abort
- Retry
- Result: Last AI attempt should be erased for a new entry

# Current Behavior

- Abort
- Retry
- Result: AI continues from where it stopped
- Pressing "Back" results in a double last entry

**Comment by LostRuins** [comment]
Should be fixed, please check

**Comment by jojorne** [comment]
Not fixed =\

**Comment by jojorne** [comment]
Version 1.50, yes.

**Comment by LostRuins** [comment]
What browser are you using?

**Comment by jojorne** [comment]
Firefox.

**Comment by LostRuins** [comment]
Alright, I think I found the issue. Will do a fix release for koboldcpp within the next few days, for now you can test if its solved connecting via the web version https://lite.koboldai.net/?local=1&port=5001

**Comment by jojorne** [comment]
It takes a while for the Abort button to appear. If it's a 16 tokens output, it can finish before that. Is it intended?

**Comment by LostRuins** [comment]
I'm confused. How do you get a stop sequence triggered after aborting?

**Comment by jojorne** [comment]
It's the slow speed~
I think it's still processing a token by the time I press Abort and it queue the command?

**Comment by LostRuins** [comment]
Is your "trim sentences" enabled in settings? 
![image](https://github.com/LostRuins/koboldcpp/assets/39025047/de8d48ea-6d60-4258-abe1-8b1adf90cf07)

and yes, the abort button has a short delay before appearing, this is intentional to prevent accidental submit+cancel multiple times.

**Comment by jojorne** [comment]
![image](https://github.com/LostRuins/koboldcpp/assets/18329136/355dcded-922f-48d0-8ce0-b23e7bb23093)

One of the examples above, the stop sequence was a quote, so the sentence ended with a period.

**Comment by jojorne** [comment]
Should I open a new issue to track this problem? Version 1.49 has the problem, so it's not new. It just happens that with this fix it became more recurrent.

**Comment by LostRuins** [comment]
I cannot repro the issue you mention about text disappearing on ABORT. My text never disappears once it shows up as the yellow streamed text. Can you launch from https://lite.koboldai.net/?local=1&port=5001 and check that

trim sentences is OFF
streaming set to SSE or ON
lite is set to STORY MODE

for easy testing you can do a reset-to-default settings and then load Niko's revenge story. Also note any errors that are shown in console or popups.

then, trigger an abort after the generation has started, and check if your text is consistently disappearing.... if its still bugged, perhaps if you have a video i can try to repro it too following the above steps.

**Comment by jojorne** [comment]
All seems to be fixed.
