### ISSUE TITLE
I found some misspelling inside"scenario_db"

### ISSUE THREAD

**Issue by jojorne** [LostRuins/koboldcpp#532]
seperate -> separate
https://github.com/LostRuins/koboldcpp/blob/a00a32e0498e316086e4528ab15a4ba7a1e27b7c/klite.embd#L1939

scavange -> scavenge
https://github.com/LostRuins/koboldcpp/blob/a00a32e0498e316086e4528ab15a4ba7a1e27b7c/klite.embd#L2003
https://github.com/LostRuins/koboldcpp/blob/a00a32e0498e316086e4528ab15a4ba7a1e27b7c/klite.embd#L2007

knowledgable -> knowledgeable
Note: This one might not be wrong though.
https://github.com/LostRuins/koboldcpp/blob/a00a32e0498e316086e4528ab15a4ba7a1e27b7c/klite.embd#L2032
https://github.com/LostRuins/koboldcpp/blob/a00a32e0498e316086e4528ab15a4ba7a1e27b7c/klite.embd#L2041

And there are others most common on UK. So...

**Comment by LostRuins** [comment]
Thank you! I don't have autocorrect in my IDE so it's very easy for me to miss these issues.

**Comment by LostRuins** [comment]
Should be fixed now

**Comment by jojorne** [comment]
Will keep it as UK english or convert to US?

**Comment by LostRuins** [comment]
most of them are already US spellings I believe

**Comment by jojorne** [comment]
unkown -> unknown
table promp -> table prompt

UK -> US
realise -> realize
travelling -> traveling
happyness -> happiness

**Comment by jojorne** [comment]
All fixed.
