### ISSUE TITLE
Save chosen LoRA Base to config

### ISSUE THREAD

**Issue by StripedPuppy** [LostRuins/koboldcpp#535]
# Feature Description

Save the user's chosen LoRA Base setting to the config file they create.

# Motivation

I've noticed that saving configuration files only records the LoRA path and not LoRA Base. I'm unsure if this is an oversight or intended.

**Comment by LostRuins** [comment]
LoRA base is being saved. Please check your GUI again.

**Comment by StripedPuppy** [comment]
Unfortunately, it's not. I'm on release v1.50. Loading the .KCPPS still leaves the LoRA Base field empty.
![2023-11-20 14_05_36](https://github.com/LostRuins/koboldcpp/assets/34108520/816c1909-fa9f-4a83-afbb-7b90079c49f1)



`{"model": null, "model_param": "D:/7b - openhermes-2.5-mistral-7b.Q8_0.gguf", "port": 5001, "port_param": 49881, "host": "", "launch": false, "lora": null, "config": null, "threads": 1, "blasthreads": 12, "highpriority": false, "contextsize": 8192, "blasbatchsize": 1024, "ropeconfig": [0.0, 10000.0], "smartcontext": false, "noshift": false, "bantokens": null, "forceversion": 0, "nommap": false, "usemlock": false, "noavx2": false, "debugmode": 0, "skiplauncher": false, "hordeconfig": null, "noblas": false, "useclblast": null, "usecublas": ["normal", "0", "mmq"], "gpulayers": 99, "tensor_split": null, "onready": "", "multiuser": false, "remotetunnel": false, "foreground": false, "preloadstory": null}`

**Comment by LostRuins** [comment]
Your LoRA is showing as `null`. Did you save and overwrite the config file after selecting the LoRA? Make sure the config is saved correctly.
[test.zip](https://github.com/LostRuins/koboldcpp/files/13422489/test.zip)
Here's a zip containing a test config file with Lora set.

**Comment by StripedPuppy** [comment]
Either saving a new config or overwriting one still results in null. I upgraded to v1.50.1.

LoRA Base is correctly written as long as a regular LoRA is selected. But I can't run LoRA's due to insufficient RAM.

**Comment by LostRuins** [comment]
You cannot use LoRA base without LoRA. LoRA can be used without LoRA base, but not the other way around.
