### ISSUE TITLE
[Enhancement] Any chances to add basic model management feature in API like changing model on run?

### ISSUE THREAD

**Issue by racheandre** [LostRuins/koboldcpp#536]
# Feature Description

I would like to change the model on run through the API

# Motivation

It is useful when implementing a client application switching to different model on different situation. Currently, it must be stop manually on server and restart with a different cli parameter, which is okay, but not ideal if you want the client application can do it itself, or even serving to multiple user (though not sure how capable of koboldcpp on that).

**Comment by LostRuins** [comment]
Changing the model on the fly will probably not be supported, as there's no clean procedure to unload and free the memory used by the previous model except closing the app currently.

**Comment by racheandre** [comment]
I don't think it is not possible to create a daemon to manage another process, but may require refactoring. So, it is fair if this is not what you want. Thank you.

**Comment by LostRuins** [comment]
It should be possible to abstract it though, for example what you could do is setup a pipeline for docker which takes a model string as an argument or env variable. Then whenever you want to change model, simply restart the container with the new value.
