### ISSUE TITLE
ComfyUI API support

### ISSUE THREAD

**Issue by cherrerajobs** [LostRuins/koboldcpp#540]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

We have support for the local Automatic1111 endpoint. It would be awesome to have access to ComfyUI's API, which seems to be well explored with implementations in [CushyStudio](https://github.com/rvion/CushyStudio) and [Krita](https://github.com/Acly/krita-ai-diffusion). A common attribute of implementations seems to be submitting a json config that ComfyUI runs and returns the image output of.

# Motivation

This is useful for those of us running ComfyUI, which seems to be a larger and larger group despite its node based architecture since it runs models using a _lot_ less memory. (see [ComfyUI Update: Stable Video Diffusion on 8GB vram with 25 frames and more.](https://blog.comfyui.ca/comfyui/update/2023/11/24/Update.html))

# Possible Implementation

See two examples linked above for code research.

**Comment by LostRuins** [comment]
Looked through the API and it doesn't really seem very user friendly for a third party implementation. I wouldn't discount it but I don't think this will be a priority at this time.

Perhaps you can also consider using SHARK, which supports the A1111 api, and should work out of the box:
https://github.com/nod-ai/SHARK

**Comment by LostRuins** [comment]
Worth noting that KoboldCpp now has inbuilt image generation capabilities.
