### ISSUE TITLE
Support RWKV5

### ISSUE THREAD

**Issue by Jcuhfehl** [LostRuins/koboldcpp#542]
I'm attempting to use the latest version of RWKV (version 5) ggml models from https://huggingface.co/latestissue/rwkv-5-world-ggml-quantized. The version 4 equivalent of these models work fine, but these crash with a segmentation fault:
```
Tensor has an invalid shape (3 dimensions)
./otherarch/rwkv_v3.cpp:318: header.dim_count == 1 || header.dim_count == 2
Invalid tensor header
./otherarch/rwkv_v3.cpp:1389: rwkv_fread_tensor_header(file.file, tensor_header)

./otherarch/rwkv_v3.cpp:1554: rwkv_instance_from_file(file_path, *instance.get())
/usr/bin/koboldcpp: line 2: 59282 Segmentation fault      (core dumped) python koboldcpp.py "$@"
```

These models are supported in RWKV.cpp, so implementing this in koboldcpp should be relatively easy, since the code for RWKV here is based on that repository.

**Comment by LostRuins** [comment]
It's not that easy, the GGML libraries are not compatible as they have many modifications.
