### ISSUE TITLE
How to remove or hide <|im_end|> on the UI?

### ISSUE THREAD

**Issue by lejunzhu** [LostRuins/koboldcpp#543]
I'm using 1.50.1 and the Yi 34B Chat model. I found that the EOS token (<|im_end|>) is shown in the browser, at the end of the AI response. How do I remove or hide it?

Part of the debug log:
```
...

llm_load_vocab: mismatch in special tokens definition ( 498/64000 vs 267/64000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 64000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 7168
llm_load_print_meta: n_head           = 56
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 60
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 7
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 20480
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 5000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 30B
llm_load_print_meta: model ftype      = unknown, may not work
llm_load_print_meta: model params     = 34.39 B
llm_load_print_meta: model size       = 19.24 GiB (4.81 BPW)
llm_load_print_meta: general.name   = LLaMA v2
llm_load_print_meta: BOS token = 6 '<|im_start|>'
llm_load_print_meta: EOS token = 7 '<|im_end|>'
llm_load_print_meta: UNK token = 0 '<unk>'
llm_load_print_meta: PAD token = 0 '<unk>'
llm_load_print_meta: LF token  = 315 '<0x0A>'
llm_load_tensors: ggml ctx size = 19700.44 MiB

...

Generating (1 / 120 tokens) [(你好 92.77%) (您好 7.23%)]
127.0.0.1 - - [01/Dec/2023 09:42:14] "POST /api/extra/generate/check HTTP/1.1" 200 -
Generating (2 / 120 tokens) [(！ 100.00%)]
127.0.0.1 - - [01/Dec/2023 09:42:14] "POST /api/extra/generate/check HTTP/1.1" 200 -
Generating (3 / 120 tokens) [(有什么 89.40%) (看起来 8.89%) (很高兴 0.57%) (我 0.55%)]
Generating (4 / 120 tokens) [(可以帮助 50.82%) (我可以 47.38%) (问题 1.80%)]
127.0.0.1 - - [01/Dec/2023 09:42:15] "POST /api/extra/generate/check HTTP/1.1" 200 -
Generating (5 / 120 tokens) [(你的 100.00%)]
127.0.0.1 - - [01/Dec/2023 09:42:15] "POST /api/extra/generate/check HTTP/1.1" 200 -
Generating (6 / 120 tokens) [(吗 100.00%)]
Generating (7 / 120 tokens) [(？ 100.00%)]
127.0.0.1 - - [01/Dec/2023 09:42:16] "POST /api/extra/generate/check HTTP/1.1" 200 -
Generating (8 / 120 tokens) [(<|im_end|> 100.00%)]

(EOS token triggered!)
ContextLimit: 23/1600, Processing:0.56s (555.0ms/T), Generation:2.30s (287.0ms/T), Total:2.85s (2.81T/s)
Output: 你好！有什么可以帮助你的吗？<|im_end|>
127.0.0.1 - - [01/Dec/2023 09:42:16] "POST /api/v1/generate HTTP/1.1" 200 -
```

**Comment by lejunzhu** [comment]
> Set it as a "custom stop sequence" in memory

Thank you. It solves the problem.

**Comment by Fr0d0Beutl1n** [comment]
Is there a way to persist this setting when starting a new session?

**Comment by LostRuins** [comment]
it is a consequence of using the chatml format. You can try setting it as the instruct end tag, then it will be hidden in the instruct mode (see chatml preset format)

**Comment by nomicpro** [comment]
@LostRuins I’m a noob here, but how do you change the custom stop sequence? any chance you could walk me through it?

**Comment by LostRuins** [comment]
It's all in the settings panel, under tokens section

<img width="669" height="233" alt="Image" src="https://github.com/user-attachments/assets/2bc3767c-8240-41ab-93e8-df2d0a859043" />

**Comment by nomicpro** [comment]
@LostRuins I’m running on a mac, the UI is very different I may need to add a line of code through the server because the UI doesn’t have a Tokens tab. It has a Chat GPT looking UI.

<!-- Uploading "Screenshot 2026-05-22 at 9.25.09 PM.png"... —>

**Comment by LostRuins** [comment]
Are you using the corpo mode? Or the lcpp mode?

<img width="702" height="459" alt="Image" src="https://github.com/user-attachments/assets/cb4de6f2-dc1d-4f84-bc6b-805762d41de1" />

For the lite corpo UI, you can still set the stop sequences in the Settings tab (top bar)

**However if you are not using KoboldAI Lite UI at all**,

If you're using the lcpp instead UI (see pic)

<img width="588" height="358" alt="Image" src="https://github.com/user-attachments/assets/ef4bc3e5-5309-423c-b586-d17a8f6fcf66" />

Then you must add the stop sequences from the server side via the `--gendefaults` launch flag, like this:

`--gendefaults {\"stop\":[\"apple\",\"banana\"]}`

or in the GUI

<img width="463" height="95" alt="Image" src="https://github.com/user-attachments/assets/5f00b57d-a748-4e60-9bcb-0b403ff27824" />
