### ISSUE TITLE
openai api doesn't seem to work correctly

### ISSUE THREAD

**Issue by Jake36921** [LostRuins/koboldcpp#546]
sites like janitor ai and software plugins that uses chatgpt/openai api wouldn't work correctly, the message gets sent but after generating a response it would just be an error when receiving it or the connection would be invalid. I tried the cloudflare tunnel but it still wouldn't work
(I know I can use the koboldai option but I have to make sure that vpet sim isn't the only thing that's having errors)
![image](https://github.com/LostRuins/koboldcpp/assets/113159896/da672259-fe15-4bb1-bcc6-fb5e9da22228)

![image](https://github.com/LostRuins/koboldcpp/assets/113159896/04763b01-8500-4038-8b37-820ec46e4338)

**Comment by LostRuins** [comment]
Should be fixed in 1.51.1, please try
