### ISSUE TITLE
Recurring Media Disconnected Issues After Installation 

### ISSUE THREAD

**Issue by Megayosh** [LostRuins/koboldcpp#551]
I’ll be upfront and honestly admit I'm not much of a software person. But each and every time the fallow events takes place.

Install the program, make sure program has the proper permissions in the firewall, things go well for a time, then get a windows prompt saying it’s blocked certain features, Media Disconnected issue then follows.

With it blocking certain sites, and not allowing me to use the search bar twice in a row (I can type egg into it but if I try to edit it the bar spaces and then wont let me do anything else). The most error given is PR_CONNECT_RESET_ERROR.

This process has occurred on multiple different versions for me but I’ve always found a solution. Uninstall my Graphics Driver, reset the network, reset DNS, reset IP, and I’m certain a few other methods I’ve forgotten.

Come version 1.51.1 and it props up again only I can’t find a solution. Used DDU to Uninstall then reinstall my graphics driver, reset the network, ensured prior versions are uninstalled, scanned for viruses only to come up empty, check multiple browsers, turn off antivirus, reset IP and DNS, and checked SSL certificates. 

For this recent release I ensured Network sharing (for kobold) was off. If it helps, it was left on (accidentally) for the prior 3 releases and potentially every prior release (I can only confirm the prior 3 fully). That being the feature I assume windows defender is having issues with.

I use an Alienware 17 R5, run on Windows 10 version 22H2, have 16 GB of RAM, have an Intel(R) Core i7-8750H CPU, have McAfee installed (with Windows Defender scans on as well), and use Firefox as my browser of choice.

I would leave an error log but two factors, one I cannot log into GitHub on my PC, and two I’m not entirely sure what exactly to provide.

If you need anything else just let me know and I’ll do my best to provide it for you.

**Comment by LostRuins** [comment]
It sounds like the issue may not be with kobold, but either with your GPU drivers, RAM/VRAM, or an unrelated program e.g. firewall on your PC.

The next time it happens, please take a screenshot of any popups and error messages (such as the thing claiming something is blocked or media disconnected). Also, check if your wifi connection is stable and whether it drops from time to time.

**Comment by Megayosh** [comment]
Heya, thank you for the help. I eventually found and fixed the issue. It was a corrupted OS file that was involved in the network function. Which looks to have been little more than a coincidence. My apologies for any wasted time, but for what it’s worth thank you again for your help.
