### ISSUE TITLE
Can I specify a prompt template for the openai drop in api? [to the devs]

### ISSUE THREAD

**Issue by nanafy** [LostRuins/koboldcpp#552]
I love the koboldcpp backend, especially contextshift. I am wondering if there's a way to specify the chat template for the openai api, similar to the example I am posting below, so I can use a more suitable front-end for my needs.

### Example
> The high-level API also provides a simple interface for chat completion.
Note that chat_format option must be set for the particular model you are using.
You probably also want to set the prompt format. For chatml, use

> python3 -m llama_cpp.server --model models/7B/llama-model.gguf --chat_format chatml

> That will format the prompt according to how model expects it. You can find the prompt format in the model card. For possible options, see [llama_cpp/llama_chat_format.py](https://github.com/abetlen/llama-cpp-python/blob/main/llama_cpp/llama_chat_format.py) and look for lines starting with "@register_chat_format".

_Sourced from: https://github.com/abetlen/llama-cpp-python#web-server_
### If NOT
If not, could you perhaps point me in the right direction? I was looking at the code in koboldcpp.py and noticed the `instruction` and `response` on lines ~419-430. Would changing these to the chatML format hardcode it to work? This looks like the alpaca template. 

                ```# translate openai chat completion messages format into one big string.
                messages_array = genparams.get('messages', [])
                adapter_obj = genparams.get('adapter', {})
                messages_string = ""
                system_message_start = adapter_obj.get("system_start", "\n### Instruction:\n")
                system_message_end = adapter_obj.get("system_end", "")
                user_message_start = adapter_obj.get("user_start", "\n### Instruction:\n")
                user_message_end = adapter_obj.get("user_end", "")
                assistant_message_start = adapter_obj.get("assistant_start", "\n### Response:\n")
                assistant_message_end = adapter_obj.get("assistant_end", "")```

A. Is this where I would modify the code? 
B. Would changing these to the chatML format hardcode it to work? This looks like it has the `alpaca` template hardcoded.

Thank you so much for all of your hardwork to the community, I love koboldcpp. I am not a great coder, so please forgive my question if it is silly.

**Comment by LostRuins** [comment]
Yes you can! This was added as an adapter in the API. Please refer to https://github.com/LostRuins/koboldcpp/pull/466

**Comment by nanafy** [comment]
Thank you, I somehow missed your original comment in Dec. I am going to check it out shortly. Thanks again LostRuins.

**Comment by nanafy** [comment]
I have downloaded the latest .exe, and I was looking through the possible help functions, but I don't really understand how to use the adapter functionality. I thought it would be something I specify as a parameter argument upon launch. E.g. --adapter [Chatformat]. Could you please help me get started? I would very much appreciate it.

**Comment by LostRuins** [comment]
The adapter is just a JSON object that you send along with your client's request when using the API. It's not a launch parameter.
