### ISSUE TITLE
Extra ways of handling stop sequences

### ISSUE THREAD

**Issue by Hisu0** [LostRuins/koboldcpp#553]
Hi! Could you please add this feature? It's going to be useful for cowriting, roleplay and others. Maybe even long chats.
What I suggest is an option to switch between different ways of handling stop sequences:
a) stop generation when sequence is encountered (current behavour)
b) retry remaining tokens when sequence is encountered, stop after N attempts (0 for indefinite re-generation)
c) retry the whole output when sequence is encountered, stop after N attempts (0 for indefinite re-generation), change temperature by X on every attempt (0 for no change, +X to increase, -X to decrease)

**Comment by LostRuins** [comment]
I think this should be a behavior of the frontend client rather than the backend.

**Comment by Yorunetsu** [comment]
Completed? But I can't find any of that in the latest release (1.57)...

**Comment by Yorunetsu** [comment]
![image](https://github.com/LostRuins/koboldcpp/assets/89686166/d0e519ed-6896-40a8-b5e6-9488ebbc1452)
