### ISSUE TITLE
Huge delay and resource usage when (finishing) editing larger texts

### ISSUE THREAD

**Issue by VL4DST3R** [LostRuins/koboldcpp#559]
# Expected Behavior

Somewhat parity between Firefox and Chromium derived browsers.

# Current Behavior

The following issue seems to happen only on Firefox/Waterfox, Edge seems to not be affected almost at all by this.

I have noticed that with particularly long texts and especially when done in chat mode (I'm talking really big like ~100 pages worth/50.000 words) a hanging issue starts to become noticeable and gets exponentially worse the further you increase the generated text. While the generating itself or even re-rolling works as expected, clicking within the text to edit anything within the UI causes a huge lag spike **when clicking outside the editable box**. It has now reached the point where it hangs for about 30 or so seconds every time i attempt to correct anything within the text.

I usually get notices from the browser that NoScript is slowing down the browser and would seem to cause this (although it blocks nothing on this page), but even testing inside a private window with all addons disabled it still does the same, with the browser reporting that the page itself is now slowing the browser and suggesting me to stop it.

# Environment and Context

Seems to be somewhat affected by hardware specs, with my more powerful desktop strong-arming it to process faster compared to my older laptop, but it's still very much noticeable.

Currently testing on Waterfox G6.0.6 (latest) and latest built-in Edge version but I can confirm this being an issue for a while now, on older versions of WF as well.

Running the browser profiler I get the following timeline:

![image](https://github.com/LostRuins/koboldcpp/assets/32654378/23ff7617-d602-4656-ac3b-ac9feae245a5)

With a large spike in CPU usage and time taken by `merge_edit_field` and `render_gametext` which I presume is what handles color coding chat participants and whatnot.

This feels like a good context to also mention another odd behavior I noticed especially when dealing with chats and lots of character names:

Correct me if I'm wrong but I'm pretty sure the UI attempts to "invisibly" split the user text into chunks to display the text to the user, instead of an actual giant plain block of text, however this sometimes seem to bug out generating formatting codes around character names in the form of `</span><span class="txtchunk">` when the UI updates the coloring of the participants.

It seems to be very inconsistent when it happens, but it always seem to stem from manually editing either the names or manually adding another chat entry from another character (e.g. copy/paste).

**Comment by LostRuins** [comment]
Yes this is a known issue. A fix is being worked on https://github.com/LostRuins/koboldcpp/issues/492

**Comment by LostRuins** [comment]
Should be fixed in the latest version

**Comment by VL4DST3R** [comment]
Problem indeed seems to be fixed, awesome! Closing.
