### ISSUE TITLE
Temp files stack up continuously

### ISSUE THREAD

**Issue by MoodCharge** [LostRuins/koboldcpp#560]
# Prerequisites

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [[README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md)](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [[searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests)](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [[Discussions](https://github.com/ggerganov/llama.cpp/discussions)](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior

The Kobold Lite builds a folder like C:\Users\UserNmae\AppData\Local\Temp_MEI197082 every time opening the Kobold Lite. I don't know what it is exactly. But this (settings?Environments?) should be one per user, or at least one per model.

# Current Behavior

The Kobold Lite creates a new folder like C:\Users\UserNmae\AppData\Local\Temp_MEI197082 every time opening the Kobold Lite. If you don't load a model and close the program, it will be deleted. But once you load a model, it will be permanetly there. So each time you load a model, it will create a folder roughly 450 MB in size, filling up you system drive. I found this problem when my C drive got occupied by more than 50 GB.

# Environment and Context

Microsoft Edge 120.0.2210.61

Windows 11 22H2

Operating System Windows 11 22H2

I5 10400F, 2060super

KoboldCpp Lite 1.51.1

# Failure Information (for bugs)

It happens on any model. I tested it on 1.52 and 1.49 and they have the same problem.

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.

1. Download the latest Windows binaries executable with CUDA.
2. Open this Kobold Lite 1.51.1 (It will create a folder like C:\Users\UserNmae\AppData\Local\Temp_MEI197082)
3. Load any model.
4. After loading the model, the folder and it's files will stay permanent and can only be deleted manually. Accumulate about 450 MB each time you load a model. Eventually filling up the C drive.

# Failure Logs

It works fine so they are not failure logs, but I'll paste here anyway.

***

```
Welcome to KoboldCpp - Version 1.51
For command line arguments, please refer to --help

***

Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.

Initializing dynamic library: koboldcpp_cublas.dll
==========

Namespace(bantokens=None, blasbatchsize=512, blasthreads=5, config=None, contextsize=2048, debugmode=0, forceversion=0, foreground=False, gpulayers=200, highpriority=False, hordeconfig=None, host='', launch=True, lora=None, model=None, model_param='F:/text_webUI/models/mistral-7b-instruct-v0.2.Q5_K_M.gguf', multiuser=1, noavx2=False, noblas=False, nommap=False, noshift=False, onready='', port=5001, port_param=5001, preloadstory=None, quiet=False, remotetunnel=False, ropeconfig=[0.0, 10000.0], skiplauncher=False, smartcontext=False, tensor_split=None, threads=5, useclblast=None, usecublas=['normal', '0', 'mmq'], usemlock=False)
==========

Loading model: F:\text_webUI\models\mistral-7b-instruct-v0.2.Q5_K_M.gguf
[Threads: 5, BlasThreads: 5, SmartContext: False, ContextShift: True]

---

Identified as LLAMA model: (ver 6)

Attempting to Load...
---

Using automatic RoPE scaling. If the model has customized RoPE settings, they will be used directly instead!
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 |
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   maybe
ggml_init_cublas: CUDA_USE_TENSOR_CORES: maybe
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 2060 SUPER, compute capability 7.5
llama_model_loader: loaded meta data with 24 key-value pairs and 291 tensors from F:\text_webUI\models\mistral-7b-instruct-v0.2.?宬蠭llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = unknown, may not work
llm_load_print_meta: model params     = 7.24 B
llm_load_print_meta: model size       = 4.78 GiB (5.67 BPW)
llm_load_print_meta: general.name     = mistralai_mistral-7b-instruct-v0.2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.11 MiB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: mem required  =   86.04 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 35/35 layers to GPU
llm_load_tensors: VRAM used: 4807.05 MiB
..................................................................................................
Automatic RoPE Scaling: Using model internal value.
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: offloading v cache to GPU
llama_kv_cache_init: offloading k cache to GPU
llama_kv_cache_init: VRAM kv self = 256.00 MiB
llama_new_context_with_model: kv self size  =  256.00 MiB
llama_build_graph: non-view tensors processed: 676/676
llama_new_context_with_model: compute buffer total size = 159.07 MiB
llama_new_context_with_model: VRAM scratch buffer: 156.00 MiB
llama_new_context_with_model: total VRAM used: 5219.06 MiB (model: 4807.05 MiB, context: 412.00 MiB)
Load Model OK: True
Embedded Kobold Lite loaded.
Starting Kobold API on port 5001 at http://localhost:5001/api/

Starting OpenAI Compatible API on port 5001 at http://localhost:5001/v1/
======

Please connect to custom endpoint at http://localhost:5001
```

**Comment by LostRuins** [comment]
How are you exiting your KoboldCpp sessions? 

This is handled by PyInstaller, and it should automatically clean up the temp folder on exit. Are you doing something like force killing the process in task manager?

**Comment by MoodCharge** [comment]
> How are you exiting your KoboldCpp sessions?
> 
> This is handled by PyInstaller, and it should automatically clean up the temp folder on exit. Are you doing something like force killing the process in task manager?

No, I just left click the "X" button on the top right of the command window to exit.

**Comment by LostRuins** [comment]
Hmm then I am not sure. Perhaps something is causing it to crash on exit?

**Comment by MoodCharge** [comment]
I don't know, could you reproduce this problem in your system?

**Comment by LostRuins** [comment]
Nope, if I exit normally the temp folder gets deleted on my system.

**Comment by MoodCharge** [comment]
> Nope, if I exit normally the temp folder gets deleted on my system.

If I don't load the model, the temp folder will be deleted. But once I load any model, it will stay there

**Comment by MoodCharge** [comment]
I wonder if you could make the temp files "permanent" and reuse them the next time, so it doesn't have to create these files each time, could this be a possible solution?

**Comment by LostRuins** [comment]
That behavior would need to be in the Pyinstaller. The self deleting temp file functionality also comes from them.

**Comment by LostRuins** [comment]
Here is some insight: https://github.com/pyinstaller/pyinstaller/issues/2379 

If it does not solve the issue, you might want to open an issue on the PyInstaller repo.

For providing details, you can mention that Python 3.9 is used with PyInstaller version 5.9.0

**Comment by MoodCharge** [comment]
> Here is some insight: [pyinstaller/pyinstaller#2379](https://github.com/pyinstaller/pyinstaller/issues/2379)
> 
> If it does not solve the issue, you might want to open an issue on the PyInstaller repo.
> 
> For providing details, you can mention that Python 3.9 is used with PyInstaller version 5.9.0

Thanks, this seems to be the problem with PyInstaller
