### ISSUE TITLE
Feature request: EOS token handling

### ISSUE THREAD

**Issue by actually-a-cat** [LostRuins/koboldcpp#561]
The prompt format for Mixtral-Instruct requires the EOS token following every model response, and in my experimentation, doing that seems to have some positive effect on its ability to stick to the format. Unfortunately, unless I'm missing something, it seems it's not possible to do that in the Kobold webui, because EOS tokens generated by the model are not included in the content of the text (when set to not ignore, they correctly interrupt generation, but then looking at token lists output with  `--debugmode`, it doesn't get passed on in further generations) and because it is not possible to insert EOS into the text manually (e.g. for creating a pre-made instruct session to continue, in llama.cpp this can be done by putting `</s>` into the prompt text, in Kobold it gets passed on literally)

So for Mixtral-Instruct and any other models that care about EOS tokens in the text, it would be nice to:
* have an option to retain the EOS token in the text when the model generates it
* ~~have a way to type the EOS token into the text~~

In the text editor, the token could be represented with a placeholder, e.g. `{{[EOS]}}`

**Comment by LostRuins** [comment]
What string does the EOS tokenize to in Mixtral?

**Comment by actually-a-cat** [comment]
On load it says this:

`llm_load_print_meta: EOS token        = 2 '</s>'`

**Comment by LostRuins** [comment]
Then you should be able to add that to your prompts, and it will behave like the EOS when tokenized.

**Comment by actually-a-cat** [comment]
Thank you, you're right it does work, I'm not sure why I saw something else when trying earlier.
