### ISSUE TITLE
Generation stopping from SillyTavern doesn't work.

### ISSUE THREAD

**Issue by dariox1337** [LostRuins/koboldcpp#568]
Trying to stop output generation from SillyTavern doesn't work. Koboldcpp just keeps going while SillyTavern stops updating this specific generation or streaming. If I try to start another generation while the first one is still running in kobolcpp, SillyTavern receives API error 'Server is busy.' 

Also, when streaming is enabled and I try to stop generation, koboldcpp outputs `[Errno 32] Broken pipe` in console. Trying to start a new generation after this error causes koboldcpp to crash.

P.S. Tested on Linux with Mixtral.

**Comment by LostRuins** [comment]
Are you connecting via Kobold API or OpenAI API (text generation ooba api)? Some features like aborting an ongoing generation only work with Kobold API

**Comment by LostRuins** [comment]
Is this still an issue in the latest release? I enabled streaming and tested with SillyTavern 1.11 and it seems to work.
