### ISSUE TITLE
[User] Failed to start koboldcpp

### ISSUE THREAD

**Issue by Nillarin** [LostRuins/koboldcpp#57]
Hi, I have such a problem, I turn on the kobold and select the following llama-65b-ggml-q4_0, and nothing happens further than this process, GTX 1080 + i78700k + 32 Ram
How long to wait or nothing works?
![image](https://user-images.githubusercontent.com/68595884/231870534-f8f710ef-2dbe-4637-af62-76887a97a27c.png)

**Comment by Belarrius1** [comment]
32Gb of RAM is not enough, you will need to have a lot of SWAP. (Pagefile on windows)

**Comment by Nillarin** [comment]
Or is it better to try a weaker model? I have 
![image](https://user-images.githubusercontent.com/68595884/231875158-ccecfed7-9efc-45f7-b8bb-0ab915b7ab91.png)
Witch is better

**Comment by Nillarin** [comment]
For me PC

**Comment by Nillarin** [comment]
Okey

**Comment by Nillarin** [comment]
And how do you think 7B will react quickly to my setup?

**Comment by gustrd** [comment]
You have to find it via trial and error, it's impossible to know without
testing.


Em qui., 13 de abr. de 2023 às 17:43, Nillarin ***@***.***>
escreveu:

**Comment by LostRuins** [comment]
Closing this issue - do note that if you see nothing happening, it might still be loading. When mmap is enabled, model load progress is not displayed.
