### ISSUE TITLE
[Enhancement] Support for phi models

### ISSUE THREAD

**Issue by juanjgit** [LostRuins/koboldcpp#574]
Please, add support for Miscosoft's Phi models. Last [phi-2 ](https://huggingface.co/microsoft/phi-2 ) model performance is out of the scale for its size (2.7B).  LlamaCpp recently added support for this architecture in this commit: https://github.com/LostRuins/koboldcpp/commit/b9e74f9bca5fdf7d0a22ed25e7a9626335fdfa48

**Comment by LostRuins** [comment]
yeah that will be merged in the next version
