### ISSUE TITLE
Request support for TheBloke/Magicoder-S-DS-6.7B-GGUF

### ISSUE THREAD

**Issue by MrBenzWorld** [LostRuins/koboldcpp#575]
Please add support for TheBloke/Magicoder-S-DS-6.7B-GGUF

**Comment by hubba1987** [comment]
@MrBenzWorld the hugginface page says the GGUF format is supported by koboldcpp. Have you tried?

**Comment by BeHappy2021** [comment]
I've tried it and also can't get it to work. I've tried magicoder-s-ds-6.7b.Q5_K_M and magicoder-s-ds-6.7b.Q4_K_M on Windows and Linux without success. The error I get is
`'llama'error loading model: invalid unordered_map<K, T> key
llama_load_model_from_file: failed to load model`

**Comment by LostRuins** [comment]
It seems like this GGUF model is defective or possibly incorrectly converted - I'm unable to load it using the official llama.cpp program as well. Might be worthwhile to try requantizing it.

**Comment by BeHappy2021** [comment]
Yep, does look like the model is the issue as it is the only one I can't get to work (I have nous-capybara and openhermes both working). Everything worked fine using this version instead:
[https://huggingface.co/itsdotscience/Magicoder-S-DS-6.7B-GGUF/blob/main/Magicoder-S-DS-6.7B_q8_0.gguf](https://huggingface.co/itsdotscience/Magicoder-S-DS-6.7B-GGUF/blob/main/Magicoder-S-DS-6.7B_q8_0.gguf)

**Comment by BeHappy2021** [comment]
I did a bit more digging and found there was an upstream problem with that model - [https://huggingface.co/TheBloke/Magicoder-S-DS-6.7B-GGUF/discussions](https://huggingface.co/TheBloke/Magicoder-S-DS-6.7B-GGUF/discussions). The upstream issue appears to have been fixed so maybe there will be a fix for this model.
As an alternative I've also found this model which I've tested to generate a few bits of python code: [https://huggingface.co/TheBloke/Everyone-Coder-33B-Base-GGUF](https://huggingface.co/TheBloke/Everyone-Coder-33B-Base-GGUF)

**Comment by LostRuins** [comment]
FYI almost all llama based models can code reasonably well. If you're using Kobold Lite UI, there's a "Coding Assistant" scenario that should help greatly.
