### ISSUE TITLE
IDEA: Handling Openai API tool / function call requests in koboldcpp

### ISSUE THREAD

**Issue by teddybear082** [LostRuins/koboldcpp#585]
Hi LostRuins, hope you are doing well.  It took me far too long, but eventually I was able to hack my way into a grammars format that duplicates openai's function calling response.  Tested in koboldcpp user interface with https://huggingface.co/TheBloke/CodeNinja-1.0-OpenChat-7B-GGUF/resolve/main/codeninja-1.0-openchat-7b.Q4_K_M.gguf so far, and it produced the expected results.  See below:

```
root ::= array

array ::= "[" ws object ws "]"

object ::= "{" ws pairid ws "," ws pairtype ws "," ws pairfunction ws "}"

pairid ::= "\"id\"" ":" ws string

pairtype ::= "\"type\"" ":" ws "\"function\""

pairfunction ::= "\"function\"" ":" ws functionobject

functionobject ::= "{" ws pairname ws "," ws pairarguments ws "}"

pairname ::= "\"name\"" ":" ws string

pairarguments ::= "\"arguments\"" ":" ws "{" ws members ws "}"

members ::= pair (ws "," ws pair)*

pair ::= string ":" ws value

value ::= string | number | "true" | "false" | "null"

number ::= int frac? exp? ws

int ::= "-"? ("0" | [1-9] [0-9]*)

frac ::= "." [0-9]+

exp ::= ("e" | "E") ("+" | "-")? [0-9]+

string ::=
  "\"" (
    [^"\\] |
    "\\" (["\\/bfnrt"] | "u" hex hex hex hex) # escapes
  )* "\"" ws

hex ::= [0-9a-fA-F]

ws ::= [ \t\n\r]*
```

As for the intake of the functions, I took the full array from the "tools:" part of the body of the request and appended it to the end of the user prompt. Example:

```
       Hi how are you doing today? [
            {
                "type": "function",
                "function": {
                    "name": "execute_command",
                    "description": "Executes a command",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "command_name": {
                                "type": "string",
                                "description": "The command to execute",
                                "enum": ["None", "LandShip", "ToggleFlashlight","SpeedUp"],
                            },
                        },
                        "required": ["command_name"],
                    },
                },
            },
        ]
```

So the high level idea would be (but this is where I need your input, including whether you are interested at all in a PR for this), if user calls the chat / completions API and includes as part of the body "tools", a few things happen:

1. Stream for that particular response is automatically set to false.
2. The content of the tools array submitted in the body is appended to the user's message/prompt content in a big string
3. The above grammar is automatically applied in generating the response
4. When we know the above has occurred, the formatting of the response to the user is changed so that a "tool_calls" field is added to the response and the grammar-generated response is provided as the value (example response from openai is in the following format: ```{'role': 'assistant',
 'content': None,
 'tool_calls': [{'id': 'call_o7uyztQLeVIoRdjcDkDJY3ni',
   'type': 'function',
   'function': {'name': 'get_current_weather',
    'arguments': '{\n  "location": "Glasgow, Scotland",\n  "format": "celsius"\n}'}}]}```

It seems like all this would be doable?  The main things missing would be multiple function calls (might have to adjust the grammars, do more testing with llms), and how the model might be able to tell the user that it doesn't want to generate a function response and generate a verbal response instead.  Obviously not all models may be up to the task but that would be up to users to select appropriate models they have vetted.  I wanted to and did test with a 7b figuring if a 7b model could "get" it, presumably bigger coding models would do even better.

**Comment by teddybear082** [comment]
I'm actually going to close this.  As I tested with more complex function calls, things fell apart at least with a 7b model.  It's not that the grammars are bad, I think it's fine and I think the approach above would "work." But I thought about this more and I think people would probably have unfair expectations and post a bunch of issues about how function calling "doesn't work" for their particular use case even if they have a bad model, etc.

**Comment by LostRuins** [comment]
No worries, thanks for trying. Maybe we can revisit in future.

**Comment by lee-b** [comment]
> I'm actually going to close this. As I tested with more complex function calls, things fell apart at least with a 7b model. It's not that the grammars are bad, I think it's fine and I think the approach above would "work." But I thought about this more and I think people would probably have unfair expectations and post a bunch of issues about how function calling "doesn't work" for their particular use case even if they have a bad model, etc.

It depends on the model size and model training; some are designed/trained specifically for function calling.  Also, 7b is far below what most people can now run with quants. Modern models like Phi are very capable even at low parameter counts. Nvidia have said that eventually core tool-calling models will be 1B or so.

**Comment by LostRuins** [comment]
There is actually tool calling from koboldcpp now, and it uses grammar to enforce format. Seems to work well enough.
