### ISSUE TITLE
when network changes or remote network not stable, the fetch resource will failed, is it possible automatic/manul reconnect and resume?

### ISSUE THREAD

**Issue by Dunkelicht** [LostRuins/koboldcpp#589]
Greetings, LostRuins and community!

This app is great, and I can make own options to set Top p ,etc.! I wish I could thank you more!

I use this app in my laptop and usually works great, but when I change wireless network or lan cable, or something like that, it will be pop up:

`Error while submitting prompt: TypeError: NetworkError when attempting to fetch resource.`

It is expected as network change,  http://localhost:5001/#  was temperately lost (I guess).

I thought it was OK, but recently I found even my network was ok but it will also pop up this message, the generating processing in cmd is not stopped or error outputted, I click ctrl+c and reopen it will be fine.

I thought it may related that koboldcpp is using remote js and my connection is metered make remote js load failed. I tried to track it via firefox dev tool, but koboldcpp seems does not connect any remote JavaScript server...

So is there any possibility that when the front-end found that connection lost, the  front-end could reconnect, get history and resume receiving generating data? Or give any suggestion is appreciated!

Please consider, as C# learner I know this may not easy... I wish I could help but I have very limited knowledge in C++/python... 

Happy new year ! Wish you all well in 2024!

**Comment by Vladonai** [comment]
Write your own application to interact with Koboldcpp in C# programming language like I did :) It's complicated, but you can get counseling from ChatGPT, which is pretty ironic in itself.

But maybe the author will make a small improvement specifically for your case. Happy holidays!

**Comment by LostRuins** [comment]
If your connection is interrupted halfway while generating, that message may be lost. However, since the prompt has already been processed, simply reconnect and resubmitting the same request (press send again) should allow you to get the response quickly.
