### ISSUE TITLE
concedo_experimental: LLAMA_CUBLAS build fails, -lcuda missing in CUBLASLD_FLAGS

### ISSUE THREAD

**Issue by Deathcow** [LostRuins/koboldcpp#591]
Currently the koboldcpp_cublas.so built from Makefile in the experimental branch fails to run with "undefined symbol: CuMemCreate". Seems like -lcuda is now required => adding the flag to CUBLASLD_FLAGS seems to work around this issue for now.

**Comment by nalf3in** [comment]
I had the same problem for a while and I confirm it fixes it for me.
For those of us less familiar with makefiles the file to change is "Makefile" in the root directory of the repo and just change the line

"CUBLASLD_FLAGS = -lcublas -lculibos -lcudart -lcublasLt -lpthread" (more things...)

to 

"CUBLASLD_FLAGS = -lcuda -lcublas -lculibos -lcudart -lcublasLt -lpthread"

**Comment by LostRuins** [comment]
Thank you!

**Comment by henk717** [comment]
PR #593 will fix this

**Comment by LostRuins** [comment]
Should be fixed now, please reopen this if there are any further issues!
