### ISSUE TITLE
Horde shows right ContextLimit, console stuck to 2048

### ISSUE THREAD

**Issue by rondlite** [LostRuins/koboldcpp#596]
When changing contextlimit to 4096, the output of the console stuck at `ContextLimit: 1934/2048`

The horde APi shows that I am accepting 4096.

Do I need to rebuild after changing the max ctx set for Horde in `koboldcpp.py` ?

**Comment by LostRuins** [comment]
After setting `--contextsize`, you should also adjust the requested `max_context_length` from your UI. 
If you are using lite, This can be found in the settings panel:
![image](https://github.com/LostRuins/koboldcpp/assets/39025047/52c9df5e-2b8d-4969-ac4e-e3952ca789cb)

**Comment by rondlite** [comment]
So changing in `koboldcpp.py` is not enough?
```
maxctx = 4096
maxhordectx = 4096
```

I will give it a shot, changed in `koboldcpp.py` since I wanted to skip UI..

**Comment by LostRuins** [comment]
For the embedded horde worker, there is a separate horde config. See the args for --hordeconfig on the wiki. It's also in the GUI launcher.

**Comment by rondlite** [comment]
I did use the horde config (see above) and set it to `4096`. 
Horde gets advertised that I accept 4096 ctx, but when a request arrives it becomes:
` ContextLimit: 614/2048, Processing:0.43s (5.5ms/T), Generation:3.62s (55.8ms/T), Total:4.06s (16.02T/s)`

Wonder where the 2048 comes from, will check traffic from horde to make sure the request is actually 4096 size, but given the log I am pretty sure the logged max ctx is what is on koboldcpp.

**Comment by LostRuins** [comment]
That is fine then. It means the requestor only asked for 2048 context.

Horde context limit is a *limit*, not an enforcement. It is perfectly fine for users to request values lower than the limit, and koboldcpp will respond appropriately.

**Comment by rondlite** [comment]
I figured out it must be in my horde client or horde host, indeed is not koboldcpp.
