### ISSUE TITLE
Issues with cloudflare tunnels on windows

### ISSUE THREAD

**Issue by MathapMathonwy** [LostRuins/koboldcpp#601]
I noticed more automated support was added for Cloudflare tunnels on Windows, have encountered odd errors when trying to use it. These do not appear when running on my local lan without Cloudflare (or when accessing localhost:5001 obviously).
![image](https://github.com/LostRuins/koboldcpp/assets/155705636/07f64023-55e7-4899-8da2-8ca11542850b)

Prior to this error occurring I can see the generation streaming in normally, then it vanishes when this error appears.

EDIT: Apologies! This is with the current release, v1.54

**Comment by MathapMathonwy** [comment]
Additionally, I'm unsure if this is intended behavior, but a copy of the cloudflared executable is downloaded every time the server launched with the tunnel option, regardless of whether the executable is present in the same directory.

**Comment by MathapMathonwy** [comment]
I've run some additional tests, the error still occurs with streaming disabled. I had a suspicion it might be related to packet loss, but that doesn't appear to be the case. Testing with cloudflare shows I don't seem to be experiencing connection issues (and the koboldcpp server continues to run and accept requests over the cloudflared tunnel)

**Comment by LostRuins** [comment]
Yeah currently the latest cloudflared binary is always downloaded when launching with remotetunnel. I should probably change that.

Is it possible that cloudflare was experiencing downtime when you observed this issue? Could you try it again, and if it fails again, check what was the response received (open the chrome devtools tab with F12, click Network, click on the failed request and see what the server Response was)

**Comment by MathapMathonwy** [comment]
No errors show up in the network tab of Chrome Devtools, but there are errors in console.

![image](https://github.com/LostRuins/koboldcpp/assets/155705636/857a0704-646f-48dc-8e75-ef4578934db2)

I'm pretty sure that cloudflare is working. I can load the kobold UI from the URL provided, submit a request, and it does generate a reply. When streaming is enabled I can watch the reply get generated in the UI, the message just gets removed if when the error occurs. I can load the UI using the cloudflare link even on my phone using its data connection. So it must be working on some level?

**Comment by MathapMathonwy** [comment]
This issue appears to be related to generation time. If I use a model that I can load entirely on GPU (Mistral based models), then I don't see the error, and UI works normally, with generated responses.
My preferred models have to to be run split between GPU and CPU, but have very long generation times on my hardware (60+ seconds)

**Comment by LostRuins** [comment]
Ah yes, error 524 means the request timed out - took too long to respond. Cloudflare could be timing out slow requests on their end.

Here are 2 solutions you can try:
1. Switch the "Streaming" option to SSE, which would avoid a long sync generate call and keep the connection alive.
2. Reduce the "amount to generate" to a lower value so it replies faster.

**Comment by MathapMathonwy** [comment]
Neither seems to work, but thank you very much for your help.
