### ISSUE TITLE
[API] Missing "usage" section in the response

### ISSUE THREAD

**Issue by juanjgit** [LostRuins/koboldcpp#603]
Hello!  I am trying to use KonboldCpp API instead of OpenAI in the [Notepad++ plugin](https://github.com/Krazal/nppopenai) but I get this error:

> Missing "choices" and/or "usage" from JSON response

I did a sample request and compared to OpenAI example.

OpenAi:

```json
{
    "id": "chatcmpl-abc123",
    "object": "chat.completion",
    "created": 1677858242,
    "model": "gpt-3.5-turbo-1106",
    "usage": {
        "prompt_tokens": 13,
        "completion_tokens": 7,
        "total_tokens": 20
    },
    "choices": [
        {
            "message": {
                "role": "assistant",
                "content": "\n\nThis is a test!"
            },
            "logprobs": null,
            "finish_reason": "stop",
            "index": 0
        }
    ]
}
```

KoboldCpp:

```json
{
   "id":"chatcmpl-1",
   "object":"chat.completion",
   "created":1,
   "model":"koboldcpp/deepseek-coder-1.3b-instruct.Q5_K_S",
   "choices":[
      {
         "index":0,
         "message":{
            "role":"assistant",
            "content":"Hello, it's me. How can I assist you with your programming or computer science questions today?\n"
         },
         "finish_reason":"length"
      }
   ]
}
```

So, yes, the "usage" section of the JSON response does not exists. Could you please implement the "usage" object in the JSON responses?

This is the [reference in the official API](https://platform.openai.com/docs/api-reference/chat/object#chat/object-usage)

**Comment by LostRuins** [comment]
Yeap, this can be added, however those usage values may not be accurate.

**Comment by juanjgit** [comment]
> Yeap, this can be added, however those usage values will not be accurate as the current API does not measure token usage when generating. So it will just be placeholder values.

That would be great. I don't think this particular plugin is going to use those numbers other than to check if the API answer is well-formatted.

**Comment by LostRuins** [comment]
Should be fixed in the latest release

**Comment by juanjgit** [comment]
Working on 1.55.1. Thank you!
