### ISSUE TITLE
Just an observation

### ISSUE THREAD

**Issue by Vladonai** [LostRuins/koboldcpp#605]
Model "toxicqa-Llama2-13B-GGUF" [https://huggingface.co/TheBloke/toxicqa-Llama2-13B-GGUF](https://huggingface.co/TheBloke/toxicqa-Llama2-13B-GGUF)

The Q_2_K version (5.43Gb) fits completely in video memory (RTX3050, 8GB VRAM). The result of the generation is 250ms per token, тhe CPU is barely utilized.

The Q_6_K version (10.7Gb) does not fit in the video memory completely (--gpulayers 17 of 41). The result of the generation is 300ms per token.

If you don't load the Q_6_K version into video memory almost at all (--gpulayers 1 of 41), the generation result will be 350ms per token.

Context is processed quickly (if there is free video memory). But there are some unclear points about generation.

**Comment by LostRuins** [comment]
If you can fit the whole model, be sure to disable "lowvram" so the kv cache gets offloaded.

**Comment by Vladonai** [comment]
Model "Dawn-v2-70B.q2_k.gguf" (27,2Gb): --gpulayers 15 of 81, the result of the generation is ~850ms per token

Model "megadolphin-120b.Q2_K.gguf" (47,2Gb): --gpulayers 15 of 141, the result of the generation is ~1500ms per token

For my configuration (i12500, 64Gb DDR4-3100, RTX3050 8GB) these are pretty amazingly good results.
