### ISSUE TITLE
Using grammar on phi2 floods the console with GGML_ASSERT_CONTINUE: D:\a\koboldcpp\koboldcpp\llama.cpp:11007: false

### ISSUE THREAD

**Issue by adam-ah** [LostRuins/koboldcpp#606]
# Problem

Using grammar on phi2 floods the console with 
```
GGML_ASSERT_CONTINUE: D:\a\koboldcpp\koboldcpp\llama.cpp:11007: false
GGML_ASSERT_CONTINUE: D:\a\koboldcpp\koboldcpp\llama.cpp:11007: false
...
```

The output is still correct, eventually, but there are many thousands of this message.

Other models work well with no errors with the same grammar file.

# Simple code to reproduce the problem

## Download 
a Phi2 gguf file from https://huggingface.co/TheBloke/phi-2-GGUF/tree/main
(tested and same problem with `phi-2.Q5_K_M.gguf`, `phi-2.Q6_K.gguf`, `phi-2.Q4_K_M.gguf`)

## Python code
```
import requests
import sys

if len(sys.argv) != 2:
    print("Usage: python script.py <path-to-text-file>")
    sys.exit(1)

grammar_file_path = sys.argv[1]

with open(grammar_file_path, "r") as f:
    grammar = f.read()

prompts = [
    "How's the weather in London?",
]

for prompt in prompts:
    data_json = { "prompt": prompt, "temperature": 0.1, "n_predict": 512, "stream": False, "grammar": grammar }

    resp = requests.post(
        url='http://10.0.0.10:5001/api/v1/generate',
        headers={"Content-Type": "application/json"},
        json=data_json,
    )
    result = resp.json()["results"]

    print(f"Prompt: {prompt}")
    print(f"Result: {result}\n")
```

## Grammar code
```
root ::= Weather
Weather ::= "{"   ws   "\"temperature_celsius\":"   ws   number   ","   ws   "\"sky\":"   ws   string   "}"
Weatherlist ::= "[]" | "["   ws   Weather   (","   ws   Weather)*   "]"
string ::= "\""   ([^"]*)   "\""
boolean ::= "true" | "false"
ws ::= [ \t\n]*
number ::= [0-9]+   "."?   [0-9]*
stringlist ::= "["   ws   "]" | "["   ws   string   (","   ws   string)*   ws   "]"
numberlist ::= "["   ws   "]" | "["   ws   string   (","   ws   number)*   ws   "]"
```

## Call the API

```
python3 grammar.py weather.gbnf 
```

## Result
<img width="1030" alt="image" src="https://github.com/LostRuins/koboldcpp/assets/3745745/4205dc61-2b05-49f7-8c3b-9808fb0dffe4">

**Comment by LostRuins** [comment]
For this case, it means that a unknown (abnormal) token was encountered when converting the output back into a string in the BPE detokenizer. If your output is fine, I wouldn't worry about it.

**Comment by adam-ah** [comment]
It's not a "worry", it's an actual problem: for anything more than a few characters output the generation is rendered so slow that it becomes useless due to the console writes holding back the system. I use the Phi2 model because it's fast, not because it's good. The bug makes is render approx 100x slower than Mixtral

**Comment by LostRuins** [comment]
Fair enough - I'll make it such that the assert only triggers once per session.

**Comment by LostRuins** [comment]
Should be fixed in the latest release

**Comment by adam-ah** [comment]
It does work indeed, thanks, happy to close the bug.

For reference, these are the speed differences on the actual task we use the models on (btw, neither phi2 nor tiny actually solves the problem, only mixtral generate valuable outputs)

### Phi2
`ContextLimit: 281/2048, Processing:0.06s (0.8ms/T), Generation:4.04s (38.1ms/T), Total:4.10s (25.83T/s)`

### Mixtral
`ContextLimit: 298/2048, Processing:2.36s (24.3ms/T), Generation:9.21s (91.2ms/T), Total:11.57s (8.73T/s)`

### Tinyllama
`ContextLimit: 321/2048, Processing:0.02s (0.2ms/T), Generation:1.31s (12.6ms/T), Total:1.33s (78.37T/s)`

Phi2 is surprisingly slow compared to both mixtral and tiny, especially that in our context it does not even solve our problem.

**Comment by LostRuins** [comment]
You can try Tiefighter, it's a good model. https://huggingface.co/KoboldAI/LLaMA2-13B-Tiefighter-GGUF
