### ISSUE TITLE
[API] & [langchain] - Getting strange results when using API and langchain memory

### ISSUE THREAD

**Issue by ChaseRichardsonGit** [LostRuins/koboldcpp#609]
Hello,

I am using koboldcpp_rocm with a few different models depending on needs.  I have tried other openai compatible API servers serving local models and have only run into my issue with kobold.  

Using langchain.memory ConversationBufferMemory in my scripts works great with other API's and openai directly.  However when I try to use kobold, memory doesn't seem to be handled the same by the API server.  What I mean by this, is I see the conversation history showing up in the "INPUT" as would be expected, however the model doesn't seem to have any context of that history when asked to recall something that was previously mentioned by the user or assistant.

I was told on Discord to post an issue, but I'm not sure what other information would be most helpful at this point.

I'm happy to provide any logs or screenshots needed.  

Thanks,
Chase

**Comment by LostRuins** [comment]
Is there a separate api that controls what goes in and out of langchain memory? Because as far as I know, OpenAI API has no specification for permanent data storage - it is stateless - everything required is passed in within the same API call.

**Comment by ChaseRichardsonGit** [comment]
As far as I know you're correct that OpenAI API is stateless.  I don't know enough about the inner workings of the inference engines and API's to really know what's going wrong.  I just know with the same exact code "memory" works via OpenAI API and LM Studio API, but not with Kobold.  Kobold is by far my favorite, but no matter what I've tweaked I cannot get "memory" working well at all, though I do see the "memory" in the "Input" of the Kobold API call.

If there's any way to debug further or any logs I could provide from either API that's working, I'd be happy to provide.

Thanks for a great piece of software either way!
