### ISSUE TITLE
Contextshift requiring context mismatch.

### ISSUE THREAD

**Issue by LBrockmanK** [LostRuins/koboldcpp#613]
Recently adjusted my settings to improve performance and noticed when I was done that contextshift was no longer working, every generation reprocessed the full prompt (no world info / memories).

After some experimentation I tracked it down. Contextshift seems to only be working if the context size I set in sillytavern exceeds my setting in koboldcpp. It doesn't matter how much of that context is used, behavior is the same for new chats with only a few hundred tokens or existing chats with 10k+ tokens.

**Comment by Spacellary** [comment]
Just for reference and information reasons, I'll keep updating if I notice anything weird there too:

I have the same context size in Agnaistic AI and in Koboldcpp launch parameters and context shifting is working as intended. Or at least I didn't notice yet.

**Comment by LBrockmanK** [comment]
As an update, contextshift stopped happening again in a recent session. Not sure why at this point. It happened after reaching the context limit but not immediately upon that.

**Comment by LBrockmanK** [comment]
I keep getting inconsistent results, closing this issue as it is not accurate and I haven't determined the specific issue at play.
