### ISSUE TITLE
Request: Additional max context values between 32k and 64k

### ISSUE THREAD

**Issue by candre23** [LostRuins/koboldcpp#618]
As multi-GPU users are still stuck with the "context on 1st GPU only" problem, and 64k doesn't fit into 24GB, would it be possible to get a few additional valid context values so we can squeeze the most out of the VRAM we're allowed to use?  I propose 40960, 49152, 57344 be added to the list of allowed values.

**Comment by LostRuins** [comment]
Added in 1.56
