### ISSUE TITLE
Make compilation problem on last experimental (20/01/2024)

### ISSUE THREAD

**Issue by Nexesenex** [LostRuins/koboldcpp#626]
Here comes the problem, under WIndows 11 & w64devkit  :

gpttype_adapter.cpp: In function 'ModelLoadResult gpttype_load_model(load_model_inputs, FileFormat, FileFormatExtraMeta ':
gpttype_adapter.cpp:786:13: error: 'ggml_cuda_set_main_device' was not declared in this scope; did you mean 'ggml_v3_cuda_set_main_device'?
  786 |             ggml_cuda_set_main_device(cu_parseinfo_maindevice);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |             ggml_v3_cuda_set_main_device
make: *** [Makefile:458: gpttype_adapter_cublas.o] Error 1

**Comment by LostRuins** [comment]
Yeap I am aware, there were some api changes. Should be fixed now.
