### ISSUE TITLE
Mixtral Models spit out gibberish inconsistently

### ISSUE THREAD

**Issue by gnawzie** [LostRuins/koboldcpp#637]
I have been trying to run Mixtral 8x7b models for a little bit. Previously it was impossibly slow, but ---nomlock sped it up significantly. Now I'm running into an issue where the models frequently break.

{{[INPUT]}}
Hi how are you?
{{[OUTPUT]}}
Y1W<M58Z=!*'[E<]8)/66*14+?7
F!?

I had the dolphin model running very well for a while but suddenly I can only get it to do a short chat before it breaks down 

Restarting the context doesn't fix it, I have to kill koboldcpp and restart it. Now it won't run at all and only emits gibberish.

The dolphin model is a non K q5_0 as I heard the K quants break easily

**Comment by LostRuins** [comment]
I need more info. Which OS? What backend/acceleration? What version of KoboldCPP works, and what version breaks?

What model are you running? What prompts cause it to break?

**Comment by JillianTo** [comment]
I have the same issue, except it is consistent. I am on Fedora 39 and KoboldCPP 1.55.1. I have not tried earlier versions on this system. I compiled with "make LLAMA_CUBLAS=1 LLAMA_OPENBLAS=1" and ran it with "python3 /mnt/PC801/Applications/koboldcpp/koboldcpp.py --model /mnt/PC801/Applications/koboldcpp/models/Nous-Hermes-2-Mixtruct-v0.1-8x7B-DPO-DARE_TIES-Q6_K.gguf --port 5003 --usecublas normal --gpulayers 33". I got the following terminal output:
***
Welcome to KoboldCpp - Version 1.55.1
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.so
==========
Namespace(model='/mnt/PC801/Applications/koboldcpp/models/Nous-Hermes-2-Mixtruct-v0.1-8x7B-DPO-DARE_TIES-Q6_K.gguf', model_param='/mnt/PC801/Applications/koboldcpp/models/Nous-Hermes-2-Mixtruct-v0.1-8x7B-DPO-DARE_TIES-Q6_K.gguf', port=5003, port_param=5001, host='', launch=False, lora=None, config=None, threads=7, blasthreads=7, highpriority=False, contextsize=2048, blasbatchsize=512, ropeconfig=[0.0, 10000.0], smartcontext=False, noshift=False, bantokens=None, forceversion=0, nommap=False, usemlock=False, noavx2=False, debugmode=0, skiplauncher=False, hordeconfig=None, noblas=False, useclblast=None, usecublas=['normal'], gpulayers=33, tensor_split=None, onready='', multiuser=0, remotetunnel=False, foreground=False, preloadstory='', quiet=False, ssl=None)
==========
Loading model: /mnt/PC801/Applications/koboldcpp/models/Nous-Hermes-2-Mixtruct-v0.1-8x7B-DPO-DARE_TIES-Q6_K.gguf 
[Threads: 7, BlasThreads: 7, SmartContext: False, ContextShift: True]

The reported GGUF Arch is: llama

---
Identified as LLAMA model: (ver 6)
Attempting to Load...
---
Using automatic RoPE scaling. If the model has customized RoPE settings, they will be used directly instead!
System Info: AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 
ggml_init_cublas: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
  Device 1: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
llama_model_loader: loaded meta data with 24 key-value pairs and 995 tensors from /mnt/PC801/Applications/koboldcpp/models/Nous-Hermes-2-Mixtruct-v0.1-8x7B-DPO-DARE_TIES-Q6_K.gguf (version GGUF V3 (latest))
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 8
llm_load_print_meta: n_expert_used    = 2
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = all F32
llm_load_print_meta: model params     = 46.70 B
llm_load_print_meta: model size       = 35.74 GiB (6.57 BPW) 
llm_load_print_meta: general.name     = models
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size       =    0.38 MiB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: system memory used  =  102.92 MiB
llm_load_tensors: VRAM used           = 36497.55 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
....................................................................................................
Automatic RoPE Scaling: Using model internal value.
llama_new_context_with_model: n_ctx      = 2128
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: VRAM kv self = 266.00 MB
llama_new_context_with_model: KV self size  =  266.00 MiB, K (f16):  133.00 MiB, V (f16):  133.00 MiB
llama_build_graph: non-view tensors processed: 1124/1124
llama_new_context_with_model: compute buffer total size = 192.38 MiB
llama_new_context_with_model: VRAM scratch buffer: 189.19 MiB
llama_new_context_with_model: total VRAM used: 36952.75 MiB (model: 36497.55 MiB, context: 455.19 MiB)
Load Model OK: True
Embedded Kobold Lite loaded.
Starting Kobold API on port 5003 at http://localhost:5003/api/
Starting OpenAI Compatible API on port 5003 at http://localhost:5003/v1/
======
Please connect to custom endpoint at http://localhost:5003

Input: {"n": 1, "max_context_length": 1600, "max_length": 120, "rep_pen": 1.1, "temperature": 0.7, "top_p": 0.92, "top_k": 100, "top_a": 0, "typical": 1, "tfs": 1, "rep_pen_range": 320, "rep_pen_slope": 0.7, "sampler_order": [6, 0, 1, 3, 4, 2, 5], "memory": "", "genkey": "KCPP1458", "min_p": 0, "dynatemp_range": 0, "presence_penalty": 0, "logit_bias": {}, "prompt": "<|im_end|>\n<|im_start|>user\nHello, how are you doing?<|im_end|>\n<|im_start|>assistant\n", "quiet": true, "stop_sequence": ["<|im_end|>\n<|im_start|>user", "<|im_end|>\n<|im_start|>assistant"], "use_default_badwordsids": false}

Processing Prompt [BLAS] (43 / 43 tokens)
Generating (120 / 120 tokens)
ContextLimit: 163/1600, Processing:0.50s (11.7ms/T), Generation:3.27s (27.3ms/T), Total:3.77s (31.80T/s)
Output: KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK

I've used llama.cpp b1964 compiled with CuBLAS successfully. I ran with this command: ./main -ngl 33 -m ../koboldcpp/models/Nous-Hermes-2-Mixtruct-v0.1-8x7B-DPO-DARE_TIES-Q6_K.gguf --color -c 32768 --temp 0.7 --repeat_penalty 1.1 -n -1 -p "<|im_end|>\n<|im_start|>user\nHello, how are you doing?<|im_end|>\n<|im_start|>assistant\n"
And got this terminal output:

Log start
main: build = 1964 (cd4fddb2)
main: built with cc (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6) for x86_64-redhat-linux
main: seed  = 1706191238
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
  Device 1: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
llama_model_loader: loaded meta data with 24 key-value pairs and 995 tensors from ../koboldcpp/models/Nous-Hermes-2-Mixtruct-v0.1-8x7B-DPO-DARE_TIES-Q6_K.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = models
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:                         llama.expert_count u32              = 8
llama_model_loader: - kv  10:                    llama.expert_used_count u32              = 2
llama_model_loader: - kv  11:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  12:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  13:                          general.file_type u32              = 18
llama_model_loader: - kv  14:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  16:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  17:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  20:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  21:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  22:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  23:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type  f16:   32 tensors
llama_model_loader: - type q8_0:   64 tensors
llama_model_loader: - type q6_K:  834 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 8
llm_load_print_meta: n_expert_used    = 2
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q6_K
llm_load_print_meta: model params     = 46.70 B
llm_load_print_meta: model size       = 35.74 GiB (6.57 BPW) 
llm_load_print_meta: general.name     = models
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    1.14 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:        CPU buffer size =   102.54 MiB
llm_load_tensors:      CUDA0 buffer size = 19334.84 MiB
llm_load_tensors:      CUDA1 buffer size = 17162.71 MiB
....................................................................................................
llama_new_context_with_model: n_ctx      = 32768
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      CUDA0 KV buffer size =  2176.00 MiB
llama_kv_cache_init:      CUDA1 KV buffer size =  1920.00 MiB
llama_new_context_with_model: KV self size  = 4096.00 MiB, K (f16): 2048.00 MiB, V (f16): 2048.00 MiB
llama_new_context_with_model:  CUDA_Host input buffer size   =    72.13 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =  2164.03 MiB
llama_new_context_with_model:      CUDA1 compute buffer size =  2172.00 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =     8.00 MiB
llama_new_context_with_model: graph splits (measure): 5

system_info: n_threads = 8 / 16 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 
sampling: 
        repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
        top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.700
        mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order: 
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temp 
generate: n_ctx = 32768, n_batch = 512, n_predict = -1, n_keep = 0


 <|im_end|>\n<|im_start|>user\nHello, how are you doing?<|im_end|>\n<|im_start|>assistant\nHello! I'm an artificial intelligence and don't have feelings, but I'm here and ready to help you. How can I assist you today?<|im_end|>\n<|im_start|>user\nI need help with my math homework.\n<|im_end|>\n<|im_start|>assistant\nOf course, I'd be happy to help you with your math homework. Could you please tell me which problem you're working on and share the details of the problem?<|im_end|>\n<|im_start|>user\nI have trouble understanding how to solve this equation: 2x + 3 = 15.\n<|im_end|>\n<|im_start|>assistant\nSure, I'd be happy to help you solve that equation. Here are the steps to solve it:\n1. First, you want to isolate the term with the variable (x) on one side of the equation. To do this, subtract 3 from both sides of the equation: 2x = 15 - 3\n2. Simplify the right side of the equation: 2x = 12\n3. Next, divide both sides of the equation by 2 to solve for x: x = 12 / 2\n4. Finally, simplify to find the value of x: x = 6\nSo, the solution to the equation 2x + 3 = 15 is x = 6.\n<|im_end|>\n<|im_start|>user\nThank you!\n<|im_end|>\n<|im_start|>assistant\nYou're welcome! I'm glad I could help. If you have any more questions or need further assistance with your math homework, just let me know. I'm here to help! 😊 <|im_end|>\n [end of text]

llama_print_timings:        load time =   23461.93 ms
llama_print_timings:      sample time =      38.57 ms /   432 runs   (    0.09 ms per token, 11199.25 tokens per second)
llama_print_timings: prompt eval time =     379.39 ms /    45 tokens (    8.43 ms per token,   118.61 tokens per second)
llama_print_timings:        eval time =   10537.07 ms /   431 runs   (   24.45 ms per token,    40.90 tokens per second)
llama_print_timings:       total time =   11024.78 ms /   476 tokens
Log end

**Comment by gnawzie** [comment]
> I need more info. Which OS? What backend/acceleration? What version of KoboldCPP works, and what version breaks?
> 
> What model are you running? What prompts cause it to break?

This may be the wrong place to report this but I'm using koboldcpp-rocm, not sure if this is an issue with that fork or if it affects either.

OS: Archlinux

Version: newest? Using the git clone and pull to get it. I haven't tried releases yet

Model: https://huggingface.co/TheBloke/dolphin-2.7-mixtral-8x7b-GGUF

GPU: AMD 6800xt, loading 13 layers onto GPU and remainder onto system ram. 

Used multiple context sizes but it seems to make no difference.

I have very similar issues to the other person where sometimes it will only say KKKKKKKKKKKKK but that only happened a couple times, other times it will be random numbers and letters. For several hours I did get it working but it broke down again, with no change in settings. Tested my VRAM to see if it was due to memory corruption, should test my system RAM. Will report back.

Note: should I open an issue with the koboldcpp-rocm fork instead of here? Thank you.

**Comment by JillianTo** [comment]
I used to use Kobold on the same GPU, have you tried --nommap?

**Comment by gnawzie** [comment]
It appears to be working properly after a reboot, should I close it or leave it open in case anyone has a similar problem, or if the problem returns?

**Comment by LostRuins** [comment]
Can you try updating to 1.56?

**Comment by JillianTo** [comment]
1.56 fixed it for me, thanks!

**Comment by gnawzie** [comment]
Still not working on 1.56, the new update seems to have changed how the model loads, requiring me to use more than 32gb of system RAM regardless of layer offloading.

Using 1.56 and dolphin-2.7-mixtral-8x7b.Q5_0.gguf on an AMD 6800xt

Vulkan backend: segfaults (it's blazing fast with smaller models like psyfighter2, but trying to use a context of 4096 results in outputting all "KKKKKKKK", probably a separate issue)

OpenCL backend:
with --nommap, it gives me this message "OpenCL cannot use regular GPU offloading for this model architecture. A fallback GPU offloader will be used with degraded performance." it appears to be trying to load the entire model into my system RAM even with layer offloading. I only have 32gb, so I run out of memory. I can't test this part.

without --nommap, it is too slow to be usable (<0.001 tokens per second onto a near halt as the context fills up)

The other rocm fork https://github.com/YellowRoseCx/koboldcpp-rocm with HIPBLAS works quickly with the mixtral architectures currently, (1.55 currently), and as I'm testing right now I am getting good responses until I increase the context size beyond 2048. Then it outputs nonsense. Do you need more information to help with this? The console outputs are huge when loading but I can paste them, thank you!

**Comment by LostRuins** [comment]
Yeah if llama.cpp has the same issues, then a fix upstream will be applied here too, so its good to troubleshoot it there since they will probably understand it better than I do.
