### ISSUE TITLE
Performance Regression in 1.56

### ISSUE THREAD

**Issue by rcchan123** [LostRuins/koboldcpp#649]
There has been a notable performance regression from 1.55.1 to 1.56:

1.55.1:
1. SillyTavern: ![Screenshot (44)](https://github.com/LostRuins/koboldcpp/assets/18182696/102b958b-cd4a-46b0-82c3-31b9e77c3f38)
2. Kobold Lite: ![Screenshot (46)](https://github.com/LostRuins/koboldcpp/assets/18182696/4d44edf4-c07b-4957-88c0-6da0fc6e5cfc)

1.56:
1. SillyTavern: ![Screenshot (45)](https://github.com/LostRuins/koboldcpp/assets/18182696/5effb428-7d43-45bd-b84a-7428c124933f)
2. Kobold Lite: ![Screenshot (47)](https://github.com/LostRuins/koboldcpp/assets/18182696/d84a2a9e-c121-427b-aebd-75506e8d982f)

Please let me know if there is any other information I should provide. Thanks!

**Comment by LostRuins** [comment]
Are you using multigpu?

**Comment by rcchan123** [comment]
System Info:
Processor: 12th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz
RAM: 32.0 GB
System type: 64-bit operating system, x64-based processor
GPU: NVIDIA GeForce RTX 3060 Laptop GPU

Flags:
--gpulayers=28 --usecublas lowvram --blasbatchsize=512 --contextsize 3072  --bantokens [ --foreground

Model:
OpenHermes-2.5-AshhLimaRP-Mistral-7B-Q5_K_M.gguf

Also, no, I am not using MultiGPU

**Comment by LostRuins** [comment]
I'm unable to find a solution.

Related: https://github.com/LostRuins/koboldcpp/issues/642

**Comment by rcchan123** [comment]
Update, It appears that with mmq on, there is no longer a speed regression on my device. It still occurs with mmq off, but this is faster anyway.
