### ISSUE TITLE
Changing the template for OpenAI-compatible chat completion

### ISSUE THREAD

**Issue by ewired** [LostRuins/koboldcpp#654]
I would like to change the template to ChatML when using the OpenAI-compatible chat completion endpoint. It looks like this is possible as of #466 but with the client continue.dev I cannot add an arbitrary key to the request body. Could it be possible to configure koboldcpp to use ChatML by default for any chat request?

**Comment by LostRuins** [comment]
The proper way to do that would be to add the adapter field with the desired tags. If you can't do that, you would have to modify the koboldcpp.py file and change the instruct tags from Alpaca to ChatML. Is there any reason why Alpaca format does not work for you?

**Comment by ewired** [comment]
I found that the Alpaca format works for some models, but some other models trained for ChatML will exhaust the token limit for every message with a never-ending screed of tangentially-related information and follow-up questions. While it demonstrated impressive performance of koboldcpp over llamafile, some desirable models like NeuralBeagle would not be viable as a continue.dev assistant due to the format mismatch. To clarify, I was not requesting to change the default behavior in koboldcpp, but rather to provide the adapter fields on a per-instance rather than per-request basis. For example, using CLI flags or an external .json file to specify the adapter fields. This would work for those running the self-contained Windows build that can't edit the Python source, and clients that can't include non-OpenAI-compatible options in each request.

**Comment by ewired** [comment]
I'm thinking of a design where you can specify a JSON file to be merged with every incoming request to the chat endpoint. Like specify `--completions-chat-body chatml.json` and that JSON file will contain the right adapter field. It can merge the two dictionaries with the request body taking precedence. If this sounds good to you, I can try to work on a PR in Codespaces (sadly can't use my Windows GPU workstation because it ran out of space and I ain't got no more money.)

**Comment by ewired** [comment]
The request-level option is good, and my suggested design has the request's options take precedence. My thought is that without the ability to specify `adapter` outside of the request, the `/v1/chat/completions` endpoint with non-Alpaca models isn't compatible with OpenAI clients. Optional extensions to OpenAI (like `grammar`) are usually fine, but this one is mandatory to use many models, unfortunately limiting koboldcpp for many use-cases. It needs every client to have specific integration for koboldcpp, so it isn't OpenAI-compatible. In my view, the added complexity is small, and an easy win for how many existing integrations and models are unlocked.

It was trivial to temporarily work around this by writing an OpenAI-to-Kobold HTTP proxy server, using the same method I proposed to add Kobold-specific JSON to every request on behalf of OpenAI clients:
```
URL="http://localhost:5001" MERGE='{"adapter": {
        "templates": {
          "system": {
              "start": "<|im_start|>system\n",
              "end": "<|im_end|>\n"
          },
          "user": {
              "start": "<|im_start|>user\n",
              "end": "<|im_end|>\n"
          },
          "assistant": {
              "start": "<|im_start|>assistant\n",
              "end": "<|im_end|>\n"
          },
          "after_last_message": ""
        }
    }}' deno eval 'Deno.serve(async (req) => {
  let url = new URL(await Deno.env.get("URL")); url.pathname = new URL(req.url).pathname;
  let body = {...(await req.json()), ...(JSON.parse(Deno.env.get("MERGE")))};
  return await fetch(url, {method:"POST", body: JSON.stringify(body)});
});'
```

**Comment by jppaolim** [comment]
Hi supporting this as I am desperatly looking for a local alternative for downstream task that expect openAI ... so I can't touch the API request, but starting the server with a certain type of configuration including temperature, adapter etc... would be amazing. In the meantime, how did you exactly @ewired  write your proxy ? anyway to share the full code js, python or whatever :) ? thanks !

**Comment by LostRuins** [comment]
@ewired you can choose to remove stop tokens with `trim_stop` (see api documentation)

**Comment by LostRuins** [comment]
Hello, this has now been added in the latest version! You can specify an adapter json to use on load.
