### ISSUE TITLE
Termux Requirements

### ISSUE THREAD

**Issue by jojorne** [LostRuins/koboldcpp#662]
To make it work with Termux you have to change numpy and sentencepiece version.
```Python
numpy>=1.24.4
sentencepiece>=0.1.98
transformers>=4.34.0
gguf>=0.1.0
customtkinter>=5.1.0
protobuf>=4.21.0
```

**Comment by LostRuins** [comment]
You don't actually need any of that except customtkinter at runtime. Those requirements are intended for people who want to *convert* models, which I don't think you'd be doing in termux.

Does it not work if you don't install them?
