### ISSUE TITLE
Here is a script to automate the build on Windows

### ISSUE THREAD

**Issue by jojorne** [LostRuins/koboldcpp#664]
- Create a folder called "KoboldCpp".
- Download and extract [KoboldCpp](https://github.com/LostRuins/koboldcpp) inside that folder or open the CMD inside the folder and use this command `git clone https://github.com/LostRuins/koboldcpp.git`. You must have [Git for Windows](https://gitforwindows.org/) installed for this.
- Install the [Visual Studio](https://visualstudio.microsoft.com/downloads) with the "Desktop development with C++" loadout.
- Install the [CUDA Toolkit](https://developer.nvidia.com/cuda-toolkit) version 11.8.0. If it fails to install, uncheck "CUDA\Visual Studio Integration" and all the "CUDA\Nsight" during the installation. Then open the installation package with [7zip](https://www.7-zip.org/download.html) and extract all the 4 files inside "visual_studio_integration\CUDAVisualStudioIntegration\extras\visual_studio_integration\MSBuildExtensions" to your Visual Studio "Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations" folder.
- Force the encode to be UTF8 by adding this to CMakeLists.txt file.

```cmake
set(CMAKE_CXX_FLAGS "/utf-8")
set(CMAKE_C_FLAGS "/utf-8")
```

CMakeLists.txt will become like so:

```cmake
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED true)
set(CMAKE_CXX_FLAGS "/utf-8")
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED true)
set(CMAKE_C_FLAGS "/utf-8")
set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)
```

- Install the latest release of w64devkit (https://github.com/skeeto/w64devkit) and add its path to environment variables or to the make.bat below like so:
`set PATH=c:\path\to\w64devkit\bin;%PATH%`
- Create these two files "make.bat" and "make.sh" inside the first "KoboldCpp" folder (not inside the extracted folder).

make.sh

```bash
make -C "${1}"
```

make.bat

```bat
@echo off
set LLAMA_CLBLAST=1
set LLAMA_CUBLAS=1
set LLAMA_OPENBLAS=1
call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_x64
cd /d "%~dp0"
cd "koboldcpp"
mkdir "build"
cd "build"
cmake ".." -G "MinGW Makefiles"
sh -l ../../make.sh "%cd%"
copy /y .\bin\koboldcpp_cublas.dll ..\koboldcpp_cublas.dll
cd ".."
copy /y "%CUDA_PATH%\bin\cublas64_11.dll" ".\cublas64_11.dll"
copy /y "%CUDA_PATH%\bin\cublasLt64_11.dll" ".\cublasLt64_11.dll"
copy /y "%CUDA_PATH%\bin\cudart64_110.dll" ".\cudart64_110.dll"
set LLAMA_CUBLAS=
sh -l ../make.sh "%cd%"
```

- Now execute the "make.bat" and wait for it to close.
- Run KoboldCpp with `py -m koboldcpp` as usual.

**Comment by PhoenixtheII** [comment]
This was far more helpful than the readme.md of the repo for windows building....

**Comment by LostRuins** [comment]
Very nice. I will link to this in the wiki.

**Comment by jojorne** [comment]
Updated to include the Vulkan change of KoboldCpp 1.57 and added a script for CUDA Toolkit v12.

**Comment by rosemash** [comment]
For anyone who got stuck like I did, you have to install cmake from https://cmake.org/download/ and change `cmake ".." -G "MinGW Makefiles" --fresh` in the build script to `path\to\bin\cmake.exe ".." -G "MinGW Makefiles" --fresh`, (replacing path\to\bin\cmake.exe to the cmake distribution you downloaded) otherwise it tries to use a version of cmake bundled with Visual Studio, which results in an error about there being no generator called "MinGW Makefiles". After that I was able to build successfully.

**Comment by jojorne** [comment]
Guide was updated to use Build Tools 14.39.

**Comment by jojorne** [comment]
> For anyone who got stuck like I did, you have to install cmake from https://cmake.org/download/ and change `cmake ".." -G "MinGW Makefiles" --fresh` in the build script to `path\to\bin\cmake.exe ".." -G "MinGW Makefiles" --fresh`, (replacing path\to\bin\cmake.exe to the cmake distribution you downloaded) otherwise it tries to use a version of cmake bundled with Visual Studio, which results in an error about there being no generator called "MinGW Makefiles". After that I was able to build successfully.

![image](https://github.com/LostRuins/koboldcpp/assets/18329136/4bd252b3-4ac4-40ca-8f2d-a0bedab07d45)

Visual Studio's `Desktop development with C++` workload comes bundled with cmake by default. But to use it, you need to start the `Developer Command Prompt for VS 2022`.  The script start it with `call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_x64` line. You can also install cmake through Python with `pip install cmake` and Python will take care of the rest.
