### ISSUE TITLE
trying to build for windows

### ISSUE THREAD

**Issue by vautieri** [LostRuins/koboldcpp#667]
I'm trying to build for windows and tried nmake and cmake.  I have VS2022.  I have the cuda toolkit installed and I believe I have all the required python projects installed within an active condo environment.

Only koboldcpp_cublas.dll  is getting created with cmake.  make_pyinstaller is trying to copy dlls that I don't see are getting created.  I could probably spend quite a bit of time trying to figure out what I am missing but I'm wondering if someone has something to show me how the environment needs to get setup (more detailed than what is documented).

Thanks you!

**Comment by LostRuins** [comment]
What backends are you trying to build for on windows? Remember that CMAKE only supports the CUDA backend, and nothing else. It even says so in the console message displayed when the cmake runs.

For the other backends, you should be referring to the wiki under Building For Windows:  

https://github.com/LostRuins/koboldcpp/wiki#how-do-i-get-started-with-koboldcpp-what-do-i-need-how-do-i-compile-koboldcpp-from-source-code

**Comment by LostRuins** [comment]
Also: https://github.com/LostRuins/koboldcpp/issues/664

**Comment by jojorne** [comment]
llama.cpp, which KoboldCpp is based on, was meant to be built on Linux which uses packages to build. According to NVIDIA tech support, there is no package for CUDA on Windows. Therefore they provided an alternative way which uses cmake and Visual Studio. If you managed to build it, congratulations, you did it! Now if you want to build the rest, just continue using the Linux method which on Windows, it uses the make and w64devkit.

**Comment by jojorne** [comment]
> It's worth noting that you can actually just exclude the unbuilt files from the `make_pyinstaller.bat` and it should still work - you'll just have fewer backends

There is no need to create an executable, which will just double the size by packing everything up just like a zip file would. KoboldCpp can be run as a module using Python.

**Comment by LostRuins** [comment]
That is correct. You just need to install all dependencies (like tkinter) and that will work too.
