### ISSUE TITLE
Only the first streaming request works correctly

### ISSUE THREAD

**Issue by sasha0552** [LostRuins/koboldcpp#669]
The first (OpenAI compatible) streaming request works fine. The second one doesn't. It doesn't stream, and it seems to return the previous response (?) completely (as a single token). I think it just accepts the values of the previous generation before the tokens are cleared on the C++ side.

https://github.com/LostRuins/koboldcpp/blob/d1aff0e96475a3bae6850bc620488c762a642061/koboldcpp.py#L656
Setting the value to 1s fixes the problem.

I'm using
`koboldcpp 1.56` (manually checked the difference between 1.56 and 1.57 and did not notice any change in this logic)
`SillyTavern 1.11.3 'release' (318235e1) ` (connected as `Text Completion -> KoboldCpp`)
Mixtral 8x7B Q5_0, two NVIDIA Tesla P40

**Comment by LostRuins** [comment]
I'd imagine this is not a very common scenario. I have tried ST multiple times with no issues.

**Comment by sasha0552** [comment]
In my case, it happens every time. Do you need access to the affected host for debugging? I don't have a problem with this as I'm running koboldcpp in a virtual machine.

**Comment by LostRuins** [comment]
No need, but help me test this - what value of ` await asyncio.sleep(0.05)` is required until the issue goes away? 1 second is far too long. Can you try ` await asyncio.sleep(0.08)` and ` await asyncio.sleep(0.1)`

**Comment by LostRuins** [comment]
So high? That is very strange.

**Comment by sasha0552** [comment]
> Do you have an unusual setup?

Maybe? I don't think that anyone is running in VM with GPUs passthroughed.

`AMD Ryzen 5 5600 6-Core Processor`
32 GB of RAM.
4 vCPUs and 8GB of RAM assigned to VM, two P40s passthroughed.

Does not affect the speed of inference on GPUs, I think.
`ContextLimit: 1081/32768, Processing:4.16s (4.2ms/T), Generation:4.61s (46.1ms/T), Total:8.77s (87.7ms/T = 11.40T/s)`

**Comment by LostRuins** [comment]
It won't affect the speed of inference, but it means that every SSE request will take a minimum of 0.25s to start, which is less than ideal.

**Comment by sasha0552** [comment]
I know that it doesn't affect the inference speed, since the inference is done in a different thread. I mean, running in VM doesn't affect the speed of inference.
Anyway, maybe a command line flag is enough for this?

**Comment by LostRuins** [comment]
Should be fixed now in 1.58!

**Comment by sasha0552** [comment]
It works now. Thank you.
