### ISSUE TITLE
Force Closes

### ISSUE THREAD

**Issue by DjagbleyEmmanuel** [LostRuins/koboldcpp#671]
Software force closes every time I click on launch After loading my 13b llava model. Tried everything, still can't make it function. Need help pls, thanks.

**Comment by foxbg** [comment]
If you try running it from the command line it will give more details on what is the error.

**Comment by DjagbleyEmmanuel** [comment]
@foxbg  Attempting to use OpenBLAS library for faster prompt ingestion. A compatible libopenblas will be required.
Initializing dynamic library: koboldcpp_openblas.so
==========
Namespace(bantokens=None, benchmark=None, blasbatchsize=512, blasthreads=7, config=None, contextsize=2048, debugmode=0, forceversion=0, foreground=False, gpulayers=6, highpriority=False, hordeconfig=None, host='', launch=True, lora=None, model=None, model_param='/home/kb/Documents/phi-2-electrical-engineering.Q8_0.gguf', multiuser=1, noavx2=False, noblas=False, nommap=False, noshift=False, onready='', port=5001, port_param=5001, preloadstory=None, quiet=False, remotetunnel=False, ropeconfig=[0.0, 10000.0], skiplauncher=False, smartcontext=False, ssl=None, tensor_split=None, threads=7, useclblast=None, usecublas=None, usemlock=False, usevulkan=None)
==========
Loading model: /home/kb/Documents/phi-2-electrical-engineering.Q8_0.gguf 
[Threads: 7, BlasThreads: 7, SmartContext: False, ContextShift: True]
fish: Job 1, './koboldcpp-linux-x64' terminated by signal SIGILL (Illegal instruction)

**Comment by DjagbleyEmmanuel** [comment]
Attempting to use OpenBLAS library for faster prompt ingestion. A compatible libopenblas will be required.
Initializing dynamic library: koboldcpp_openblas.so
==========
Namespace(bantokens=None, benchmark=None, blasbatchsize=512, blasthreads=7, config=None, contextsize=2048, debugmode=0, forceversion=0, foreground=False, gpulayers=6, highpriority=False, hordeconfig=None, host='', launch=True, lora=None, model=None, model_param='/home/kb/Documents/phi-2-electrical-engineering.Q8_0.gguf', multiuser=1, noavx2=False, noblas=False, nommap=False, noshift=False, onready='', port=5001, port_param=5001, preloadstory=None, quiet=False, remotetunnel=False, ropeconfig=[0.0, 10000.0], skiplauncher=False, smartcontext=False, ssl=None, tensor_split=None, threads=7, useclblast=None, usecublas=None, usemlock=False, usevulkan=None)
==========
Loading model: /home/kb/Documents/phi-2-electrical-engineering.Q8_0.gguf 
[Threads: 7, BlasThreads: 7, SmartContext: False, ContextShift: True]
fish: Job 1, './koboldcpp-linux-x64' terminated by signal SIGILL (Illegal instruction)

**Comment by LostRuins** [comment]
Try launching with `--noavx2`

**Comment by LostRuins** [comment]
If using GUI, select the "Old CPU" option.

**Comment by DjagbleyEmmanuel** [comment]
@LostRuins Worked!

**Comment by DjagbleyEmmanuel** [comment]
But when trying with the --noavx2 flag it force closes. and my CPU fully supports avs.
I also have NVIDIA Geforce GT 635m drivers installed on my system, Is there any way i can put that to use? Thanks

**Comment by DjagbleyEmmanuel** [comment]
But when trying with the --noavx2 flag it force closes. and my CPU fully supports avx.
I also have NVIDIA Geforce GT 635m drivers installed on my system, Is there any way i can put that to use? Thanks

**Comment by LostRuins** [comment]
Which setting worked? `--noavx2` should give you the same results as the "Old CPU" option. "Failsafe" is if you dont have avx at all.

**Comment by DjagbleyEmmanuel** [comment]
Only "Old CPU" and "Failsafe" worked.

**Comment by LostRuins** [comment]
Yep, that means your CPU doesn't support the AVX2 instruction. You can still use it in old cpu mode with reduced speeds. You can try the `CLBlast NoAVX2 (Old CPU)` ,that might work too.
