### ISSUE TITLE
The result file from --benchmark is missing a new line

### ISSUE THREAD

**Issue by jojorne** [LostRuins/koboldcpp#677]
k, it's appending the results on the same line creating an inconsistency with the header.
yea... i solved it by doing:
```bat
set results=..\results.csv
py -m koboldcpp --benchmark "%results%"
echo:>>"%results%"
```

**Comment by jojorne** [comment]
i can dump the whole `{}` json config to the file and use query to compare the settings~ 🥰

**Comment by LostRuins** [comment]
Confirmed, will fix
