### ISSUE TITLE
[ISSUE_INVESTIGATIVE] Potential interactions within SillyTavern might be unexpectanty affecting Context Shifting.

### ISSUE THREAD

**Issue by Spacellary** [LostRuins/koboldcpp#681]
### Discussed in https://github.com/LostRuins/koboldcpp/discussions/674 - Converting to issue for Tracking

<div type='discussions-op-text'>

<sup>Originally posted by **Spacellary** February 10, 2024</sup>
When near max context only some messages benefit from Context Shifting, I can't seem to find the reason why that happens.

Real examples:
```
CtxLimit: 11892/12288, Process:34.76s (3.0ms/T = 338.83T/s), Generate:9.61s (82.9ms/T = 12.07T/s), Total:44.37s (2.61T/s)
CtxLimit: 11959/12288, Process:33.04s (3.1ms/T = 323.44T/s), Generate:9.76s (82.7ms/T = 12.09T/s), Total:42.81s (2.76T/s)
CtxLimit: 11833/12288, Process:32.48s (3.1ms/T = 325.81T/s), Generate:7.91s (82.4ms/T = 12.13T/s), Total:40.39s (2.38T/s)
[Context Shifting: Erased 240 tokens at position 1238]
CtxLimit: 11782/12288, Process:0.81s (10.6ms/T = 94.41T/s), Generate:9.38s (82.3ms/T = 12.15T/s), Total:10.19s (11.19T/s)
[Context Shifting: Erased 191 tokens at position 1237]
CtxLimit: 11757/12288, Process:0.67s (9.7ms/T = 103.60T/s), Generate:8.09s (82.5ms/T = 12.12T/s), Total:8.75s (11.20T/s)
[Context Shifting: Erased 192 tokens at position 1239]
CtxLimit: 11762/12288, Process:0.81s (8.9ms/T = 112.35T/s), Generate:8.83s (82.5ms/T = 12.12T/s), Total:9.64s (11.10T/s)
CtxLimit: 11890/12288, Process:32.69s (3.1ms/T = 325.07T/s), Generate:9.20s (82.9ms/T = 12.06T/s), Total:41.89s (2.65T/s)
[Context Shifting: Erased 193 tokens at position 1376]
CtxLimit: 11897/12288, Process:0.81s (8.9ms/T = 111.93T/s), Generate:9.10s (82.7ms/T = 12.09T/s), Total:9.91s (11.10T/s)
CtxLimit: 11899/12288, Process:0.08s (83.0ms/T = 12.05T/s), Generate:9.29s (82.9ms/T = 12.06T/s), Total:9.37s (11.95T/s)
CtxLimit: 11892/12288, Process:0.08s (83.0ms/T = 12.05T/s), Generate:8.71s (83.0ms/T = 12.05T/s), Total:8.80s (11.94T/s)
[Context Shifting: Erased 181 tokens at position 1377]
CtxLimit: 11894/12288, Process:0.78s (9.5ms/T = 105.26T/s), Generate:8.46s (83.0ms/T = 12.05T/s), Total:9.24s (11.04T/s)
```

```
CtxLimit: 7786/8192, Process:0.14s (138.0ms/T = 7.25T/s), Generate:6.48s (64.2ms/T = 15.58T/s), Total:6.62s (15.25T/s)
[Context Shifting: Erased 178 tokens at position 1132]
CtxLimit: 7781/8192, Process:0.57s (8.1ms/T = 122.81T/s), Generate:6.67s (64.1ms/T = 15.59T/s), Total:7.24s (14.36T/s)
[Context Shifting: Erased 182 tokens at position 1133]
CtxLimit: 7772/8192, Process:0.67s (9.0ms/T = 111.28T/s), Generate:6.34s (64.0ms/T = 15.62T/s), Total:7.01s (14.12T/s)
CtxLimit: 7830/8192, Process:21.61s (3.2ms/T = 308.77T/s), Generate:7.01s (64.3ms/T = 15.56T/s), Total:28.61s (3.81T/s)
[Context Shifting: Erased 197 tokens at position 1237]
CtxLimit: 7801/8192, Process:0.54s (8.4ms/T = 118.52T/s), Generate:6.83s (65.0ms/T = 15.38T/s), Total:7.37s (14.25T/s)
[Context Shifting: Erased 101 tokens at position 1237]
CtxLimit: 7874/8192, Process:0.58s (7.8ms/T = 128.21T/s), Generate:6.46s (64.6ms/T = 15.48T/s), Total:7.05s (14.19T/s)
CtxLimit: 7865/8192, Process:21.98s (3.3ms/T = 305.74T/s), Generate:6.10s (64.2ms/T = 15.58T/s), Total:28.08s (3.38T/s)
CtxLimit: 8006/8192, Process:22.33s (3.3ms/T = 307.17T/s), Generate:6.41s (65.4ms/T = 15.30T/s), Total:28.73s (3.41T/s)
```
_You can see the huge drop in final T/s when shifting doesn't happen._

I am using the prebuilt `koboldcpp 1.57.1` + `SillyTavern 1.11.4+` (staging, latest commits), and I made sure I don't have any dynamic information added anywhere in the context sent for processing.

### Context/Response Formatting:
![image](https://github.com/LostRuins/koboldcpp/assets/39604793/d0144662-6669-43a9-90ad-c3636002d427)

### I **don't** have (I even disabled the modules and extensions I mention):

- Summary
- Any lorebooks or similar, either global or on character
- Vector Storage (RAG)
- Silly Tavern's "Smart Context" (which is also a RAG)
- Objectives (extension)
- Anything on characters or otherwise being inserted `@D` or similar

<hr>

So, I am not using any Memory or other dynamic information that might trigger additional context reprocessing, but this keeps happening.

#### `Input: {"prompt": }` diffs - Successful vs Failed Shift:

Success Example - Diff (1 to 2):
https://www.diffchecker.com/bNJECF4S/

Fail Example - Diff (2 to 3):
https://www.diffchecker.com/5rJgaHUZ/

More deletions/additions are made in the failed example, as opposed to the successful one.
<br>

#### `n_past`:

1. [Debug: n_past=11812 Context Size = 11812]
(Context Shifted From 1 to 2)
2. [Debug: n_past=11784 Context Size = 11784]
(No Shift Happended from 2 to 3)
3. [Debug: n_past=951 Context Size = 951]

#### ~~What causes this? Is it an issue with the Model - due to quantization and RoPE?~~

For the example and this discussion, I'm using [s3nh/Kunoichi-DPO-v2-7B-GGUF](https://huggingface.co/s3nh/Kunoichi-DPO-v2-7B-GGUF) ([Q4_K_M](https://huggingface.co/s3nh/Kunoichi-DPO-v2-7B-GGUF/blob/main/kunoichi-dpo-v2-7b.Q4_K_M.gguf)):
```
koboldcpp "...\kunoichi-dpo-v2-7b.Q4_K_M.gguf" --multiuser --gpulayers 33 --contextsize 12288 --port 6969 --blasbatchsize 256 --usecublas --quiet --remotetunnel --nommap --highpriority
```

```
Namespace(bantokens=None, benchmark=None, blasbatchsize=256, blasthreads=5, config=None, contextsize=12288, debugmode=0, forceversion=0, foreground=False, gpulayers=33, highpriority=True, hordeconfig=None, host='', launch=False, lora=None, model=None, model_param='...\kunoichi-dpo-v2-7b.Q4_K_M.gguf', multiuser=1, noavx2=False, noblas=False, nommap=True, noshift=False, onready='', port=6969, port_param=5001, preloadstory='', quiet=True, remotetunnel=True, ropeconfig=[0.0, 10000.0], skiplauncher=False, smartcontext=False, ssl=None, tensor_split=None, threads=5, useclblast=None, usecublas=[], usemlock=False, usevulkan=None)
```
GPU: GTX 1070Ti - 8GB - Pascal
RAM: 32GB DDR4 3200MHZ
CPU: Ryzen 5 1600 AF 6C/12T 3.2-3.6MHZ (Zen 2 Arch)
OS: Windows 11 22H2
</div>

**Comment by LostRuins** [comment]
Should be improved now in 1.58, please try!

**Comment by Spacellary** [comment]
@LostRuins

So it didn't change much. I'll try to get diffs from each prompt, meanwhile here are the Debug logs at 12K Context...

https://gist.github.com/Spacellary/c084ded8cdb6b6552ec1aae2ea03522f

**Comment by Spacellary** [comment]
Added:

A to B - Shifted:
https://www.diffchecker.com/3bIcm14h/

B to C - No Shift (Long Processing):
https://www.diffchecker.com/ynppu6GS/

**Comment by Spacellary** [comment]
Added:

**Debug: n_past**

A to B - Shifted:
https://www.diffchecker.com/llcjA7of/

B to C - No Shift:
https://www.diffchecker.com/kOPVUzSt/

We can see the cut-off.

**Comment by Spacellary** [comment]
Added:

**[Debug: Dump Input Tokens, format: 6]**
_Why must we suffer?_

A to B - Shifted:
https://www.diffchecker.com/iJIhN8gT/

B to C - No Shift:
https://www.diffchecker.com/oFa5hEKD/

**Comment by LostRuins** [comment]
A quick look at your B to C - No shift examples, I'm not sure how you would want it to be shifted?

In the first example, you are just removing a large chunk of text at the end of the prompt. There's nothing to shift.

In the second example, there is barely any text to shift. After removing the unmatched initial section, you are left with maybe 20 tokens? 

If you want to try a good example, create a 500 word text. Then remove the first 100 words, and add 100 new ones at the end, and see if the shift triggers.

**Comment by Spacellary** [comment]
@LostRuins 

So what is perplexing me, is that Shifts are not triggering, A, B and C are all subsequent messages in that exact order, with nothing dynamic enabled in the front end, so all prompts **should** be consistent and match what you said, a portion removed at the start and one added at the end (unless there's already room for it, in which case it's not necessary of course).

This just doesn't seem to be happening given:

> In the second example, there is barely any text to shift. After removing the unmatched initial section, you are left with maybe 20 tokens?

These all all subsequent prompts, A - B - C, one after the other, why was the generation so different that there was barely anything to Shift given the only changes should be the new message?

@Cohee1207, does it make sense such differences in one prompt to the next, given I believe I have anything that could dynamic information early on disabled in SillyTavern (staging, latest), can you take a look at the prompt? Like I said they are all subsequent.

**Comment by Spacellary** [comment]
@Cohee1207 - Something I noticed when inspecting the Itemizer:

I noticed only full reprocessings happening, 20s+:

```
CtxLimit: 7984/8192, Process:22.66s (3.3ms/T = 306.25T/s), Generate:6.82s (68.9ms/T = 14.52T/s), Total:29.48s (3.36T/s)
CtxLimit: 7834/8192, Process:22.55s (3.3ms/T = 306.38T/s), Generate:7.31s (69.6ms/T = 14.37T/s), Total:29.86s (3.52T/s)
CtxLimit: 7899/8192, Process:22.63s (3.2ms/T = 308.76T/s), Generate:6.22s (67.6ms/T = 14.79T/s), Total:28.85s (3.19T/s)
CtxLimit: 7796/8192, Process:22.06s (3.2ms/T = 312.37T/s), Generate:5.74s (67.5ms/T = 14.82T/s), Total:27.79s (3.06T/s)
```

Looking at the itemizer from A to B to C:
![image](https://github.com/LostRuins/koboldcpp/assets/39604793/b1f5ef30-cb49-4fc8-a9d7-85110c923788)

Diff A to B:
https://www.diffchecker.com/js45ifyp/

Diff B to C:
https://www.diffchecker.com/D3izdCfH/

Isn't the `Example roleplay chat:` section supposed to be consistent? Why it's present and then not anymore, without any changes to the Prompt other than sending a new message?

Context formatting:
```
### Instruction:
Write {{char}}'s next reply in a fictional roleplay chat between {{user}} and {{char}}. Do not speak for {{user}} or act for them in your responses. Use the provided character sheet and example dialogue for formatting direction and character speech patterns.

{{#if system}}{{system}}

{{/if}}{{#if wiBefore}}{{wiBefore}}

{{/if}}Description of {{char}}:
{{#if description}}{{description}}
{{/if}}{{#if personality}}{{char}}'s personality: {{personality}}

{{/if}}{{#if scenario}}Scenario: {{scenario}}

{{/if}}{{#if persona}}Description of {{user}}: {{persona}}

{{/if}}Play the role of {{char}}

{{#if wiAfter}}{{wiAfter}}
{{/if}}
```

**Comment by Spacellary** [comment]
> Diff A to B:
> https://www.diffchecker.com/js45ifyp/
> 
> Diff B to C:
> https://www.diffchecker.com/D3izdCfH/

This behavior is affecting Context Shifting, in a sequence of 6 successful shifts, when it finally broke, was because of this addition to prompt:

![image](https://github.com/LostRuins/koboldcpp/assets/39604793/9909ee59-b09c-4bfc-83eb-3dca62331cbf)

**Comment by LostRuins** [comment]
There are a few criteria to determine whether shifting can be applied. Text length, number of matched tokens, number of different tokens, and continuity of text all have an impact. Take a look at https://github.com/LostRuins/koboldcpp/blob/concedo/gpttype_adapter.cpp#L615

**Comment by Spacellary** [comment]
@LostRuins - I'm changing my original idea of the issue, at least with my current examples, the issue seems to be directly related to the conditional detection or seemly random inspersions of the `Example Dialogue` into context, even then it isn't changed. This doesn't apply to the `Scenario` Field. Tested for around 50 messages, when not using `Example Dialogue` the issue doesn't occur.

Will wait on @Cohee1207's input for this behavior as it's something that pretty much all character cards come with and could cause direct issues for your Context Shifting.

**Comment by Spacellary** [comment]
**Testing for confirmation:**

Once removing the `messageExamples` from the character, I ran 196 consecutive prompts and Context was Shifted properly in **all** cases.


Info:` --contextsize` is set to12880. Longest observed prompt Process time was 1.24s.

**Comment by LostRuins** [comment]
Well yeah, if they are inserted randomly or at varying offsets/varying messages then shifting will definitely fail.

**Comment by Spacellary** [comment]
@LostRuins -- Yea I just had not pinpointed the exact cause behavior before. It makes sense now.

So what is left to determine is why `exampleMessages` are being inserted so inconsistently.

Want to make sure with Cohee that this isn't some intended behavior I am not understanding and as I continue testing to be sure that was it.

**Comment by Spacellary** [comment]
> This is the default behavior for example messages - they are pushed out of context gradually as the chat goes on. This is very expected across most known frontends.

Thanks for the clarification @Cohee1207, I did see that this is the recommended Behavior for the V2 Character Card spec.

It is not immediately apparent in my opinion without that context, but like I said I understand now that it is part of the spec.

**Comment by Spacellary** [comment]
Thanks LostRuins for the last improvements and Cohee for clarifying that the default behavior is according to V2 character spec.

All is fine as of right now, hopefully. Cheers and kudos for the work on your respective projects as always!
