### ISSUE TITLE
aider stopping

### ISSUE THREAD

**Issue by CoqueTornado** [LostRuins/koboldcpp#682]
hello, whenever I use Aider from https://github.com/paul-gauthier/aider connecting via openai

In Koboldcpp it says this:

Processing Prompt [BLAS] (195 / 195 tokens)
Generating (3 / 100 tokens)Token streaming was interrupted or aborted!

it generates 100 tokens and just that. Maybe it worths a try. Please install aider and try this line with koboldcpp using any model any context lenght... all is always the same. The owner of Aider told us that this comes from Koboldcpp so, here I am.

aider --openai-api-base http://0.0.0.0:5001/v1 --openai-api-key fake-key

(is not any antivirus or firewall because I tried to stop em all and did not work). Text webui Generator stops at ~500 tokens, same error, but at least it generate some.

thank you for all

**Comment by LostRuins** [comment]
I don't think the issue is with koboldcpp. Every other frontend works with it fine. I suspect they are dropping the connection halfway, but I dont know why they would do that. 

Maybe they should try implement the synchronous (non-streaming) endpoint first.

**Comment by paul-gauthier** [comment]
FYI, you can tell aider not to stream with `--no-stream`.
