### ISSUE TITLE
Always show "Processing Prompts" logs (even with quiet mode)

### ISSUE THREAD

**Issue by drummerv** [LostRuins/koboldcpp#690]
https://github.com/LostRuins/koboldcpp/blob/d1aff0e96475a3bae6850bc620488c762a642061/gpttype_adapter.cpp#L1809-L1812

Prompt processing can take a long time and it would be nice to see this logged even on quiet mode.

**Comment by LostRuins** [comment]
That defeats the purpose of quiet mode, which is not suppose to output anything related to the generations. Why don't you run it in regular mode?

**Comment by drummerv** [comment]
KOBO LOST

**Comment by drummerv** [comment]
Also <3 I remember this. I was one month into LLMs when I asked this question.

**Comment by LostRuins** [comment]
kobo
