### ISSUE TITLE
[ROCm fork]: Errors loading or using models

### ISSUE THREAD

**Issue by brknsoul** [LostRuins/koboldcpp#692]
I can't seem to load any models with the ROCm fork on my 6600xt.

With "Use QuantMalMut (mmq)" ticked, I get;
```
CUDA error: named symbol not found
  current device: 0, in function ggml_cuda_op_mul_mat at D:/a/koboldcpp-rocm/koboldcpp-rocm/ggml-cuda.cu:9464
  hipGetLastError()
GGML_ASSERT: D:/a/koboldcpp-rocm/koboldcpp-rocm/ggml-cuda.cu:241: !"CUDA error"
```

Without mmq ticked, the browser launches, but any attempt at generation results in nonsense;

![image](https://github.com/LostRuins/koboldcpp/assets/1969381/0e843a8b-4e03-45fc-a522-43d13281c6f7)

**Comment by BrandenStoberReal** [comment]
Can confirm this is also happening to me on Ubuntu 23.10 with Python 3.11.8.

**Comment by brknsoul** [comment]
This issue is solved with later releases of kcpp_rocm (at least for windows).
