### ISSUE TITLE
Report a bug about "BLSA Batch Size"

### ISSUE THREAD

**Issue by sssfhfhchasd** [LostRuins/koboldcpp#693]
With version 1.54 and above, when loading "Qwen-14B-Chat.Q4_K_M.gguf" and "Causallm-14b-dpo-alpha.Q4_K_M.gguf", the model can only output normally in the first few sentences, and then only meaningless garbled characters will be output. Adjusting "BLSA Batch Size" to the lowest value can solve the problem, but it will make the reasoning speed very slow. This seems to be a bug. I hope it can be fixed if possible. Thank you very much.

**Comment by sssfhfhchasd** [comment]
The graphics card model is “NVDIA GeForce gtx 1050“.

**Comment by nopperl** [comment]
@sssfhfhchasd are you using `--usecublas`?

**Comment by sssfhfhchasd** [comment]
@nopperl Yes, my graphics card model is “NVDIA GeForce gtx 1050“. The default setting is "usecublas".
