### ISSUE TITLE
After multiple generations, commas started to disappear from newly generated text.

### ISSUE THREAD

**Issue by ColourfulPhoenix** [LostRuins/koboldcpp#694]
Hello! I recently started using koboldcpp a few days ago.
I noticed a strange behavior: After generating many times(like around 15 times), commas started to disappear from newly created sentences, making the text difficult to read :( However, when I changed the repetition penalty from 1.1 to 1.0, this situation seemed to be alleviated. Is this a software bug or a problem with the llm? 
I mainly used two models:nous-hermes-2-solar-10.7b.Q5_K_M and nous-hermes-2-mixtral-8x7b-dpo.Q4_K_M.
Thanks! :)

**Comment by LostRuins** [comment]
Model issue. Try lowering rep pen.

**Comment by ColourfulPhoenix** [comment]
> Model issue. Try lowering rep pen.

I see,thanks! :)
