### ISSUE TITLE
Allow to choose different HordeAi url for embedded worker

### ISSUE THREAD

**Issue by Tomislaw** [LostRuins/koboldcpp#698]
Currently url is hardcoded.
It would be great if we can change it via cmd args.

https://github.com/LostRuins/koboldcpp/blob/concedo/koboldcpp.py#L2095

**Comment by LostRuins** [comment]
Is there a new horde cluster I'm not aware of?

**Comment by Tomislaw** [comment]
No, I just experimenting with creating api wrapper for current horde, which introduces some extra logging and monitoring and I wanted to change url to localhost instead.

And If for some reason current horde url changes in the future then it might cause some issues. 

(horde.koboldai.net already redirect requests to 
stablehorde.net, so my assumption isn't far-fetched )

**Comment by LostRuins** [comment]
I see, cool. it probably won't be a new launcher parameter, but it should be quite easy to change it within the python script as you highlighted.
