### ISSUE TITLE
Format for running a model from command line?

### ISSUE THREAD

**Issue by Enferlain** [LostRuins/koboldcpp#70]
I wanna try the new options like this: koboldcpp.exe --useclblast 0 0 and --smartcontext 

Previously when I tried --smartcontext it let me select a model the same way as if I just ran the exe normally, but with the other flag added it now says `cannot find model file: and`

I saw that I should do [model_file] but [ggml-model-q4_0.bin] and --ggml-model-q4_0.bin doesn't work. What would be the correct format?

**Comment by Omniphantasm** [comment]
.\koboldcpp.exe --useclblast 0 0 --smartcontext

**Comment by LostRuins** [comment]
The command line arguments work for me. In any case, you can also pass in a path the the model as the first argument.

**Comment by dsiens** [comment]
Coul'd it be possible to change model from UI in future version?

**Comment by Enferlain** [comment]
@Omniphantasm this worked, thanks. 

Any idea what a constant spam of 

```
Error creating OpenCL Buffer A: -4
Error creating OpenCL Buffer B: -4
Error creating OpenCL Buffer C: -4
```

means?

**Comment by Omniphantasm** [comment]
Pretty sure it just means you targeted the wrong hardware with --useclblast you'll have to just fiddle around as far as i know with 0 1, 1 0, 1 1, to find which one is your GPU.

**Comment by Enferlain** [comment]
It's working now with 0 0, was getting the error randomly when I afked but I've been running it for like 4 hours at this point with no issues so yeah. Thanks btw
