### ISSUE TITLE
[Minor bug] Repetition range hard capped at 0≤RpRng≤8192

### ISSUE THREAD

**Issue by bucketcat** [LostRuins/koboldcpp#703]
RpRng locked at 8192 or lower. Allow it to scale to at least the size of the context for sampler compatibility. I.e. 0≤RpRng≤Ctx

Edit: In lite UI, v1.58.

**Comment by LostRuins** [comment]
Hi, this should now be fixed. Please check the latest version!

**Comment by bucketcat** [comment]
> Hi, this should now be fixed. Please check the latest version!

Fixed
