### ISSUE TITLE
Fresh install on ubuntu throws error and GUI fails to start - no display name and no $DISPLAY environment variable; customtkinter python module required!

### ISSUE THREAD

**Issue by therky04** [LostRuins/koboldcpp#716]
Ubuntu LTS 22.04 - cloned the git and ran ./koboldcpp.sh dist

But when I then run ./koboldcpp.sh again, it just throws me this error. I've also tried installing customktinter and tk via pip, and python3-tk respectively, but that won't fix it.

***
Welcome to KoboldCpp - Version 1.59.1
For command line arguments, please refer to --help
***
Warning, GUI failed to start: Reason: no display name and no $DISPLAY environment variable
File selection GUI unsupported.
customtkinter python module required!
Please check command line: script.py --help

Setting export = display=0.0 won't fix it either.

Can you please point me in the right direction?

**Comment by LostRuins** [comment]
Does your system support a graphical interface? Is X11 installed?

If you don't need the GUI launcher, you can simply pass your model via CLI and it will work e.g. `--model`
For commands, run `--help`

**Comment by therky04** [comment]
Thanks for your reply, thank you for pointing me in the right direction. I wasn't aware that GUI did not mean the webserver but an actual interface that you can access locally. I only accessed my client via ssh, thus no X11. With the right model and the right settings I now got it to work. Thank you very much for your assistance!
