### ISSUE TITLE
koboldcpp.py only sets half of the available threads

### ISSUE THREAD

**Issue by Myrminki** [LostRuins/koboldcpp#72]
I had to manually set the thread count in the default_threads variable. I don't know if it's something that can be set with an argument and I like it because it helps with stability, but I should be able to use all threads if I want to.

**Comment by LostRuins** [comment]
This is by design, as we found that using more threads can actually lead to a worse performance. There is a `--threads` parameter you can use when running the program to override this.

**Comment by Myrminki** [comment]
Well in my case I get a nice performance boost when using all threads, thanks for replying and thanks for the work y'all are doing.
