### ISSUE TITLE
Support for newer I-Quant formats 

### ISSUE THREAD

**Issue by InferenceIllusionist** [LostRuins/koboldcpp#722]
Hi there, trying to run inference on an IQ4_XS quant (see this PR for more info - https://github.com/ggerganov/llama.cpp/pull/5747)
Koboldcpp loads the model and immediately crashes. Before the window closes the error message mentions something about a unhandled exception with koboldcpp.  I also noticed that the amount of CUDA memory being reserved is significantly higher than the size of the model (9.93 gb) 

This issue also happens to other newer quant formats like IQ2_M. Any workarounds I could try? Thanks!
![screenshot-iq4_xs](https://github.com/LostRuins/koboldcpp/assets/161771862/57a83e31-7be2-42b1-8235-16827dead1ca)

**Comment by LostRuins** [comment]
The latest quant support in v1.59.1 currently is `IQ3_S`. Anything newer will require waiting for the next release, which should be out before the end of next week.

**Comment by InferenceIllusionist** [comment]
Understood, thanks for letting me know. Happy to help test once the next release is out and appreciate your work on this.
