### ISSUE TITLE
set up a api key please。 label:enhancement 

### ISSUE THREAD

**Issue by lin16303** [LostRuins/koboldcpp#729]
Could you please add api key support to the application? thanks

text-generation-webui can with --api --key xxx

**Comment by LostRuins** [comment]
There's currently no support for setting an API key as the Kobold API doesn't support authentication. However, you can use a reverse proxy to provide it on the OpenAI API

https://gitgud.io/khanon/oai-reverse-proxy

**Comment by LostRuins** [comment]
Update: API key support has been added

**Comment by lin16303** [comment]
Thank you for your efforts and dedication！

**Comment by SimplyCorbett** [comment]
> Update: API key support has been added

What's the parameter for it?

**Comment by henk717** [comment]
--password
