### ISSUE TITLE
Embedded A1111 config?

### ISSUE THREAD

**Issue by aolko** [LostRuins/koboldcpp#730]
How do i configure embedded A1111? I'd like to change the image size and the default prompts. Also, will hires fix/upscale be implemented?

**Comment by LostRuins** [comment]
No upscalers at the moment - the default prompts, cfg scale, step counts can all be changed by clicking the "Style" button. Image size is currently fixed at 512x512 from the UI, but can be set up to 1024x1024 over the API.

![image](https://github.com/LostRuins/koboldcpp/assets/39025047/93b749d3-50d0-42df-b744-dd0ce6b1157a)
