### ISSUE TITLE
[Feature Request] Japanese Support

### ISSUE THREAD

**Issue by AsuraAce** [LostRuins/koboldcpp#733]
not sure whether this is Kobald or model related but i'm having trouble getting japanese characters to work. they only manage to respond in hiragana but won't use kanji.

**Comment by LostRuins** [comment]
What model are you using? Maybe try a different model?

**Comment by AsuraAce** [comment]
tried Echidna 13b. it works in chat mode but i have a hard time getting it to work in adventure mode with a companion. the only thing that works sometimes, is a Japanese response in Hiragana instead of Kanji.

**Comment by LostRuins** [comment]
You'd want to look for more multilingual models. 

How about https://huggingface.co/Elizezen/Hameln-japanese-mistral-7B-GGUF

**Comment by LostRuins** [comment]
It's worth noting that models tend to follow the style and format of your own prompt. So try speaking in Japanese as well.

I just tried my normal Mistral Airoboros model, no issues.

![image](https://github.com/LostRuins/koboldcpp/assets/39025047/bfbd3e24-e81e-4041-add6-046f316d6f1b)

**Comment by AsuraAce** [comment]
@LostRuins as i mentioned earlier, i'm talking about Adventure mode. i would like to have a companion while playing adventure mode, that speaks a different language and this doesn't seem to work.

chat and instruct mode work however, just not what i'm looking for.

It seems other ppl have tried as well and this is just something that doesn't work well. will close this, feel free to reopen if you think there is something that can be done about it.
