### ISSUE TITLE
[RESOLVED] Compiling KoboldCpp at Windows, now successful

### ISSUE THREAD

**Issue by gustrd** [LostRuins/koboldcpp#74]
Hello guys,

I was just able to compile the project succesfully at Windows using w64devkit version 1.18.0 . 

The problem I had is that I was using the binaries directly at my PATH, and I needed to use the embedded terminal to compile the project. Both "make simple" and "make" worked at the first try.

Just registering it here to help anyone that is having the same issue.

@LostRuins , do you think that it would be good adding a Compiling at Windows session at the readme? I can do it if you agree. 

Best regards and congratulations by the new features, it's getting great!

**Comment by Ph0rk0z** [comment]
I compiled using msys and it can't find the DLL even though they are built in the same former.

**Comment by LostRuins** [comment]
Sure, if you like you can do a draft for windows build instructions next to OSX and linux section. I'll take a look tomorrow.
