### ISSUE TITLE
A1111 local SD1.5 and SDXL pf16 compatible models

### ISSUE THREAD

**Issue by CorentinWicht** [LostRuins/koboldcpp#747]
Dear Developper,

I am trying to configure the Local Image Generation with the A1111 compatible endpoint and I am having a real hard-time finding compatible models. 
As specified in your [Wiki](https://github.com/LostRuins/koboldcpp/wiki), any "_[...] compatible SD1.5 or SDXL .safetensors fp16 model [...]_" should work, but from what I have tested so far this seems not to be the case.

Here are the models I have tested and which failed:

1. sdxl-turbo/[diffusion_pytorch_model.fp16.satefensors](https://huggingface.co/stabilityai/sdxl-turbo/blob/main/unet/diffusion_pytorch_model.fp16.safetensors)
2. madebyollin/[sdxl-vae-fp16-fix](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/blob/main/sdxl_vae.safetensors)
3. [Stable Diffusion v1.5 [bf16/fp16] [no-ema/ema-only] [no-vae] [SafeTensors] [Checkpoint]](https://civitai.com/models/155256/stable-diffusion-v15-bf16fp16-no-emaema-only-no-vae-safetensors-checkpoint)

The error returned when running ```/usr/bin/python /opt/koboldcpp-latest/koboldcpp.py /home/frillm/Models/llama-2-70b-chat.Q5_K_M.gguf 8008 --multiuser 20 --highpriority --usecublas --gpulayers 60 --nommap --preloadstory /opt/settings.json --sdconfig /opt/A1111/sdXL_v10VAEFix.safetensors normal``` is the following:
```
python[8787]: ImageGen Init - Load Model: /opt/A1111/diffusion_pytorch_model.fp16.safetensors
python[8787]: Error: KCPP SD Failed to create context!
```

The following model loads correctly but generates black images only:
[sdXL_v10VAEFix.safetensors](https://civitai.com/models/101055?modelVersionId=128078)

While the only one that is currently working is the following:
hollowstrawberry/[sd-v1-5-pruned-noema-fp16.safetensors](https://huggingface.co/hollowstrawberry/stable-diffusion-guide/blob/main/models/sd-v1-5-pruned-noema-fp16.safetensors)
![image](https://github.com/LostRuins/koboldcpp/assets/52161904/bfd8390f-3882-4ca6-98ad-3f91dfeb9d8a)

I am pretty new to this and I may have missed something ?

Best wishes,

C.

**Comment by LostRuins** [comment]
Hey there, thanks for pointing it out.

Okay I think maybe I need to update the wiki. The models need to be standalone and have a VAE baked into it. Unfortunately it's quite hard to tell which works by looking at the file so a bit of trial and error might be needed.

1. The first model you linked is an incomplete model - you'll notice it's only the `unet` part of the model but does not include the `tokenizer` or `vae`. 

2. The second link is just a `vae` only, with no model associated! You'll noticed it's only 300mb. A proper model should be at least 2gb.

3. The third link I didn't try, but it appears to not have a VAE inside too?

---

I should have included good examples in the wiki, these should all work:

For the original Stable Diffusion 1.5 model, try https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors , I tested it and it works.

And here's a good Anime-styled model, which I've also tested (and it works) https://huggingface.co/admruul/anything-v3.0/resolve/main/Anything-V3.0-pruned-fp16.safetensors

Could you try these and let me know if they work for you? I've updated my wiki for clarity too. Thanks!

**Comment by LostRuins** [comment]
Also just a heads up its probably best to run the `--sdconfig` with the `clamped` and `quant` flags to limit max resolution if its a shared server, since you don't want someone making a request for a massive image to make the server run out of memory and crash. That will clamp the max image resolution at 512x512

**Comment by CorentinWicht** [comment]
> Hey there, thanks for pointing it out.
> 
> Okay I think maybe I need to update the wiki. The models need to be standalone and have a VAE baked into it. Unfortunately it's quite hard to tell which works by looking at the file so a bit of trial and error might be needed.
> 
> 1. The first model you linked is an incomplete model - you'll notice it's only the `unet` part of the model but does not include the `tokenizer` or `vae`.
> 2. The second link is just a `vae` only, with no model associated! You'll noticed it's only 300mb. A proper model should be at least 2gb.
> 3. The third link I didn't try, but it appears to not have a VAE inside too?
> 
> I should have included good examples in the wiki, these should all work:
> 
> For the original Stable Diffusion 1.5 model, try https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors , I tested it and it works.
> 
> And here's a good Anime-styled model, which I've also tested (and it works) https://huggingface.co/admruul/anything-v3.0/resolve/main/Anything-V3.0-pruned-fp16.safetensors
> 
> Could you try these and let me know if they work for you? I've updated my wiki for clarity too. Thanks!

Thanks you very much for your quick reply.

Then, it also came for my lack of understanding of these VAE, unet, etc. concepts.

I can confirm that the provided original [Stable Diffusion 1.5 model](https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors) works perfectly, thanks.

What about SDXL models, would you have a suggestion?

**Comment by CorentinWicht** [comment]
I actually just found a working SDXL model, but it's much ressource-heavey compared to the SD 1.5 you provided:
`https://civitai.com/models/117188?modelVersionId=129581`

Is there possible to load two models and then be able to switch from one to another in Lite with:
![image](https://github.com/LostRuins/koboldcpp/assets/52161904/6fac017e-4700-465f-b1e3-c983d48bce69)

**Comment by LostRuins** [comment]
Nope, right now a single server instance only allows the loading of one image model - unlike the real A1111 it is not possible to swap them on the fly.

Did you load the models with the `quant` flag on? That helps save memory (uses 3x less!)

If you really need to host both - you will need to run 2 separate koboldcpp instances (on different ports)

Your command is missing a `threads` parameter - the `sdconfig` command takes positional arguments. The correct format should be something like `--sdconfig myfile.gguf clamped 4 quant`

**Comment by CorentinWicht** [comment]
> Nope, right now a single server instance only allows the loading of one image model - unlike the real A1111 it is not possible to swap them on the fly.
> 
> Did you load the models with the `quant` flag on? That helps save memory (uses 3x less!)
> 
> If you really need to host both - you will need to run 2 separate koboldcpp instances (on different ports)
> 
> Your command is missing a `threads` parameter - the `sdconfig` command takes positional arguments. The correct format should be something like `--sdconfig myfile.gguf clamped 4 quant`
> 
> With quant enabled correctly the SDXL should work better (may take longer to load).

Good to know, thanks for the tips! 

Alright sure I forgot the `thread` argument, thanks for pointing it out.

Best wishes,

C.

**Comment by maxwell-kalin** [comment]
i seem to get black images with any model provided in the wiki

**Comment by maxwell-kalin** [comment]
![image](https://github.com/LostRuins/koboldcpp/assets/62115669/40585b9a-e799-4c85-866e-6d76fcf8ccf0)

**Comment by Amin456789** [comment]
use sdxl turbo and choose fix vae and compress with quant, it works this way

**Comment by maxwell-kalin** [comment]
i want Anything 3.0 to be honest

**Comment by LostRuins** [comment]
Yes that will work. Just enable the fix bad vae checkbox. Or replace the vae with a different one

**Comment by maxwell-kalin** [comment]
Well, its only giving me a black image (see above)

**Comment by LostRuins** [comment]
Ah, okay I think that was a bug in 1.66, you can try 1.65 for now that should work. It will be fixed in 1.67 which is going to be released by the end of this week.

Alternatively you can try a pre-release build of 1.67 here : 
https://github.com/LostRuins/koboldcpp/actions/runs/9351708061/artifacts/1563052074

**Comment by LostRuins** [comment]
Let me know if that works

**Comment by maxwell-kalin** [comment]
can you link me the linux no cuda, i dont use Windoze

BTW, SDXL works way better in my case
i use this currently https://civitai.com/models/9409/or-anything-xl

**Comment by LostRuins** [comment]
Hi, please try the latest version which is now released

https://github.com/LostRuins/koboldcpp/releases/latest

**Comment by maxwell-kalin** [comment]
Works far more consistent thanks
