### ISSUE TITLE
Some pointers on the --useclblast

### ISSUE THREAD

**Issue by chille9** [LostRuins/koboldcpp#75]
I would love to try this, do i need to download the release of https://github.com/CNugteren/CLBlast and use in some way?
Or is it necessary build the project? 
I´m just using the exe.

Love the software and would really appreciate a couple of simple pointers.

**Comment by TravelingMan** [comment]
At the moment I think it takes some trial and error. I usually just use  `koboldcpp.exe --useclblast 0 0 --smartcontext`, but on a different machine, I have to use `--useclblast 0 1` for it to find the GPU.

You'll know if it's working right when it starts generating a response. It'll usually insta-crash if you've got the wrong IDs. Try again until it works! 🤞

**Comment by chille9** [comment]
![image](https://user-images.githubusercontent.com/1384523/232364509-2630ade4-ea07-49b3-ad56-0607ed93501e.png)
That seem to have done the trick! Im using --useclblast 0 0 --smartcontext 

I´m guessing the low cpu-usage at around 15% is normal? Would be cool if it got used more!

Big thanks for the advice TravelDood! 🥇
