### ISSUE TITLE
cublast old cpu supprot

### ISSUE THREAD

**Issue by Loko415** [LostRuins/koboldcpp#755]
add old cpu support cu blast because cl blast is slower.

**Comment by Tacx79** [comment]
Cublas works only on nvidia cards ('cu' in the name is from CUDA, 'cl' is from OpenCL which works on all gpus and cpus)

**Comment by Loko415** [comment]
> Cublas works only on nvidia cards ('cu' in the name is from CUDA, 'cl' is from OpenCL which works on all gpus and cpus)

i do have cublast?

**Comment by henk717** [comment]
Give Vulkan a try, its much faster than CLBlast.

**Comment by LostRuins** [comment]
Both CUDA and Vulkan now have old cpu support. Do give it a try, and reopen this issue if it doesnt work!
