### ISSUE TITLE
Story Mode appends newline to edited prompt sometimes

### ISSUE THREAD

**Issue by horenbergerb** [LostRuins/koboldcpp#76]
Running on Ubuntu 22, problem affects all models that I've tried.

Workflow is as follows:
1) Input some large prompt and press "Submit." Wait for generation to complete.
2) Select "Allow Editing" and modify the prompt, typically appending something to the bottom.
3) I press "Submit" again.

The issue is that sometimes (but not always), a newline character is appended to my prompt. Here is an example prompt where this just happened:

```
User: Provide the three most salient facts from the following text:
'''
The opening quotation from one of the few documentary sources on Egyptian mathematics and the fictional story of the Mesopotamian scribe illustrate...
<shortened for brevity in issue>
'''
Your answer should be in the following format:
'''
* Fact 1
* Fact 2
* Fact 3
'''
Assistant: *
```

The logs then show the prompt being interpreted as:

```
Input: {"n": 1, "max_context_length": 2048, "max_length": 8, "rep_pen": 1.1, "temperature": 0.7, "top_p": 0.5, "top_k": 0, "top_a": 0.75, "typical": 0.19, "tfs": 0.97, "rep_pen_range": 1024, "rep_pen_slope": 0.7, "sampler_order": [5, 4, 3, 2, 1, 0, 6], "prompt": "User: Provide the three most salient facts from the following text:\n```\nThe opening quotation from one of the few documentary sources on Egyptian mathematics and the fictional story of the Mesopotamian scribe illustrate...\n```\nYour answer should be in the following format:\n```\n* Fact 1\n* Fact 2\n* Fact 3\n```\nAssistant: *\n", "quiet": true}
```
As you can see, the prompt now ends in a newline character: `...\nAssistant: *\n"`, which ruins the formatting... What's worse is that this happens unreliably; sometimes I don't get these newlines, and sometimes I can't get them to go away, even by erasing and rewriting parts of the prompt. I haven't been able to nail down explicit criteria for causing the newlines to be appended.

I'm pretty sure these are being appended by code and not generated because the logged input appears as I press "Submit."

Any ideas what's going on here? Thanks!

**Comment by horenbergerb** [comment]
It's possible these are just being generated by the model and I'm a dummy, but sometimes they generate consistently in places I would think to be highly unlikely.

**Comment by LostRuins** [comment]
What mode are you using? If you are on Instruct mode, this is by design as the default instruct format requires newlines after the delimiter. 

If you are on Story mode, this should not happen as your input is sent **raw**: otherwise you'd end up with a new paragraph after every submission.

**Comment by horenbergerb** [comment]
I am definitely using Story mode in the settings menu, not Instruct mode.

**Comment by LostRuins** [comment]
You can test that story mode doesn't append newlines automatically by sending a sequence of numbers e.g. `1 2 3 4 5 6`, it should continue from where you stopped, on the same line. You may have to retry a few times. Anything else is definitely model behavior.

**Comment by horenbergerb** [comment]
@LostRuins Ah, thank you, I actually got something to reproduce using that smaller example. Here's what I did:
1) Edit the prompt to be `1 2 3 4 5 6`
2) Press enter twice, adding newlines
3) Press backspace twice, deleting newlines
4) Press "Submit"

Sure enough, the input still has a newline at the end:
```
Input: {"n": 1, "max_context_length": 2048, "max_length": 8, "rep_pen": 1.1, "temperature": 0.7, "top
_p": 0.5, "top_k": 0, "top_a": 0.75, "typical": 0.19, "tfs": 0.97, "rep_pen_range": 1024, "rep_pen_sl
ope": 0.7, "sampler_order": [5, 4, 3, 2, 1, 0, 6], "prompt": "1 2 3 4 5 6\n", "quiet": true}
```
And now that newline gets "stuck" in the prompt; it's not rendered so I can't directly delete it.

**Comment by horenbergerb** [comment]
In the case of `1 2 3 4 5 6`, I can get rid of the ghost newline by deleting and rewriting `6`. Very strange.

**Comment by horenbergerb** [comment]
Ah! If I delete `6` by pressing backspace, the ghost newline remains. But if I delete `6` by highlighting it and pressing backspace, then it eliminates the ghost newline too.

**Comment by LostRuins** [comment]
Sounds like it's some browser specific behavior with how it handles `contenteditable` text fields. Sometimes, a browser will break up your text into multiple `<div>`s when you edit them, these `<div>`s then go on to become newlines when the text field is saved again. Unfortunately this is quite difficult to resolve (as you can see with the differences between backspace vs highlighting), so my suggestion for now would be to either send your prompts directly with the input submission box below, or to do the highlight+delete on a text to ensure you erase any hidden `<div>` elements.

**Comment by horenbergerb** [comment]
I'm using Firefox in Ubuntu 22. Just checked and I can't reproduce it reliably on Chrome on my Android phone, although I could swear I've hit this issue on my phone previously...
Anyways, I'm happy now that I have a workaround, so it sounds like this issue can be closed.
