### ISSUE TITLE
Can't ban multiple tokens in .kcpps file?

### ISSUE THREAD

**Issue by pbz134** [LostRuins/koboldcpp#762]
I want to ban tokens, such as "###instruction" or "<dummy:32000>" (as they often are being generated by the model and it annoys me) but specifying them always results in a json error when executing the file.

Here is my .kcpps file with what I got now:
{"model": null, "model_param": "model.gguf", "port": 5001, "port_param": 5001, "host": "", "launch": true, "lora": null, "config": null, "threads": 15, "blasthreads": null, "highpriority": false, "contextsize": 2048, "blasbatchsize": 512, "ropeconfig": [0.0, 10000.0], "smartcontext": false, "noshift": false, "bantokens": "#", "forceversion": 0, "nommap": true, "usemlock": false, "noavx2": false, "debugmode": 0, "skiplauncher": false, "hordeconfig": null, "noblas": false, "useclblast": null, "usecublas": ["normal", "0", "mmq"], "usevulkan": null, "gpulayers": 200, "tensor_split": null, "onready": "", "benchmark": null, "multiuser": 1, "remotetunnel": false, "foreground": false, "quiet": false, "ssl": null, "nocertify": false}

**Comment by LostRuins** [comment]
I'd recommend removing them with logit bias instead. For example:
![image](https://github.com/LostRuins/koboldcpp/assets/39025047/cb962f81-4d41-4545-895b-e91e9c74d71a)

**Comment by pbz134** [comment]
Is this configurable in a .kcpps file? I'm using koboldcpp over the API.

**Comment by LostRuins** [comment]
It's not configurable in the kcpps file, it's a field sent over the API, called `logit_bias`.

See this: https://koboldai-koboldcpp-tiefighter.hf.space/api/#/api%2Fv1/post_api_v1_generate

**Comment by pbz134** [comment]
Got it, thank you!
