### ISSUE TITLE
Access kcpp api for llava from comfyui somehow?

### ISSUE THREAD

**Issue by merc4derp** [LostRuins/koboldcpp#764]
We got nodes that support ollama endpoints for this task in comfyui. But ollama doesn't do clblast for older amd gpus.

Can we have an ollama compatible endpoint in kcpp or someone make a comfy node that works with the existing kcpp a1111-compatible endpoint maybe?

**Comment by henk717** [comment]
If they support GPT4Vision give that a try, we emulate that one.

**Comment by LostRuins** [comment]
Ollama and ComfyUI API endpoints are now added. Please reopen if you encounter issues.
