### ISSUE TITLE
Model loads forever

### ISSUE THREAD

**Issue by ghost** [LostRuins/koboldcpp#766]
I tried to load some GGUF models, but the loading process is stuck at this line:
`[Threads: 2, BlasThreads: 2, SmartContext: False, ContextShift: True]`

I already tried it without ContextShift and SmartContext, but it still won't load. With [Oobabooga](https://github.com/oobabooga/text-generation-webui) it works without problem.

**Comment by henk717** [comment]
Which models are these?

**Comment by ghost** [comment]
The models I tried are Toppy-M-7B and SnowLotus-v2-10.7B.

**Comment by LostRuins** [comment]
Do you have a link to the specific model quant file that doesn't work?

**Comment by ghost** [comment]
Yes, here are the links:

Toppy-M-7B: https://huggingface.co/Undi95/Toppy-M-7B-GGUF/resolve/main/Toppy-M-7B.q4_k_s.gguf
SnowLotus-v2-10.7B: https://huggingface.co/BlueNipples/DaringLotus-SnowLotus-10.7b-IQ-GGUF/resolve/main/SnowLotus-v2-10.7B-Q3_K.gguf

**Comment by LostRuins** [comment]
Hi, I tried Toppy-M-7B and it worked fine. Please try the latest version which is just released. Also, try reducing the number of offloaded layers.

**Comment by ghost** [comment]
Thanks, I tried it with the latest version and I get this error while starting:

```
Warning, GUI failed to start: Reason: No module named 'customtkinter'
File selection GUI unsupported.
customtkinter python module required!
Please check command line: script.py --help
```
I installed customtkinter, but it still show this error message.

**Comment by LostRuins** [comment]
What is your OS? For windows and linux you can grab the [latest release here](https://github.com/LostRuins/koboldcpp/releases/latest).

Otherwise, you can run it without GUI with the command line. For example

`python koboldpp.py --model /path/to/your/model.gguf`

**Comment by ghost** [comment]
I use Linux. I use the "koboldcpp.sh" and I also tried the program from the release.

I tried it with "koboldcpp.py" and I get a error in my language which translates to "`Invalid machine command (memory dump written)". Is the problem related to my OS?

**Comment by LostRuins** [comment]
Alright. Do you have a GUI? If yes, I suggest just trying this binary https://github.com/LostRuins/koboldcpp/releases/download/v1.62.2/koboldcpp-linux-x64 which should make things easier.

**Comment by ghost** [comment]
This is the one I tried. I tried it in a live OS this time to see if it works there, but it gave the same error as with the "koboldcpp.py": `Illegal instruction`.

**Comment by henk717** [comment]
I suspect your trying to use the regular backends on a CPU that does not have AVX2 support.
Can you double check your CPU supports AVX2 and if not try the Old CPU or Failsave backends?

**Comment by gustrd** [comment]
Sometimes this is the error when you try to call a .py file like a .sh file. Try to call with python3 before, like:

```
python3 ./koboldcpp.py
```

**Comment by ghost** [comment]
My CPU only supports AVX, but I read somewhere that it's enough. I tested it with the Old CPU backend and it works now. Thank you very much for your help.
