### ISSUE TITLE
Generation API lacks the dynatemp_exponent parameter

### ISSUE THREAD

**Issue by OcelotTheOcelot** [LostRuins/koboldcpp#767]
Looking at the /api/v1/generate request's GenerationInput schema, I only see "dynatemp_range" and "smoothing_factor" fields, but nothing seems to represent the DynaTemp-Exponent parameter from the UI.
Is it there but under a different name, or is it really missing?
![image](https://github.com/LostRuins/koboldcpp/assets/52647789/a8acfea7-7412-44fe-8a09-0b0c945db357)

**Comment by LostRuins** [comment]
That's an oversight. I'll add it. Thanks.
