### ISSUE TITLE
Very low gpu usage

### ISSUE THREAD

**Issue by Jake36921** [LostRuins/koboldcpp#773]
The gpu is barely being used during generation.

![Screenshot 2024-04-11 112649](https://github.com/LostRuins/koboldcpp/assets/113159896/8e2e4728-08d1-4599-b196-9b57d3adc3e1)

![Screenshot 2024-04-11 110935](https://github.com/LostRuins/koboldcpp/assets/113159896/69b82deb-575a-46e8-8101-992496294533)

![Screenshot 2024-04-11 110947](https://github.com/LostRuins/koboldcpp/assets/113159896/9430aa07-4685-48d5-a8ec-71b5089c92f2)

Arguments:
Start koboldcpp --threads 4 --launch --usecublas 0 0 --gpulayers 31 --contextsize 8192 --usemlock --blasbatchsize 1024 --multiuser --port 5002

Model: [Merged-RP-Stew-V2-34B.i1-IQ3_S.gguf](https://huggingface.co/mradermacher/Merged-RP-Stew-V2-34B-i1-GGUF)

System:
cpu: 5600g
ram: 32gb
gpu: 3060 12gb

**Comment by starstar222** [comment]
The GPU usage displayed only reflects the usage of the 3D engine; it does not show the utilization of AI acceleration computations. GPU load can be inferred by observing changes in VRAM usage and GPU temperature.

**Comment by starstar222** [comment]
Additionally, your GPU memory usage exceeds the maximum limit of 12GB, which can result in particularly slow calculations and make it look like the GPU is not working.

**Comment by LostRuins** [comment]
@Jake36921 did you select Use CuBLAS option and offload GPU layers? What model are you using?

**Comment by Jake36921** [comment]
> @Jake36921 did you select Use CuBLAS option and offload GPU layers? What model are you using?

Yes, I did both of them and I was using [Merged-RP-Stew-V2-34B.i1-IQ3_S.gguf](https://huggingface.co/mradermacher/Merged-RP-Stew-V2-34B-i1-GGUF).
Idk if task manager is reporting the wrong values or something but it reports that the gpu is being used on different models like [mythomax-l2-13b](https://huggingface.co/TheBloke/MythoMax-L2-13B-GGUF).

**Comment by LostRuins** [comment]
I mean, I can see your GPU VRAM being filled. So it probably is working correctly.

**Comment by Jake36921** [comment]
Still weird that task manager reports that its barely being used but I can see that it works during text generation after checking temps on msi afterburner.
