### ISSUE TITLE
Need help with stop sequences

### ISSUE THREAD

**Issue by inspir3dArt** [LostRuins/koboldcpp#790]
I try to make the LLM stop it's reply when it is about to write the following things:

<START> <END> <STOP> <BOT> <USER> (End) [END] Note: (Note: *** {{user}}: You: User:

I tried to list them using --bantokens, but it says in the terminal "<" is unexpected.

I tried it using the set grammar option in the settings, tried to separate them with a comma, put every word in quotes, and so on, but it doesn't work.

I know I can edit the last reply in chat, but it often causes that a lot of tokens get processed again, and that takes quite some time.

How can I make the LLM stop at this outputs I'm chat mode, because what it writes from there on is usually Off-Topic or out of character and ruin's the roleplay.

Edit: The post don't show words like START and STOP in between "<" and ">" for some reason, I want the LLM to stop at that outputs too

**Comment by LostRuins** [comment]
You should use the "Extra Stop Sequences" in the UI
![image](https://github.com/LostRuins/koboldcpp/assets/39025047/f5cb73f2-fabc-4873-88bd-01f9e73648ec)
Set it to this string
`(End)||$||[END]||$||Note||$||***||$||You:||$||User:`

**Comment by inspir3dArt** [comment]
How do I find that option? I have installed koboldcpp in termux on Android.

![Screenshot_2024-04-19-08-50-56-17_82cebf612ef3f9a8762672c971adaed4](https://github.com/LostRuins/koboldcpp/assets/66431329/80ccb587-90b3-4274-8417-d750ea64652e)

**Comment by LostRuins** [comment]
Click "Memory" or "Context" button outside

**Comment by inspir3dArt** [comment]
Works perfectly from my first test, many thanks for your help. It would be nice if this could be saved in the future in the browser catch, like the settings.

I just realized that I used the wrong place to ask my question, since it is not a bug report, sorry for that, I'm not used much to GitHub. I will use the discussion section for this kind of questions in the future.
