### ISSUE TITLE
found a sdxl lightning gguf repo that works

### ISSUE THREAD

**Issue by teddybear082** [LostRuins/koboldcpp#796]
for those looking I stumbled upon this sdxl lightning gguf repo that works with koboldcpp (in lite interface cfg_scale = 1, steps = 4, sampler LCM)

maybe this could be added to wiki if others validate it works for them.  I tried with q4_1, was much faster than regular sdxl.

https://huggingface.co/mzwing/SDXL-Lightning-GGUF/tree/main

EDIT: the LCM sampler seems to do really well with this, and 4 steps with cfg_scale =1 seems perfect.  Here's an example image for the prompt "a man with a hat": 
![image](https://github.com/LostRuins/koboldcpp/assets/87204721/d93f6ad0-af05-4c22-a746-a6efeca88aa8)

**Comment by LostRuins** [comment]
That's neat. Is it the base model or a finetuned one?

**Comment by teddybear082** [comment]
I think it's based off of https://huggingface.co/ByteDance/SDXL-Lightning but has the vae included.

**Comment by LostRuins** [comment]
Awesome.

**Comment by schorhr** [comment]
Awesome, any chance sdxs-512-0.9 or hypersd-sd1-5-1-step could work? I can't get them to run.

**Comment by LostRuins** [comment]
Can you link to the safetensors in question so I can take a look?

**Comment by schorhr** [comment]
Yes, of course :-)

https://huggingface.co/IDKiro/sdxs-512-dreamshaper/tree/main 
(was ~https://huggingface.co/IDKiro/sdxs-512-0.9/tree/main~, links to sdxs-512-dreamshaper now)

https://huggingface.co/rupeshs/hypersd-sd1-5-1-step-lora/tree/main
Thanks for looking into it.

**Comment by teddybear082** [comment]
> https://huggingface.co/rupeshs/hypersd-sd1-5-1-step-lora/tree/main
> Thanks for looking into it.

That one looks like it's just a lora not a full model.

**Comment by LostRuins** [comment]
Yeah, the model that you have linked is not in a format you can use. You need the packed version, which includes clip tokenizer, unet, and vae, usually its a 2.3GB safetensors file for SD1.5

Also, that seems to be a "SDXS" model, which I'm not sure is actually compatible.

If you're looking for dreamshaper, may I suggest this: https://civitai.com/models/112902/dreamshaper-xl

**Comment by LostRuins** [comment]
Hi, Custom LORA, TAESD and custom VAE are now supported in the latest version. This can help fix any models with broken VAEs
