### ISSUE TITLE
Reprocessing Issue with Llama 3

### ISSUE THREAD

**Issue by Nabokov86** [LostRuins/koboldcpp#803]
When using Llama 3, I've noticed that unnecessary reprocessing occurs on previously generated text.
To reproduce this issue, try generating a short piece of text couple of times and see how the processing sometimes happens.

Latest concedo_experimental.

**Comment by Nabokov86** [comment]
It seems like the reprocessing occurs after a new line is generated.
![Screenshot from 2024-04-23](https://github.com/LostRuins/koboldcpp/assets/26260168/b4a57395-fb9d-4094-b532-f4dfc2c1295d)

**Comment by LostRuins** [comment]
Did you by any chance enable "Trim Sentences" or "Author Note"?

**Comment by Nabokov86** [comment]
No, I use default settings without trimming. So, you can't reproduce it?
[saved_story.json](https://github.com/LostRuins/koboldcpp/files/15092767/saved_story.json)

**Comment by LostRuins** [comment]
Yes, I can reproduce it. Looking closer, the tokenizer is behaving weirdly. I think there is an issue with token merges. 

Relevant: https://github.com/ggerganov/llama.cpp/issues/6809 

You should experience a small amount of reprocessing all the way back to the previous newline. This is a bug.

**Comment by LostRuins** [comment]
Hi, Should be fixed in the latest version. Remember to get freshly reconverted GGUFs

**Comment by Nabokov86** [comment]
@LostRuins Thanks! Yes, it looks like it’s working now. Thank you for continuing to maintain this project, you’re awesome!
