### ISSUE TITLE
GUI controls are very small

### ISSUE THREAD

**Issue by elclanrs** [LostRuins/koboldcpp#805]
Configuration GUI on hidpi screens is very tiny and barely usable:

![Screenshot from 2024-04-23 20-29-10](https://github.com/LostRuins/koboldcpp/assets/1661925/8e4ad335-4552-45f8-9d4b-a59eaa5aa33b)

(Note that what you see on the image above on Github is 2x the size I see on my screen)

**Comment by puff-dayo** [comment]
Same issue here on a 2160x1440 screen with 200% scale. DPI/scaling factor detecting seems not working or not implemented.

Debian 12 GNOME/Wayland

**Comment by LostRuins** [comment]
Hmm that's odd. But that gave me an idea to allow the window to be resizable and automatically scale UI elements based on that, so it'll be in the next ver.

**Comment by LostRuins** [comment]
Hi, Should be fixed in the latest version, you can now freely resize the window, everything will scale up and down.

**Comment by savchenko** [comment]
@LostRuins , doesn't seem to work even under XWayland:
![image](https://github.com/user-attachments/assets/46cc7fe7-af25-4914-8884-68133a2daa49)
