### ISSUE TITLE
How to create high-quality images?

### ISSUE THREAD

**Issue by theluanr** [LostRuins/koboldcpp#809]
How can I create high-quality images?
Will there be more options available in subsequent editions?
Ty~

**Comment by LostRuins** [comment]
![image](https://github.com/LostRuins/koboldcpp/assets/39025047/da0fce59-6625-480a-bc36-74a9c89bb848)

Enable the "high res" toggle in image settings.
Use a good model. You can try this one: https://huggingface.co/Yntec/Deliberate2/resolve/main/Deliberate_v2.safetensors
