### ISSUE TITLE
The release 1.64.1 has inconsistent asset name

### ISSUE THREAD

**Issue by RikudouSage** [LostRuins/koboldcpp#827]
The asset name for [1.64.1](https://github.com/LostRuins/koboldcpp/releases/tag/v1.64.1) has the asset named `koboldcpp-linux-x64-cuda1150` instead of the usual `koboldcpp-linux-x64`. This breaks scripts that rely on the asset being the same (for example by downloading from the universal URL https://github.com/LostRuins/koboldcpp/releases/latest/download/koboldcpp-linux-x64)

**Comment by LostRuins** [comment]
Yes, sorry about that. The change was done preemptively as the next release will contain cuda12 builds, thus we are adding the cuda version as a suffix to differentiate them 

You can simply amend the link to https://github.com/LostRuins/koboldcpp/releases/latest/download/koboldcpp-linux-x64-cuda1150 and it should work for any future release.

**Comment by henk717** [comment]
To further add to that, https://koboldai.org/cpplinux is the URL shortner I update when changes like this happen.
