### ISSUE TITLE
Missing ollama in Release Image generation.

### ISSUE THREAD

**Issue by v3ss0n** [LostRuins/koboldcpp#840]
![image](https://github.com/LostRuins/koboldcpp/assets/419606/500bde29-e8d6-4051-91b4-b3567ccaa697)

On the release image - you are missing biggest freeloader Ollama.
Ollama is already getting most popular and probably getting investments while llamacpp and koboldcpp are doing hardest work. You are missing it there.

**Comment by i486** [comment]
It's not that serious.

**Comment by henk717** [comment]
It got cropped off in the image when it was pasted in the UI (Its originally a meme from reddit).
But fear not, ollama is standing right next to lmstudio.

**Comment by LostRuins** [comment]
Original meme in all it's glory

![image](https://github.com/LostRuins/koboldcpp/assets/39025047/2cd7d094-4a5d-4617-8fe2-4fddd818dbe8)
