### ISSUE TITLE
Flash Attention

### ISSUE THREAD

**Issue by ss4elby** [LostRuins/koboldcpp#844]
So I noticed it runs WAY slow, then realized my card was not set up for that, I am running ye oldie p40. So no tensor cores. But this fellow over at flash attention apparently made it possible to work without them? https://github.com/ggerganov/llama.cpp/pull/7188 I assume this in not implemented for this yet, any chance?

**Comment by LostRuins** [comment]
No, it's not implemented yet. I will merge it for the next version

**Comment by ss4elby** [comment]
Appreciated, your work is something amazing!

**Comment by Spacellary** [comment]
Truly a joyous occasion! This looks very promising!

**Comment by LostRuins** [comment]
Hi, can see if this works fine for you on the latest version?

**Comment by gustrd** [comment]
I checked with my old MX150 and now it works. 

The llama.cpp upgrade to CUDA without tensor cores must have solved it. The prompt processing speed is higher now (around 2x faster), but the generation a bit slower (around 20%). But this is a good tradeoff in the end.

**Comment by ss4elby** [comment]
It seems to work fine, holy hell its quick too. Thank you!
