### ISSUE TITLE
Make text in "Input Kobold API Key" as dots

### ISSUE THREAD

**Issue by unixshaman** [LostRuins/koboldcpp#851]
Now text in "Input Kobold API Key" visible.
![image](https://github.com/LostRuins/koboldcpp/assets/1523779/be91bd41-0578-434a-a80e-8ba10cc93eab)

How about making a field as password type and adding an eye symbol so that you can see the password if necessary?
![image](https://github.com/LostRuins/koboldcpp/assets/1523779/01eb52ed-096a-4ecb-a249-8a02860943e2)

**Comment by unixshaman** [comment]
Thanks for working on my issue.

I check relese 1.66.1.
- The saved password is not automatically entered into a new field in Chrome.
- Chrome does not automatically save when entering a value in a field.
- And the field itself is still not masked.
- And for some reason the field was turned into a 5-line block of text.

**Comment by LostRuins** [comment]
Hi, can you try 1.67? I think I fixed it properly this time.

**Comment by unixshaman** [comment]
\- When user click field for input key, it has text type and key visible again. Its not good.
\+ Key not visible when click somewhere else.
\- I dont now how, but now Chrome offers a list of saved keys not for ai.site.com, but also from all sites like a.site.com, b.site.com, c.site.com and so on. And if I select some of passwords, its become a visible.

I think key must be visible if user click on icon with eye, because onfocus is random operation (when the user moves the mouse across the screen).

**Comment by LostRuins** [comment]
`onfocus` should only apply when clicking into the textbox. Which is the same behavior for all other password fields in kobold lite, like the other API keys etc
