### ISSUE TITLE
Update llama.cpp for Phi 3 support

### ISSUE THREAD

**Issue by tdisheng** [LostRuins/koboldcpp#860]
Hi, Phi 3 Medium 128K GGUF only works with latest version of llama. Possible to update for koboldcpp?

See: https://github.com/ggerganov/llama.cpp/commit/201cc11afa0a1950e1f632390b2ac6c937a0d8f0

**Comment by LostRuins** [comment]
Yes, there will be a release by the end of the week.

**Comment by LostRuins** [comment]
Hi, new version is now released.
