### ISSUE TITLE
Koboldcpp api defaults to chat mode when sending command over api.

### ISSUE THREAD

**Issue by mercurial-moon** [LostRuins/koboldcpp#883]
I have Kobold cpp up and running from the launcher, I didn't configure any settings in the web gui.
And i open up a command prompt and send a curl request.

`
curl -H "Content-type:application/json" -X POST http://127.0.0.1:5001/api/v1/generate -d "{  \"max_context_length\": 2048,  \"max_length\
": 100,  \"prompt\": \"Who are you?\",  \"quiet\": false,  \"rep_pen\": 1.1,  \"rep_pen_range\": 256,  \"rep_pen_slope\": 1,  \"temperature\": 0.5,  \"tfs\": 1,
  \"top_a\": 0,  \"top_k\": 100,  \"top_p\": 0.9,  \"typical\": 1}"
`
Just to keep it short the prompt is "Who are you?"

The response is
```
  {"results": [{"text": " I am a 25-year-old woman named Sarah. I have been fascin
ated with the concept of time travel for as long as I can remember. As a child,I would spend hours reading about different theories and imagining what it would
 be like to visit different eras.\nWhat do you hope to achieve by coming here? My ultimate goal is to change the course of history. I believe that there are man
y injustices that have occurred throughout the centuries, and I want to use my knowledge of the future"}
```
I believe that it is switching to `chat mode` or a particular scenario named "Sarah". I want it to be in `instruct mode`
Is there a api command to switch to instruct mode?

**Comment by LostRuins** [comment]
To do that, you need to use an instruct prompt format, which depends on the model loaded. For example, the alpaca prompt format uses
```
### Instruction:
### Response:
```

This varies based on model.
Alternatively, you can use the openai compatible ChatCompletions api which handles that for you. Kobold serves both endpoints

**Comment by mercurial-moon** [comment]
Hi, Thanks for the update. Do i also have to manage context or does Koboldcpp do that for me. I mean take the previous conversation and prepend it to the current request.

**Comment by LostRuins** [comment]
Yes, context needs to be managed by the user. The backend does not store any data permanently
