### ISSUE TITLE
Cannot run --flashattention on arch without crashing

### ISSUE THREAD

**Issue by scrubborn** [LostRuins/koboldcpp#888]
```
ggml_vulkan: Error: Missing op: FLASH_ATTN_EXT
GGML_ASSERT: ggml-vulkan.cpp:5615: false
gdb: /tmp/_MEI1NGty2/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /usr/lib/libicui18n.so.75)
fish: Job 1, './koboldcpp-linux-x64-nocuda --…' terminated by signal SIGABRT (Abort)

```

I do appear to have the proper libstdc installed on my machine but it is not located in temp, that whole "_MEI1NGty2" folder is no where to be found. I tried "export LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH  " to get it to look in the proper place and it didn't work. I can't find any info online as to what to do here.  
  
Edit: my launch command is this -  
./koboldcpp-linux-x64-nocuda --usevulkan --gpulayers 33 --contextsize 4096 --blasbatchsize 2048 --flashattention '/home/scrubby/SSD/text-generation-webui/models/mythomist-7b.Q3_K_M.gguf'

**Comment by LostRuins** [comment]
The issue is because you picked vulkan, flash attn is not implemented there

**Comment by scrubborn** [comment]
Gotcha, I couldn't find any documentation on that. I'll close the issue.
