### ISSUE TITLE
Feature request: auto sleep

### ISSUE THREAD

**Issue by baronvertigovongrahamthesecondofsealand** [LostRuins/koboldcpp#892]
Is it at all possible to have the model go to sleep (ie. not use any resources) if conversation hasnt happened in a certain timeout value?

**Comment by LostRuins** [comment]
KoboldCpp is idle the moment the generation is complete - it does not use any CPU resources when not generating. The memory will stay in use until the model is unloaded - this will not happen automatically. You'd need some external script to start and close kobold as needed.
