### ISSUE TITLE
some non-ascii character streaming issue

### ISSUE THREAD

**Issue by luzamm** [LostRuins/koboldcpp#901]
![image](https://github.com/LostRuins/koboldcpp/assets/28832715/eab80bdf-7ab5-4c90-8806-c219438bfc49)
When some special characters are prefixed with a space, in streaming mode, webui including SillyTavern and KoboldAI Lite are unable to retrieve those characters and the space. This happened both on Windows and Linux.
![image](https://github.com/LostRuins/koboldcpp/assets/28832715/c51c9677-e3c0-4967-8cf0-cd320290b274)
But when observing cli, it works well. 
![image](https://github.com/LostRuins/koboldcpp/assets/28832715/6cc8a43e-831f-4dec-9514-6b2ef30fdc41)
And everything ok using text-generation-webui with streaming enabled.
![image](https://github.com/LostRuins/koboldcpp/assets/28832715/d9a400e6-4adf-4bf6-841a-472a5121ab10)
When webui using non-streaming mod, everything is ok,koboldcpp also works well.

**Comment by luzamm** [comment]
seems it is model related, both qwen2-72b and qwen2-7b have the problem, command-r-plus don't

**Comment by LostRuins** [comment]
Can you see if this is already fixed in the latest version
