### ISSUE TITLE
Feature request: Ability to "Generate More" when using Speech Control

### ISSUE THREAD

**Issue by NGgmnBQGwR** [LostRuins/koboldcpp#903]
In "koboldcpp-1.67", a great feature was added - "Speech Control".
But the button that acts as a voice indicator or Push-To-Talk toggle is the same "Generate More" button that is available without this feature enabled.

However, that means that right now there is no way to make the model generate more text with enabled speech control?
My request is to separate the functionality into 2 buttons.

That is, instead of either "Generate More":
![image](https://github.com/LostRuins/koboldcpp/assets/4226721/4757adf9-9c79-4373-890b-4c4f9f5cc528)
OR Speech Control:
![image](https://github.com/LostRuins/koboldcpp/assets/4226721/d232f171-ddcd-47fc-a21e-302c87210973)
To have both buttons available together:
![image](https://github.com/LostRuins/koboldcpp/assets/4226721/aaf1323c-12d1-4e17-ae96-9b669825c964)

**Comment by LostRuins** [comment]
I've added a workaround for this for the next version - you can try it on the experimental branch or connecting via https://lite.koboldai.net/ 

If you tap lightly on the button, it will generate more.
If you press and hold, then PTT will be activated.
Try it and let me know what you think.

**Comment by NGgmnBQGwR** [comment]
Thank you!
I've tried the "concedo_experimental" branch, and it works, but it's not really obvious - other users will probably miss this feature.

**Comment by LostRuins** [comment]
I think they'll try tapping the button when they want to generate same as usual non-voice mode, so it should work

**Comment by LostRuins** [comment]
The fix is now in the latest released version, please try it.
