### ISSUE TITLE
Crash when loading GPU such as q_XS and q_XSS models (Preset NoAVX2)

### ISSUE THREAD

**Issue by grtsata** [LostRuins/koboldcpp#904]
My CPU is old and does not support AVX2, so I am using the NoAVX2 preset.
The q4_K_M model can read the GPU with no problem.
For q4_XS, q3_XSS, etc., it crashes with the following message at the end

Preset: CLBlast NoAVX2 (Old CPU)
GGML_ASSERT: ggml-opencl.cpp:1815: to_fp32_cl ! = nullptr

Preset: Vulcan NoAVX2(Old CPU)
GGML_ASSERT: ggml-vulkan.cpp:2999: !qx_needs_dequant ||to_fp16_vk_0 ! = nullptr

**Comment by LostRuins** [comment]
Those quants are not supported on those backends. Try using a K quant

**Comment by grtsata** [comment]
You are correct that the K_M and K_S models work fine.
Is it due to NoAVX2 mode that XS models and others are not supported? It was difficult to identify the problem as the documentation does not mention such information.
Also, they work fine in text-generation-webui-main, so they should be workable in hardware, and we hope you will consider supporting them.

**Comment by LostRuins** [comment]
Are you sure text-gen webui supports vulkan/clblast?

**Comment by grtsata** [comment]
In text-generation-webui, the XS and XSS models are loaded on the GPU and work fine, even on the AVX1 CPU.

**Comment by LostRuins** [comment]
Please try this build: https://github.com/LostRuins/koboldcpp/actions/runs/9436096249/artifacts/1582996921 and select cublas.

**Comment by grtsata** [comment]
I tried the build and it works with Preset cublas selected K and XS and XSS Model also works. It is working very well.

**Comment by LostRuins** [comment]
Yup there you go.
