### ISSUE TITLE
Better Undo/Redo

### ISSUE THREAD

**Issue by Azirine** [LostRuins/koboldcpp#905]
Currently, the 'Back' button only goes back one message variation, and all previous variations are lost. Plus, if I remove a few messages and press 'Retry', 'Back' does not restore the messages I removed.

Ideally, Undo/Redo should work like in a word processor, tracking changes and restoring previous states exactly.

**Comment by LostRuins** [comment]
I can look into expanding the undo variation history. But I am confused, if you undo a few actions in a word processor, and then perform something new, won't that action stack be lost too?

**Comment by Azirine** [comment]
By "remove a few messages" I don't mean with undo, but selecting and deleting them. This is a "forward" action that can be undone (restore deleted text) and then redone (re-delete restored text) in a word processor.

If you remove a few messages then perform something new, these are two "forward" actions, so the action stack won't be lost.

**Comment by LostRuins** [comment]
oh, unfortunately once the text editing process is finished the text is merged, and then you cant revert it anymore

**Comment by Azirine** [comment]
If this is not possible, expanding the undo variation history would still be a big improvement.

**Comment by LostRuins** [comment]
Retry stack size has been increased in the latest released version, please try it.
