### ISSUE TITLE
New requirements: 1. I hope to be able to load the webpage first like the open webui, and the model can be freely selected and switched in the webui. 2. When not used after 5 minutes or any set time, all GPU memory should be automatically released and loaded the next time someone requests an inference task on the web.

### ISSUE THREAD

**Issue by windkwbs** [LostRuins/koboldcpp#907]
New requirements:
1. I hope to be able to load the webpage first like the open webui, and the model can be freely selected and switched in the webui.
2. When not used after 5 minutes or any set time, all GPU memory should be automatically released and loaded the next time someone requests an inference task on the web.

**Comment by LostRuins** [comment]
Unfortunately, Koboldcpp does not currently and has no immediate plans to support hotswapping models or loading models from the web ui.
