### ISSUE TITLE
Maybe add gguf fine-tuning function and can be used in ui.

### ISSUE THREAD

**Issue by win10ogod** [LostRuins/koboldcpp#911]
Maybe add gguf fine-tuning function and can be used in ui.

**Comment by yukiarimo** [comment]
That's would be cool! Especially, with some QLoRA and MLX optimization ;)

**Comment by win10ogod** [comment]
Yes, but when gguf supports fla, it should also be used for fine-tuning nvidia gpu

> That's would be cool! Especially, with some QLoRA and MLX optimization ;)

**Comment by LostRuins** [comment]
Both koboldcpp and llama.cpp aren't ideal for finetuning - your best bet would be something like Unsloth or Axolotl
