### ISSUE TITLE
bark.cpp as TTS

### ISSUE THREAD

**Issue by tororon1231** [LostRuins/koboldcpp#912]
Integrate bark.cpp as TTS from [this repository](https://github.com/PABannier/bark.cpp) into koboldcpp. It would be nice to have it running natively.

**Comment by LostRuins** [comment]
The quality of speech produced by bark is very poor, and is also very slow. Have you tried XTTS or the built-in browser TTS?

**Comment by tororon1231** [comment]
The built-in browser TTS and XTTS don't have the ability to produce non-speech sounds and expressions (such as laughing, crying, etc.) like bark. Even the speech quality of the built-in browser TTS can be worse than bark. XTTS is good, but I have to set up an additional server, whereas it would be better and easier to have the TTS functionality running natively in koboldcpp. From a practical point of view, bark.cpp has its limitations, but it will serve as a basis for adding more and better models in the future, as the developer of bark.cpp wants to add ([1](https://github.com/PABannier/bark.cpp?tab=readme-ov-file#description), [2](https://github.com/PABannier/bark.cpp/issues/180#issuecomment-2152369612)).

**Comment by tororon1231** [comment]
@LostRuins I have just produced two sentences with bark. It is actually quite decent. Have a listen. Transcription: I couldn’t believe my eyes when I saw the puppy run towards me, its tail wagging as if to say, ‘I’ve missed you!’ [laughs]
And then, out of nowhere, the lights flickered off, leaving us in an eerie silence that seemed to whisper secrets from the shadows.

https://github.com/LostRuins/koboldcpp/assets/172286123/86d464c9-2b7f-4909-8ec4-293d447b20e5

**Comment by tororon1231** [comment]
@LostRuins  So what do you think? Does bark.cpp or something similar for TTS have any potential to be included in koboldcpp at some point in the future?

**Comment by tororon1231** [comment]
Here is an earlier [discussion](https://github.com/LostRuins/koboldcpp/discussions/886) of this idea in your repository.

**Comment by LostRuins** [comment]
Yeah, if you compare that sample with the XTTS voice that I used inside the latest 1.67 release video, they are worlds apart.
