### ISSUE TITLE
Option to selectively disable GPU acceleration for each model type

### ISSUE THREAD

**Issue by tororon1231** [LostRuins/koboldcpp#916]
Add a way to selectively disable GPU acceleration for each model type (even from the GUI). For example, use the GPU only for text generation and not for image generation, and vice versa. This is needed for low-end GPUs with small amounts of VRAM, so that CUDA does not easily run out of memory and crash when running multiple models.

**Comment by LostRuins** [comment]
There is an easy solution to this: Simply run 2 instances of koboldcpp on two different ports, one with GPU selected and one without. Then, from the Web UI you can connect to both instances individually, e.g. select the img generation from instance 2 and txt gen from instance 1.

**Comment by tororon1231** [comment]
Okay, nice workaround. Thanks!

**Comment by tororon1231** [comment]
@LostRuins Just one question. Can I do this for other model types like Whisper?

**Comment by tororon1231** [comment]
@LostRuins Hi. I just have one question. Can I use this method in the web UI for other model types like Whisper.

**Comment by LostRuins** [comment]
For whisper, it currently does not allow you to use a different URL - I might add that in future.
