### ISSUE TITLE
Help: How to set Phi-3 prompt template?

### ISSUE THREAD

**Issue by LeMoussel** [LostRuins/koboldcpp#924]
I want to use[ bartowski/Phi-3-medium-128k-instruct-GGUF](https://huggingface.co/bartowski/Phi-3-medium-128k-instruct-GGUF).
Prompt format: `<|user|> {prompt}<|end|><|assistant|><|end|>`

In settings I can't find anything about Phi-3 prompt. So, I think I should choose `[custom]`, but what should I complete?
Does I set 
- _Start Seq._ to `<|user|> `
- _End Seq._ to `<|end|><|assistant|><|end|>`

Thank you for your help

![image](https://github.com/LostRuins/koboldcpp/assets/1816573/b47a7fad-b00e-4689-a05d-d4e5f64b5756)

**Comment by LostRuins** [comment]
Phi 3 prompt will be added in the next version. For now, you can use this:

start seq = `<|end|><|user|>\\n`
end seq = `<|end|>\\n<|assistant|>`
