### ISSUE TITLE
Auto apply correct chat template when using OpenAI compatible API

### ISSUE THREAD

**Issue by Tureti** [LostRuins/koboldcpp#925]
v1 api currently uses a harcoded alpaca prompt template with support for specifying adapters to change it: https://github.com/LostRuins/koboldcpp/pull/466
This method is not supported in for example Open-WebUI. It would be great if koboldcpp could automatically apply the chat template specified in tokenizer.chat_template of the gguf model.

**Comment by Tureti** [comment]
Allowing to set a custom chat template for the v1 api when starting koboldcpp would be enough for a quick fix as well if that seems easier.

**Comment by LostRuins** [comment]
This is supported, see https://github.com/LostRuins/koboldcpp/wiki#what-is---chatcompletionsadapter

**Comment by Tureti** [comment]
Ok sorry I missed that.
