### ISSUE TITLE
Is there a way to share story as plaintext?

### ISSUE THREAD

**Issue by AlexysLovesLexxie** [LostRuins/koboldcpp#928]
I'm looking for a way to share/export my story as plaintext to allow for easier sharing/editing of the story?

The "export story as textdata" function (from the load/save dialog's "share" option) produces the following:
 
![Screenshot 2024-06-17 001348](https://github.com/LostRuins/koboldcpp/assets/126999069/bd29d445-2303-45d3-86b1-ef321a5f7be1)

Could an "export to textfile" option please be added?

**Comment by LostRuins** [comment]
Sure, actually its as easy as just copying the story from the clipboard and pasting it into a text document. But I can probably add an option to download txt as well.

**Comment by AlexysLovesLexxie** [comment]
That would be awesome, thanks.

**Comment by LostRuins** [comment]
Added in the latest released version, please try it.

**Comment by AlexysLovesLexxie** [comment]
> Added in the latest released version, please try it.

How my story looks in the interface : 
![Screenshot 2024-06-19 023032](https://github.com/LostRuins/koboldcpp/assets/126999069/cb4ab7f2-50cb-4ee0-b09d-cac1c5fca969)

How my story looks after exporting as plaintext and pasting into Notepad : 
![Screenshot 2024-06-19 023113](https://github.com/LostRuins/koboldcpp/assets/126999069/db1e0804-1d8a-45ed-828d-114f1dbac675)

it does not seem to keep the formatting when I export.  I can always fix this manually, but I had hoped it would at least keep the line-feeds.

But it is functional.  At this point, copying the buffer is actually the better solution, though.
