### ISSUE TITLE
Phi-3 vulkan?

### ISSUE THREAD

**Issue by paryska99** [LostRuins/koboldcpp#931]
Did anybody manage to make phi-3 work with vulkan backend? Im testing latest koboldcpp on a very restricted device when it comes to available drivers (windows steam-deck), so vulkan is the only backend that manages to work and be semi-quick.
Codeqwen1.5 works great with vulkan on KCPP but phi-3 mini just crashes while loading.

**Comment by LostRuins** [comment]
Yes, Phi 3 works well on vulkan. Do update to the latest version. You can try this model: https://huggingface.co/concedo/Phi-SoSerious-Mini-V1-GGUF

Reopen an issue if the problem persists.
