### ISSUE TITLE
Error compiling with -lcblas

### ISSUE THREAD

**Issue by h3ndrik** [LostRuins/koboldcpp#95]
After the rewrite of the Makefile (i think in 346cd68), koboldcpp doesn't compile anymore with openblas.

`$ make LLAMA_OPENBLAS=1`

Error message:
```bash
g++ -I. -I./examples -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s -Wno-multichar -pthread        ggml_openblas.o ggml_rwkv.o ggml_v1.o expose.o common.o llama_adapter.o gpttype_adapter.o -lcblas -lopenblas -shared -o koboldcpp_openblas.so 
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
make: *** [Makefile:247: koboldcpp_openblas] Error 1
```

Removing the `-lcblas` makes it compile.

I'm running Debian GNU/Linux 11 (bullseye)

I installed both `libclblast-dev` and `libopenblas-dev` (and the intel libmkl)

**Comment by h3ndrik** [comment]
Well. I also installed `libatlas-base-dev` and now it compiles with that flag. But i don't really know what i'm doing. I only searched for a package which provides that library.

**Comment by horenbergerb** [comment]
I hit the same issue, actually. I'll try installing that lib later and see if it fixes the problem for me as well.

**Comment by LostRuins** [comment]
@h3ndrik @horenbergerb 

Okay so the main issue was that some linux distros seem to need it when they use -lopenblas and some *break* if they have it. It has to do with libopenblas actually containing different stuff in different distros, specifically arch linux requires -lcblas but that makes the debian build fail apparently. 

anyway hopefully all that mess is out of the way. sorry for the troubles. Can you all please try pull the latest and build and see if its works? 

Specifically, try run `make LLAMA_CLBLAST=1 LLAMA_OPENBLAS=1` and then after that use the appropriate python flags (e.g. `--useclblast`) to run the desired functionality.

Please let me know if its still broken

**Comment by h3ndrik** [comment]
Seems to be fine now.

Now successfully compiles with `make LLAMA_CLBLAST=1 LLAMA_OPENBLAS=1`
I'm not using clblast, though... And I removed my extra atlas package before trying.

I think if this fixes it for everybody, we can close this. Thank you very much!

**Comment by horenbergerb** [comment]
Just pulled and hit the same error again while trying to build with `make LLAMA_CLBLAST=1 LLAMA_OPENBLAS=1`, but installing `libatlas-base-dev` fixed the problem for me too. Ubuntu 22.04.2 LTS

**Comment by AllesMeins** [comment]
I seem to have an issue that might be related: When compiling it fails with

`g++ -I. -I./examples -I./include -I./include/CL -Ofast -DNDEBUG -std=c++11 -fPIC -pthread -s -Wno-multichar -pthread     ggml_clblast.o ggml_rwkv.o ggml_v1.o expose.o common.o gpttype_adapter.o -lclblast -lOpenCL -lcblas -lopenblas -shared -o koboldcpp_clblast.so 
/usr/bin/ld: cannot find -lclblast: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:267: koboldcpp_clblast] Error 1
`

I'm running on Manjaro Linux (which is a variety of Arch) and have cblas and openblas packages installed. But to be honest: I also somewhat lost track of what all the different blas/blast/cblas/openblas/closedblas/blasblast/blablabla are and do - so I might not be the most reliable witness :-)

**Comment by LostRuins** [comment]
Someone once mentioned that the clblast library has a different name on certain distros. Can't find the thread now but you can try messing with the name of `-lclblast`
