### ISSUE TITLE
IDK chat Bug? kobold give random code...

### ISSUE THREAD

**Issue by alastor367** [LostRuins/koboldcpp#951]
_I deleted the old sessions but on the old session literally displayed in the messages after writing hello some code for min 30 lines_

During the generation:
![image](https://github.com/LostRuins/koboldcpp/assets/132879286/7343185e-b62b-418b-b933-54c40ea824df)
when the generation has finished:
![image](https://github.com/LostRuins/koboldcpp/assets/132879286/3032910d-7192-40f9-a4d7-6d72788605a2)

I have a dual boot system with Windows and Linux on both systems I used kobold I used two separate versions of the kobold to test both of them had the same effect versions: 1.58 and 1.64
everything was going well, only from today it's been like this

![image](https://github.com/LostRuins/koboldcpp/assets/132879286/cd113ea1-b41f-4855-ade1-4aa4b59914cc)

**Comment by alastor367** [comment]
The problems in a way have been fixed after upgrading to the latest version and changing to OpenBlast but he can still sometimes answer me with my own question

**Comment by alastor367** [comment]
but it would still be nice if someone would be able to tell me that it could be caused by

**Comment by LostRuins** [comment]
Hmm, what model were you using? Make sure you're using the correct instruct format, and make sure the story memory doesn't contain unwanted data. 

You can try load the KoboldGPT Instruct scenario and repeat the query, it should be better.

![image](https://github.com/LostRuins/koboldcpp/assets/39025047/bea37fc3-0070-426e-abb5-f258066e0b52)
