### ISSUE TITLE
Enable streaming on KoboldAI Lite when using remote hosts

### ISSUE THREAD

**Issue by morbidCode** [LostRuins/koboldcpp#966]
Hello,

I’ve got an openrouter account with some credits to use LLM models. I noticed that the official KoboldAI Lite page (https://koboldai.net) supports openrouter’s API, which is great for me. However, I can't stream the generated responses, and I saw this mentioned on the Koboldcpp wiki page.
Is there any way to turn on streaming for remote APIs? It would be nice to immediately cut off the response if I don't like the generation and save some credits.

Thanks!

**Comment by LostRuins** [comment]
Hi, streaming should now work for remote hosts. Be sure to select the streaming option when connecting.
![image](https://github.com/user-attachments/assets/ac07de4c-57c2-4f60-9df6-c06c24e45594)

 Please let me know if you have issues.
