### ISSUE TITLE
error loading model: missing tok_embeddings.weight

### ISSUE THREAD

**Issue by trappedinspacetime** [LostRuins/koboldcpp#98]
First of all, I congratulate you on this project.
I am on Ubuntu 22.04 platform. 
I wanted to try https://huggingface.co/cakewalk/ggml-q4_0-stablelm-tuned-alpha-7b/blob/main/ggml-model-stablelm-tuned-alpha-7b-q4_0.bin 
when I run 

     python koboldcpp.py /home/me/Downloads/ggml-model-stablelm-tuned-alpha-7b-q4_0.bin 9777
     
I get 

     error loading model: missing tok_embeddings.weight
error.

**Comment by JeroenAdam** [comment]
I'm having the same error 'missing tok_embeddings.weight' trying to run with latest llama.cpp

**Comment by LostRuins** [comment]
StableLM is not a llama model, it is a Gpt NeoX model. Future support is planned, but it is not yet ready.

**Comment by LostRuins** [comment]
Gpt neox support has been added in the latest version. Please update and try again.

**Comment by simulanics** [comment]
I'm getting the following error:

`Welcome to KoboldCpp - Version 1.11
Attempting to use OpenBLAS library for faster prompt ingestion. A compatible libopenblas will be required.
Initializing dynamic library: koboldcpp_openblas.dll
Loading model: C:\Users\Matthew\Desktop\smarts\ggml-model-stablelm-tuned-alpha-7b-q4_0.bin
[Threads: 3, SmartContext: False]

---
Identified as GPT-NEO-X model: (ver 400)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
stablelm_model_load: loading model from 'C:\Users\Matthew\Desktop\smarts\ggml-model-stablelm-tuned-alpha-7b-q4_0.bin' - please wait ...
stablelm_model_load: n_vocab = 50432
stablelm_model_load: n_ctx   = 6144
stablelm_model_load: n_embd  = 48
stablelm_model_load: n_head  = 16
stablelm_model_load: n_layer = 32
stablelm_model_load: n_rot   = 1
stablelm_model_load: ftype   = 2
stablelm_model_load: ggml ctx size =  75.89 MB
stablelm_model_load: memory_size =    36.00 MB, n_mem = 196608
stablelm_model_load: stablelm_model_load: tensor 'gpt_neox.embed_in.weight' has wrong size in model file
gpttype_load_model: failed to load model from 'C:\Users\Matthew\Desktop\smarts\ggml-model-stablelm-tuned-alpha-7b-q4_0.bin'
Load Model OK: False
Could not load model: C:\Users\Matthew\Desktop\smarts\ggml-model-stablelm-tuned-alpha-7b-q4_0.bin`

**Comment by trappedinspacetime** [comment]
I get the same error as @simulanics 

          python koboldcpp.py /home/user/Downloads/ggml-model-stablelm-tuned-alpha-7b-q4_0.bin 9777
          Welcome to KoboldCpp - Version 1.12
          Warning: OpenBLAS library file not found. Non-BLAS library will be used.
          Initializing dynamic library: koboldcpp.so
          Loading model: /home/user/Downloads/ggml-model-stablelm-tuned-alpha-7b-q4_0.bin 
          [Threads: 5, SmartContext: False]
          
          ---
          Identified as GPT-NEO-X model: (ver 400)
          Attempting to Load...
          ---
          System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
          stablelm_model_load: loading model from '/home/user/Downloads/ggml-model-stablelm-tuned-alpha-7b-q4_0.bin' - please wait ...
          stablelm_model_load: n_vocab = 50432
          stablelm_model_load: n_ctx   = 6144
          stablelm_model_load: n_embd  = 48
          stablelm_model_load: n_head  = 16
          stablelm_model_load: n_layer = 32
          stablelm_model_load: n_rot   = 1
          stablelm_model_load: ftype   = 2
          stablelm_model_load: ggml ctx size =  75.89 MB
          stablelm_model_load: memory_size =    36.00 MB, n_mem = 196608
          stablelm_model_load: tensor 'gpt_neox.embed_in.weight' has wrong size in model file
          gpttype_load_model: failed to load model from '/home/user/Downloads/ggml-model-stablelm-tuned-alpha-7b-q4_0.bin'
          Load Model OK: False
          Could not load model: /home/user/Downloads/ggml-model-stablelm-tuned-alpha-7b-q4_0.bin
          stablelm_model_load:

**Comment by LostRuins** [comment]
Seems like it's only this specific model that has the wrong size. I've tried other NeoX models and they seem to work. But not very sure how to fix it.

**Comment by LostRuins** [comment]
Hi, This should be fixed. I believe it was due to an older NeoX format that I have since integrated.

**Comment by trappedinspacetime** [comment]
@LostRuins Unfortunately I get the error:

        Welcome to KoboldCpp - Version 1.15
        Warning: OpenBLAS library file not found. Non-BLAS library will be used.
        Initializing dynamic library: koboldcpp.so
        ==========
        Loading model: /home/user/Downloads/ggml-model-stablelm-tuned-alpha-7b-q4_0.bin 
        [Threads: 5, SmartContext: False]
        
        ---
        Identified as GPT-NEO-X model: (ver 401)
        Attempting to Load...
        ---
        System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
        stablelm_model_load: loading model from '/home/user/Downloads/ggml-model-stablelm-tuned-alpha-7b-q4_0.bin' - please wait ...
        stablelm_model_load: n_vocab = 50432
        stablelm_model_load: n_ctx   = 6144
        stablelm_model_load: n_embd  = 48
        stablelm_model_load: n_head  = 16
        stablelm_model_load: n_layer = 32
        stablelm_model_load: n_rot   = 1
        stablelm_model_load: ftype   = 2
        stablelm_model_load: ggml ctx size =  75.89 MB
        stablelm_model_load: memory_size =    36.00 MB, n_mem = 196608
        stablelm_model_load: tensor 'gpt_neox.embed_in.weight' has wrong size in model file
        gpttype_load_model: failed to load model from '/home/user/Downloads/ggml-model-stablelm-tuned-alpha-7b-q4_0.bin'
        Load Model OK: False
        Could not load model: /home/user/Downloads/ggml-model-stablelm-tuned-alpha-7b-q4_0.bin
        stablelm_model_load:

**Comment by LostRuins** [comment]
Okay I tried that same model and it appears to be defective.

**Comment by trappedinspacetime** [comment]
@LostRuins You mean that model is faulty? Is there another model that I can test?

**Comment by LostRuins** [comment]
Sure there are plenty. If you want to test NeoX, you can try some GGML Pythias https://huggingface.co/Merry/ggml-pythia-deduped/resolve/main/2023-04-20/ggml-pythia-1b-deduped-q4_3.bin
