### ISSUE TITLE
koboldcpp execution issues and memory-related questions

### ISSUE THREAD

**Issue by kbuwel** [LostRuins/koboldcpp#984]
I want to run koboldcpp with an x300 barebones system.
CPU is Ryzen 5600g.
There was no problem on the 5600x system, but on the 5600g system, if you select the gguf model, the 
web browser does not run.
Even if you wait all day, the first launch screen remains the same.
I'm not sure what the reason is.
RAM capacity is 32GB.
The network is connected to the iPhone 11 via USB.
The data capacity is 100GB and there is over 90GB remaining.
I downloaded the latest version of koboldcpp_nocuda.exe.
Please tell me the solution.
I'm not sure how to use memory now.
There are many difficulties in writing a screenplay.
I think using memory will help me write scenarios, but I'm not sure what to input and how to input 
it.
Are there any samples to input into memory?

**Comment by LostRuins** [comment]
Is it crashing? Can you please provide some error logs from the console output?

**Comment by kbuwel** [comment]
Welcome to KoboldCpp - Version 1.69.1                                      
For command line arguments, please refer to --help                         
***

**Comment by LostRuins** [comment]
For examples on writing, check out the provided "Scenarios" in Kobold Lite
