### ISSUE TITLE
Response is cut off after first paragraph.

### ISSUE THREAD

**Issue by SirasB** [LostRuins/koboldcpp#988]
**Describe the Issue**
Using KoboldCpp and setting SillyTavern to 500 Tokens output, The AI tends to respond in several paragraphs, which is what I would want. But SillyTavern cuts off the answer after the first paragraph.

**Additional Information:**
Not sure if this is an issue or if I just didn't see the correct setting. Also not sure if KoboldCpp API would send all the paragraphs to SillyTavern. I have no user stop tokens set. It seems like a single CR would be enough to cut the rest.

**Comment by SirasB** [comment]
Umm... Seems like the issue lies somewhere in the extended formatting. Sorry to have bothered you...

**Comment by LostRuins** [comment]
The response would have been sent from the KoboldCpp backend, the trimming is probably done from SillyTavern side. So you'll need to check your settings there.

**Comment by SirasB** [comment]
Thank you for your reply. Yes, the problem was a somewhat messed up extended formatting. I still don't understand, why it happened, but switching to another formatting solved the problem completely.
