### ISSUE TITLE
Gemma-2 End Seq.

### ISSUE THREAD

**Issue by Azirine** [LostRuins/koboldcpp#990]
Default End Seq. for Gemma-2 is set to be `<end_of_turn>\n<start_of_turn>assistant\n`

However, the docs show it should be `<end_of_turn>\n<start_of_turn>model\n`

https://huggingface.co/google/gemma-2-9b-it
https://ai.google.dev/gemma/docs/formatting

KoboldCpp 1.69.1

**Comment by LostRuins** [comment]
Yes, this issue has been noted and will be fixed in the next version. Thanks.
