### ISSUE TITLE
Qwen2 does not terminate correctly in Instruct Mode

### ISSUE THREAD

**Issue by Azirine** [LostRuins/koboldcpp#995]
```
Generating (471 / 512 tokens) [(.\n 44.57%) (. 53.76%) ( before 1.38%) ( to 0.29%)]
Generating (472 / 512 tokens) [(<|endoftext|> 100.00%)]
Generating (473 / 512 tokens) [(Human 67.28%) (Assistant 23.98%) (I 2.92%) (Write 1.49%)]
Generating (474 / 512 tokens) [(: 100.00%)]
Generating (475 / 512 tokens) [( The 0.71%) ( Can 19.76%) ( I 18.86%) ( How 13.24%) ( What 11.63%)]
Generating (476 / 512 tokens) [( following 58.24%) ( new 25.89%) ( professor 1.33%) ( first 1.17%)]
Generating (477 / 512 tokens) [( is 79.94%) ( article 5.29%) ( are 4.31%) ( code 3.35%)]
Generating (478 / 512 tokens) [( a 88.94%) ( an 10.22%) ( the 0.83%)]
Generating (479 / 512 tokens) [( dialogue 4.86%) ( simplified 34.34%) ( conversation 18.15%) ( table 10.41%) ( list 8.67%)]
Generating (480 / 512 tokens) [( between 94.50%) ( about 4.26%) (:\n 0.76%) ( where 0.48%)]
Generating (481 / 512 tokens) [( two 77.06%) ( a 18.50%) ( Alice 4.44%)]
Generating (482 / 512 tokens) [( AI 14.48%) ( people 25.59%) ( characters 15.38%) ( colleagues 12.03%)]
Generating (483 / 512 tokens) [( agents 58.73%) ( language 24.68%) ( assistants 7.82%) ( systems 3.02%)]
...
```

<|endoftext|> should give control back to user but it keeps generating unrelated text.

Format: Instruct Mode
Instruct Tag Preset: ChatML
Model tested: https://huggingface.co/Qwen/Qwen2-72B-Instruct-GGUF
Koboldcpp 1.69.1

**Comment by LostRuins** [comment]
According to the model description for Qwen2, the registered EOS token is actually `<|im_end|>` which is ID 151645. 

You can try adding `<|endoftext|>` to the custom stopping sequences instead.

**Comment by Azirine** [comment]
For some reason, sometimes it uses `<|endoftext|>` instead of `<|im_end|>`. I tried on llama.cpp cli and didn't experience this issue.

Also, I don't see where I can add custom stopping sequences.

**Comment by LostRuins** [comment]
Click on "Context" button under the "Tokens" tab

![image](https://github.com/user-attachments/assets/6a07980a-f835-40f4-adbd-692f77b94298)
