### ISSUE TITLE
Silent audio track emits deep buzzing sound + another small issue

### ISSUE THREAD

**Issue by pbz134** [LostRuins/koboldcpp#998]
**Describe the Issue**
1. When enabling the "Run in background" option, a deep buzzing sound is heard. This should not occur, as the audio track is described as a "silent" audio track.

2. I noticed that in the new corpo theme, my custom background image is slightly visible on both sides.
In other words, the dark grey color provided by the corpo theme does not fully fill the screen.  

And I would like to request a feature to change the AI's icon, like in the Aesthetic theme :)

Issue 1 and 2 examples:

https://github.com/user-attachments/assets/5a065eca-8784-48ed-9796-627678c7b55c

![111](https://github.com/user-attachments/assets/1a10e437-8379-44d9-9319-4e2cca875ab4)

**Comment by LostRuins** [comment]
Hi, sorry for the delay. I took a look at your video but I don't actually hear any buzzing. Could it be a result of your audio/speaker setup?

The reason why the audio is required is that browsers treat running audio as an "ongoing" activity and prevents the tab or device from going to sleep. However, they also require the audio data to have a volume greater than 0. The volume for this audio has been set to an extremely low value, and is imperceptible to me, but perhaps your sound system generates a buzz just from being active.

**Comment by pbz134** [comment]
Hey, I checked the audio in a video editor and in FL Studio. Both are showing that there is actually audible sound while the feature is enabled. Tested on phone speakers, headphones and PC speakers.

If we import the video into Shotcut, it's clearly visible:
![grafik](https://github.com/user-attachments/assets/eef2f821-03aa-4d16-b72b-67ef77adddfe)

However, if you can't fix it, that's no problem. I will use the Windows audio mixer to mute my browser. Thanks for your reply!

**Comment by LostRuins** [comment]
Yeah there is sound, but it's set to a really low volume. I can't make it complete silence as browsers recognize this and will treat the audio as disabled, then run in background won't work.

**Comment by pbz134** [comment]
Got it! :)
