### ISSUE TITLE
Web UI Output Missing First Chinese Character of Each Paragraph

### ISSUE THREAD

**Issue by gzmud** [LostRuins/koboldcpp#999]
Issue Title: Web UI Output Missing First Chinese Character of Each Paragraph
Description: The web user interface output misses the first Chinese character of each paragraph, resulting in an incomplete display of the content. This issue affects the readability and user experience of the output.
Severity Level: High
Affected Versions: All versions since the last release
Steps to Reproduce:
Open the web application and observe the output.
Look for any paragraphs with missing characters at the beginning.
Example Output:
Console：
“您好，……”
![bug](https://github.com/user-attachments/assets/4d430e20-930c-4b7e-97d2-a6486b02b143)

Web UI
“好，……”
Possible Solutions:
Review the code responsible for rendering the output and identify the cause of the missing characters.
Implement a fix to ensure that the first character of each paragraph is properly displayed.
Attachments: Screenshots showing the issue
Deadline for Resolution: Within one week
Assigned To: Development Team Lead
Follow-up Actions:
Conduct a thorough test after the fix to confirm its effectiveness.
Provide training or documentation on how to use the corrected feature effectively.

**Comment by LostRuins** [comment]
Hi, thanks for the report. Can you share a sample save file, as well as the name of the model you are using?

**Comment by LostRuins** [comment]
Hi, please try the test binary here: https://github.com/LostRuins/koboldcpp/actions/runs/10164784312 (you may need to login to github to download it) does it work correctly?

**Comment by LostRuins** [comment]
Hi, this should be fixed in 1.72, please try!
